import type { CulturalRef } from "../types.js";

export const deCulturalRefs: readonly CulturalRef[] = [
  {
    id: "de_saudade",
    type: "expression",
    contentPt: "Saudade",
    contentL1: "Sehnsucht (das nächste deutsche Wort)",
    explanation: "The famous untranslatable Portuguese word. German 'Sehnsucht' is the closest equivalent — a deep longing for something absent. But saudade includes a bittersweet pleasure in the longing itself. Central to fado music, which has a similar emotional register to German Lieder traditions.",
    cefrMin: "B1",
    tags: ["culture", "emotion", "music"],
  },
  {
    id: "de_kaffee_bica",
    type: "reference",
    contentPt: "Uma bica / um galão",
    contentL1: "Espresso / Milchkaffee",
    explanation: "In Lisbon, espresso is called 'bica', not 'café'. A 'galão' is milky coffee in a tall glass — like a German Milchkaffee but stronger. Coffee culture in Portugal is as serious as Germany's Kaffee und Kuchen tradition, but faster: Portuguese stand at the counter, drink in two sips, and go.",
    cefrMin: "A1",
    tags: ["food", "daily-life"],
  },
  {
    id: "de_pasteis_kuchen",
    type: "reference",
    contentPt: "Pastéis de nata",
    contentL1: "Portugals berühmtestes Gebäck (like Kuchen culture)",
    explanation: "Flaky custard tarts found in every pastelaria for about one euro. Like German Kuchen culture but portable — eaten standing at the counter, warm, sprinkled with cinnamon. The original recipe comes from the Jerónimos monastery in Belém. Every German who visits Lisbon becomes addicted.",
    cefrMin: "A1",
    tags: ["food", "culture", "lisbon"],
  },
  {
    id: "de_fado_lieder",
    type: "reference",
    contentPt: "Fado",
    contentL1: "Fado (vergleichbar mit deutschen Liedern / Chanson)",
    explanation: "Fado is Portugal's soul music — mournful, intimate, about fate and saudade. German speakers can connect it to the Lieder tradition of Schubert or the emotional depth of Chanson. Amália Rodrigues is fado's greatest voice. Best experienced live in Alfama, Lisbon.",
    cefrMin: "B1",
    tags: ["music", "culture"],
  },
  {
    id: "de_pois",
    type: "expression",
    contentPt: "Pois...",
    contentL1: "Ja... / Na ja... / Tja...",
    explanation: "'Pois' is the most versatile Portuguese filler word, like German 'tja' or 'na ja'. It can mean agreement, resignation, acknowledgment, or just fill a pause. 'Pois pois' (doubled) is politely disinterested. Master this word and you sound immediately more natural.",
    cefrMin: "A1",
    tags: ["conversation", "daily-life"],
  },
  {
    id: "de_bacalhau",
    type: "reference",
    contentPt: "Bacalhau (365 Rezepte)",
    contentL1: "Stockfisch / Klippfisch",
    explanation: "Salted cod is Portugal's national ingredient — they claim 365 recipes, one for each day. Germany knows Stockfisch from Hanseatic trade. Portugal imported cod from Norway and Iceland for centuries. 'Bacalhau à Brás' (shredded cod with potatoes and eggs) is the most popular preparation.",
    cefrMin: "A2",
    tags: ["food", "culture"],
  },
  {
    id: "de_25_abril",
    type: "reference",
    contentPt: "25 de Abril — Revolução dos Cravos",
    contentL1: "Nelkenrevolution (wie der Mauerfall für Portugal)",
    explanation: "On April 25, 1974, Portugal peacefully overthrew its dictatorship. Soldiers put red carnations in their rifle barrels. For Portuguese people, this date is what November 9, 1989 (Mauerfall) is for Germans — the day freedom began. The bridge in Lisbon is named Ponte 25 de Abril.",
    cefrMin: "B1",
    tags: ["history", "culture", "identity"],
  },
  {
    id: "de_fixe",
    type: "expression",
    contentPt: "Fixe!",
    contentL1: "Cool! / Geil! / Toll!",
    explanation: "'Fixe' means 'cool' or 'awesome' in Portuguese slang. Use it like 'toll' or 'geil'. When something impresses you: 'Que fixe!' (How cool!). The most common positive reaction in everyday Portuguese.",
    cefrMin: "A1",
    tags: ["slang", "daily-life"],
  },
  {
    id: "de_desenrascar",
    type: "expression",
    contentPt: "Desenrascar-se",
    contentL1: "Sich durchwursteln / improvisieren",
    explanation: "The art of improvising a solution with whatever is available — like German 'sich durchwursteln' but elevated to a national philosophy. Portuguese people take pride in 'desenrascar-se'. It is the opposite of German Ordnung — and it works.",
    cefrMin: "B1",
    tags: ["culture", "daily-life"],
  },
  {
    id: "de_tu_voce",
    type: "reference",
    contentPt: "Tu vs Você vs O Senhor",
    contentL1: "du / Sie — ähnlich, aber mit Falle",
    explanation: "Like German du/Sie, Portuguese has informal 'tu' and formal 'o senhor/a senhora'. But 'você' is a trap: in Portugal (unlike Brazil), 'você' can sound cold or condescending. Default to 'tu' with peers. Use 'o senhor/a senhora' for formal situations, not 'você'.",
    cefrMin: "A1",
    tags: ["social", "grammar", "etiquette"],
  },
  {
    id: "de_wurst_vs_enchidos",
    type: "reference",
    contentPt: "Enchidos: chouriço, alheira, morcela, farinheira",
    contentL1: "Portugiesische Wurst (wie deutsche Wurstkultur)",
    explanation: "Portugal has a rich sausage tradition rivaling Germany's Wurstkultur. 'Chouriço' is smoked pork sausage (not Spanish chorizo), 'alheira' was invented by crypto-Jews to disguise non-pork sausage, 'morcela' is blood sausage like Blutwurst. A whole universe to explore.",
    cefrMin: "A2",
    tags: ["food", "culture"],
  },
  {
    id: "de_santos_populares",
    type: "reference",
    contentPt: "Festas dos Santos Populares",
    contentL1: "Volksfeste im Juni (wie Oktoberfest, aber im Sommer)",
    explanation: "Every June, Portugal celebrates street festivals for Santo António (Lisbon, June 13), São João (Porto, June 24), and São Pedro (June 29). Grilled sardines, music, and dancing fill the streets. São João in Porto involves hitting strangers on the head with plastic hammers. Think Oktoberfest energy but with sardines instead of Weisswurst.",
    cefrMin: "A2",
    tags: ["culture", "festivals"],
  },
  {
    id: "de_lisbon_porto",
    type: "reference",
    contentPt: "Lisboa vs Porto",
    contentL1: "Die Rivalität wie München vs Berlin",
    explanation: "Lisbon and Porto have a friendly rivalry like Munich and Berlin. Lisbon is the cosmopolitan capital; Porto (whose residents are called 'tripeiros', tripe-eaters) is proudly working-class and independent. Each city has its own espresso name: bica (Lisbon), cimbalino (Porto). Never tell someone from Porto that Lisbon is better.",
    cefrMin: "B1",
    tags: ["culture", "cities"],
  },
  {
    id: "de_nas_tintas",
    type: "expression",
    contentPt: "Estar-se nas tintas",
    contentL1: "Das ist mir Wurst / Das ist mir egal",
    explanation: "Literally 'to be in the paints' — means you couldn't care less. Perfect equivalent of German 'Das ist mir Wurst'. Very common in everyday speech, mildly rude depending on context.",
    cefrMin: "B1",
    tags: ["slang", "emotion"],
  },
  {
    id: "de_pronto",
    type: "expression",
    contentPt: "Pronto!",
    contentL1: "Fertig! / So! / Na gut!",
    explanation: "'Pronto' is one of the most common Portuguese words. It means 'done!', 'ready!', or 'OK then!'. Used like German 'So!' to wrap up a thought, or 'Fertig!' to signal completion. 'Pronto, vamos!' = 'So, gehen wir!'",
    cefrMin: "A1",
    tags: ["daily-life", "conversation"],
  },
  {
    id: "de_punctuality",
    type: "reference",
    contentPt: "Pontualidade à portuguesa",
    contentL1: "Pünktlichkeit auf Portugiesisch (Kulturschock)",
    explanation: "Germans are famously punctual. Portuguese are famously not. 'Vamos jantar às 20h' means dinner might start at 20:30 or later. This is not rude — it is cultural. Arriving on time to a Portuguese house party means helping set up. Adjust your German clock by 15-30 minutes.",
    cefrMin: "A2",
    tags: ["culture", "daily-life", "etiquette"],
  },
  {
    id: "de_vinho_wein",
    type: "reference",
    contentPt: "Vinho do Porto / Vinho Verde",
    contentL1: "Portwein / Vinho Verde (Weinkultur wie in Deutschland)",
    explanation: "Portugal is the world's 11th largest wine producer. Germans already know Portwein, but Vinho Verde (young, slightly sparkling white) is perfect for summer. Portugal has more grape varieties than any other country. Wine culture is as embedded as Germany's Weinkultur in the Mosel or Rhine.",
    cefrMin: "A2",
    tags: ["food", "culture"],
  },
  {
    id: "de_fique_vontade",
    type: "expression",
    contentPt: "Fique à vontade",
    contentL1: "Fühlen Sie sich wie zu Hause",
    explanation: "'Fique à vontade' literally means 'stay at will' — the Portuguese equivalent of 'Fühlen Sie sich wie zu Hause'. Hospitality is deeply valued. You will hear this immediately when visiting a Portuguese home. Accept the offer sincerely.",
    cefrMin: "A2",
    tags: ["culture", "hospitality"],
  },
  {
    id: "de_nif_bureaucracy",
    type: "reference",
    contentPt: "NIF — Número de Identificação Fiscal",
    contentL1: "Die portugiesische Steuernummer (wie die Steuer-ID)",
    explanation: "The NIF is Portugal's tax identification number. Like the German Steuer-ID, it is needed for everything: bank accounts, rental contracts, phone plans. You get it at 'as Finanças' (Finanzamt). Unlike Germany's efficient Finanzamt, expect longer queues and more paperwork. 'Preciso de um NIF' is your most important first sentence.",
    cefrMin: "A1",
    tags: ["practical", "bureaucracy"],
  },
  {
    id: "de_azulejo",
    type: "reference",
    contentPt: "Azulejos",
    contentL1: "Portugiesische Kachelkunst",
    explanation: "Portugal's signature blue-and-white ceramic tiles cover buildings, churches, train stations, and even metro stations. The tradition started with Moorish geometric patterns and evolved into figurative scenes. The Museu Nacional do Azulejo in Lisbon is a must-visit. Germany has Jugendstil tile traditions, but Portuguese azulejo is on a different scale — entire buildings are wrapped in it.",
    cefrMin: "A2",
    tags: ["art", "culture", "architecture"],
  },
  {
    id: "de_caldo_verde",
    type: "reference",
    contentPt: "Caldo verde",
    contentL1: "Grünkohlsuppe (wie norddeutsche Tradition)",
    explanation: "Portugal's most traditional soup — thinly shredded kale in potato broth with slices of chouriço. Northern Germany has Grünkohl, so the love of kale is shared. Caldo verde is served everywhere from Michelin restaurants to village festivals. It is the first 'real' Portuguese dish every newcomer should try.",
    cefrMin: "A1",
    tags: ["food", "culture"],
  },
  {
    id: "de_sardinha",
    type: "reference",
    contentPt: "Sardinhas assadas",
    contentL1: "Gegrillte Sardinen (Sommertradition)",
    explanation: "From June through August, grilled sardines are Portugal's ultimate street food. Eaten whole, on a slice of bread, with a cold beer. The smell fills entire neighbourhoods during Santos Populares festivals. Germans grill sausages; Portuguese grill sardines. The fresh sardines from Sesimbra or the Algarve are incomparable. 'Uma dose de sardinhas' at a tasca is the most Portuguese thing you can order.",
    cefrMin: "A2",
    tags: ["food", "festivals"],
  },
  {
    id: "de_bairro",
    type: "reference",
    contentPt: "Bairros de Lisboa — Alfama, Bairro Alto, Mouraria",
    contentL1: "Lissabons Kieze (wie Berliner Bezirke)",
    explanation: "Lisbon's neighbourhoods each have strong identities, like Berlin's Bezirke. Alfama is the old Moorish quarter (narrow streets, fado houses). Bairro Alto is nightlife (like Kreuzberg). Mouraria is the multicultural heart (like Neukölln). Príncipe Real is the trendy quarter (like Prenzlauer Berg). Each 'bairro' has its own cafes, tasca restaurants, and personality.",
    cefrMin: "B1",
    tags: ["cities", "culture", "daily-life"],
  },
  {
    id: "de_obrigado_danke",
    type: "expression",
    contentPt: "Obrigado / Obrigada",
    contentL1: "Danke — aber mit Geschlecht",
    explanation: "'Thank you' in Portuguese changes by the speaker's gender: men say 'obrigado', women say 'obrigada'. This is NOT about who you are thanking — it is about YOU. A man always says 'obrigado', a woman always says 'obrigada'. Germans find this surprising since 'Danke' never changes. The word comes from Latin 'obligatus' — 'I am obliged (to you)'.",
    cefrMin: "A1",
    tags: ["daily-life", "grammar"],
  },
  {
    id: "de_alentejo",
    type: "reference",
    contentPt: "Alentejo — o interior português",
    contentL1: "Alentejo — Portugals ländliche Seele",
    explanation: "South of Lisbon lies the Alentejo — vast plains, cork oak forests, and a slow pace of life that feels timeless. Like Mecklenburg-Vorpommern's empty beauty. The food is hearty and simple: migas (bread crumbs with pork), açorda (bread soup), porco preto (black Iberian pork). Wine from the Alentejo is Portugal's best-kept secret. The region is also home to Europe's largest artificial lake (Alqueva) and some of the darkest skies for stargazing.",
    cefrMin: "B1",
    tags: ["geography", "food", "culture"],
  },
  // --- MODERN SLANG ---
  {
    id: "de_bue",
    type: "expression",
    contentPt: "Bué",
    contentL1: "Voll / mega / total (Jugendslang)",
    explanation: "'Bué' means 'a lot' or 'very' — from Kimbundu (Angolan language). 'Tenho bué fome' (I'm mega hungry), 'Havia bué gente' (There were loads of people). Used like German 'voll' or 'mega' in youth speech. Ubiquitous in Lisbon and among anyone under 40. Also used as an adjective: 'É bué fixe' (It's really cool).",
    cefrMin: "A2",
    tags: ["slang", "daily-life"],
  },
  {
    id: "de_cena",
    type: "expression",
    contentPt: "Cena",
    contentL1: "Ding / Sache / Kram",
    explanation: "The ultimate placeholder word. 'Cena' literally means 'scene' but in modern PT-EU slang it means 'thing/stuff/situation'. 'Que cena!' (What a thing!), 'É uma cena estranha' (It's a weird thing). Like German 'Ding' or 'Kram'. You can use it for anything you can't name: 'Dá-me aquela cena' (Give me that thing).",
    cefrMin: "A2",
    tags: ["slang", "daily-life"],
  },
  {
    id: "de_tipo",
    type: "expression",
    contentPt: "Tipo...",
    contentL1: "So... / halt... / quasi... (Füllwort)",
    explanation: "The Portuguese 'like' filler word. 'Ele disse, tipo, que não podia vir' (He said, like, that he couldn't come). Used exactly like German 'halt' or 'quasi' in casual speech. Every young Portuguese person uses it constantly. Not appropriate in formal speech.",
    cefrMin: "A2",
    tags: ["slang", "conversation"],
  },
  {
    id: "de_ganda",
    type: "expression",
    contentPt: "Ganda / Granda",
    contentL1: "Mega / riesig / Hammer-",
    explanation: "Contraction of 'grande' — used as an intensifier. 'Ganda filme!' (What a great film!), 'Granda maluco!' (What a legend/crazy guy!). Used like German prefix 'Mega-' or 'Hammer-'. Colloquial Lisbon slang, slightly vulgar — don't use with your boss.",
    cefrMin: "B1",
    tags: ["slang"],
  },
  {
    id: "de_bazar",
    type: "expression",
    contentPt: "Bazar / Ir-se embora",
    contentL1: "Abhauen / sich verdrücken",
    explanation: "'Bazar' means 'to leave/bounce'. From Arabic 'bazara' via Brazilian Portuguese. 'Vou bazar' (I'm bouncing/leaving). Informal, like German 'Ich hau ab'. The more formal version is 'ir-se embora': 'Vou-me embora' (I'm leaving).",
    cefrMin: "B1",
    tags: ["slang", "daily-life"],
  },
  {
    id: "de_curtir",
    type: "expression",
    contentPt: "Curtir",
    contentL1: "Genießen / abfeiern / mögen",
    explanation: "'Curtir' means to enjoy or to be into something. 'Curto bué música portuguesa' (I really enjoy Portuguese music). 'Vamos curtir a noite' (Let's enjoy the night out). Also used for liking someone romantically: 'Ela curte-o' (She's into him). Like German 'abfeiern' or 'stehen auf'.",
    cefrMin: "A2",
    tags: ["slang", "daily-life"],
  },
  {
    id: "de_na_boa",
    type: "expression",
    contentPt: "Na boa",
    contentL1: "Kein Problem / alles easy",
    explanation: "'Na boa' means 'no worries / it's all good / no problem'. 'Podes usar o meu carro, na boa' (You can use my car, no problem). Also used as a question: 'Tás na boa?' (You OK?). Like German 'alles easy' or 'kein Ding'. One of the most useful casual phrases.",
    cefrMin: "A1",
    tags: ["slang", "daily-life"],
  },
  {
    id: "de_o_pa",
    type: "expression",
    contentPt: "Ó pá!",
    contentL1: "Ey! / Mann! / Alter!",
    explanation: "The quintessential Portuguese interjection. 'Ó pá, não acredito!' (Man, I can't believe it!). Used between friends, like German 'Alter!' or 'Mann!'. Short for 'rapaz' (boy). Can express surprise, frustration, or just be a casual address. Heard dozens of times daily in any Portuguese conversation between friends.",
    cefrMin: "A1",
    tags: ["slang", "daily-life"],
  },
  {
    id: "de_mano",
    type: "expression",
    contentPt: "Mano / Mana",
    contentL1: "Bruder / Schwester (Anrede unter Freunden)",
    explanation: "Short for 'irmão/irmã' (brother/sister). Used as 'bro/sis' between close friends. 'Olha, mano, ouve lá...' (Look, bro, listen...). Like German 'Bruder/Brudi' in youth slang. Very common in Lisbon, especially in multicultural neighbourhoods.",
    cefrMin: "A2",
    tags: ["slang", "daily-life"],
  },
  {
    id: "de_mandar_vir",
    type: "expression",
    contentPt: "Mandar vir",
    contentL1: "Meckern / lästern / bestellen",
    explanation: "Has two completely different meanings depending on context. 1) 'To complain/rant': 'Ele está sempre a mandar vir com tudo' (He's always complaining about everything) — like German 'meckern'. 2) 'To order': 'Manda vir mais uma cerveja' (Order another beer). Context always tells you which.",
    cefrMin: "B1",
    tags: ["slang", "daily-life"],
  },
  {
    id: "de_ta_se_bem",
    type: "expression",
    contentPt: "Tá-se bem",
    contentL1: "Passt! / Alles klar!",
    explanation: "Contraction of 'está-se bem' — 'it's all good'. Used to accept a proposal or confirm you're fine. 'Vamos ao cinema?' — 'Tá-se bem!' (Let's go to the cinema? — Sure thing!). Like German 'Passt!' or 'Alles klar!'. Very casual, very common.",
    cefrMin: "A1",
    tags: ["slang", "daily-life"],
  },
  // --- ANCIENT PROVERBS / PROVÉRBIOS ---
  {
    id: "de_cao_gato",
    type: "expression",
    contentPt: "Quem não tem cão, caça com gato",
    contentL1: "Wer keinen Hund hat, jagt mit der Katze (Improvisation)",
    explanation: "Literally: 'Who doesn't have a dog, hunts with a cat.' The proverb form of 'desenrascar-se' — make do with what you have. Germany has 'Not macht erfinderisch' (Necessity is the mother of invention). This proverb is centuries old and captures the Portuguese philosophy of creative survival with limited resources.",
    cefrMin: "B1",
    tags: ["proverb", "culture"],
  },
  {
    id: "de_agua_pedra",
    type: "expression",
    contentPt: "Água mole em pedra dura, tanto bate até que fura",
    contentL1: "Steter Tropfen höhlt den Stein",
    explanation: "Literally: 'Soft water on hard stone, hits until it pierces.' Identical in meaning to the German 'Steter Tropfen höhlt den Stein'. Both come from Latin (Ovid). Persistence wins. One of the oldest shared proverbs between Portuguese and German culture — proof that wisdom travels across languages.",
    cefrMin: "B1",
    tags: ["proverb", "wisdom"],
  },
  {
    id: "de_grao_galinha",
    type: "expression",
    contentPt: "Grão a grão, enche a galinha o papo",
    contentL1: "Kleinvieh macht auch Mist",
    explanation: "Literally: 'Grain by grain, the hen fills her crop.' Small things add up. Germany's equivalent is 'Kleinvieh macht auch Mist' (Small livestock also makes manure). Both celebrate the value of small, consistent effort. Used when someone dismisses a small gain.",
    cefrMin: "B1",
    tags: ["proverb", "wisdom"],
  },
  {
    id: "de_pepino",
    type: "expression",
    contentPt: "De pequenino se torce o pepino",
    contentL1: "Was Hänschen nicht lernt, lernt Hans nimmermehr",
    explanation: "Literally: 'You bend the cucumber when it's small.' Meaning: habits are formed young. Germany's equivalent: 'Was Hänschen nicht lernt, lernt Hans nimmermehr' (What little Hans doesn't learn, big Hans never will). Used by Portuguese parents and grandparents since forever.",
    cefrMin: "B1",
    tags: ["proverb", "education"],
  },
  {
    id: "de_tripas_coracao",
    type: "expression",
    contentPt: "Fazer das tripas coração",
    contentL1: "Sich ein Herz fassen / sich zusammenreißen",
    explanation: "Literally: 'To make heart out of guts.' To summon courage when you have none, to push through despite fear or exhaustion. Like 'sich ein Herz fassen' but more visceral. Origin debated: some link it to Porto, whose residents sent all their good meat to the Age of Discovery fleets and ate only tripe ('tripas') — hence Porto's nickname 'cidade dos tripeiros'.",
    cefrMin: "B1",
    tags: ["proverb", "history", "porto"],
  },
  {
    id: "de_ver_navios",
    type: "expression",
    contentPt: "Ficar a ver navios",
    contentL1: "In die Röhre gucken / das Nachsehen haben",
    explanation: "Literally: 'To be left watching ships.' To be left empty-handed, disappointed, stood up. Origin: during the Age of Discoveries, women waited on the docks watching ships that never returned. Like German 'in die Röhre gucken'. 'Fiquei a ver navios' = 'I was left hanging / got nothing'.",
    cefrMin: "B1",
    tags: ["proverb", "history", "discoveries"],
  },
  {
    id: "de_engolir_sapos",
    type: "expression",
    contentPt: "Engolir sapos",
    contentL1: "Die Kröte schlucken / in den sauren Apfel beißen",
    explanation: "Literally: 'To swallow frogs.' To endure insults or unfair situations without reacting. German has the nearly identical 'eine Kröte schlucken' (to swallow a toad). 'No trabalho, tenho de engolir muitos sapos' (At work, I have to swallow a lot of frogs). Ancient proverb, still used daily.",
    cefrMin: "B1",
    tags: ["proverb", "daily-life"],
  },
  {
    id: "de_burros_agua",
    type: "expression",
    contentPt: "Dar com os burros na água",
    contentL1: "Auf die Nase fallen / scheitern",
    explanation: "Literally: 'To end up with the donkeys in the water.' To fail, to have your plan go wrong. Origin: donkey drivers crossing rivers — sometimes the donkeys fell in and the cargo was lost. 'Tentei negociar mas dei com os burros na água' (I tried to negotiate but it all went wrong). Like German 'auf die Nase fallen'.",
    cefrMin: "B1",
    tags: ["proverb", "daily-life"],
  },
  {
    id: "de_rossio_betesga",
    type: "expression",
    contentPt: "Meter o Rossio na Betesga",
    contentL1: "Die Quadratur des Kreises / das Unmögliche versuchen",
    explanation: "Literally: 'To fit the Rossio (Lisbon's grand square) into the Betesga (a tiny alley nearby).' Means attempting the impossible — cramming something huge into something tiny. Like German 'die Quadratur des Kreises' (squaring the circle). A purely Lisbon-born proverb from the Middle Ages, still alive today.",
    cefrMin: "B2",
    tags: ["proverb", "lisbon", "history"],
  },
  {
    id: "de_mar_lugar",
    type: "expression",
    contentPt: "Quem vai ao mar, perde o lugar",
    contentL1: "Wer zuerst kommt, mahlt zuerst (umgekehrt)",
    explanation: "Literally: 'Who goes to sea, loses their place.' If you leave, someone else takes your spot. The inverse of German 'Wer zuerst kommt, mahlt zuerst' (First come, first served). Maritime origin — fishermen who went to sea lost their seat at the tavern. Used today for parking spots, restaurant seats, any contested position.",
    cefrMin: "A2",
    tags: ["proverb", "maritime", "daily-life"],
  },
  // --- DAILY IDIOMS ---
  {
    id: "de_ora_essa",
    type: "expression",
    contentPt: "Ora essa!",
    contentL1: "Aber nein! / Na selbstverständlich!",
    explanation: "An exclamation of modest denial when thanked or praised. 'Obrigado pela ajuda!' — 'Ora essa!' (Thank you for the help! — Oh, don't mention it!). Like German 'Aber nein!' or 'Nichts zu danken!'. Can also express surprise: 'Ora essa, quem diria!' (Well I never, who'd have thought!).",
    cefrMin: "A2",
    tags: ["daily-life", "etiquette"],
  },
  {
    id: "de_descansado",
    type: "expression",
    contentPt: "Está descansado / Fica descansado",
    contentL1: "Sei unbesorgt / Mach dir keine Sorgen",
    explanation: "Literally: 'Be rested/at ease.' Means 'don't worry about it, I've got it covered.' 'Fica descansado, eu trato disso' (Don't worry, I'll handle it). Like German 'Sei unbesorgt'. Used constantly to reassure. Feminine form: 'Fica descansada'.",
    cefrMin: "A2",
    tags: ["daily-life", "conversation"],
  },
  {
    id: "de_nao_faz_mal",
    type: "expression",
    contentPt: "Não faz mal",
    contentL1: "Macht nichts / Kein Problem",
    explanation: "Literally: 'It doesn't do harm.' The standard response when someone apologizes for a minor thing. 'Desculpa o atraso!' — 'Não faz mal!' (Sorry for being late! — No problem!). Exact equivalent of German 'Macht nichts'. One of the first phrases you'll hear and need.",
    cefrMin: "A1",
    tags: ["daily-life", "etiquette"],
  },
  {
    id: "de_deixa_la",
    type: "expression",
    contentPt: "Deixa lá",
    contentL1: "Lass mal / Vergiss es / Lass gut sein",
    explanation: "'Deixa lá' means 'let it go / forget about it / never mind.' 'Queres que te pague?' — 'Deixa lá!' (Want me to pay you back? — Forget about it!). Can also be consoling: 'Deixa lá, amanhã corre melhor' (Never mind, tomorrow will be better). Like German 'Lass gut sein'.",
    cefrMin: "A1",
    tags: ["daily-life", "conversation"],
  },
  {
    id: "de_e_o_que_e",
    type: "expression",
    contentPt: "É o que é",
    contentL1: "Es ist, was es ist / So ist das eben",
    explanation: "The Portuguese 'it is what it is' — a philosophical acceptance of things you can't change. 'O preço subiu? É o que é.' (The price went up? It is what it is.) Spoken with a shrug. Like German 'So ist das eben'. Captures the Portuguese fatalism that coexists with 'desenrascar-se'.",
    cefrMin: "A2",
    tags: ["daily-life", "culture"],
  },
  {
    id: "de_olha_la",
    type: "expression",
    contentPt: "Olha lá / Ouve lá",
    contentL1: "Hör mal / Schau mal / Sag mal",
    explanation: "'Olha lá' (look here) and 'ouve lá' (listen here) are used to get attention or start a question. 'Olha lá, sabes onde fica o correio?' (Hey, do you know where the post office is?). Like German 'Hör mal' or 'Sag mal'. Not rude — it's the standard way to approach someone.",
    cefrMin: "A1",
    tags: ["daily-life", "conversation"],
  },
  {
    id: "de_entao",
    type: "expression",
    contentPt: "Então?",
    contentL1: "Und? / Na? / Also?",
    explanation: "'Então?' is the universal Portuguese greeting-question. 'Então, tudo bem?' (So, all good?). Also used to prompt: 'Então, o que é que queres fazer?' (So, what do you want to do?). Like German 'Na?' or 'Und?'. Short, warm, multipurpose.",
    cefrMin: "A1",
    tags: ["daily-life", "conversation"],
  },
  {
    id: "de_se_calhar",
    type: "expression",
    contentPt: "Se calhar",
    contentL1: "Vielleicht / eventuell / möglicherweise",
    explanation: "Literally: 'if it falls (that way).' Means 'maybe / perhaps / possibly.' 'Se calhar vou ao cinema amanhã' (Maybe I'll go to the cinema tomorrow). More common than 'talvez' in everyday speech. Like German 'vielleicht' but with an undertone of fate deciding. Note: in PT-EU this does NOT trigger the subjunctive — unlike 'talvez'.",
    cefrMin: "A2",
    tags: ["daily-life", "grammar"],
  },
  {
    id: "de_com_certeza",
    type: "expression",
    contentPt: "Com certeza",
    contentL1: "Selbstverständlich / Sicher / Natürlich",
    explanation: "'Com certeza' means 'certainly / of course.' BUT be careful: in PT-EU it is often used as a polite but non-committal agreement — like saying 'sure' without really meaning it. A Portuguese 'com certeza' can mean 'I'll think about it' (and then forget). Germans take 'selbstverständlich' literally. Portuguese use 'com certeza' more loosely.",
    cefrMin: "A2",
    tags: ["daily-life", "etiquette", "culture"],
  },
];
