import type { CulturalRef } from "../types.js";

export const deCulturalRefs: readonly CulturalRef[] = [
  {
    id: "de_saudade",
    type: "expression",
    contentPt: "Saudade",
    contentL1: "Sehnsucht (das nächste deutsche Wort)",
    explanation: "The famous untranslatable Portuguese word. German 'Sehnsucht' is the closest equivalent — a deep longing for something absent. But saudade includes a bittersweet pleasure in the longing itself. Central to fado music, which has a similar emotional register to German Lieder traditions.",
    cefrMin: "B1",
    tags: ["culture", "emotion", "music"],
  },
  {
    id: "de_kaffee_bica",
    type: "reference",
    contentPt: "Uma bica / um galão",
    contentL1: "Espresso / Milchkaffee",
    explanation: "In Lisbon, espresso is called 'bica', not 'café'. A 'galão' is milky coffee in a tall glass — like a German Milchkaffee but stronger. Coffee culture in Portugal is as serious as Germany's Kaffee und Kuchen tradition, but faster: Portuguese stand at the counter, drink in two sips, and go.",
    cefrMin: "A1",
    tags: ["food", "daily-life"],
  },
  {
    id: "de_pasteis_kuchen",
    type: "reference",
    contentPt: "Pastéis de nata",
    contentL1: "Portugals berühmtestes Gebäck (like Kuchen culture)",
    explanation: "Flaky custard tarts found in every pastelaria for about one euro. Like German Kuchen culture but portable — eaten standing at the counter, warm, sprinkled with cinnamon. The original recipe comes from the Jerónimos monastery in Belém. Every German who visits Lisbon becomes addicted.",
    cefrMin: "A1",
    tags: ["food", "culture", "lisbon"],
  },
  {
    id: "de_fado_lieder",
    type: "reference",
    contentPt: "Fado",
    contentL1: "Fado (vergleichbar mit deutschen Liedern / Chanson)",
    explanation: "Fado is Portugal's soul music — mournful, intimate, about fate and saudade. German speakers can connect it to the Lieder tradition of Schubert or the emotional depth of Chanson. Amália Rodrigues is fado's greatest voice. Best experienced live in Alfama, Lisbon.",
    cefrMin: "B1",
    tags: ["music", "culture"],
  },
  {
    id: "de_pois",
    type: "expression",
    contentPt: "Pois...",
    contentL1: "Ja... / Na ja... / Tja...",
    explanation: "'Pois' is the most versatile Portuguese filler word, like German 'tja' or 'na ja'. It can mean agreement, resignation, acknowledgment, or just fill a pause. 'Pois pois' (doubled) is politely disinterested. Master this word and you sound immediately more natural.",
    cefrMin: "A1",
    tags: ["conversation", "daily-life"],
  },
  {
    id: "de_bacalhau",
    type: "reference",
    contentPt: "Bacalhau (365 Rezepte)",
    contentL1: "Stockfisch / Klippfisch",
    explanation: "Salted cod is Portugal's national ingredient — they claim 365 recipes, one for each day. Germany knows Stockfisch from Hanseatic trade. Portugal imported cod from Norway and Iceland for centuries. 'Bacalhau à Brás' (shredded cod with potatoes and eggs) is the most popular preparation.",
    cefrMin: "A2",
    tags: ["food", "culture"],
  },
  {
    id: "de_25_abril",
    type: "reference",
    contentPt: "25 de Abril — Revolução dos Cravos",
    contentL1: "Nelkenrevolution (wie der Mauerfall für Portugal)",
    explanation: "On April 25, 1974, Portugal peacefully overthrew its dictatorship. Soldiers put red carnations in their rifle barrels. For Portuguese people, this date is what November 9, 1989 (Mauerfall) is for Germans — the day freedom began. The bridge in Lisbon is named Ponte 25 de Abril.",
    cefrMin: "B1",
    tags: ["history", "culture", "identity"],
  },
  {
    id: "de_fixe",
    type: "expression",
    contentPt: "Fixe!",
    contentL1: "Cool! / Geil! / Toll!",
    explanation: "'Fixe' means 'cool' or 'awesome' in Portuguese slang. Use it like 'toll' or 'geil'. When something impresses you: 'Que fixe!' (How cool!). The most common positive reaction in everyday Portuguese.",
    cefrMin: "A1",
    tags: ["slang", "daily-life"],
  },
  {
    id: "de_desenrascar",
    type: "expression",
    contentPt: "Desenrascar-se",
    contentL1: "Sich durchwursteln / improvisieren",
    explanation: "The art of improvising a solution with whatever is available — like German 'sich durchwursteln' but elevated to a national philosophy. Portuguese people take pride in 'desenrascar-se'. It is the opposite of German Ordnung — and it works.",
    cefrMin: "B1",
    tags: ["culture", "daily-life"],
  },
  {
    id: "de_tu_voce",
    type: "reference",
    contentPt: "Tu vs Você vs O Senhor",
    contentL1: "du / Sie — ähnlich, aber mit Falle",
    explanation: "Like German du/Sie, Portuguese has informal 'tu' and formal 'o senhor/a senhora'. But 'você' is a trap: in Portugal (unlike Brazil), 'você' can sound cold or condescending. Default to 'tu' with peers. Use 'o senhor/a senhora' for formal situations, not 'você'.",
    cefrMin: "A1",
    tags: ["social", "grammar", "etiquette"],
  },
  {
    id: "de_wurst_vs_enchidos",
    type: "reference",
    contentPt: "Enchidos: choiriço, alheira, morcela, farinheira",
    contentL1: "Portugiesische Wurst (wie deutsche Wurstkultur)",
    explanation: "Portugal has a rich sausage tradition rivaling Germany's Wurstkultur. 'Choiriço' is smoked pork sausage (not Spanish chorizo), 'alheira' was invented by crypto-Jews to disguise non-pork sausage, 'morcela' is blood sausage like Blutwurst. A whole universe to explore.",
    cefrMin: "A2",
    tags: ["food", "culture"],
  },
  {
    id: "de_santos_populares",
    type: "reference",
    contentPt: "Festas dos Santos Populares",
    contentL1: "Volksfeste im Juni (wie Oktoberfest, aber im Sommer)",
    explanation: "Every June, Portugal celebrates street festivals for Santo António (Lisbon, June 13), São João (Porto, June 24), and São Pedro (June 29). Grilled sardines, music, and dancing fill the streets. São João in Porto involves hitting strangers on the head with plastic hammers. Think Oktoberfest energy but with sardines instead of Weisswurst.",
    cefrMin: "A2",
    tags: ["culture", "festivals"],
  },
  {
    id: "de_lisbon_porto",
    type: "reference",
    contentPt: "Lisboa vs Porto",
    contentL1: "Die Rivalität wie München vs Berlin",
    explanation: "Lisbon and Porto have a friendly rivalry like Munich and Berlin. Lisbon is the cosmopolitan capital; Porto (whose residents are called 'tripeiros', tripe-eaters) is proudly working-class and independent. Each city has its own espresso name: bica (Lisbon), cimbalino (Porto). Never tell someone from Porto that Lisbon is better.",
    cefrMin: "B1",
    tags: ["culture", "cities"],
  },
  {
    id: "de_nas_tintas",
    type: "expression",
    contentPt: "Estar-se nas tintas",
    contentL1: "Das ist mir Wurst / Das ist mir egal",
    explanation: "Literally 'to be in the paints' — means you couldn't care less. Perfect equivalent of German 'Das ist mir Wurst'. Very common in everyday speech, mildly rude depending on context.",
    cefrMin: "B1",
    tags: ["slang", "emotion"],
  },
  {
    id: "de_pronto",
    type: "expression",
    contentPt: "Pronto!",
    contentL1: "Fertig! / So! / Na gut!",
    explanation: "'Pronto' is one of the most common Portuguese words. It means 'done!', 'ready!', or 'OK then!'. Used like German 'So!' to wrap up a thought, or 'Fertig!' to signal completion. 'Pronto, vamos!' = 'So, gehen wir!'",
    cefrMin: "A1",
    tags: ["daily-life", "conversation"],
  },
  {
    id: "de_punctuality",
    type: "reference",
    contentPt: "Pontualidade à portuguesa",
    contentL1: "Pünktlichkeit auf Portugiesisch (Kulturschock)",
    explanation: "Germans are famously punctual. Portuguese are famously not. 'Vamos jantar às 20h' means dinner might start at 20:30 or later. This is not rude — it is cultural. Arriving on time to a Portuguese house party means helping set up. Adjust your German clock by 15-30 minutes.",
    cefrMin: "A2",
    tags: ["culture", "daily-life", "etiquette"],
  },
  {
    id: "de_vinho_wein",
    type: "reference",
    contentPt: "Vinho do Porto / Vinho Verde",
    contentL1: "Portwein / Vinho Verde (Weinkultur wie in Deutschland)",
    explanation: "Portugal is the world's 11th largest wine producer. Germans already know Portwein, but Vinho Verde (young, slightly sparkling white) is perfect for summer. Portugal has more grape varieties than any other country. Wine culture is as embedded as Germany's Weinkultur in the Mosel or Rhine.",
    cefrMin: "A2",
    tags: ["food", "culture"],
  },
  {
    id: "de_fique_vontade",
    type: "expression",
    contentPt: "Fique à vontade",
    contentL1: "Fühlen Sie sich wie zu Hause",
    explanation: "'Fique à vontade' literally means 'stay at will' — the Portuguese equivalent of 'Fühlen Sie sich wie zu Hause'. Hospitality is deeply valued. You will hear this immediately when visiting a Portuguese home. Accept the offer sincerely.",
    cefrMin: "A2",
    tags: ["culture", "hospitality"],
  },
];
