import type { L1Profile } from "../types.js";

export const deProfile: L1Profile = {
  code: "de",
  name: "German",
  nativeName: "Deutsch",
  writingDirection: "ltr",
  hasLatinScript: true,
  transfer: {
    cognates: [
      "Familie (família — family)",
      "Musik (música — music)",
      "Nation (nação — nation)",
      "Kultur (cultura — culture)",
      "Problem (problema — problem)",
      "Universität (universidade — university)",
      "Hospital (hospital — hospital)",
      "Gruppe (grupo — group)",
      "Person (pessoa — person)",
      "Natur (natureza — nature)",
      "Information (informação — information)",
      "Idee (ideia — idea)",
      "Moment (momento — moment)",
      "System (sistema — system)",
      "Dokument (documento — document)",
      "Energie (energia — energy)",
      "Demokratie (democracia — democracy)",
      "Philosophie (filosofia — philosophy)",
      "Transport (transporte — transport)",
      "Telefon (telefone — telephone)",
    ],
    falseFriends: [
      { word: "also", l1Meaning: "also means 'so/therefore' in German", ptMeaning: "also does not exist in PT — 'portanto' or 'então' for 'so/therefore'" },
      { word: "Gift", l1Meaning: "Gift means 'poison' in German", ptMeaning: "similar-sounding 'giz' means 'chalk' — poison = veneno" },
      { word: "bekommen", l1Meaning: "bekommen means 'to receive' in German", ptMeaning: "sounds like 'become' — receber = to receive" },
      { word: "Rat", l1Meaning: "Rat means 'advice/council' in German", ptMeaning: "rato means 'mouse' — advice = conselho" },
      { word: "Tag", l1Meaning: "Tag means 'day' in German", ptMeaning: "no PT cognate — dia means 'day'" },
      { word: "fast", l1Meaning: "fast means 'almost' in German", ptMeaning: "sounds like English 'fast' — quase = almost, rápido = fast" },
      { word: "Fabrik", l1Meaning: "Fabrik means 'factory' in German", ptMeaning: "fábrica means 'factory' — same meaning, good cognate" },
      { word: "Dom", l1Meaning: "Dom means 'cathedral' in German", ptMeaning: "Dom means 'Mr/Sir' (title) or 'gift/talent' — cathedral = catedral/sé" },
      { word: "Keller", l1Meaning: "Keller means 'cellar/basement' in German", ptMeaning: "no PT cognate — cave = cellar/basement" },
      { word: "prima", l1Meaning: "prima means 'great/excellent' in German (colloquial)", ptMeaning: "prima means 'female cousin' — great = ótimo/excelente" },
      { word: "See", l1Meaning: "See means 'lake' (der See) or 'sea' (die See) in German", ptMeaning: "sé means 'cathedral' — lake = lago, sea = mar" },
      { word: "Mal", l1Meaning: "Mal means 'time/occasion' in German (ein Mal = one time)", ptMeaning: "mal means 'badly/evil' — time = vez" },
      { word: "Mist", l1Meaning: "Mist means 'manure/rubbish' in German", ptMeaning: "misto means 'mixed' (e.g., tosta mista = grilled cheese sandwich)" },
      { word: "nota", l1Meaning: "Note means 'grade/mark' in German too", ptMeaning: "nota also means 'banknote' in PT, not just grade" },
      { word: "bar", l1Meaning: "Bar means 'bar/pub' in both languages", ptMeaning: "same meaning — but 'bar' in German also means 'cash' (bar bezahlen), which it doesn't in PT" },
      { word: "comer", l1Meaning: "sounds like 'kommen' (to come) in German", ptMeaning: "comer means 'to eat' — to come = vir/chegar" },
      { word: "largo", l1Meaning: "sounds like 'lang' (long) in German", ptMeaning: "largo means 'wide' or 'public square' — long = comprido" },
      { word: "balde", l1Meaning: "sounds like 'bald' (soon) in German", ptMeaning: "balde means 'bucket' — soon = em breve" },
      { word: "cola", l1Meaning: "Cola means 'cola drink' in German", ptMeaning: "cola means 'glue' — also slang for cheating on a test" },
      { word: "arte", l1Meaning: "Art means 'kind/type/manner' in German", ptMeaning: "arte means 'art/fine art' — kind/type = tipo/espécie" },
      { word: "carta", l1Meaning: "Karte means 'card/map/ticket' in German", ptMeaning: "carta means 'letter' — card = cartão, map = mapa" },
      { word: "taça", l1Meaning: "sounds like 'Tasse' (teacup) in German", ptMeaning: "taça means 'trophy/wine glass/goblet' — teacup = chávena" },
      { word: "pena", l1Meaning: "sounds like 'Pein' (agony) in old German", ptMeaning: "pena means 'feather' or 'pity' or 'penalty' — agony = agonia" },
      { word: "caro", l1Meaning: "sounds like 'Karo' (diamonds/check pattern)", ptMeaning: "caro means 'expensive' or 'dear'" },
      { word: "falar", l1Meaning: "sounds like 'fallen' (to fall) in German", ptMeaning: "falar means 'to speak' — to fall = cair" },
      { word: "ata", l1Meaning: "no German cognate, but looks like 'hat' backwards", ptMeaning: "ata means 'minutes (of a meeting)' — do not confuse with até (until)" },
      { word: "vaga", l1Meaning: "sounds like 'vage' (vague) in German", ptMeaning: "vaga means 'wave' or 'vacancy' — vague = vago (different word)" },
    ],
    phoneticDifficulties: [
      {
        sound: "ão",
        ipa: "/ɐ̃w̃/",
        description: "Nasal diphthong -ão",
        tip: "German has no nasal vowels at all. Start with an open 'a', let air through your nose, then glide to a nasal 'u'. Practice with 'pão', 'mão', 'não' daily.",
        mouthPosition: "nasal_ao",
      },
      {
        sound: "ã/õ/ẽ",
        ipa: "/ɐ̃/ /õ/ /ẽ/",
        description: "Nasal vowels",
        tip: "German never nasalizes vowels. Lower your soft palate to let air through the nose while holding the vowel. 'Maçã' (apple), 'limão' (lemon), 'irmã' (sister).",
        mouthPosition: "nasal_vowel",
      },
      {
        sound: "reduced vowels",
        ipa: "/ɨ/ /ə/",
        description: "Unstressed vowels nearly vanish",
        tip: "German pronounces every syllable clearly. PT-EU swallows unstressed vowels — 'telefonema' sounds like 'tlfnema'. This is the biggest rhythm difference.",
      },
      {
        sound: "open/closed e",
        ipa: "/ɛ/ vs /e/",
        description: "Two e sounds that change meaning",
        tip: "German has similar pairs (Bett vs beten). PT-EU uses accents: 'é' is open (/ɛ/ as in 'café'), 'ê' is closed (/e/ as in 'você'). 'Avó' (grandmother) vs 'avô' (grandfather).",
        mouthPosition: "open_e",
      },
      {
        sound: "open/closed o",
        ipa: "/ɔ/ vs /o/",
        description: "Two o sounds",
        tip: "Open 'ó' (/ɔ/) vs closed 'ô' (/o/). German has this distinction too, so use your instinct. The accent marks tell you which one.",
        mouthPosition: "open_o",
      },
      {
        sound: "lh",
        ipa: "/ʎ/",
        description: "Palatal lateral lh",
        tip: "No German equivalent. Press the flat of your tongue against the hard palate while making an L. 'Trabalho' (work), 'filho' (son), 'olho' (eye).",
        mouthPosition: "palatal_lateral",
      },
      {
        sound: "nh",
        ipa: "/ɲ/",
        description: "Palatal nasal nh",
        tip: "Like English 'ny' in 'canyon'. German doesn't have this either. 'Espanha' (Spain), 'vinho' (wine), 'amanhã' (tomorrow).",
        mouthPosition: "palatal_nasal",
      },
      {
        sound: "r/rr",
        ipa: "/ʁ/",
        description: "Uvular R (initial and double)",
        tip: "Good news for Germans: PT-EU initial R and double RR are uvular, very similar to the standard German R. Use your normal German R for 'rato' (mouse) and 'carro' (car).",
        mouthPosition: "uvular_r",
      },
      {
        sound: "r (between vowels)",
        ipa: "/ɾ/",
        description: "Alveolar tap (intervocalic)",
        tip: "Single 'r' between vowels is a quick flap — NOT the uvular R. 'Caro' (expensive) has a light tap. Germans often over-pronounce this with their uvular R.",
        mouthPosition: "alveolar_tap",
      },
      {
        sound: "s/z/ʃ/ʒ",
        ipa: "/s/ /z/ /ʃ/ /ʒ/",
        description: "Four sibilants",
        tip: "German has s, z, and sch. PT-EU final 's' becomes /ʃ/ ('os livros' = 'osh livrosh'). 'J' and 'g' before e/i are /ʒ/ (French-like). Germans often use /dʒ/ instead of pure /ʒ/.",
        mouthPosition: "sibilant_sh",
      },
      {
        sound: "b/v distinction",
        ipa: "/b/ vs /v/",
        description: "B and V are always distinct",
        tip: "German distinguishes b and w (not v). PT-EU 'v' is labiodental (teeth on lip, like German 'w'). PT-EU 'b' is a stop. 'Bola' (ball) vs 'vela' (candle).",
        mouthPosition: "labiodental_v",
      },
      {
        sound: "dark L",
        ipa: "/ɫ/",
        description: "Velarized L at end of syllables",
        tip: "German L is always clear/light. PT-EU final L is dark and thick, almost like a 'w'. 'Portugal', 'sol' (sun), 'mal' (badly) — the L is heavy at the back of the mouth.",
      },
      {
        sound: "word-final -e",
        ipa: "/ɨ/ or silent",
        description: "Final -e nearly disappears",
        tip: "German Schwa (e in 'bitte') is similar but still audible. PT-EU final -e is barely a whisper or drops entirely. 'Cidade' sounds like 'cidadɨ' or even 'cidad'.",
      },
    ],
    grammarGaps: [
      {
        concept: "No case system",
        explanation: "Portuguese has no grammatical cases — word function is shown by prepositions and word order",
        l1Comparison: "German has Nominativ, Akkusativ, Dativ, Genitiv. PT-EU dropped all cases (inherited from Latin). Instead of case endings, use prepositions: 'de' (genitive function), 'a/para' (dative), direct objects have no marker.",
      },
      {
        concept: "Only 2 genders",
        explanation: "Portuguese has masculine and feminine only — no neuter",
        l1Comparison: "German has der/die/das. PT-EU has only o (m) and a (f). Gender assignments often differ: 'das Mädchen' (neuter) → 'a rapariga' (feminine). Learn each noun with its article.",
      },
      {
        concept: "Ser vs Estar",
        explanation: "Two verbs for 'to be' — ser for identity, estar for states",
        l1Comparison: "German uses only 'sein'. PT-EU splits: 'Sou alemão' (I am German — ser, permanent) vs 'Estou cansado' (I am tired — estar, temporary). The choice changes meaning.",
      },
      {
        concept: "Personal infinitive",
        explanation: "Infinitive conjugated for person: falar, falares, falar, falarmos, falardes, falarem",
        l1Comparison: "Doesn't exist in German. Used after prepositions: 'Para eles entenderem' (for them to understand). Replaces a full dass-clause in many cases.",
      },
      {
        concept: "Subjunctive mood",
        explanation: "Actively used for doubt, desire, emotion, uncertainty",
        l1Comparison: "German Konjunktiv II is mostly hypothetical ('wenn ich wäre'). PT-EU subjunctive is required in everyday speech: 'Espero que venhas' (I hope you come), 'Talvez chova' (Maybe it rains).",
      },
      {
        concept: "Future subjunctive",
        explanation: "Used for uncertain future events: 'quando eu for' (when I go)",
        l1Comparison: "German has no future subjunctive at all. PT-EU uses it daily in 'quando' (when), 'se' (if) clauses about the future: 'Se quiseres' (if you want).",
      },
      {
        concept: "Tu vs Você",
        explanation: "PT-EU uses 'tu' as default informal, 'você' is formal/distant",
        l1Comparison: "Like German du/Sie, but with a twist: 'você' in Portugal can sound condescending or cold. Default to 'tu' with peers. 'O senhor/a senhora' is the safest formal.",
      },
      {
        concept: "Preposition contractions",
        explanation: "Mandatory: em+o=no, de+a=da, a+o=ao, por+o=pelo, etc.",
        l1Comparison: "German has 'im' (in dem), 'zum' (zu dem). PT-EU has many more mandatory contractions: no, na, do, da, ao, à, pelo, pela, num, numa. You cannot separate them.",
      },
      {
        concept: "Continuous with 'estar a + infinitive'",
        explanation: "PT-EU ongoing actions: 'Estou a trabalhar' (I am working)",
        l1Comparison: "German uses present tense for ongoing actions ('Ich arbeite gerade'). PT-EU requires the construction 'estar a + infinitive'. The gerund form ('estou trabalhando') is Brazilian.",
      },
      {
        concept: "Object pronoun placement",
        explanation: "Complex enclisis (after) and proclisis (before) rules",
        l1Comparison: "German puts pronouns in fixed positions. PT-EU defaults to after the verb ('Dá-me') but moves before with negative/question words ('Não me dás'). Mesoclisis exists too: 'Dir-lhe-ei'.",
      },
      {
        concept: "Definite article with possessives",
        explanation: "'O meu carro' — article + possessive + noun",
        l1Comparison: "German drops the article: 'mein Auto'. PT-EU keeps both: 'o meu carro'. Omitting the article sounds Brazilian.",
      },
      {
        concept: "Definite article with names",
        explanation: "'A Maria', 'o João' — articles before proper names",
        l1Comparison: "German doesn't use articles with names (except in Bavarian dialect). PT-EU always uses them: 'A Maria vem amanhã'. This is standard, not informal.",
      },
      {
        concept: "Pretérito perfeito simples vs composto",
        explanation: "Simple past = single event; compound past = repeated/ongoing past action",
        l1Comparison: "German splits Perfekt (conversational past) and Präteritum (written past). PT-EU splits differently: 'Comi' (I ate, once) vs 'Tenho comido' (I have been eating, repeatedly). Not the same as German Perfekt.",
      },
      {
        concept: "Haver vs Ter",
        explanation: "PT-EU uses 'ter' as both possession and perfect auxiliary",
        l1Comparison: "German splits 'haben' (have) and uses it as auxiliary. PT-EU uses 'ter' for both: 'Eu tenho um carro' (I have a car) AND 'Eu tenho feito' (I have done). 'Haver' is impersonal: 'Há muitas pessoas' (there are many people).",
      },
    ],
    skipBasics: false,
    startingCEFR: "A1",
  },
};
