import type { CulturalRef } from "../types.js";

export const plCulturalRefs: readonly CulturalRef[] = [
  {
    id: "pl_saudade",
    type: "expression",
    contentPt: "Saudade",
    contentL1: "Tęsknota / Żal",
    explanation: "Polish 'tęsknota' (longing) and 'żal' (sadness/regret) together approximate saudade. Both cultures have a deep tradition of melancholic art — fado in Portugal, Chopin in Poland. The Slavic soul meets the Portuguese alma.",
    cefrMin: "B1",
    tags: ["culture", "emotion"],
  },
  {
    id: "pl_fixe",
    type: "expression",
    contentPt: "Fixe!",
    contentL1: "Super! / Ekstra!",
    explanation: "'Fixe' means 'cool'. Use it like super or ekstra. 'Que fixe!' = Ale super!",
    cefrMin: "A1",
    tags: ["slang", "daily-life"],
  },
  {
    id: "pl_pois",
    type: "expression",
    contentPt: "Pois...",
    contentL1: "No... / No właśnie...",
    explanation: "'Pois' is the most versatile Portuguese filler, like Polish 'no' or 'no właśnie'. It fills pauses and expresses agreement or resignation.",
    cefrMin: "A1",
    tags: ["conversation", "daily-life"],
  },
  {
    id: "pl_pasteis",
    type: "reference",
    contentPt: "Pastéis de nata",
    contentL1: "Babeczki z kremem (ale flaky ciasto)",
    explanation: "Flaky custard tarts for about one euro. Like Polish kremowe babeczki but lighter and caramelized. Found in every pastelaria. Eat warm with cinnamon.",
    cefrMin: "A1",
    tags: ["food", "culture"],
  },
  {
    id: "pl_fado",
    type: "reference",
    contentPt: "Fado",
    contentL1: "Jak piosenki Chopina (muzyka losu)",
    explanation: "Fado's emotional depth connects to Poland's own musical melancholy — Chopin's nocturnes, Polish patriotic songs about exile. Both traditions channel national identity through sorrow.",
    cefrMin: "B1",
    tags: ["music", "culture"],
  },
  {
    id: "pl_bacalhau",
    type: "reference",
    contentPt: "Bacalhau",
    contentL1: "Dorsz solony (365 przepisów)",
    explanation: "Salt cod is Portugal's national dish. Poland also has a strong fish tradition, especially carp at Christmas. Bacalhau is dried and salted, served in hundreds of preparations.",
    cefrMin: "A2",
    tags: ["food", "culture"],
  },
  {
    id: "pl_25_abril",
    type: "reference",
    contentPt: "25 de Abril — Revolução dos Cravos",
    contentL1: "Rewolucja Goździków (1974)",
    explanation: "Portugal's peaceful democratic revolution in 1974. Soldiers put carnations in their rifles. Poles, who lived through Solidarity and 1989, can deeply appreciate a peaceful transition from dictatorship to democracy.",
    cefrMin: "B1",
    tags: ["history", "identity"],
  },
  {
    id: "pl_pronto",
    type: "expression",
    contentPt: "Pronto!",
    contentL1: "Gotowe! / No to co!",
    explanation: "'Pronto' = done/ready/OK then. Like gotowe or 'no to co'. 'Pronto, vamos!' = No to jedźmy!",
    cefrMin: "A1",
    tags: ["daily-life", "conversation"],
  },
  {
    id: "pl_diaspora",
    type: "reference",
    contentPt: "Comunidade polaca em Portugal",
    contentL1: "Polska społeczność w Portugalii",
    explanation: "There is a small but growing Polish community in Portugal, especially since remote work made Lisbon and the Algarve popular with European workers. Polish shops and communities exist in Lisbon.",
    cefrMin: "A2",
    tags: ["culture", "community"],
  },
  {
    id: "pl_catholicism",
    type: "reference",
    contentPt: "Fátima e o catolicismo",
    contentL1: "Fatima i katolicyzm (jak Częstochowa)",
    explanation: "Portugal and Poland are both deeply Catholic countries. Fátima is to Portugal what Częstochowa is to Poland — a national pilgrimage site. Pope John Paul II credited Our Lady of Fátima with saving his life.",
    cefrMin: "B1",
    tags: ["religion", "culture"],
  },
  {
    id: "pl_tu_voce",
    type: "reference",
    contentPt: "Tu vs O Senhor",
    contentL1: "Ty vs Pan/Pani",
    explanation: "Like Polish ty/Pan/Pani, Portuguese has 'tu' (informal) and 'o senhor/a senhora' (formal). Polish speakers will feel at home with this formality system. Avoid 'você' in Portugal — it can sound cold.",
    cefrMin: "A1",
    tags: ["social", "etiquette"],
  },
  {
    id: "pl_desenrascar",
    type: "expression",
    contentPt: "Desenrascar-se",
    contentL1: "Kombinować / Dać radę",
    explanation: "The art of improvising solutions. Like Polish kombinować or dać sobie radę. Both cultures celebrate creative problem-solving under pressure.",
    cefrMin: "B1",
    tags: ["culture", "daily-life"],
  },
  {
    id: "pl_family",
    type: "reference",
    contentPt: "Família é tudo",
    contentL1: "Rodzina jest najważniejsza",
    explanation: "Like Polish culture, Portuguese culture is deeply family-oriented. Sunday lunches are sacred. Grandparents help raise children. The family closeness will feel very natural.",
    cefrMin: "A2",
    tags: ["culture", "family"],
  },
  {
    id: "pl_santos",
    type: "reference",
    contentPt: "Festas dos Santos Populares",
    contentL1: "Festyny ludowe (jak Noc Świętojańska)",
    explanation: "June street festivals with sardines and dancing. São João (June 24) coincides with Polish Noc Świętojańska — both are midsummer celebrations with fire and communal joy.",
    cefrMin: "A2",
    tags: ["culture", "festivals"],
  },
  {
    id: "pl_nas_tintas",
    type: "expression",
    contentPt: "Estar-se nas tintas",
    contentL1: "Mam to gdzies / Mnie to nie obchodzi",
    explanation: "Literally 'to be in the paints' — couldn't care less. Like 'mam to gdzies'. Very common, mildly rude.",
    cefrMin: "B1",
    tags: ["slang", "emotion"],
  },
];
