import type { CulturalRef } from "../types.js";

export const plCulturalRefs: readonly CulturalRef[] = [
  {
    id: "pl_saudade",
    type: "expression",
    contentPt: "Saudade",
    contentL1: "Tęsknota / Żal",
    explanation: "Polish 'tęsknota' (longing) and 'żal' (sadness/regret) together approximate saudade. Both cultures have a deep tradition of melancholic art — fado in Portugal, Chopin in Poland. The Slavic soul meets the Portuguese alma.",
    cefrMin: "B1",
    tags: ["culture", "emotion"],
  },
  {
    id: "pl_fixe",
    type: "expression",
    contentPt: "Fixe!",
    contentL1: "Super! / Ekstra!",
    explanation: "'Fixe' means 'cool'. Use it like super or ekstra. 'Que fixe!' = Ale super!",
    cefrMin: "A1",
    tags: ["slang", "daily-life"],
  },
  {
    id: "pl_pois",
    type: "expression",
    contentPt: "Pois...",
    contentL1: "No... / No właśnie...",
    explanation: "'Pois' is the most versatile Portuguese filler, like Polish 'no' or 'no właśnie'. It fills pauses and expresses agreement or resignation.",
    cefrMin: "A1",
    tags: ["conversation", "daily-life"],
  },
  {
    id: "pl_pasteis",
    type: "reference",
    contentPt: "Pastéis de nata",
    contentL1: "Babeczki z kremem (ale flaky ciasto)",
    explanation: "Flaky custard tarts for about one euro. Like Polish kremowe babeczki but lighter and caramelized. Found in every pastelaria. Eat warm with cinnamon.",
    cefrMin: "A1",
    tags: ["food", "culture"],
  },
  {
    id: "pl_fado",
    type: "reference",
    contentPt: "Fado",
    contentL1: "Jak piosenki Chopina (muzyka losu)",
    explanation: "Fado's emotional depth connects to Poland's own musical melancholy — Chopin's nocturnes, Polish patriotic songs about exile. Both traditions channel national identity through sorrow.",
    cefrMin: "B1",
    tags: ["music", "culture"],
  },
  {
    id: "pl_bacalhau",
    type: "reference",
    contentPt: "Bacalhau",
    contentL1: "Dorsz solony (365 przepisów)",
    explanation: "Salt cod is Portugal's national dish. Poland also has a strong fish tradition, especially carp at Christmas. Bacalhau is dried and salted, served in hundreds of preparations.",
    cefrMin: "A2",
    tags: ["food", "culture"],
  },
  {
    id: "pl_25_abril",
    type: "reference",
    contentPt: "25 de Abril — Revolução dos Cravos",
    contentL1: "Rewolucja Goździków (1974)",
    explanation: "Portugal's peaceful democratic revolution in 1974. Soldiers put carnations in their rifles. Poles, who lived through Solidarity and 1989, can deeply appreciate a peaceful transition from dictatorship to democracy.",
    cefrMin: "B1",
    tags: ["history", "identity"],
  },
  {
    id: "pl_pronto",
    type: "expression",
    contentPt: "Pronto!",
    contentL1: "Gotowe! / No to co!",
    explanation: "'Pronto' = done/ready/OK then. Like gotowe or 'no to co'. 'Pronto, vamos!' = No to jedźmy!",
    cefrMin: "A1",
    tags: ["daily-life", "conversation"],
  },
  {
    id: "pl_diaspora",
    type: "reference",
    contentPt: "Comunidade polaca em Portugal",
    contentL1: "Polska społeczność w Portugalii",
    explanation: "There is a small but growing Polish community in Portugal, especially since remote work made Lisbon and the Algarve popular with European workers. Polish shops and communities exist in Lisbon.",
    cefrMin: "A2",
    tags: ["culture", "community"],
  },
  {
    id: "pl_catholicism",
    type: "reference",
    contentPt: "Fátima e o catolicismo",
    contentL1: "Fatima i katolicyzm (jak Częstochowa)",
    explanation: "Portugal and Poland are both deeply Catholic countries. Fátima is to Portugal what Częstochowa is to Poland — a national pilgrimage site. Pope John Paul II credited Our Lady of Fátima with saving his life.",
    cefrMin: "B1",
    tags: ["religion", "culture"],
  },
  {
    id: "pl_tu_voce",
    type: "reference",
    contentPt: "Tu vs O Senhor",
    contentL1: "Ty vs Pan/Pani",
    explanation: "Like Polish ty/Pan/Pani, Portuguese has 'tu' (informal) and 'o senhor/a senhora' (formal). Polish speakers will feel at home with this formality system. Avoid 'você' in Portugal — it can sound cold.",
    cefrMin: "A1",
    tags: ["social", "etiquette"],
  },
  {
    id: "pl_desenrascar",
    type: "expression",
    contentPt: "Desenrascar-se",
    contentL1: "Kombinować / Dać radę",
    explanation: "The art of improvising solutions. Like Polish kombinować or dać sobie radę. Both cultures celebrate creative problem-solving under pressure.",
    cefrMin: "B1",
    tags: ["culture", "daily-life"],
  },
  {
    id: "pl_family",
    type: "reference",
    contentPt: "Família é tudo",
    contentL1: "Rodzina jest najważniejsza",
    explanation: "Like Polish culture, Portuguese culture is deeply family-oriented. Sunday lunches are sacred. Grandparents help raise children. The family closeness will feel very natural.",
    cefrMin: "A2",
    tags: ["culture", "family"],
  },
  {
    id: "pl_santos",
    type: "reference",
    contentPt: "Festas dos Santos Populares",
    contentL1: "Festyny ludowe (jak Noc Świętojańska)",
    explanation: "June street festivals with sardines and dancing. São João (June 24) coincides with Polish Noc Świętojańska — both are midsummer celebrations with fire and communal joy.",
    cefrMin: "A2",
    tags: ["culture", "festivals"],
  },
  {
    id: "pl_nas_tintas",
    type: "expression",
    contentPt: "Estar-se nas tintas",
    contentL1: "Mam to gdzies / Mnie to nie obchodzi",
    explanation: "Literally 'to be in the paints' — couldn't care less. Like 'mam to gdzies'. Very common, mildly rude.",
    cefrMin: "B1",
    tags: ["slang", "emotion"],
  },
  {
    id: "pl_procissoes",
    type: "reference",
    contentPt: "Procissões e romarias",
    contentL1: "Procesje i pielgrzymki (jak Boże Ciało)",
    explanation: "Portugal's religious processions mirror Polish Boże Ciało (Corpus Christi) parades. Entire villages carry saints through the streets with flowers, candles, and music. Polish Catholics will recognise the ritual immediately — the scent of incense, the solemnity, the communal prayer. The Semana Santa processions in Braga rival anything in Poland.",
    cefrMin: "A2",
    tags: ["religion", "culture", "festivals"],
  },
  {
    id: "pl_polish_community",
    type: "reference",
    contentPt: "Polacos em Portugal",
    contentL1: "Polacy w Portugalii — rosnąca społeczność",
    explanation: "The Polish community in Portugal has grown significantly since EU free movement. Lisbon, Porto, and the Algarve attract Polish remote workers and retirees. Polish shops (sklep polski) exist in major cities. The SEF/AIMA office, NIF tax number, and conta bancária are the first bureaucratic steps — ask any Pole who has done it.",
    cefrMin: "A2",
    tags: ["community", "practical", "daily-life"],
  },
  {
    id: "pl_ginjinha_nalewka",
    type: "reference",
    contentPt: "Ginjinha e tasquinhas",
    contentL1: "Ginjinha — jak nalewka wiśniowa",
    explanation: "Ginjinha is a cherry liqueur served in tiny cups at hole-in-the-wall bars in Lisbon — Poles will immediately think of nalewka wiśniowa. A shot costs about one euro. The ritual of standing at a tiny counter, drinking one small glass, and continuing your walk is pure Portuguese street culture. 'Tasquinhas' are the traditional neighbourhood bars where old men play cards — like Polish gospodas.",
    cefrMin: "A2",
    tags: ["food", "culture", "daily-life"],
  },
  // --- MODERN SLANG ---
  {
    id: "pl_bue",
    type: "expression",
    contentPt: "Bué",
    contentL1: "Mega / Strasznie / Full",
    explanation: "'Bué' means 'a lot' or 'very' in PT-EU slang, from Kimbundu (Angolan). 'Bué fixe' (mega fajne), 'bué gente' (strasznie dużo ludzi). Like Polish youth slang 'full' or 'mega'. Used by anyone under 40, ubiquitous in Lisbon.",
    cefrMin: "A2",
    tags: ["slang", "daily-life"],
  },
  {
    id: "pl_cena",
    type: "expression",
    contentPt: "Cena",
    contentL1: "Coś / Rzecz / Sprawa",
    explanation: "Originally 'scene' but in PT-EU slang means 'thing/stuff/situation'. 'Que cena!' (Co za sprawa!), 'é uma cena estranha' (to dziwna rzecz). Like Polish 'coś tam' or 'sprawa'. Universal placeholder — 'dá-me aquela cena' (daj mi tę rzecz).",
    cefrMin: "A2",
    tags: ["slang", "daily-life"],
  },
  {
    id: "pl_tipo",
    type: "expression",
    contentPt: "Tipo...",
    contentL1: "Jakby... / Typu... / No wiesz...",
    explanation: "The Portuguese filler word, like Polish 'jakby' or 'no wiesz'. 'Ele é tipo alto' (On jest jakby wysoki). Every young Portuguese person uses it constantly. Not formal, but extremely natural in conversation.",
    cefrMin: "A2",
    tags: ["slang", "conversation"],
  },
  {
    id: "pl_ganda",
    type: "expression",
    contentPt: "Ganda / Granda",
    contentL1: "Mega / Kozak / Petarda",
    explanation: "Contraction of 'grande' — intensifier meaning 'great/massive'. 'Ganda filme!' (Mega film!), 'granda maluco!' (kozak!). Like Polish 'kozak' or 'petarda'. Lisbon street slang, don't use with your professor.",
    cefrMin: "B1",
    tags: ["slang"],
  },
  {
    id: "pl_bazar",
    type: "expression",
    contentPt: "Bazar",
    contentL1: "Spadać / Zwijać się / Lecieć",
    explanation: "'Bazar' means 'to leave/bounce'. 'Vou bazar' (spadam). Like Polish 'spadam' or 'zwijam się'. Nothing to do with a marketplace. 'Ele bazou' = 'on spadł'. Informal departure.",
    cefrMin: "B1",
    tags: ["slang", "daily-life"],
  },
  {
    id: "pl_curtir",
    type: "expression",
    contentPt: "Curtir",
    contentL1: "Kręcić się na czymś / Jarać się / Lubić",
    explanation: "'Curtir' means to enjoy, to be into something. 'Curto bué este sítio' (mega mi się tu podoba). Also romantic: 'Ela curte-o' (ona się na nim kręci). Like Polish 'jarać się' or 'kręcić się na'.",
    cefrMin: "A2",
    tags: ["slang", "daily-life"],
  },
  {
    id: "pl_na_boa",
    type: "expression",
    contentPt: "Na boa",
    contentL1: "Spoko / Luz / Bez stresu",
    explanation: "'Na boa' = 'no worries / it's all good'. 'Podes ficar, na boa' (Możesz zostać, spoko). Also a question: 'Tás na boa?' (Spoko jesteś?). Exact equivalent of Polish 'spoko' or 'luz'. One of the most useful casual phrases.",
    cefrMin: "A1",
    tags: ["slang", "daily-life"],
  },
  {
    id: "pl_o_pa",
    type: "expression",
    contentPt: "Ó pá!",
    contentL1: "Stary! / Człowieku! / Ej!",
    explanation: "The quintessential Portuguese interjection. 'Ó pá, não acredito!' (Stary, nie wierzę!). Used between friends like Polish 'stary!' or 'ej!'. Short for 'rapaz'. Express surprise, frustration, or casual address. Heard dozens of times daily.",
    cefrMin: "A1",
    tags: ["slang", "daily-life"],
  },
  {
    id: "pl_mano",
    type: "expression",
    contentPt: "Mano / Mana",
    contentL1: "Bracie / Ziom / Siostra",
    explanation: "Short for 'irmão/irmã' (brother/sister). Used as 'bro/sis' between close friends. 'Olha, mano' (Ej, ziom). Like Polish 'bracie' or 'ziom'. Very common in Lisbon, especially in multicultural neighbourhoods like Mouraria and Amadora.",
    cefrMin: "A2",
    tags: ["slang", "daily-life"],
  },
  {
    id: "pl_mandar_vir",
    type: "expression",
    contentPt: "Mandar vir",
    contentL1: "Narzekać / Zamawiać (dwa znaczenia!)",
    explanation: "Two completely different meanings: 1) 'To complain/rant': 'Ele está sempre a mandar vir' (On ciągle narzeka) — like Polish 'narzekać'. 2) 'To order': 'Manda vir mais uma cerveja' (Zamów jeszcze jedno piwo). Context tells you which. Poles will appreciate the narzekanie aspect.",
    cefrMin: "B1",
    tags: ["slang", "daily-life"],
  },
  {
    id: "pl_ta_se_bem",
    type: "expression",
    contentPt: "Tá-se bem",
    contentL1: "Spoko! / Okej! / Gituwa!",
    explanation: "Contraction of 'está-se bem' — 'it's all good'. 'Vamos ao cinema?' — 'Tá-se bem!' (Idziemy do kina? — Spoko!). Like Polish 'gituwa' or 'okej'. Very casual, very common agreement.",
    cefrMin: "A1",
    tags: ["slang", "daily-life"],
  },
  // --- ANCIENT PROVERBS ---
  {
    id: "pl_agua_pedra",
    type: "expression",
    contentPt: "Água mole em pedra dura, tanto bate até que fura",
    contentL1: "Kropla drąży skałę",
    explanation: "Literally: 'Soft water on hard stone, hits until it pierces.' Identical to Polish 'Kropla drąży skałę' (A drop hollows the rock). Both from Latin (Ovid). Persistence wins. One of the oldest shared proverbs between Portuguese and Polish — proof that wisdom crosses borders.",
    cefrMin: "B1",
    tags: ["proverb", "wisdom"],
  },
  {
    id: "pl_cao_gato",
    type: "expression",
    contentPt: "Quem não tem cão, caça com gato",
    contentL1: "Jak nie ma co, to i rakiem na wojnę",
    explanation: "Literally: 'Who doesn't have a dog, hunts with a cat.' Make do with what you have. The Polish equivalent 'Jak nie ma co, to i rakiem na wojnę' (If there's nothing else, even a crab goes to war) has the same spirit. Both celebrate resourcefulness with limited tools.",
    cefrMin: "B1",
    tags: ["proverb", "culture"],
  },
  {
    id: "pl_grao_galinha",
    type: "expression",
    contentPt: "Grão a grão, enche a galinha o papo",
    contentL1: "Ziarnko do ziarnka, a zbierze się miarka",
    explanation: "Literally: 'Grain by grain, the hen fills her crop.' Small things add up. The Polish 'Ziarnko do ziarnka, a zbierze się miarka' (Grain by grain, a full measure gathers) is remarkably close — same image, same wisdom. Used when someone dismisses a small gain.",
    cefrMin: "B1",
    tags: ["proverb", "wisdom"],
  },
  {
    id: "pl_pepino",
    type: "expression",
    contentPt: "De pequenino se torce o pepino",
    contentL1: "Czego Jaś się nie nauczy, tego Jan nie będzie umiał",
    explanation: "Literally: 'You bend the cucumber when it's small.' Habits are formed young. Poland's equivalent: 'Czego Jaś się nie nauczy, tego Jan nie będzie umiał' (What little Jan doesn't learn, big Jan won't know). Used by parents and grandparents since forever, in both countries.",
    cefrMin: "B1",
    tags: ["proverb", "education"],
  },
  {
    id: "pl_tripas_coracao",
    type: "expression",
    contentPt: "Fazer das tripas coração",
    contentL1: "Zebrać się na odwagę / Wziąć się w garść",
    explanation: "Literally: 'To make heart out of guts.' To summon courage when you have none. Like Polish 'wziąć się w garść' (to pull yourself together) or 'zebrać się na odwagę'. Origin linked to Porto — residents sent their good meat to the ships and ate only tripe, hence Porto's nickname 'cidade dos tripeiros'.",
    cefrMin: "B1",
    tags: ["proverb", "history"],
  },
  {
    id: "pl_ver_navios",
    type: "expression",
    contentPt: "Ficar a ver navios",
    contentL1: "Zostać z niczym / Zostać na lodzie",
    explanation: "Literally: 'To be left watching ships.' To be left empty-handed, stood up. Origin: during the Age of Discoveries, women waited on docks for ships that never returned. Like Polish 'zostać na lodzie' (to be left on the ice) or 'zostać z niczym'.",
    cefrMin: "B1",
    tags: ["proverb", "history"],
  },
  {
    id: "pl_engolir_sapos",
    type: "expression",
    contentPt: "Engolir sapos",
    contentL1: "Połknąć żabę / Gryźć się w język",
    explanation: "Literally: 'To swallow frogs.' To endure insults silently. Polish has the nearly identical 'połknąć żabę' (to swallow a frog). 'No trabalho, tenho de engolir muitos sapos' (W pracy muszę połknąć wiele żab). Ancient proverb, still used daily.",
    cefrMin: "B1",
    tags: ["proverb", "daily-life"],
  },
  {
    id: "pl_burros_agua",
    type: "expression",
    contentPt: "Dar com os burros na água",
    contentL1: "Spalić na panewce / Nie wypalić",
    explanation: "Literally: 'To end up with the donkeys in the water.' To fail completely. Origin: donkey drivers crossing rivers — sometimes the donkeys fell in and the cargo was lost. Like Polish 'spalić na panewce' (to burn on the pan). 'Tentei mas dei com os burros na água' (Próbowałem ale spalił mi na panewce).",
    cefrMin: "B1",
    tags: ["proverb", "daily-life"],
  },
  {
    id: "pl_rossio_betesga",
    type: "expression",
    contentPt: "Meter o Rossio na Betesga",
    contentL1: "Kwadratura koła",
    explanation: "Literally: 'To fit the Rossio (Lisbon's grand square) into the Betesga (a tiny alley nearby).' Attempting the impossible. Like Polish 'kwadratura koła' (squaring the circle). A purely Lisbon-born proverb from the Middle Ages, still used today.",
    cefrMin: "B2",
    tags: ["proverb", "lisbon"],
  },
  {
    id: "pl_mar_lugar",
    type: "expression",
    contentPt: "Quem vai ao mar, perde o lugar",
    contentL1: "Kto wstał, ten stracił miejsce",
    explanation: "Literally: 'Who goes to sea, loses their place.' If you leave, someone takes your spot. Identical to Polish 'Kto wstał, ten stracił miejsce' (Who stood up, lost their seat). Maritime origin — fishermen who left lost their seat at the tavern. Used for parking spots, restaurant seats, any contested position.",
    cefrMin: "A2",
    tags: ["proverb", "daily-life"],
  },
  // --- DAILY IDIOMS ---
  {
    id: "pl_ora_essa",
    type: "expression",
    contentPt: "Ora essa!",
    contentL1: "Ależ proszę! / Nie ma za co!",
    explanation: "Exclamation of modest denial when thanked. 'Obrigado pela ajuda!' — 'Ora essa!' (Dziękuję za pomoc! — Ależ proszę!). Like Polish 'nie ma za co'. Can also express surprise: 'Ora essa, quem diria!' (No proszę, kto by pomyślał!).",
    cefrMin: "A2",
    tags: ["daily-life", "etiquette"],
  },
  {
    id: "pl_descansado",
    type: "expression",
    contentPt: "Fica descansado / Fica descansada",
    contentL1: "Nie martw się / Spokojnie",
    explanation: "Literally: 'Be rested/at ease.' Means 'don't worry, I've got it.' 'Fica descansado, eu trato disso' (Nie martw się, ja się tym zajmę). Like Polish 'spokojnie' or 'nie martw się'. Used constantly to reassure.",
    cefrMin: "A2",
    tags: ["daily-life", "conversation"],
  },
  {
    id: "pl_nao_faz_mal",
    type: "expression",
    contentPt: "Não faz mal",
    contentL1: "Nic się nie stało / Nie szkodzi",
    explanation: "Literally: 'It doesn't do harm.' Standard response when someone apologises for a minor thing. 'Desculpa o atraso!' — 'Não faz mal!' (Przepraszam za spóźnienie! — Nic się nie stało!). Exact equivalent of Polish 'nic się nie stało'.",
    cefrMin: "A1",
    tags: ["daily-life", "etiquette"],
  },
  {
    id: "pl_deixa_la",
    type: "expression",
    contentPt: "Deixa lá",
    contentL1: "Daj spokój / Olej to / Nieważne",
    explanation: "'Deixa lá' = 'let it go / forget it / never mind.' 'Queres que te pague?' — 'Deixa lá!' (Chcesz żebym ci zapłacił? — Daj spokój!). Can also console: 'Deixa lá, amanhã corre melhor' (Daj spokój, jutro będzie lepiej). Like Polish 'daj spokój'.",
    cefrMin: "A1",
    tags: ["daily-life", "conversation"],
  },
  {
    id: "pl_e_o_que_e",
    type: "expression",
    contentPt: "É o que é",
    contentL1: "Jak jest, tak jest / Co poradzisz",
    explanation: "'It is what it is' — philosophical acceptance. 'O preço subiu? É o que é.' (Cena wzrosła? Jak jest, tak jest.) Spoken with a shrug. Like Polish 'co poradzisz' or 'tak to jest'. Captures Portuguese fatalism alongside resourcefulness.",
    cefrMin: "A2",
    tags: ["daily-life", "culture"],
  },
  {
    id: "pl_olha_la",
    type: "expression",
    contentPt: "Olha lá / Ouve lá",
    contentL1: "Słuchaj / Hej / Powiedz mi",
    explanation: "'Olha lá' (look here) and 'ouve lá' (listen here) get attention or start a question. 'Olha lá, sabes onde fica o correio?' (Słuchaj, wiesz gdzie jest poczta?). Like Polish 'słuchaj' or 'hej'. Not rude — it is the standard way to approach someone.",
    cefrMin: "A1",
    tags: ["daily-life", "conversation"],
  },
  {
    id: "pl_entao",
    type: "expression",
    contentPt: "Então?",
    contentL1: "No i co? / I jak? / No to?",
    explanation: "'Então?' is the universal Portuguese greeting-question. 'Então, tudo bem?' (No i co, wszystko dobrze?). Also prompts: 'Então, o que queres fazer?' (No to, co chcesz robić?). Like Polish 'no i co?' or 'i jak?'. Short, warm, multipurpose.",
    cefrMin: "A1",
    tags: ["daily-life", "conversation"],
  },
  {
    id: "pl_se_calhar",
    type: "expression",
    contentPt: "Se calhar",
    contentL1: "Może / Być może / Chyba",
    explanation: "Literally: 'if it falls (that way).' Means 'maybe/perhaps.' 'Se calhar vou ao cinema' (Może pójdę do kina). More common than 'talvez' in everyday PT-EU speech. Like Polish 'może' or 'chyba'. Note: unlike 'talvez', this does NOT trigger the subjunctive in Portuguese.",
    cefrMin: "A2",
    tags: ["daily-life", "grammar"],
  },
  {
    id: "pl_com_certeza",
    type: "expression",
    contentPt: "Com certeza",
    contentL1: "Oczywiście / Na pewno (ale uwaga!)",
    explanation: "'Com certeza' means 'certainly'. BUT in PT-EU it is often polite but non-committal — like saying 'sure' without meaning it. A Portuguese 'com certeza' can mean 'I'll think about it' (and forget). Poles take 'oczywiście' literally. Portuguese use 'com certeza' more loosely. Watch for this trap.",
    cefrMin: "A2",
    tags: ["daily-life", "etiquette"],
  },
];
