import type { L1Profile } from "../types.js";

export const plProfile: L1Profile = {
  code: "pl",
  name: "Polish",
  nativeName: "Polski",
  writingDirection: "ltr",
  hasLatinScript: true,
  transfer: {
    cognates: [
      "muzyka (música — music)",
      "kultura (cultura — culture)",
      "problem (problema — problem)",
      "uniwersytet (universidade — university)",
      "dokument (documento — document)",
      "grupa (grupo — group)",
      "moment (momento — moment)",
      "system (sistema — system)",
      "informacja (informação — information)",
      "demokracja (democracia — democracy)",
      "energia (energia — energy)",
      "transport (transporte — transport)",
      "telefon (telefone — telephone)",
      "restauracja (restaurante — restaurant)",
      "teatr (teatro — theatre)",
      "profesor (professor — professor/teacher)",
    ],
    falseFriends: [
      { word: "pasta", l1Meaning: "pasta means 'paste/toothpaste/strip' in Polish", ptMeaning: "pasta means 'folder/briefcase' — paste = massa" },
      { word: "sala", l1Meaning: "sala means 'hall/room' in Polish too — similar!", ptMeaning: "sala means 'room/living room' — true cognate in this case" },
      { word: "lista", l1Meaning: "lista means 'list/letter' in Polish", ptMeaning: "lista means 'list/menu' — letter = carta" },
      { word: "nota", l1Meaning: "nota means 'grade/mark' in Polish", ptMeaning: "nota means 'grade/mark' AND 'banknote' — also applies to money in PT" },
      { word: "kara", l1Meaning: "kara means 'punishment' in Polish", ptMeaning: "cara means 'face' or 'guy' (informal) — punishment = castigo" },
      { word: "masa", l1Meaning: "masa means 'mass/dough' in Polish", ptMeaning: "massa means 'dough/pasta' — mesa means 'table' (the sound is close)" },
      { word: "forma", l1Meaning: "forma means 'form/mould/uniform' in Polish", ptMeaning: "forma means 'form/shape/mould' — very similar, but uniform = farda" },
      { word: "mal", l1Meaning: "sounds like 'mały' (small) in Polish", ptMeaning: "mal means 'badly/evil' — small = pequeno" },
      { word: "bar", l1Meaning: "bar means 'bar/cheap canteen' in Polish", ptMeaning: "bar means 'bar/pub' — similar but Polish 'bar mleczny' (milk bar) is a canteen" },
      { word: "prima", l1Meaning: "prima means 'prima donna' in Polish", ptMeaning: "prima means 'female cousin' — prima donna = protagonista" },
      { word: "dom", l1Meaning: "dom means 'house/home' in Polish", ptMeaning: "dom means 'Mr/Sir' (title) or 'gift/talent' — house = casa" },
      { word: "manga", l1Meaning: "manga — Japanese comics", ptMeaning: "manga primarily means 'sleeve' — also mango" },
    ],
    phoneticDifficulties: [
      {
        sound: "ão",
        ipa: "/ɐ̃w̃/",
        description: "Nasal diphthong -ão",
        tip: "Polish has nasal vowels (ą, ę) — a major advantage! PT-EU 'ão' is a nasal diphthong: start nasal, glide to a rounded nasal 'u'. Your Polish nasal instinct helps, but add the glide. Practice: pão, mão, não.",
        mouthPosition: "nasal_ao",
      },
      {
        sound: "ã/õ/ẽ",
        ipa: "/ɐ̃/ /õ/ /ẽ/",
        description: "Nasal vowels",
        tip: "Your Polish ą and ę give you a head start! PT-EU nasalizes 'a', 'o', and 'e'. The mechanism is the same — lower the soft palate. Polish speakers usually master PT-EU nasals faster than any other Slavic speakers.",
        mouthPosition: "nasal_vowel",
      },
      {
        sound: "r/rr",
        ipa: "/ʁ/",
        description: "Uvular R (initial and double)",
        tip: "Polish uses a trilled alveolar R. PT-EU initial R and double RR are uvular — at the back of the throat, like French R. Do not trill! 'Rato' (mouse), 'carro' (car).",
        mouthPosition: "uvular_r",
      },
      {
        sound: "r (tap)",
        ipa: "/ɾ/",
        description: "Alveolar tap between vowels",
        tip: "Single 'r' between vowels is a quick tap — lighter than a full Polish trill. 'Caro' (expensive), 'para' (for). Just one touch, not a sustained vibration.",
        mouthPosition: "alveolar_tap",
      },
      {
        sound: "lh",
        ipa: "/ʎ/",
        description: "Palatal lateral lh",
        tip: "Polish has soft ł/l distinction. PT-EU 'lh' is a palatal lateral — tongue flat against the hard palate. 'Trabalho' (work), 'filho' (son). Not like Polish ł.",
        mouthPosition: "palatal_lateral",
      },
      {
        sound: "nh",
        ipa: "/ɲ/",
        description: "Palatal nasal nh",
        tip: "Like Polish ń! Same sound. 'Vinho' (wine) = ń in 'koń'. 'Amanhã' (tomorrow), 'Espanha' (Spain). Polish speakers get this one for free.",
        mouthPosition: "palatal_nasal",
      },
      {
        sound: "open/closed e",
        ipa: "/ɛ/ vs /e/",
        description: "Two e sounds",
        tip: "Polish doesn't distinguish open/closed e as phonemes. PT-EU does: 'é' (open /ɛ/, café) vs 'ê' (closed /e/, você). The accent mark tells you which. This changes meaning.",
        mouthPosition: "open_e",
      },
      {
        sound: "open/closed o",
        ipa: "/ɔ/ vs /o/",
        description: "Two o sounds",
        tip: "Polish has a similar o/ó distinction! Polish ó = /u/, but the concept of open vs closed helps. PT-EU: open 'ó' (/ɔ/, avó) vs closed 'ô' (/o/, avô).",
        mouthPosition: "open_o",
      },
      {
        sound: "reduced vowels",
        ipa: "/ɨ/ /ə/",
        description: "Unstressed vowels nearly vanish",
        tip: "Polish pronounces every vowel. PT-EU swallows unstressed vowels drastically — 'telefonema' sounds like 'tlfnema'. This is the biggest rhythm adjustment for Polish speakers.",
      },
      {
        sound: "s/z/ʃ/ʒ",
        ipa: "/s/ /z/ /ʃ/ /ʒ/",
        description: "Four sibilants",
        tip: "Polish has even more sibilants (s/z/sz/ż/ś/ź/cz/dż). PT-EU has four: final 's' = /ʃ/ (like sz), 's' between vowels = /z/, 'j' = /ʒ/ (like ż). Easy for Polish ears!",
        mouthPosition: "sibilant_sh",
      },
      {
        sound: "v/b distinction",
        ipa: "/v/ vs /b/",
        description: "V and B are different",
        tip: "Polish distinguishes w and b perfectly. PT-EU does the same: 'vela' (candle) vs 'bela' (beautiful). Use your Polish instinct.",
        mouthPosition: "labiodental_v",
      },
    ],
    grammarGaps: [
      {
        concept: "Articles (o/a, um/uma)",
        explanation: "Every noun requires a definite or indefinite article",
        l1Comparison: "Polish has no articles. You must always say 'o livro' (the book), 'uma casa' (a house). The article signals gender and definiteness. This is the biggest grammar shock.",
      },
      {
        concept: "Only 2 genders (no neuter)",
        explanation: "Portuguese has masculine (o) and feminine (a) only",
        l1Comparison: "Polish has three genders (masculine with animate/inanimate split, feminine, neuter). PT-EU has two. Gender assignments often differ: 'okno' (neuter window) → 'a janela' (feminine).",
      },
      {
        concept: "No case system",
        explanation: "Portuguese uses prepositions and word order instead of cases",
        l1Comparison: "Polish has 7 cases (mianownik → wołacz). PT-EU uses none — prepositions replace them all: 'de' for genitive, 'a/para' for dative. Major simplification, but word order matters more.",
      },
      {
        concept: "Ser vs Estar",
        explanation: "Two verbs for 'to be'",
        l1Comparison: "Polish 'być' covers both. PT-EU splits: 'Sou polaco' (I am Polish — ser, identity) vs 'Estou cansado' (I am tired — estar, state). Some expressions change meaning depending on which you use.",
      },
      {
        concept: "Verb conjugation (tenses, not aspects)",
        explanation: "6 persons × 12+ tenses across 3 moods",
        l1Comparison: "Polish uses 2 aspects (dokonany/niedokonany) × 3 tenses. PT-EU replaces aspects with multiple past tenses: pretérito perfeito (completed) vs imperfeito (ongoing). Similar concept, different mechanism.",
      },
      {
        concept: "Subjunctive mood",
        explanation: "Required for doubt, desire, emotion, uncertainty",
        l1Comparison: "Polish tryb warunkowy (with by/żeby) is simpler. PT-EU has present, past, AND future subjunctive — all fully conjugated. 'Espero que venhas', 'Se eu fosse', 'Quando eu for'.",
      },
      {
        concept: "Personal infinitive",
        explanation: "Infinitive conjugated for person — unique to Portuguese",
        l1Comparison: "No Polish equivalent. 'Para nós fazermos' (for us to do) replaces a full żeby clause. Once learned, it actually simplifies sentence structure.",
      },
      {
        concept: "Preposition contractions",
        explanation: "Mandatory: em+o=no, de+a=da, a+o=ao, por+o=pelo",
        l1Comparison: "Polish prepositions stay separate. PT-EU contractions are mandatory and frequent: 'Estou no café' (em + o = no). You cannot separate them.",
      },
      {
        concept: "Object pronoun placement",
        explanation: "Before or after the verb depending on context",
        l1Comparison: "Polish has free word order. PT-EU has strict pronoun rules: after the verb by default ('Dá-me'), before with negation ('Não me dás'). Mesoclisis exists: 'Dir-lhe-ei'.",
      },
      {
        concept: "Tu vs Você vs O Senhor",
        explanation: "Three formality levels for 'you'",
        l1Comparison: "Polish ty/Pan/Pani gives three levels too — natural match. 'Tu' = ty, 'você' is a middle ground, 'o senhor/a senhora' = Pan/Pani. In Portugal, 'tu' is standard among peers.",
      },
      {
        concept: "Definite article with names",
        explanation: "'A Maria', 'o João' — articles before proper names",
        l1Comparison: "Polish never uses articles with names. PT-EU always does in speech: 'A Maria vem amanhã'. This is standard Portuguese.",
      },
      {
        concept: "Continuous with 'estar a + infinitive'",
        explanation: "'Estou a trabalhar' = I am working",
        l1Comparison: "Polish uses imperfective aspect for ongoing actions. PT-EU uses 'estar a + infinitive'. The gerund form ('estou trabalhando') is Brazilian, not European.",
      },
    ],
    skipBasics: false,
    startingCEFR: "A1",
  },
};
