import type { L1Profile } from "../types.js";

export const plProfile: L1Profile = {
  code: "pl",
  name: "Polish",
  nativeName: "Polski",
  writingDirection: "ltr",
  hasLatinScript: true,
  transfer: {
    cognates: [
      "muzyka (música — music)",
      "kultura (cultura — culture)",
      "problem (problema — problem)",
      "uniwersytet (universidade — university)",
      "dokument (documento — document)",
      "grupa (grupo — group)",
      "moment (momento — moment)",
      "system (sistema — system)",
      "informacja (informação — information)",
      "demokracja (democracia — democracy)",
      "energia (energia — energy)",
      "transport (transporte — transport)",
      "telefon (telefone — telephone)",
      "restauracja (restaurante — restaurant)",
      "teatr (teatro — theatre)",
      "profesor (professor — professor/teacher)",
      "bank (banco — bank)",
      "doktor (doutor — doctor)",
      "policja (polícia — police)",
      "ekonomia (economia — economy)",
      "technika (técnica — technique)",
      "program (programa — program)",
      "literatura (literatura — literature)",
      "prezydent (presidente — president)",
      "sytuacja (situação — situation)",
      "komunikacja (comunicação — communication)",
      "materiał (material — material)",
      "proces (processo — process)",
      "muzeum (museu — museum)",
      "nacja (nação — nation)",
    ],
    falseFriends: [
      { word: "pasta", l1Meaning: "pasta means 'paste/toothpaste/strip' in Polish", ptMeaning: "pasta means 'folder/briefcase' — paste = massa" },
      { word: "sala", l1Meaning: "sala means 'hall/room' in Polish too — similar!", ptMeaning: "sala means 'room/living room' — true cognate in this case" },
      { word: "lista", l1Meaning: "lista means 'list/letter' in Polish", ptMeaning: "lista means 'list/menu' — letter = carta" },
      { word: "nota", l1Meaning: "nota means 'grade/mark' in Polish", ptMeaning: "nota means 'grade/mark' AND 'banknote' — also applies to money in PT" },
      { word: "kara", l1Meaning: "kara means 'punishment' in Polish", ptMeaning: "cara means 'face' or 'guy' (informal) — punishment = castigo" },
      { word: "masa", l1Meaning: "masa means 'mass/dough' in Polish", ptMeaning: "massa means 'dough/pasta' — mesa means 'table' (the sound is close)" },
      { word: "forma", l1Meaning: "forma means 'form/mould/uniform' in Polish", ptMeaning: "forma means 'form/shape/mould' — very similar, but uniform = farda" },
      { word: "mal", l1Meaning: "sounds like 'mały' (small) in Polish", ptMeaning: "mal means 'badly/evil' — small = pequeno" },
      { word: "bar", l1Meaning: "bar means 'bar/cheap canteen' in Polish", ptMeaning: "bar means 'bar/pub' — similar but Polish 'bar mleczny' (milk bar) is a canteen" },
      { word: "prima", l1Meaning: "prima means 'prima donna' in Polish", ptMeaning: "prima means 'female cousin' — prima donna = protagonista" },
      { word: "dom", l1Meaning: "dom means 'house/home' in Polish", ptMeaning: "dom means 'Mr/Sir' (title) or 'gift/talent' — house = casa" },
      { word: "manga", l1Meaning: "manga — Japanese comics", ptMeaning: "manga primarily means 'sleeve' — also mango" },
      { word: "comer", l1Meaning: "no Polish cognate", ptMeaning: "comer means 'to eat'" },
      { word: "largo", l1Meaning: "largo — music term (broadly)", ptMeaning: "largo means 'wide' or 'public square' in PT" },
      { word: "gato", l1Meaning: "sounds like 'gad' — no meaning (kot = cat)", ptMeaning: "gato means 'cat'" },
      { word: "porta", l1Meaning: "porta — sounds like port", ptMeaning: "porta means 'door' — port = porto" },
      { word: "banco", l1Meaning: "sounds like bank", ptMeaning: "banco means 'bank' AND 'bench'" },
      { word: "pena", l1Meaning: "pena sounds like Polish 'pena' — no standard meaning", ptMeaning: "pena means 'feather' or 'pity' or 'penalty'" },
      { word: "cola", l1Meaning: "kola — cola drink in Polish", ptMeaning: "cola means 'glue' in PT — cola drink = Coca-Cola" },
      { word: "caro", l1Meaning: "no Polish cognate (drogi = expensive)", ptMeaning: "caro means 'expensive' or 'dear'" },
      { word: "conta", l1Meaning: "konto means 'account' in Polish", ptMeaning: "conta means 'bill/account/story' — similar but broader" },
      { word: "data", l1Meaning: "data means 'date' in Polish too", ptMeaning: "data means 'date' — true cognate" },
      { word: "ser", l1Meaning: "ser — sounds like 'ser' (cheese, regional)", ptMeaning: "ser means 'to be' (identity/permanent)" },
      { word: "dar", l1Meaning: "dar means 'gift' in some Slavic dialects", ptMeaning: "dar means 'to give' in PT — gift = presente" },
      { word: "campo", l1Meaning: "sounds like 'kompot' (stewed fruit drink)", ptMeaning: "campo means 'field/countryside'" },
      { word: "falar", l1Meaning: "no Polish cognate (mówić = to speak)", ptMeaning: "falar means 'to speak/talk'" },
      { word: "carta", l1Meaning: "karta means 'card/sheet/page' in Polish", ptMeaning: "carta means 'letter' — card = cartão, page = página" },
      { word: "rua", l1Meaning: "no Polish cognate (ulica = street)", ptMeaning: "rua means 'street'" },
      { word: "fato", l1Meaning: "fakt means 'fact' in Polish", ptMeaning: "fato means 'suit (clothing)' AND 'fact' — suits are more common usage in daily life" },
      { word: "cama", l1Meaning: "no Polish cognate (łóżko = bed)", ptMeaning: "cama means 'bed'" },
      { word: "taça", l1Meaning: "taca means 'tray/platter' in Polish", ptMeaning: "taça means 'trophy/wine glass/goblet' — tray = tabuleiro" },
      { word: "vaga", l1Meaning: "waga means 'weight/scale/importance' in Polish", ptMeaning: "vaga means 'vacancy' or 'wave' — weight = peso" },
      { word: "mesa", l1Meaning: "sounds like 'masa' (mass/dough) in Polish", ptMeaning: "mesa means 'table' — dough = massa" },
      { word: "mala", l1Meaning: "mała means 'small (feminine)' in Polish", ptMeaning: "mala means 'suitcase/bag' — small = pequena" },
      { word: "boca", l1Meaning: "no Polish cognate (usta = mouth)", ptMeaning: "boca means 'mouth'" },
      { word: "ala", l1Meaning: "ala sounds like 'a la' — no standard meaning", ptMeaning: "ala means 'wing' (of a building or creature)" },
      { word: "mar", l1Meaning: "no Polish cognate (morze = sea, but distant root)", ptMeaning: "mar means 'sea/ocean'" },
      { word: "fila", l1Meaning: "film means 'film' in Polish — sounds similar", ptMeaning: "fila means 'queue/line' — film = filme" },
      { word: "prato", l1Meaning: "no Polish cognate (talerz = plate)", ptMeaning: "prato means 'plate/dish' or 'course of a meal'" },
      { word: "água", l1Meaning: "no Polish cognate (woda = water)", ptMeaning: "água means 'water' — looks unfamiliar but one of the first PT words learned" },
    ],
    phoneticDifficulties: [
      {
        sound: "ão",
        ipa: "/ɐ̃w̃/",
        description: "Nasal diphthong -ão",
        tip: "Polish has nasal vowels (ą, ę) — a major advantage! PT-EU 'ão' is a nasal diphthong: start nasal, glide to a rounded nasal 'u'. Your Polish nasal instinct helps, but add the glide. Practice: pão, mão, não.",
        mouthPosition: "nasal_ao",
      },
      {
        sound: "ã/õ/ẽ",
        ipa: "/ɐ̃/ /õ/ /ẽ/",
        description: "Nasal vowels",
        tip: "Your Polish ą and ę give you a head start! PT-EU nasalizes 'a', 'o', and 'e'. The mechanism is the same — lower the soft palate. Polish speakers usually master PT-EU nasals faster than any other Slavic speakers.",
        mouthPosition: "nasal_vowel",
      },
      {
        sound: "r/rr",
        ipa: "/ʁ/",
        description: "Uvular R (initial and double)",
        tip: "Polish uses a trilled alveolar R. PT-EU initial R and double RR are uvular — at the back of the throat, like French R. Do not trill! 'Rato' (mouse), 'carro' (car).",
        mouthPosition: "uvular_r",
      },
      {
        sound: "r (tap)",
        ipa: "/ɾ/",
        description: "Alveolar tap between vowels",
        tip: "Single 'r' between vowels is a quick tap — lighter than a full Polish trill. 'Caro' (expensive), 'para' (for). Just one touch, not a sustained vibration.",
        mouthPosition: "alveolar_tap",
      },
      {
        sound: "lh",
        ipa: "/ʎ/",
        description: "Palatal lateral lh",
        tip: "Polish has soft ł/l distinction. PT-EU 'lh' is a palatal lateral — tongue flat against the hard palate. 'Trabalho' (work), 'filho' (son). Not like Polish ł.",
        mouthPosition: "palatal_lateral",
      },
      {
        sound: "nh",
        ipa: "/ɲ/",
        description: "Palatal nasal nh",
        tip: "Like Polish ń! Same sound. 'Vinho' (wine) = ń in 'koń'. 'Amanhã' (tomorrow), 'Espanha' (Spain). Polish speakers get this one for free.",
        mouthPosition: "palatal_nasal",
      },
      {
        sound: "open/closed e",
        ipa: "/ɛ/ vs /e/",
        description: "Two e sounds",
        tip: "Polish doesn't distinguish open/closed e as phonemes. PT-EU does: 'é' (open /ɛ/, café) vs 'ê' (closed /e/, você). The accent mark tells you which. This changes meaning.",
        mouthPosition: "open_e",
      },
      {
        sound: "open/closed o",
        ipa: "/ɔ/ vs /o/",
        description: "Two o sounds",
        tip: "Polish has a similar o/ó distinction! Polish ó = /u/, but the concept of open vs closed helps. PT-EU: open 'ó' (/ɔ/, avó) vs closed 'ô' (/o/, avô).",
        mouthPosition: "open_o",
      },
      {
        sound: "reduced vowels",
        ipa: "/ɨ/ /ə/",
        description: "Unstressed vowels nearly vanish",
        tip: "Polish pronounces every vowel. PT-EU swallows unstressed vowels drastically — 'telefonema' sounds like 'tlfnema'. This is the biggest rhythm adjustment for Polish speakers.",
      },
      {
        sound: "s/z/ʃ/ʒ",
        ipa: "/s/ /z/ /ʃ/ /ʒ/",
        description: "Four sibilants",
        tip: "Polish has even more sibilants (s/z/sz/ż/ś/ź/cz/dż). PT-EU has four: final 's' = /ʃ/ (like sz), 's' between vowels = /z/, 'j' = /ʒ/ (like ż). Easy for Polish ears!",
        mouthPosition: "sibilant_sh",
      },
      {
        sound: "v/b distinction",
        ipa: "/v/ vs /b/",
        description: "V and B are different",
        tip: "Polish distinguishes w and b perfectly. PT-EU does the same: 'vela' (candle) vs 'bela' (beautiful). Use your Polish instinct.",
        mouthPosition: "labiodental_v",
      },
      {
        sound: "dark L",
        ipa: "/ɫ/",
        description: "Velarized L at end of syllables",
        tip: "Polish ł is now /w/ in modern pronunciation. PT-EU dark L is velarized /ɫ/ — tongue touches the alveolar ridge while the back rises. 'Portugal', 'sol' (sun), 'mal' (badly). Not the Polish ł glide, but not a clear L either.",
      },
      {
        sound: "consonant clusters",
        ipa: "/pr/ /tr/ /pl/ /str/",
        description: "Initial consonant clusters",
        tip: "Polish has even more complex clusters (ść, strz, źdź). PT-EU clusters are simpler by comparison: 'prato' (plate), 'três' (three), 'construção' (construction). Your Polish cluster skills transfer well.",
      },
      {
        sound: "word-final -e",
        ipa: "/ɨ/ or silent",
        description: "Final -e nearly disappears",
        tip: "Polish always pronounces final -e (like in 'pole', 'morze'). PT-EU final -e is barely a whisper or drops entirely. 'Cidade' sounds like 'cidadɨ' or even 'cidad'. Do not give it a full Polish -e.",
      },
      {
        sound: "word stress",
        ipa: "variable",
        description: "Unpredictable stress position",
        tip: "Polish stress is almost always on the penultimate syllable. PT-EU stress varies and can change meaning: 'sábia' (wise) vs 'sabiá' (bird). Accents mark irregular stress. Do not default to penultimate — check the word.",
      },
    ],
    grammarGaps: [
      {
        concept: "Articles (o/a, um/uma)",
        explanation: "Every noun requires a definite or indefinite article",
        l1Comparison: "Polish has no articles. You must always say 'o livro' (the book), 'uma casa' (a house). The article signals gender and definiteness. This is the biggest grammar shock.",
      },
      {
        concept: "Only 2 genders (no neuter)",
        explanation: "Portuguese has masculine (o) and feminine (a) only",
        l1Comparison: "Polish has three genders (masculine with animate/inanimate split, feminine, neuter). PT-EU has two. Gender assignments often differ: 'okno' (neuter window) → 'a janela' (feminine).",
      },
      {
        concept: "No case system",
        explanation: "Portuguese uses prepositions and word order instead of cases",
        l1Comparison: "Polish has 7 cases (mianownik → wołacz). PT-EU uses none — prepositions replace them all: 'de' for genitive, 'a/para' for dative. Major simplification, but word order matters more.",
      },
      {
        concept: "Ser vs Estar",
        explanation: "Two verbs for 'to be'",
        l1Comparison: "Polish 'być' covers both. PT-EU splits: 'Sou polaco' (I am Polish — ser, identity) vs 'Estou cansado' (I am tired — estar, state). Some expressions change meaning depending on which you use.",
      },
      {
        concept: "Verb conjugation (tenses, not aspects)",
        explanation: "6 persons × 12+ tenses across 3 moods",
        l1Comparison: "Polish uses 2 aspects (dokonany/niedokonany) × 3 tenses. PT-EU replaces aspects with multiple past tenses: pretérito perfeito (completed) vs imperfeito (ongoing). Similar concept, different mechanism.",
      },
      {
        concept: "Subjunctive mood",
        explanation: "Required for doubt, desire, emotion, uncertainty",
        l1Comparison: "Polish tryb warunkowy (with by/żeby) is simpler. PT-EU has present, past, AND future subjunctive — all fully conjugated. 'Espero que venhas', 'Se eu fosse', 'Quando eu for'.",
      },
      {
        concept: "Personal infinitive",
        explanation: "Infinitive conjugated for person — unique to Portuguese",
        l1Comparison: "No Polish equivalent. 'Para nós fazermos' (for us to do) replaces a full żeby clause. Once learned, it actually simplifies sentence structure.",
      },
      {
        concept: "Preposition contractions",
        explanation: "Mandatory: em+o=no, de+a=da, a+o=ao, por+o=pelo",
        l1Comparison: "Polish prepositions stay separate. PT-EU contractions are mandatory and frequent: 'Estou no café' (em + o = no). You cannot separate them.",
      },
      {
        concept: "Object pronoun placement",
        explanation: "Before or after the verb depending on context",
        l1Comparison: "Polish has free word order. PT-EU has strict pronoun rules: after the verb by default ('Dá-me'), before with negation ('Não me dás'). Mesoclisis exists: 'Dir-lhe-ei'.",
      },
      {
        concept: "Tu vs Você vs O Senhor",
        explanation: "Three formality levels for 'you'",
        l1Comparison: "Polish ty/Pan/Pani gives three levels too — natural match. 'Tu' = ty, 'você' is a middle ground, 'o senhor/a senhora' = Pan/Pani. In Portugal, 'tu' is standard among peers.",
      },
      {
        concept: "Definite article with names",
        explanation: "'A Maria', 'o João' — articles before proper names",
        l1Comparison: "Polish never uses articles with names. PT-EU always does in speech: 'A Maria vem amanhã'. This is standard Portuguese.",
      },
      {
        concept: "Continuous with 'estar a + infinitive'",
        explanation: "'Estou a trabalhar' = I am working",
        l1Comparison: "Polish uses imperfective aspect for ongoing actions. PT-EU uses 'estar a + infinitive'. The gerund form ('estou trabalhando') is Brazilian, not European.",
      },
      {
        concept: "Reflexive verbs",
        explanation: "Many common verbs require 'se': levantar-se, sentar-se, chamar-se",
        l1Comparison: "Polish also has reflexive verbs with 'się' (myć się, nazywać się). The concept is familiar. Difference: PT-EU reflexive pronoun changes with person (me/te/se/nos) and its position shifts — 'Chamo-me' vs 'Não me chamo'.",
      },
      {
        concept: "Definite article with possessives",
        explanation: "'O meu carro' — article + possessive + noun",
        l1Comparison: "Polish uses possessives without articles: 'mój samochód'. PT-EU keeps both: 'o meu carro' (the my car). Dropping the article sounds Brazilian. In PT-EU the article is standard.",
      },
      {
        concept: "Haver vs Ter",
        explanation: "Two verbs for 'have' with different functions",
        l1Comparison: "Polish 'mieć' covers all 'have' senses. PT-EU splits: 'ter' for possession and auxiliary ('Tenho um carro', 'Tenho feito'), 'haver' for impersonal existence ('Há muitas pessoas' = there are many people). 'Haver' is never used for possession.",
      },
    ],
    skipBasics: false,
    startingCEFR: "A1",
  },
};
