import type { CulturalRef } from "../types.js";

export const enCulturalRefs: readonly CulturalRef[] = [
  {
    id: "en_saudade",
    type: "expression",
    contentPt: "Saudade",
    contentL1: "A deep, bittersweet longing",
    explanation: "The most famous untranslatable Portuguese word. It is not simply 'missing' someone — it is a melancholic longing for something or someone you love, tinged with the happiness of having experienced it. Central to Portuguese identity, music (fado), and literature.",
    cefrMin: "A2",
    tags: ["culture", "emotion", "identity"],
  },
  {
    id: "en_desenrascar",
    type: "expression",
    contentPt: "Desenrascar-se",
    contentL1: "To figure it out / to improvise a solution",
    explanation: "The quintessential Portuguese survival skill — finding a creative, often improvised solution when everything seems impossible. More resourceful than 'winging it'. The Portuguese take pride in this ability. The noun 'desenrascanço' describes the act itself.",
    cefrMin: "B1",
    tags: ["culture", "daily-life", "identity"],
  },
  {
    id: "en_fixe",
    type: "expression",
    contentPt: "Fixe!",
    contentL1: "Cool! / Awesome!",
    explanation: "The universal Portuguese slang for 'cool'. Used constantly in informal speech. Not to be confused with 'fixo' (fixed/permanent). Pronounced 'feesh'.",
    cefrMin: "A1",
    tags: ["slang", "daily-life"],
  },
  {
    id: "en_pois",
    type: "expression",
    contentPt: "Pois...",
    contentL1: "Yeah... / Well... / Indeed... / Right...",
    explanation: "The most versatile word in Portuguese. 'Pois' can mean agreement, hesitation, resignation, acknowledgement, or filler — depending entirely on intonation. 'Pois pois' (double) often means polite but somewhat disinterested agreement. Learning to use 'pois' naturally is a milestone of fluency.",
    cefrMin: "A1",
    tags: ["daily-life", "conversation"],
  },
  {
    id: "en_bica",
    type: "reference",
    contentPt: "Uma bica",
    contentL1: "An espresso (Lisbon term)",
    explanation: "In Lisbon, an espresso is 'uma bica', not 'um café'. In Porto, it is 'um cimbalino' (from the Cimbali brand of espresso machines). Ordering 'um café' works everywhere but marks you as an outsider in Lisbon.",
    cefrMin: "A1",
    tags: ["food", "daily-life", "lisbon", "porto"],
  },
  {
    id: "en_galao",
    type: "reference",
    contentPt: "Um galão",
    contentL1: "A tall milky coffee in a glass",
    explanation: "A large coffee with a lot of milk, served in a tall glass. Not a latte — the proportions and preparation differ. A 'meia de leite' is the smaller version in a cup. Portuguese coffee culture has precise vocabulary: galão, meia de leite, garoto, abatanado, bica/cimbalino.",
    cefrMin: "A1",
    tags: ["food", "daily-life"],
  },
  {
    id: "en_pastel_nata",
    type: "reference",
    contentPt: "Pastel de nata",
    contentL1: "Custard tart",
    explanation: "Portugal's most famous pastry — a flaky pastry shell filled with egg custard, baked until caramelized. The original recipe from Mosteiro dos Jerónimos in Belém is a closely guarded secret. The Belém ones are called 'pastéis de Belém'. Sprinkle with cinnamon and powdered sugar. The plural is 'pastéis de nata', not 'pasteis' or 'pastels'.",
    cefrMin: "A1",
    tags: ["food", "lisbon", "culture"],
  },
  {
    id: "en_francesinha",
    type: "reference",
    contentPt: "Francesinha",
    contentL1: "Porto's signature sandwich",
    explanation: "A layered sandwich of bread, ham, linguiça, fresh sausage, and steak, covered in melted cheese and drenched in a spicy tomato-beer sauce, served with fries. Originally from Porto, each restaurant has a secret sauce recipe. Ordering one in Lisbon is considered heresy by nortenhos (northerners).",
    cefrMin: "A2",
    tags: ["food", "porto", "culture"],
  },
  {
    id: "en_bifana",
    type: "reference",
    contentPt: "Bifana",
    contentL1: "Thin pork steak sandwich",
    explanation: "A simple but beloved sandwich: thin marinated pork cutlet in a bread roll (papo-seco). Street food staple, often eaten at fairs and festivals. The marinade varies by region — garlic and white wine paste is classic.",
    cefrMin: "A2",
    tags: ["food", "daily-life"],
  },
  {
    id: "en_tu_voce",
    type: "reference",
    contentPt: "Tu vs Você vs O Senhor",
    contentL1: "Informal, semi-formal, and formal 'you'",
    explanation: "Getting this wrong is a real social misstep. Use 'tu' with friends, family, and people your age. Use 'você' carefully — in some regions it sounds distant or even rude between friends. Use 'o senhor/a senhora' with older people, authority figures, and in formal settings. When in doubt, start formal and let the Portuguese person switch you to 'tu'. Many Portuguese mix them in the same sentence.",
    cefrMin: "A1",
    tags: ["social", "grammar", "etiquette"],
  },
  {
    id: "en_beijinhos",
    type: "reference",
    contentPt: "Dar dois beijinhos",
    contentL1: "Greeting with two kisses on the cheeks",
    explanation: "The standard greeting between women, and between men and women who know each other. Two kisses, starting on the right cheek. Men who are close friends or family also do this. A handshake is for formal or first-time business meetings. Not kissing when expected feels cold; kissing when unexpected feels intrusive.",
    cefrMin: "A1",
    tags: ["social", "etiquette", "daily-life"],
  },
  {
    id: "en_fado",
    type: "reference",
    contentPt: "Fado",
    contentL1: "Traditional Portuguese music genre",
    explanation: "A melancholic music genre born in Lisbon's working-class neighborhoods in the early 1800s. Typically features a solo vocalist accompanied by guitarra portuguesa (12-string instrument) and viola (classical guitar). Themes revolve around saudade, fate (fado literally means 'fate'), longing, and the sea. Amália Rodrigues is the legendary fadista. UNESCO Intangible Cultural Heritage since 2011. Coimbra has its own distinct fado tradition, traditionally sung only by men.",
    cefrMin: "A2",
    tags: ["music", "culture", "lisbon", "identity"],
  },
  {
    id: "en_autocarro",
    type: "reference",
    contentPt: "Autocarro (not ônibus)",
    contentL1: "Bus (European Portuguese term)",
    explanation: "PT-EU and PT-BR differ significantly in everyday vocabulary. Bus: autocarro (PT-EU) vs ônibus (PT-BR). Train: comboio vs trem. Mobile phone: telemóvel vs celular. Breakfast: pequeno-almoço vs café da manhã. Bathroom: casa de banho vs banheiro. Ice cream: gelado vs sorvete. Using Brazilian terms in Portugal will be understood but sounds odd.",
    cefrMin: "A1",
    tags: ["vocabulary", "daily-life", "pt-eu-vs-br"],
  },
  {
    id: "en_estar_a_fazer",
    type: "expression",
    contentPt: "Estou a fazer (not estou fazendo)",
    contentL1: "I am doing (PT-EU continuous form)",
    explanation: "European Portuguese uses 'estar a + infinitive' for ongoing actions: 'Estou a comer' (I am eating). Brazilian Portuguese uses the gerund: 'Estou comendo'. This is one of the most immediately noticeable differences between the two variants and marks you as a PT-EU learner.",
    cefrMin: "A1",
    tags: ["grammar", "pt-eu-vs-br", "daily-life"],
  },
  {
    id: "en_nas_tintas",
    type: "expression",
    contentPt: "Estar-se nas tintas",
    contentL1: "To not give a damn",
    explanation: "Literally 'to be in the paints'. Means you could not care less about something. Very common, mildly rude but acceptable in casual conversation. 'Estou-me nas tintas para isso' = 'I couldn't care less about that'.",
    cefrMin: "B1",
    tags: ["slang", "emotion"],
  },
  {
    id: "en_fica_descansado",
    type: "expression",
    contentPt: "Fica descansado / Fica tranquilo",
    contentL1: "Don't worry / Relax",
    explanation: "A very common reassurance phrase. Literally 'stay rested/calm'. Used constantly in everyday speech. Can also be slightly dismissive depending on tone, similar to 'chill out'.",
    cefrMin: "A2",
    tags: ["daily-life", "conversation"],
  },
  {
    id: "en_lisbon_porto_rivalry",
    type: "reference",
    contentPt: "Lisboa vs Porto",
    contentL1: "The Lisbon-Porto cultural rivalry",
    explanation: "A friendly but real cultural divide. Lisbon (lisboetas) is the cosmopolitan capital; Porto (portuenses/tripeiros) is proudly working-class and independent-minded. Porto residents are called 'tripeiros' (tripe-eaters) — a historical badge of honor from when they gave all their meat to explorers and kept only tripe. Food, accent, football (Benfica/Sporting vs FC Porto), and attitudes all differ. Never tell someone from Porto that Lisbon is better, or vice versa.",
    cefrMin: "B1",
    tags: ["culture", "lisbon", "porto", "identity"],
  },
  {
    id: "en_benfica_sporting_porto",
    type: "reference",
    contentPt: "Benfica, Sporting, FC Porto",
    contentL1: "The 'Big Three' football clubs",
    explanation: "Football is a national passion. The 'três grandes' dominate: SL Benfica (Lisbon, red), Sporting CP (Lisbon, green), and FC Porto (Porto, blue). Benfica has the most fans nationwide. Sporting-Benfica is the Lisbon derby. Everyone has a club, and asking 'De que clube és?' is a standard getting-to-know-you question. Rivalries are intense but mostly good-natured.",
    cefrMin: "A2",
    tags: ["sports", "culture", "daily-life"],
  },
  {
    id: "en_25_abril",
    type: "reference",
    contentPt: "25 de Abril — Revolução dos Cravos",
    contentL1: "April 25th — the Carnation Revolution (1974)",
    explanation: "Portugal's defining modern moment. On April 25, 1974, a military coup peacefully overthrew the authoritarian Estado Novo dictatorship (Europe's longest, since 1933). Soldiers put red carnations in their rifle barrels. The date is a national holiday, the main bridge in Lisbon is named Ponte 25 de Abril, and 'Grândola, Vila Morena' (the song that signaled the revolution on radio) is deeply symbolic. Understanding this history is essential to understanding modern Portugal.",
    cefrMin: "B1",
    tags: ["history", "culture", "identity"],
  },
  {
    id: "en_descobrimentos",
    type: "reference",
    contentPt: "Os Descobrimentos",
    contentL1: "The Age of Discoveries (15th-16th century)",
    explanation: "Portugal's golden age of maritime exploration. Vasco da Gama reached India (1498), Pedro Álvares Cabral reached Brazil (1500), and Portuguese explorers mapped coastlines across Africa, Asia, and South America. This era shapes national identity profoundly — seen in architecture (Mosteiro dos Jerónimos), food (spices, pastéis de nata), and language (Portuguese is spoken across 4 continents). Modern Portugal increasingly grapples with the colonial legacy of this period.",
    cefrMin: "B1",
    tags: ["history", "culture", "identity"],
  },
  {
    id: "en_se_faz_favor",
    type: "expression",
    contentPt: "Se faz favor / Faz favor",
    contentL1: "Please / Excuse me (to get attention)",
    explanation: "The polite way to get a waiter's attention, ask for something, or say 'please'. More natural than 'por favor' in many everyday situations, especially in restaurants and shops. 'Faz favor' alone also works as 'excuse me' to get someone's attention.",
    cefrMin: "A1",
    tags: ["etiquette", "daily-life", "conversation"],
  },
  {
    id: "en_azulejos",
    type: "reference",
    contentPt: "Azulejos",
    contentL1: "Decorative ceramic tiles",
    explanation: "The iconic painted tin-glazed ceramic tiles covering buildings, churches, and train stations across Portugal. The tradition dates to the 15th century, influenced by Moorish art. The word comes from Arabic 'az-zulayj' (polished stone). Blue and white designs are most famous, but azulejos come in many colors and styles. The Museu Nacional do Azulejo in Lisbon is dedicated to this art form.",
    cefrMin: "A2",
    tags: ["culture", "art", "history"],
  },
  {
    id: "en_com_licenca",
    type: "expression",
    contentPt: "Com licença",
    contentL1: "Excuse me (to pass by / enter)",
    explanation: "Used when you need to physically pass someone, enter a room, or interrupt. Different from 'desculpe' (sorry/excuse me for a mistake) and 'faz favor' (to get attention). Getting these three 'excuse me' phrases right is an early fluency marker.",
    cefrMin: "A1",
    tags: ["etiquette", "daily-life"],
  },
  {
    id: "en_tuga",
    type: "expression",
    contentPt: "Tuga",
    contentL1: "Portuguese person (informal/affectionate)",
    explanation: "Informal, affectionate slang for a Portuguese person, derived from 'português'. Not offensive — the Portuguese use it themselves. 'Coisas de tuga' = 'typical Portuguese things'. The word 'lusitano' is a more literary/formal alternative, from Lusitania (the Roman province).",
    cefrMin: "B1",
    tags: ["slang", "identity"],
  },
  {
    id: "en_meal_structure",
    type: "reference",
    contentPt: "Pequeno-almoço, almoço, lanche, jantar",
    contentL1: "Breakfast, lunch, afternoon snack, dinner",
    explanation: "Portuguese meal times differ from Anglo-Saxon habits. Pequeno-almoço (breakfast) is light: coffee and a pastry. Almoço (lunch, 12:30-14:00) is the main meal — substantial, often multiple courses. Lanche (afternoon snack, ~16:00-17:00) is coffee and cake or a sandwich. Jantar (dinner, 20:00-21:00) can be lighter or full. Eating dinner before 19:30 is considered very early.",
    cefrMin: "A1",
    tags: ["food", "daily-life", "culture"],
  },
  {
    id: "en_pronto",
    type: "expression",
    contentPt: "Pronto!",
    contentL1: "Done! / There! / Ready! / OK then!",
    explanation: "One of the most frequently heard words in Portuguese. Used to signal completion ('Pronto, acabei!' = Done, I'm finished!), to move a conversation along ('Pronto, vamos lá' = OK then, let's go), or even as a filler to wrap up a thought. Like 'pois', mastering 'pronto' is a fluency milestone.",
    cefrMin: "A1",
    tags: ["daily-life", "conversation"],
  },
];
