import type { CulturalRef } from "../types.js";

export const enCulturalRefs: readonly CulturalRef[] = [
  {
    id: "en_saudade",
    type: "expression",
    contentPt: "Saudade",
    contentL1: "A deep, bittersweet longing",
    explanation: "The most famous untranslatable Portuguese word. It is not simply 'missing' someone — it is a melancholic longing for something or someone you love, tinged with the happiness of having experienced it. Central to Portuguese identity, music (fado), and literature.",
    cefrMin: "A2",
    tags: ["culture", "emotion", "identity"],
  },
  {
    id: "en_desenrascar",
    type: "expression",
    contentPt: "Desenrascar-se",
    contentL1: "To figure it out / to improvise a solution",
    explanation: "The quintessential Portuguese survival skill — finding a creative, often improvised solution when everything seems impossible. More resourceful than 'winging it'. The Portuguese take pride in this ability. The noun 'desenrascanço' describes the act itself.",
    cefrMin: "B1",
    tags: ["culture", "daily-life", "identity"],
  },
  {
    id: "en_fixe",
    type: "expression",
    contentPt: "Fixe!",
    contentL1: "Cool! / Awesome!",
    explanation: "The universal Portuguese slang for 'cool'. Used constantly in informal speech. Not to be confused with 'fixo' (fixed/permanent). Pronounced 'feesh'.",
    cefrMin: "A1",
    tags: ["slang", "daily-life"],
  },
  {
    id: "en_pois",
    type: "expression",
    contentPt: "Pois...",
    contentL1: "Yeah... / Well... / Indeed... / Right...",
    explanation: "The most versatile word in Portuguese. 'Pois' can mean agreement, hesitation, resignation, acknowledgement, or filler — depending entirely on intonation. 'Pois pois' (double) often means polite but somewhat disinterested agreement. Learning to use 'pois' naturally is a milestone of fluency.",
    cefrMin: "A1",
    tags: ["daily-life", "conversation"],
  },
  {
    id: "en_bica",
    type: "reference",
    contentPt: "Uma bica",
    contentL1: "An espresso (Lisbon term)",
    explanation: "In Lisbon, an espresso is 'uma bica', not 'um café'. In Porto, it is 'um cimbalino' (from the Cimbali brand of espresso machines). Ordering 'um café' works everywhere but marks you as an outsider in Lisbon.",
    cefrMin: "A1",
    tags: ["food", "daily-life", "lisbon", "porto"],
  },
  {
    id: "en_galao",
    type: "reference",
    contentPt: "Um galão",
    contentL1: "A tall milky coffee in a glass",
    explanation: "A large coffee with a lot of milk, served in a tall glass. Not a latte — the proportions and preparation differ. A 'meia de leite' is the smaller version in a cup. Portuguese coffee culture has precise vocabulary: galão, meia de leite, garoto, abatanado, bica/cimbalino.",
    cefrMin: "A1",
    tags: ["food", "daily-life"],
  },
  {
    id: "en_pastel_nata",
    type: "reference",
    contentPt: "Pastel de nata",
    contentL1: "Custard tart",
    explanation: "Portugal's most famous pastry — a flaky pastry shell filled with egg custard, baked until caramelized. The original recipe from Mosteiro dos Jerónimos in Belém is a closely guarded secret. The Belém ones are called 'pastéis de Belém'. Sprinkle with cinnamon and powdered sugar. The plural is 'pastéis de nata', not 'pasteis' or 'pastels'.",
    cefrMin: "A1",
    tags: ["food", "lisbon", "culture"],
  },
  {
    id: "en_francesinha",
    type: "reference",
    contentPt: "Francesinha",
    contentL1: "Porto's signature sandwich",
    explanation: "A layered sandwich of bread, ham, linguiça, fresh sausage, and steak, covered in melted cheese and drenched in a spicy tomato-beer sauce, served with fries. Originally from Porto, each restaurant has a secret sauce recipe. Ordering one in Lisbon is considered heresy by nortenhos (northerners).",
    cefrMin: "A2",
    tags: ["food", "porto", "culture"],
  },
  {
    id: "en_bifana",
    type: "reference",
    contentPt: "Bifana",
    contentL1: "Thin pork steak sandwich",
    explanation: "A simple but beloved sandwich: thin marinated pork cutlet in a bread roll (papo-seco). Street food staple, often eaten at fairs and festivals. The marinade varies by region — garlic and white wine paste is classic.",
    cefrMin: "A2",
    tags: ["food", "daily-life"],
  },
  {
    id: "en_tu_voce",
    type: "reference",
    contentPt: "Tu vs Você vs O Senhor",
    contentL1: "Informal, semi-formal, and formal 'you'",
    explanation: "Getting this wrong is a real social misstep. Use 'tu' with friends, family, and people your age. Use 'você' carefully — in some regions it sounds distant or even rude between friends. Use 'o senhor/a senhora' with older people, authority figures, and in formal settings. When in doubt, start formal and let the Portuguese person switch you to 'tu'. Many Portuguese mix them in the same sentence.",
    cefrMin: "A1",
    tags: ["social", "grammar", "etiquette"],
  },
  {
    id: "en_beijinhos",
    type: "reference",
    contentPt: "Dar dois beijinhos",
    contentL1: "Greeting with two kisses on the cheeks",
    explanation: "The standard greeting between women, and between men and women who know each other. Two kisses, starting on the right cheek. Men who are close friends or family also do this. A handshake is for formal or first-time business meetings. Not kissing when expected feels cold; kissing when unexpected feels intrusive.",
    cefrMin: "A1",
    tags: ["social", "etiquette", "daily-life"],
  },
  {
    id: "en_fado",
    type: "reference",
    contentPt: "Fado",
    contentL1: "Traditional Portuguese music genre",
    explanation: "A melancholic music genre born in Lisbon's working-class neighborhoods in the early 1800s. Typically features a solo vocalist accompanied by guitarra portuguesa (12-string instrument) and viola (classical guitar). Themes revolve around saudade, fate (fado literally means 'fate'), longing, and the sea. Amália Rodrigues is the legendary fadista. UNESCO Intangible Cultural Heritage since 2011. Coimbra has its own distinct fado tradition, traditionally sung only by men.",
    cefrMin: "A2",
    tags: ["music", "culture", "lisbon", "identity"],
  },
  {
    id: "en_autocarro",
    type: "reference",
    contentPt: "Autocarro (not ônibus)",
    contentL1: "Bus (European Portuguese term)",
    explanation: "PT-EU and PT-BR differ significantly in everyday vocabulary. Bus: autocarro (PT-EU) vs ônibus (PT-BR). Train: comboio vs trem. Mobile phone: telemóvel vs celular. Breakfast: pequeno-almoço vs café da manhã. Bathroom: casa de banho vs banheiro. Ice cream: gelado vs sorvete. Using Brazilian terms in Portugal will be understood but sounds odd.",
    cefrMin: "A1",
    tags: ["vocabulary", "daily-life", "pt-eu-vs-br"],
  },
  {
    id: "en_estar_a_fazer",
    type: "expression",
    contentPt: "Estou a fazer (not estou fazendo)",
    contentL1: "I am doing (PT-EU continuous form)",
    explanation: "European Portuguese uses 'estar a + infinitive' for ongoing actions: 'Estou a comer' (I am eating). Brazilian Portuguese uses the gerund: 'Estou comendo'. This is one of the most immediately noticeable differences between the two variants and marks you as a PT-EU learner.",
    cefrMin: "A1",
    tags: ["grammar", "pt-eu-vs-br", "daily-life"],
  },
  {
    id: "en_nas_tintas",
    type: "expression",
    contentPt: "Estar-se nas tintas",
    contentL1: "To not give a damn",
    explanation: "Literally 'to be in the paints'. Means you could not care less about something. Very common, mildly rude but acceptable in casual conversation. 'Estou-me nas tintas para isso' = 'I couldn't care less about that'.",
    cefrMin: "B1",
    tags: ["slang", "emotion"],
  },
  {
    id: "en_fica_descansado",
    type: "expression",
    contentPt: "Fica descansado / Fica tranquilo",
    contentL1: "Don't worry / Relax",
    explanation: "A very common reassurance phrase. Literally 'stay rested/calm'. Used constantly in everyday speech. Can also be slightly dismissive depending on tone, similar to 'chill out'.",
    cefrMin: "A2",
    tags: ["daily-life", "conversation"],
  },
  {
    id: "en_lisbon_porto_rivalry",
    type: "reference",
    contentPt: "Lisboa vs Porto",
    contentL1: "The Lisbon-Porto cultural rivalry",
    explanation: "A friendly but real cultural divide. Lisbon (lisboetas) is the cosmopolitan capital; Porto (portuenses/tripeiros) is proudly working-class and independent-minded. Porto residents are called 'tripeiros' (tripe-eaters) — a historical badge of honor from when they gave all their meat to explorers and kept only tripe. Food, accent, football (Benfica/Sporting vs FC Porto), and attitudes all differ. Never tell someone from Porto that Lisbon is better, or vice versa.",
    cefrMin: "B1",
    tags: ["culture", "lisbon", "porto", "identity"],
  },
  {
    id: "en_benfica_sporting_porto",
    type: "reference",
    contentPt: "Benfica, Sporting, FC Porto",
    contentL1: "The 'Big Three' football clubs",
    explanation: "Football is a national passion. The 'três grandes' dominate: SL Benfica (Lisbon, red), Sporting CP (Lisbon, green), and FC Porto (Porto, blue). Benfica has the most fans nationwide. Sporting-Benfica is the Lisbon derby. Everyone has a club, and asking 'De que clube és?' is a standard getting-to-know-you question. Rivalries are intense but mostly good-natured.",
    cefrMin: "A2",
    tags: ["sports", "culture", "daily-life"],
  },
  {
    id: "en_25_abril",
    type: "reference",
    contentPt: "25 de Abril — Revolução dos Cravos",
    contentL1: "April 25th — the Carnation Revolution (1974)",
    explanation: "Portugal's defining modern moment. On April 25, 1974, a military coup peacefully overthrew the authoritarian Estado Novo dictatorship (Europe's longest, since 1933). Soldiers put red carnations in their rifle barrels. The date is a national holiday, the main bridge in Lisbon is named Ponte 25 de Abril, and 'Grândola, Vila Morena' (the song that signaled the revolution on radio) is deeply symbolic. Understanding this history is essential to understanding modern Portugal.",
    cefrMin: "B1",
    tags: ["history", "culture", "identity"],
  },
  {
    id: "en_descobrimentos",
    type: "reference",
    contentPt: "Os Descobrimentos",
    contentL1: "The Age of Discoveries (15th-16th century)",
    explanation: "Portugal's golden age of maritime exploration. Vasco da Gama reached India (1498), Pedro Álvares Cabral reached Brazil (1500), and Portuguese explorers mapped coastlines across Africa, Asia, and South America. This era shapes national identity profoundly — seen in architecture (Mosteiro dos Jerónimos), food (spices, pastéis de nata), and language (Portuguese is spoken across 4 continents). Modern Portugal increasingly grapples with the colonial legacy of this period.",
    cefrMin: "B1",
    tags: ["history", "culture", "identity"],
  },
  {
    id: "en_se_faz_favor",
    type: "expression",
    contentPt: "Se faz favor / Faz favor",
    contentL1: "Please / Excuse me (to get attention)",
    explanation: "The polite way to get a waiter's attention, ask for something, or say 'please'. More natural than 'por favor' in many everyday situations, especially in restaurants and shops. 'Faz favor' alone also works as 'excuse me' to get someone's attention.",
    cefrMin: "A1",
    tags: ["etiquette", "daily-life", "conversation"],
  },
  {
    id: "en_azulejos",
    type: "reference",
    contentPt: "Azulejos",
    contentL1: "Decorative ceramic tiles",
    explanation: "The iconic painted tin-glazed ceramic tiles covering buildings, churches, and train stations across Portugal. The tradition dates to the 15th century, influenced by Moorish art. The word comes from Arabic 'az-zulayj' (polished stone). Blue and white designs are most famous, but azulejos come in many colors and styles. The Museu Nacional do Azulejo in Lisbon is dedicated to this art form.",
    cefrMin: "A2",
    tags: ["culture", "art", "history"],
  },
  {
    id: "en_com_licenca",
    type: "expression",
    contentPt: "Com licença",
    contentL1: "Excuse me (to pass by / enter)",
    explanation: "Used when you need to physically pass someone, enter a room, or interrupt. Different from 'desculpe' (sorry/excuse me for a mistake) and 'faz favor' (to get attention). Getting these three 'excuse me' phrases right is an early fluency marker.",
    cefrMin: "A1",
    tags: ["etiquette", "daily-life"],
  },
  {
    id: "en_tuga",
    type: "expression",
    contentPt: "Tuga",
    contentL1: "Portuguese person (informal/affectionate)",
    explanation: "Informal, affectionate slang for a Portuguese person, derived from 'português'. Not offensive — the Portuguese use it themselves. 'Coisas de tuga' = 'typical Portuguese things'. The word 'lusitano' is a more literary/formal alternative, from Lusitania (the Roman province).",
    cefrMin: "B1",
    tags: ["slang", "identity"],
  },
  {
    id: "en_meal_structure",
    type: "reference",
    contentPt: "Pequeno-almoço, almoço, lanche, jantar",
    contentL1: "Breakfast, lunch, afternoon snack, dinner",
    explanation: "Portuguese meal times differ from Anglo-Saxon habits. Pequeno-almoço (breakfast) is light: coffee and a pastry. Almoço (lunch, 12:30-14:00) is the main meal — substantial, often multiple courses. Lanche (afternoon snack, ~16:00-17:00) is coffee and cake or a sandwich. Jantar (dinner, 20:00-21:00) can be lighter or full. Eating dinner before 19:30 is considered very early.",
    cefrMin: "A1",
    tags: ["food", "daily-life", "culture"],
  },
  {
    id: "en_pronto",
    type: "expression",
    contentPt: "Pronto!",
    contentL1: "Done! / There! / Ready! / OK then!",
    explanation: "One of the most frequently heard words in Portuguese. Used to signal completion ('Pronto, acabei!' = Done, I'm finished!), to move a conversation along ('Pronto, vamos lá' = OK then, let's go), or even as a filler to wrap up a thought. Like 'pois', mastering 'pronto' is a fluency milestone.",
    cefrMin: "A1",
    tags: ["daily-life", "conversation"],
  },
  // --- MODERN SLANG ---
  {
    id: "en_bue",
    type: "expression",
    contentPt: "Bué",
    contentL1: "A lot / very / loads",
    explanation: "Universal young Portuguese slang meaning 'a lot' or 'very'. 'Isto é bué fixe' = 'This is really cool'. 'Há bué gente' = 'There's loads of people'. Originally from Kimbundu (Angolan language), brought to Lisbon through post-colonial migration. Now used by all ages informally. Shows how African Portuguese enriched PT-EU vocabulary.",
    cefrMin: "A2",
    tags: ["slang", "daily-life"],
  },
  {
    id: "en_cena",
    type: "expression",
    contentPt: "Cena",
    contentL1: "Thing / stuff / whatchamacallit",
    explanation: "The most overused word in young Portuguese speech. Literally means 'scene' but used as a catch-all for 'thing', 'stuff', 'situation'. 'Aquela cena' = 'that thing'. 'É uma cena estranha' = 'It's a weird situation'. 'Que cena!' = 'What a thing!' (surprise). Functions exactly like 'thing' in English when you can't find the right word.",
    cefrMin: "A2",
    tags: ["slang", "daily-life"],
  },
  {
    id: "en_tipo",
    type: "expression",
    contentPt: "Tipo...",
    contentL1: "Like... (filler word)",
    explanation: "Used exactly like English 'like' as a filler. 'Ele era tipo... estranho' = 'He was like... weird'. Also means 'guy' ('aquele tipo' = 'that guy'). Young Portuguese speakers pepper sentences with 'tipo' the same way English speakers use 'like'. Annoying to older generations in both languages.",
    cefrMin: "A2",
    tags: ["slang", "conversation"],
  },
  {
    id: "en_ganda",
    type: "expression",
    contentPt: "Ganda!",
    contentL1: "Sick! / What a... ! / Massive!",
    explanation: "Contraction of 'grande' (big). Used as an intensifier. 'Ganda festa!' = 'What a party!'. 'Ganda maluco' = 'What a legend/madlad'. Can be positive ('ganda golo!' — sick goal!) or negative ('ganda confusão' — what a mess). Very informal, very Lisbon. Similar to British 'massive' or 'sick'.",
    cefrMin: "B1",
    tags: ["slang", "daily-life"],
  },
  {
    id: "en_bazar",
    type: "expression",
    contentPt: "Bazar",
    contentL1: "To bounce / to dip / to leave",
    explanation: "Slang for 'to leave', originally from Persian/Arabic via Romani. 'Vou bazar' = 'I'm gonna bounce'. Very informal, used among friends. Also: 'ir-se embora' (neutral), 'pirar-se' (slang), 'ir à vida' (colloquial). Portuguese has as many ways to say 'leave' as English does.",
    cefrMin: "B1",
    tags: ["slang"],
  },
  {
    id: "en_curtir",
    type: "expression",
    contentPt: "Curtir",
    contentL1: "To enjoy / to dig / to be into",
    explanation: "'Curto muito isso' = 'I'm really into that'. 'Curtir a vida' = 'to enjoy life'. Also used for 'to make out' — 'curtir com alguém' = 'to hook up with someone'. Context tells you which meaning. A versatile verb absent from textbooks but omnipresent in real speech.",
    cefrMin: "A2",
    tags: ["slang", "daily-life"],
  },
  {
    id: "en_na_boa",
    type: "expression",
    contentPt: "Na boa",
    contentL1: "No worries / it's cool / all good",
    explanation: "'Na boa' is the Portuguese 'no worries'. 'Posso chegar mais tarde?' — 'Na boa.' Very common, totally casual. Also works as an adjective: 'Ele é na boa' = 'He's chill/easy-going'. The vibe equivalent of the Australian 'no worries' or American 'it's all good'.",
    cefrMin: "A2",
    tags: ["slang", "daily-life"],
  },
  {
    id: "en_mano",
    type: "expression",
    contentPt: "Mano / Mana",
    contentL1: "Bro / Sis",
    explanation: "From 'irmão/irmã' (brother/sister). Used exactly like 'bro' in English. 'Eh mano, tudo bem?' = 'Hey bro, all good?'. Very common among younger Portuguese. 'Mana' is the female version. Less common than 'pá' but signals a closer relationship.",
    cefrMin: "A2",
    tags: ["slang", "daily-life"],
  },
  {
    id: "en_ta_se_bem",
    type: "expression",
    contentPt: "Tá-se bem",
    contentL1: "All good / it's fine / we're cool",
    explanation: "Contraction of 'está-se bem'. A casual way to say everything is fine. 'Como é que vai?' — 'Tá-se bem'. Also used to agree: 'Tá-se' alone means 'Cool, fine, OK'. Extremely common in casual speech, never in writing.",
    cefrMin: "A2",
    tags: ["slang", "conversation"],
  },
  {
    id: "en_o_pa",
    type: "expression",
    contentPt: "Ó pá!",
    contentL1: "Dude! / Man! / Mate!",
    explanation: "The most Portuguese interjection. Used to address someone ('Ó pá, anda cá!' = 'Dude, come here!'), express surprise ('Ó pá, não acredito!' = 'Man, I can't believe it!'), or start any sentence among friends. From 'rapaz' (boy/lad) shortened to 'pá'. Roughly equivalent to British 'mate' or American 'dude'.",
    cefrMin: "A2",
    tags: ["slang", "daily-life"],
  },
  {
    id: "en_mandar_vir",
    type: "expression",
    contentPt: "Mandar vir",
    contentL1: "To complain / to order (food) — depends on context",
    explanation: "Dual meaning that confuses learners. 'Ele está sempre a mandar vir' = 'He's always complaining'. BUT at a restaurant, 'Manda vir uma dose de sardinhas' = 'Order some sardines'. Context tells you which. Also: 'mandar bocas' = to throw shade/make snide remarks.",
    cefrMin: "B1",
    tags: ["slang", "daily-life"],
  },
  {
    id: "en_chavalos",
    type: "expression",
    contentPt: "Chavalos / Putos",
    contentL1: "Kids / youngsters",
    explanation: "'Os chavalos' and 'os putos' both mean 'the kids' in colloquial Portuguese. 'Puto/a' is NOT rude in Portugal (unlike in Spanish). A mother calling her children 'os meus putos' is perfectly normal. 'O puto é esperto' = 'The kid is smart'. This false friend from Spanish catches every Spanish speaker off guard.",
    cefrMin: "B1",
    tags: ["slang", "false-friends"],
  },
  // --- ANCIENT / TRADITIONAL PROVERBS ---
  {
    id: "en_quem_nao_tem_cao",
    type: "expression",
    contentPt: "Quem não tem cão, caça com gato",
    contentL1: "Beggars can't be choosers / Make do with what you have",
    explanation: "Literally: 'Who has no dog, hunts with a cat'. One of Portugal's oldest and most-used proverbs, meaning you work with what you have available. Used when improvising — very connected to the 'desenrascanço' mentality. Heard daily in Portuguese workplaces and homes. No English proverb captures the resourceful spirit quite as well.",
    cefrMin: "B1",
    tags: ["proverb", "culture"],
  },
  {
    id: "en_agua_mole",
    type: "expression",
    contentPt: "Água mole em pedra dura, tanto bate até que fura",
    contentL1: "Slow and steady wins the race / Dripping water wears away stone",
    explanation: "Literally: 'Soft water on hard stone, hits so much it pierces through'. About persistence and patience — the Portuguese version of 'dripping water wears the stone'. Used to encourage someone to keep trying. One of the oldest proverbs in the language, echoing Latin 'gutta cavat lapidem'.",
    cefrMin: "B1",
    tags: ["proverb", "culture"],
  },
  {
    id: "en_fazer_tripas_coracao",
    type: "expression",
    contentPt: "Fazer das tripas coração",
    contentL1: "To dig deep / to summon all your courage",
    explanation: "Literally: 'To make heart out of guts'. Means to push beyond your limits, find strength you didn't know you had. Used when someone does something incredibly hard despite feeling unable. The gory metaphor dates back centuries. Porto is called 'cidade das tripas' (city of tripe) — the legend says residents gave all good meat to explorers and made the best of what was left.",
    cefrMin: "B1",
    tags: ["proverb", "culture", "porto"],
  },
  {
    id: "en_ficar_ver_navios",
    type: "expression",
    contentPt: "Ficar a ver navios",
    contentL1: "To be left high and dry / stood up / left waiting",
    explanation: "Literally: 'To stay watching ships'. From the Age of Discoveries — families watching the horizon for ships that never returned. Now means being stood up, left empty-handed, or disappointed. 'Convidaram-me mas fiquei a ver navios' = 'They invited me but I was left waiting'. One of the most evocative Portuguese expressions, carrying 500 years of maritime longing.",
    cefrMin: "B2",
    tags: ["proverb", "history", "emotion"],
  },
  {
    id: "en_meter_rossio_betesga",
    type: "expression",
    contentPt: "Meter o Rossio na Betesga",
    contentL1: "To bite off more than you can chew / to try to fit a square peg in a round hole",
    explanation: "Literally: 'To fit the Rossio into the Betesga'. The Rossio is Lisbon's grand central square; the Betesga was a narrow alley nearby. Trying to fit one into the other is absurd — the expression means attempting something impossibly ambitious or cramming too much into too little. Uniquely Lisboan, dating to medieval Lisbon.",
    cefrMin: "B2",
    tags: ["proverb", "lisbon", "history"],
  },
  {
    id: "en_engolir_sapos",
    type: "expression",
    contentPt: "Engolir sapos",
    contentL1: "To bite your tongue / to swallow insults",
    explanation: "Literally: 'To swallow frogs'. Means enduring insults or humiliation without responding. 'Tive de engolir muitos sapos naquele emprego' = 'I had to swallow a lot of frogs at that job'. French has the same image ('avaler des couleuvres' — swallow snakes). The Portuguese version is viscerally effective.",
    cefrMin: "B1",
    tags: ["proverb", "emotion"],
  },
  {
    id: "en_grao_a_grao",
    type: "expression",
    contentPt: "Grão a grão, enche a galinha o papo",
    contentL1: "Little by little / Every little bit counts",
    explanation: "Literally: 'Grain by grain, the hen fills her crop'. About patience and accumulation — small efforts add up. Used for saving money, learning skills, or any long process. The rural imagery reflects Portugal's agricultural roots. One of the most commonly quoted proverbs by older generations.",
    cefrMin: "B1",
    tags: ["proverb", "culture"],
  },
  {
    id: "en_quem_vai_ao_mar",
    type: "expression",
    contentPt: "Quem vai ao mar, perde o lugar",
    contentL1: "You snooze, you lose / Move your feet, lose your seat",
    explanation: "Literally: 'Who goes to the sea, loses their place'. If you leave, someone else takes your spot. Used when someone steps away and comes back to find their seat taken, their turn skipped, or their opportunity gone. Maritime imagery again — Portugal's seafaring soul in a proverb.",
    cefrMin: "A2",
    tags: ["proverb", "daily-life"],
  },
  {
    id: "en_dar_burros_agua",
    type: "expression",
    contentPt: "Dar com os burros na água",
    contentL1: "To fail miserably / to hit a dead end",
    explanation: "Literally: 'To end up with the donkeys in the water'. A complete failure — your plan went wrong and there is nothing to show for it. 'Tentei resolver o problema mas dei com os burros na água' = 'I tried to solve the problem but hit a dead end'. Delightfully absurd imagery from rural Portugal.",
    cefrMin: "B1",
    tags: ["proverb"],
  },
  // --- DAILY IDIOMS ---
  {
    id: "en_nao_faz_mal",
    type: "expression",
    contentPt: "Não faz mal",
    contentL1: "No worries / It's fine / Never mind",
    explanation: "Literally: 'It doesn't do harm'. The standard response when someone apologises. 'Desculpa, cheguei atrasado' — 'Não faz mal'. Warmer than 'no problem', more like 'no harm done'. Heard dozens of times daily in Portugal. One of the first phrases that makes you sound natural.",
    cefrMin: "A1",
    tags: ["daily-life", "conversation"],
  },
  {
    id: "en_deixa_la",
    type: "expression",
    contentPt: "Deixa lá",
    contentL1: "Forget about it / Let it go / Don't worry about it",
    explanation: "Literally: 'Leave it there'. Used to dismiss something — either comforting ('Deixa lá, não faz mal' = 'Forget it, it's fine') or brushing off a topic you don't want to discuss ('Deixa lá, não interessa' = 'Drop it, doesn't matter'). Tone determines everything. An essential piece of conversational Portuguese.",
    cefrMin: "A1",
    tags: ["daily-life", "conversation"],
  },
  {
    id: "en_e_o_que_e",
    type: "expression",
    contentPt: "É o que é",
    contentL1: "It is what it is",
    explanation: "Identical to English in meaning and usage. A philosophical shrug, accepting something you cannot change. 'O trânsito em Lisboa é terrível.' — 'É o que é.' Used with the same resigned sigh as the English version. Shows the Portuguese tendency toward fatalistic acceptance, connected to the concept of 'fado' (fate).",
    cefrMin: "A2",
    tags: ["daily-life", "conversation", "culture"],
  },
  {
    id: "en_entao",
    type: "expression",
    contentPt: "Então?",
    contentL1: "So? / What's up? / Well then?",
    explanation: "'Então?' is a full greeting in Portugal. Two friends meeting: 'Então, tudo bem?' = 'So, how's it going?'. Also used to prompt someone: 'Então? Decidiste?' = 'Well? Have you decided?'. And to express surprise: 'Então?! O que aconteceu?' = 'What?! What happened?'. The intonation changes everything.",
    cefrMin: "A1",
    tags: ["daily-life", "conversation"],
  },
  {
    id: "en_se_calhar",
    type: "expression",
    contentPt: "Se calhar",
    contentL1: "Maybe / Perhaps / It could be that",
    explanation: "'Se calhar' is the PT-EU way of saying 'maybe'. More natural than 'talvez' in everyday speech. 'Se calhar vou amanhã' = 'Maybe I'll go tomorrow'. Literally means 'if it happens to be'. Using 'se calhar' instead of 'talvez' in casual conversation is a strong fluency signal — textbooks teach 'talvez' but real people say 'se calhar'.",
    cefrMin: "A2",
    tags: ["daily-life", "conversation"],
  },
  {
    id: "en_olha_la",
    type: "expression",
    contentPt: "Olha lá...",
    contentL1: "Look here / Listen / Hey",
    explanation: "Literally 'look there' but functions as 'listen' or 'hey' to get attention before saying something. 'Olha lá, posso perguntar uma coisa?' = 'Hey, can I ask you something?'. Can also be confrontational: 'Olha lá, quem é que pensas que és?' = 'Look here, who do you think you are?'. Tone is everything.",
    cefrMin: "A2",
    tags: ["daily-life", "conversation"],
  },
  {
    id: "en_ora_essa",
    type: "expression",
    contentPt: "Ora essa!",
    contentL1: "Of course! / Don't mention it! / Well naturally!",
    explanation: "An emphatic 'of course!' or 'don't mention it!'. 'Obrigado pela ajuda!' — 'Ora essa!' (Don't mention it!). Also expresses surprised agreement or mild indignation. It is warm and generous — the classic Portuguese hospitable response. Old-fashioned but still very much alive.",
    cefrMin: "A2",
    tags: ["daily-life", "etiquette"],
  },
];
