import type { L1Profile } from "../types.js";

export const enProfile: L1Profile = {
  code: "en",
  name: "English",
  nativeName: "English",
  writingDirection: "ltr",
  hasLatinScript: true,
  transfer: {
    cognates: [
      "hospital", "animal", "hotel", "universal", "natural",
      "cultural", "musical", "central", "social", "total",
      "original", "digital", "federal", "final", "legal",
      "material", "metal", "moral", "normal", "real",
      "capital", "dental", "fatal", "general", "manual",
      "visual", "vital", "brutal", "casual", "formal",
    ],
    falseFriends: [
      { word: "actually", l1Meaning: "in fact / really", ptMeaning: "actualmente means 'currently/nowadays'" },
      { word: "pretend", l1Meaning: "to fake / simulate", ptMeaning: "pretender means 'to intend / to want'" },
      { word: "push", l1Meaning: "to push away", ptMeaning: "puxe means 'pull' (on doors)" },
      { word: "fabric", l1Meaning: "cloth / textile", ptMeaning: "fábrica means 'factory'" },
      { word: "sensible", l1Meaning: "practical / reasonable", ptMeaning: "sensível means 'sensitive'" },
      { word: "exquisite", l1Meaning: "beautiful / refined", ptMeaning: "esquisito means 'weird / strange'" },
      { word: "costume", l1Meaning: "outfit / disguise", ptMeaning: "costume means 'habit / custom'" },
      { word: "injury", l1Meaning: "physical harm", ptMeaning: "injúria means 'insult / defamation'" },
      { word: "library", l1Meaning: "place with books", ptMeaning: "livraria means 'bookshop' (library = biblioteca)" },
      { word: "novel", l1Meaning: "a book / fiction", ptMeaning: "novela means 'soap opera / TV series'" },
      { word: "record", l1Meaning: "to save / note", ptMeaning: "recordar means 'to remember'" },
      { word: "lecture", l1Meaning: "talk / presentation", ptMeaning: "leitura means 'reading'" },
      { word: "attend", l1Meaning: "to be present", ptMeaning: "atender means 'to answer (phone/door)'" },
      { word: "assist", l1Meaning: "to help", ptMeaning: "assistir means 'to watch / attend'" },
      { word: "parent", l1Meaning: "mother or father", ptMeaning: "parente means 'relative / family member'" },
      { word: "signature", l1Meaning: "signed name", ptMeaning: "assinatura can also mean 'subscription'" },
      { word: "date", l1Meaning: "calendar date / romantic outing", ptMeaning: "data means only 'calendar date' (no romantic meaning)" },
      { word: "resume", l1Meaning: "CV / curriculum", ptMeaning: "resumo means 'summary'" },
      { word: "college", l1Meaning: "university", ptMeaning: "colégio means 'private school (K-12)'" },
      { word: "realize", l1Meaning: "to understand / become aware", ptMeaning: "realizar means 'to accomplish / carry out'" },
      { word: "intend", l1Meaning: "to plan / mean to", ptMeaning: "entender means 'to understand'" },
      { word: "sympathetic", l1Meaning: "showing compassion", ptMeaning: "simpático means 'nice / friendly / likeable'" },
      { word: "compromise", l1Meaning: "meet halfway", ptMeaning: "compromisso means 'commitment / obligation'" },
      { word: "support", l1Meaning: "to help / hold up", ptMeaning: "suportar means 'to endure / tolerate'" },
      { word: "discuss", l1Meaning: "to talk about", ptMeaning: "discutir means 'to argue / quarrel'" },
      { word: "apply", l1Meaning: "to submit / use", ptMeaning: "aplicar can work but aplicação often means 'app' or 'investment'" },
      { word: "proper", l1Meaning: "correct / fitting", ptMeaning: "próprio means 'own' (o meu próprio = my own)" },
      { word: "exit", l1Meaning: "way out / to leave", ptMeaning: "êxito means 'success'" },
      { word: "tax", l1Meaning: "government charge", ptMeaning: "taxa means 'rate / fee' (tax = imposto)" },
      { word: "pasta", l1Meaning: "Italian noodles", ptMeaning: "pasta means 'folder / briefcase / paste'" },
      { word: "preservative", l1Meaning: "food additive for shelf life", ptMeaning: "preservativo means 'condom' — a food preservative is 'conservante'" },
      { word: "deception", l1Meaning: "dishonesty / trickery", ptMeaning: "deceção means 'disappointment' — deception is 'engano'" },
      { word: "eventually", l1Meaning: "in the end / finally", ptMeaning: "eventualmente means 'possibly / occasionally' — eventually is 'finalmente'" },
      { word: "propaganda", l1Meaning: "biased political messaging", ptMeaning: "propaganda means 'advertising / marketing' — neutral in Portuguese, not pejorative" },
      { word: "receipt", l1Meaning: "proof of purchase", ptMeaning: "receita means 'recipe' or 'revenue' — a receipt is 'recibo'" },
      { word: "constipation", l1Meaning: "digestive blockage", ptMeaning: "constipação means 'common cold' — constipation is 'obstipação'" },
      { word: "anticipate", l1Meaning: "to expect / foresee", ptMeaning: "antecipar means 'to bring forward in time' or 'to do something earlier than planned'" },
      { word: "balcony", l1Meaning: "outdoor ledge on a building", ptMeaning: "balcão means 'counter / bar / service desk' — a balcony is 'varanda'" },
      { word: "embarrassed", l1Meaning: "feeling ashamed / awkward", ptMeaning: "embaraçado means 'tangled / complicated / confused' — embarrassed is 'envergonhado'" },
      { word: "professor", l1Meaning: "university academic", ptMeaning: "professor means ANY teacher at any level — primary school, university, music tutor, driving instructor" },
    ],
    phoneticDifficulties: [
      { sound: "ão", ipa: "/ɐ̃w̃/", description: "Nasal diphthong -ão", tip: "Say 'ow' but let air through your nose. No English equivalent. Found in pão, mão, não, coração." },
      { sound: "õe", ipa: "/õj̃/", description: "Nasal diphthong -ões", tip: "Nasalize 'oy' — air through the nose throughout. Found in limões, corações, aviões." },
      { sound: "ãe", ipa: "/ɐ̃j̃/", description: "Nasal diphthong -ãe/-ães", tip: "Like 'eye' but nasal. Found in mãe, cães, pães." },
      { sound: "ã", ipa: "/ɐ̃/", description: "Nasal A", tip: "Open your mouth for 'ah' but route air through your nose. Found in lã, maçã, irmã." },
      { sound: "õ", ipa: "/õ/", description: "Nasal O", tip: "Round your lips for 'oh' and nasalize. Found in bom, com, som, onde." },
      { sound: "lh", ipa: "/ʎ/", description: "Palatal lateral", tip: "Like the 'lli' in 'million' but tongue pressed harder to the palate. Found in filho, olho, trabalho." },
      { sound: "nh", ipa: "/ɲ/", description: "Palatal nasal", tip: "Like 'ny' in 'canyon'. Found in vinho, banho, amanhã." },
      { sound: "r (initial/rr)", ipa: "/ʁ/", description: "Uvular fricative R", tip: "A guttural sound from the back of the throat, like a French R or gentle gargling. Found in rato, carro, rua." },
      { sound: "r (intervocalic)", ipa: "/ɾ/", description: "Alveolar tap R", tip: "A quick tongue tap against the ridge behind your teeth, like the 't' in American 'butter'. Found in caro, para, hora." },
      { sound: "e (unstressed)", ipa: "/ɨ/ or silent", description: "Reduced/mute unstressed E", tip: "Unstressed 'e' nearly disappears or becomes a very short grunt. 'Telefone' sounds like 'tl-fon'. This is what gives PT-EU its Slavic-sounding rhythm." },
      { sound: "o (unstressed)", ipa: "/u/", description: "Unstressed O becomes U", tip: "Unstressed 'o' is pronounced as /u/. 'Porto' sounds like 'Purtu'. This is systematic, not random." },
      { sound: "s/z distinction", ipa: "/s/ /z/ /ʃ/ /ʒ/", description: "S has four realizations", tip: "S between vowels = /z/ (casa). S before voiceless consonant or at end = /ʃ/ (estas). S before voiced consonant = /ʒ/ (mesmo). Initial S = /s/ (sim)." },
      { sound: "ch", ipa: "/ʃ/", description: "CH is always 'sh'", tip: "Unlike English 'ch' (/tʃ/), Portuguese 'ch' is always /ʃ/ like 'shoe'. Chave = 'shav-uh', not 'chav'." },
      { sound: "ge/gi", ipa: "/ʒ/", description: "Soft G is 'zh'", tip: "Before 'e' or 'i', G sounds like the 's' in 'pleasure'. Gelo = 'zheh-lu'." },
      { sound: "vowel reduction", ipa: "various", description: "Systematic vowel reduction in unstressed syllables", tip: "PT-EU swallows unstressed vowels aggressively, making words sound much shorter than they look. This is the biggest rhythm difference from English or Brazilian Portuguese." },
    ],
    grammarGaps: [
      { concept: "Grammatical gender", explanation: "Every noun is masculine or feminine, affecting articles, adjectives, and pronouns", l1Comparison: "English has no grammatical gender. You must memorize each noun with its article (o/a). Most words ending in -o are masculine, most in -a are feminine, but there are many exceptions." },
      { concept: "Verb conjugation", explanation: "Verbs conjugate for 6 persons in each tense (eu, tu, ele/ela, nós, vós, eles/elas)", l1Comparison: "English barely conjugates (only 3rd person -s). PT-EU requires a different form for every subject pronoun in every tense. Subject pronouns are often dropped because the verb form already tells you who is speaking." },
      { concept: "Ser vs Estar", explanation: "Two distinct verbs both translate to English 'to be'", l1Comparison: "Ser = permanent/inherent qualities (sou alto = I am tall). Estar = temporary states/locations (estou cansado = I am tired). Mixing them changes meaning: 'ser chato' (to be a boring person) vs 'estar chato' (to be acting annoyingly right now)." },
      { concept: "Subjunctive mood", explanation: "A separate set of verb forms for doubt, desire, emotion, possibility, and commands", l1Comparison: "English barely uses it ('if I were'). PT-EU uses it constantly after expressions like 'espero que' (I hope that), 'talvez' (maybe), 'embora' (although). It has present, past, and future forms." },
      { concept: "Personal infinitive", explanation: "The infinitive can be conjugated to show who performs the action", l1Comparison: "Unique to Portuguese and Galician. 'Para fazermos' = 'for us to do'. English just uses 'for + pronoun + to + verb'. This structure appears constantly in PT-EU." },
      { concept: "Future subjunctive", explanation: "A verb form for hypothetical/conditional future situations", l1Comparison: "Does not exist in English, Spanish, or French. Used after quando (when), se (if), assim que (as soon as) for future events: 'Quando eu tiver tempo' (When I have time — future, uncertain)." },
      { concept: "Mesoclisis", explanation: "Placing pronouns inside the verb in conditional and future tenses", l1Comparison: "No English equivalent at all. 'Dir-lhe-ia' = 'I would tell him'. The pronoun goes between the stem and the ending. Formal/literary but still appears in news and formal speech." },
      { concept: "Object pronoun placement", explanation: "Pronouns go before or after the verb depending on grammatical triggers", l1Comparison: "English always puts object pronouns after the verb ('I see him'). PT-EU has complex rules: after in affirmative sentences (vejo-o), before after negation, conjunctions, question words, and adverbs (não o vejo)." },
      { concept: "Preterite vs Imperfect", explanation: "Two past tenses: completed actions vs ongoing/habitual past actions", l1Comparison: "English 'I ate' vs 'I was eating / I used to eat'. PT-EU makes this distinction systematically: 'comi' (I ate, done) vs 'comia' (I was eating / I used to eat)." },
      { concept: "Por vs Para", explanation: "Two prepositions where English uses 'for'", l1Comparison: "Por = cause, exchange, motion through, agent in passive ('feito por mim'). Para = purpose, destination, deadline ('para ti', 'para Lisboa'). English 'for' covers both, so you must always decide which one." },
      { concept: "Definite article usage", explanation: "Used far more than in English, including before possessives and names", l1Comparison: "English: 'my car'. PT-EU: 'o meu carro' (THE my car). Also used before names in everyday speech: 'A Maria ligou' (THE Maria called). Omitted after de/em in some cases." },
      { concept: "Compound tenses with ter", explanation: "Past participle constructions use 'ter' not 'haver'", l1Comparison: "English uses 'have' as auxiliary ('I have eaten'). PT-EU uses 'ter' for compound tenses: 'Tenho comido'. Unlike Spanish/French, the past participle does NOT agree in gender/number in compound tenses." },
      { concept: "Reflexive verbs", explanation: "Many common verbs require a reflexive pronoun (se)", l1Comparison: "English uses reflexives rarely ('I wash myself'). PT-EU uses them constantly: levantar-se (get up), sentar-se (sit down), chamar-se (be called), lembrar-se (remember). The pronoun must match the subject." },
      { concept: "Tu vs Você vs O Senhor/A Senhora", explanation: "Three levels of formality for 'you'", l1Comparison: "English has only 'you'. PT-EU has tu (informal, with 2nd person verb), você (semi-formal, with 3rd person verb), and o senhor/a senhora (formal). Using the wrong level is a social mistake. Tu is standard among friends in most of Portugal." },
      { concept: "Preposition contractions", explanation: "Prepositions fuse with articles and pronouns", l1Comparison: "English keeps them separate ('in the', 'of the'). PT-EU contracts them: de + o = do, de + a = da, em + o = no, em + a = na, a + o = ao, a + a = à. These are not optional." },
    ],
    skipBasics: false,
    startingCEFR: "A1",
  },
};
