import type { CulturalRef } from "../types.js";

export const ukCulturalRefs: readonly CulturalRef[] = [
  {
    id: "uk_saudade",
    type: "expression",
    contentPt: "Saudade",
    contentL1: "Туга (tuha)",
    explanation: "Ukrainian 'туга' captures a similar bittersweet longing to Portuguese saudade. Both cultures have a deep connection to melancholy as an art form — fado in Portugal, Ukrainian folk songs about separation and homeland.",
    cefrMin: "B1",
    tags: ["culture", "emotion"],
  },
  {
    id: "uk_fado",
    type: "reference",
    contentPt: "Fado",
    contentL1: "Як українські народні пісні",
    explanation: "Fado's mournful beauty parallels Ukrainian folk songs about fate, separation, and longing for home. Both are deeply emotional vocal traditions where the singer bares their soul.",
    cefrMin: "B1",
    tags: ["music", "culture"],
  },
  {
    id: "uk_fixe",
    type: "expression",
    contentPt: "Fixe!",
    contentL1: "Клас! / Круто!",
    explanation: "'Fixe' means 'cool'. Use it like клас or круто. 'Que fixe!' = How cool!",
    cefrMin: "A1",
    tags: ["slang", "daily-life"],
  },
  {
    id: "uk_pois",
    type: "expression",
    contentPt: "Pois...",
    contentL1: "Ну... / Так...",
    explanation: "'Pois' is the most versatile Portuguese filler, like Ukrainian ну or так. It fills pauses and expresses agreement or resignation.",
    cefrMin: "A1",
    tags: ["conversation", "daily-life"],
  },
  {
    id: "uk_pasteis",
    type: "reference",
    contentPt: "Pastéis de nata",
    contentL1: "Як кошики з кремом",
    explanation: "Flaky custard tarts for about one euro. Similar to Ukrainian pastry baskets with cream, but lighter and caramelized. Portugal's most famous sweet.",
    cefrMin: "A1",
    tags: ["food", "culture"],
  },
  {
    id: "uk_bacalhau",
    type: "reference",
    contentPt: "Bacalhau",
    contentL1: "Солона риба",
    explanation: "Salt cod is Portugal's national dish — 365 recipes. Ukrainians know preserved fish well. The concept of salt-curing is shared across both food traditions.",
    cefrMin: "A2",
    tags: ["food", "culture"],
  },
  {
    id: "uk_25_abril",
    type: "reference",
    contentPt: "25 de Abril — Revolução dos Cravos",
    contentL1: "Революція гвоздик (1974)",
    explanation: "On April 25, 1974, Portugal peacefully overthrew its dictatorship. Soldiers put carnations in their rifles. Ukrainians, who know the importance of democratic transition, can appreciate this peaceful revolution.",
    cefrMin: "B1",
    tags: ["history", "identity"],
  },
  {
    id: "uk_pronto",
    type: "expression",
    contentPt: "Pronto!",
    contentL1: "Готово! / Ну от!",
    explanation: "'Pronto' = done/ready. Like готово. 'Pronto, vamos!' = Well, let's go!",
    cefrMin: "A1",
    tags: ["daily-life", "conversation"],
  },
  {
    id: "uk_tu_voce",
    type: "reference",
    contentPt: "Tu vs O Senhor",
    contentL1: "Ти vs Ви",
    explanation: "Like Ukrainian ти/Ви, Portuguese has 'tu' (informal) and 'o senhor' (formal). 'Você' in Portugal can sound cold. Ukrainian speakers understand this formality system naturally.",
    cefrMin: "A1",
    tags: ["social", "etiquette"],
  },
  {
    id: "uk_family",
    type: "reference",
    contentPt: "Família é tudo",
    contentL1: "Родина — найважливіше",
    explanation: "Like Ukrainian culture, Portuguese culture is deeply family-oriented. Sunday family lunches are sacred. The warmth and closeness will feel familiar.",
    cefrMin: "A2",
    tags: ["culture", "family"],
  },
  {
    id: "uk_santos",
    type: "reference",
    contentPt: "Festas dos Santos Populares",
    contentL1: "Народні свята (як Івана Купала)",
    explanation: "June street festivals with sardines and dancing. São João (June 24) falls on the same night as Ukrainian Івана Купала — both are midsummer celebrations with fire and water traditions.",
    cefrMin: "A2",
    tags: ["culture", "festivals"],
  },
  {
    id: "uk_desenrascar",
    type: "expression",
    contentPt: "Desenrascar-se",
    contentL1: "Викрутитися",
    explanation: "The art of improvising a solution with whatever is available. Like Ukrainian викрутитися. Both cultures celebrate resourcefulness.",
    cefrMin: "B1",
    tags: ["culture", "daily-life"],
  },
  {
    id: "uk_diaspora",
    type: "reference",
    contentPt: "Comunidade ucraniana em Portugal",
    contentL1: "Українська громада в Португалії",
    explanation: "Ukraine is one of the largest immigrant communities in Portugal (over 40,000 people). Many arrived for construction work in the 2000s. There are Ukrainian churches, shops, and associations in Lisbon and Porto. You may already know someone who has been there.",
    cefrMin: "A2",
    tags: ["culture", "daily-life", "community"],
  },
  {
    id: "uk_vinho",
    type: "reference",
    contentPt: "Vinho do Porto / Vinho Verde",
    contentL1: "Портвейн / Вінью Верде",
    explanation: "Portugal has a vast wine culture. Vinho Verde (young, sparkling white) is perfect for summer. Port wine comes from the Douro valley. Wine is deeply embedded in daily life, much like alcohol culture in Ukraine.",
    cefrMin: "A2",
    tags: ["food", "culture"],
  },
  {
    id: "uk_nas_tintas",
    type: "expression",
    contentPt: "Estar-se nas tintas",
    contentL1: "Мені все одно / пофіг",
    explanation: "Literally 'to be in the paints' — couldn't care less. Like пофіг. Very common, mildly rude.",
    cefrMin: "B1",
    tags: ["slang", "emotion"],
  },
];
