import type { CulturalRef } from "../types.js";

export const ukCulturalRefs: readonly CulturalRef[] = [
  {
    id: "uk_saudade",
    type: "expression",
    contentPt: "Saudade",
    contentL1: "Туга (tuha)",
    explanation: "Ukrainian 'туга' captures a similar bittersweet longing to Portuguese saudade. Both cultures have a deep connection to melancholy as an art form — fado in Portugal, Ukrainian folk songs about separation and homeland.",
    cefrMin: "B1",
    tags: ["culture", "emotion"],
  },
  {
    id: "uk_fado",
    type: "reference",
    contentPt: "Fado",
    contentL1: "Як українські народні пісні",
    explanation: "Fado's mournful beauty parallels Ukrainian folk songs about fate, separation, and longing for home. Both are deeply emotional vocal traditions where the singer bares their soul.",
    cefrMin: "B1",
    tags: ["music", "culture"],
  },
  {
    id: "uk_fixe",
    type: "expression",
    contentPt: "Fixe!",
    contentL1: "Клас! / Круто!",
    explanation: "'Fixe' means 'cool'. Use it like клас or круто. 'Que fixe!' = How cool!",
    cefrMin: "A1",
    tags: ["slang", "daily-life"],
  },
  {
    id: "uk_pois",
    type: "expression",
    contentPt: "Pois...",
    contentL1: "Ну... / Так...",
    explanation: "'Pois' is the most versatile Portuguese filler, like Ukrainian ну or так. It fills pauses and expresses agreement or resignation.",
    cefrMin: "A1",
    tags: ["conversation", "daily-life"],
  },
  {
    id: "uk_pasteis",
    type: "reference",
    contentPt: "Pastéis de nata",
    contentL1: "Як кошики з кремом",
    explanation: "Flaky custard tarts for about one euro. Similar to Ukrainian pastry baskets with cream, but lighter and caramelized. Portugal's most famous sweet.",
    cefrMin: "A1",
    tags: ["food", "culture"],
  },
  {
    id: "uk_bacalhau",
    type: "reference",
    contentPt: "Bacalhau",
    contentL1: "Солона риба",
    explanation: "Salt cod is Portugal's national dish — 365 recipes. Ukrainians know preserved fish well. The concept of salt-curing is shared across both food traditions.",
    cefrMin: "A2",
    tags: ["food", "culture"],
  },
  {
    id: "uk_25_abril",
    type: "reference",
    contentPt: "25 de Abril — Revolução dos Cravos",
    contentL1: "Революція гвоздик (1974)",
    explanation: "On April 25, 1974, Portugal peacefully overthrew its dictatorship. Soldiers put carnations in their rifles. Ukrainians, who know the importance of democratic transition, can appreciate this peaceful revolution.",
    cefrMin: "B1",
    tags: ["history", "identity"],
  },
  {
    id: "uk_pronto",
    type: "expression",
    contentPt: "Pronto!",
    contentL1: "Готово! / Ну от!",
    explanation: "'Pronto' = done/ready. Like готово. 'Pronto, vamos!' = Well, let's go!",
    cefrMin: "A1",
    tags: ["daily-life", "conversation"],
  },
  {
    id: "uk_tu_voce",
    type: "reference",
    contentPt: "Tu vs O Senhor",
    contentL1: "Ти vs Ви",
    explanation: "Like Ukrainian ти/Ви, Portuguese has 'tu' (informal) and 'o senhor' (formal). 'Você' in Portugal can sound cold. Ukrainian speakers understand this formality system naturally.",
    cefrMin: "A1",
    tags: ["social", "etiquette"],
  },
  {
    id: "uk_family",
    type: "reference",
    contentPt: "Família é tudo",
    contentL1: "Родина — найважливіше",
    explanation: "Like Ukrainian culture, Portuguese culture is deeply family-oriented. Sunday family lunches are sacred. The warmth and closeness will feel familiar.",
    cefrMin: "A2",
    tags: ["culture", "family"],
  },
  {
    id: "uk_santos",
    type: "reference",
    contentPt: "Festas dos Santos Populares",
    contentL1: "Народні свята (як Івана Купала)",
    explanation: "June street festivals with sardines and dancing. São João (June 24) falls on the same night as Ukrainian Івана Купала — both are midsummer celebrations with fire and water traditions.",
    cefrMin: "A2",
    tags: ["culture", "festivals"],
  },
  {
    id: "uk_desenrascar",
    type: "expression",
    contentPt: "Desenrascar-se",
    contentL1: "Викрутитися",
    explanation: "The art of improvising a solution with whatever is available. Like Ukrainian викрутитися. Both cultures celebrate resourcefulness.",
    cefrMin: "B1",
    tags: ["culture", "daily-life"],
  },
  {
    id: "uk_diaspora",
    type: "reference",
    contentPt: "Comunidade ucraniana em Portugal",
    contentL1: "Українська громада в Португалії",
    explanation: "Ukraine is one of the largest immigrant communities in Portugal (over 40,000 people). Many arrived for construction work in the 2000s. There are Ukrainian churches, shops, and associations in Lisbon and Porto. You may already know someone who has been there.",
    cefrMin: "A2",
    tags: ["culture", "daily-life", "community"],
  },
  {
    id: "uk_vinho",
    type: "reference",
    contentPt: "Vinho do Porto / Vinho Verde",
    contentL1: "Портвейн / Вінью Верде",
    explanation: "Portugal has a vast wine culture. Vinho Verde (young, sparkling white) is perfect for summer. Port wine comes from the Douro valley. Wine is deeply embedded in daily life, much like alcohol culture in Ukraine.",
    cefrMin: "A2",
    tags: ["food", "culture"],
  },
  {
    id: "uk_nas_tintas",
    type: "expression",
    contentPt: "Estar-se nas tintas",
    contentL1: "Мені все одно / пофіг",
    explanation: "Literally 'to be in the paints' — couldn't care less. Like пофіг. Very common, mildly rude.",
    cefrMin: "B1",
    tags: ["slang", "emotion"],
  },
  {
    id: "uk_growing_community",
    type: "reference",
    contentPt: "Ucranianos em Portugal — a maior comunidade eslava",
    contentL1: "Українці в Португалії — найбільша слов'янська громада",
    explanation: "Ukrainians are one of the largest immigrant communities in Portugal, with over 40,000 residents and growing rapidly since 2022. Portuguese law granted temporary protection quickly. Ukrainian associations operate in Lisbon, Porto, Setúbal, and Faro. Ukrainian churches (both Orthodox and Greek Catholic) hold services. The community has its own newspaper, social media groups, and integration support networks. Portugal felt familiar to many Ukrainians: warm people, similar family values, and a love of hearty food.",
    cefrMin: "A2",
    tags: ["community", "practical", "daily-life"],
  },
  {
    id: "uk_borshch_caldo_verde",
    type: "reference",
    contentPt: "Caldo verde e sopa — como o borshch",
    contentL1: "Caldo verde — португальський борщ",
    explanation: "Every Portuguese meal starts with soup, just like Ukrainian meals revolve around борщ. 'Caldo verde' — a thick broth with shredded kale, potato, and chouriço — is the national soup. Like борщ, it varies by region and every grandmother claims hers is best. Other soups: 'sopa de pedra' (stone soup, a legend), 'açorda' (bread soup with garlic and egg), 'canja' (chicken broth, the Portuguese cure for everything, like Ukrainian курячий бульйон). Soup culture is the easiest cultural bridge between Ukraine and Portugal.",
    cefrMin: "A1",
    tags: ["food", "culture", "daily-life"],
  },
  {
    id: "uk_practical_diaspora",
    type: "reference",
    contentPt: "Primeiros passos em Portugal",
    contentL1: "Перші кроки — NIF, NISS, conta bancária",
    explanation: "Every Ukrainian arriving in Portugal needs three things fast: NIF (número de identificação fiscal — your tax number, needed for everything), NISS (número de identificação da Segurança Social — for healthcare and work), and a conta bancária (bank account). The Finanças office issues the NIF. AIMA (formerly SEF) handles residency. Bring originals and copies of everything, with apostille where possible. Key phrase: 'Preciso de marcar atendimento' (I need to book an appointment). Portuguese bureaucracy moves slowly but the staff are patient — unlike in Ukraine, shouting will not help.",
    cefrMin: "A2",
    tags: ["practical", "bureaucracy", "daily-life"],
  },
  // --- MODERN SLANG ---
  {
    id: "uk_bue",
    type: "expression",
    contentPt: "Bué",
    contentL1: "Купа / Дуже / Дофіга",
    explanation: "'Bué' means 'a lot' or 'very' in PT-EU slang, from Kimbundu (Angolan). 'Bué fixe' (дуже круто), 'bué gente' (дофіга людей). Like Ukrainian 'дофіга' or 'купа'. Used by anyone under 40, ubiquitous in Lisbon.",
    cefrMin: "A2",
    tags: ["slang", "daily-life"],
  },
  {
    id: "uk_cena",
    type: "expression",
    contentPt: "Cena",
    contentL1: "Штука / Річ / Фігня",
    explanation: "Originally 'scene' but in PT-EU slang means 'thing/stuff/situation'. 'Que cena!' (Ну і фігня!), 'é uma cena estranha' (дивна штука). Like Ukrainian 'штука' or 'фігня'. Universal placeholder — 'dá-me aquela cena' (дай мені ту штуку).",
    cefrMin: "A2",
    tags: ["slang", "daily-life"],
  },
  {
    id: "uk_tipo",
    type: "expression",
    contentPt: "Tipo...",
    contentL1: "Типу... / Ну як би...",
    explanation: "The Portuguese filler word, like Ukrainian 'типу' or 'ну як би'. 'Ele é tipo alto' (Він типу високий). Every young Portuguese person uses it constantly. The Ukrainian 'типу' even sounds similar to 'tipo'.",
    cefrMin: "A2",
    tags: ["slang", "conversation"],
  },
  {
    id: "uk_ganda",
    type: "expression",
    contentPt: "Ganda / Granda",
    contentL1: "Файний / Крутий / Потужний",
    explanation: "Contraction of 'grande' — intensifier meaning 'great/massive'. 'Ganda filme!' (Файний фільм!), 'granda maluco!' (крутий чувак!). Like Ukrainian 'файний' or 'потужний'. Lisbon street slang, not for formal situations.",
    cefrMin: "B1",
    tags: ["slang"],
  },
  {
    id: "uk_bazar",
    type: "expression",
    contentPt: "Bazar",
    contentL1: "Злиняти / Звалити / Втекти",
    explanation: "'Bazar' means 'to leave/bounce'. 'Vou bazar' (я зливаю). Like Ukrainian 'злиняти' or 'звалити'. Nothing to do with a marketplace. 'Ele bazou' (він злиняв). Quick, informal departure.",
    cefrMin: "B1",
    tags: ["slang", "daily-life"],
  },
  {
    id: "uk_curtir",
    type: "expression",
    contentPt: "Curtir",
    contentL1: "Кайфувати / Тащитися / Подобатися",
    explanation: "'Curtir' means to enjoy, to be into something. 'Curto bué este sítio' (мені тут дуже подобається). Also romantic: 'Ela curte-o' (вона на нього запала). Like Ukrainian 'кайфувати' or 'тащитися'.",
    cefrMin: "A2",
    tags: ["slang", "daily-life"],
  },
  {
    id: "uk_na_boa",
    type: "expression",
    contentPt: "Na boa",
    contentL1: "Без проблем / Нормально / На розслабоні",
    explanation: "'Na boa' = 'no worries / it's all good'. 'Podes ficar, na boa' (Можеш залишитись, без проблем). Also a question: 'Tás na boa?' (Ти нормально?). Like Ukrainian 'без проблем'. One of the most useful casual phrases.",
    cefrMin: "A1",
    tags: ["slang", "daily-life"],
  },
  {
    id: "uk_o_pa",
    type: "expression",
    contentPt: "Ó pá!",
    contentL1: "Чувак! / Блін! / Ей!",
    explanation: "The quintessential Portuguese interjection. 'Ó pá, não acredito!' (Блін, не вірю!). Used between friends like Ukrainian 'чувак!' or 'блін!'. Short for 'rapaz'. Expresses surprise, frustration, or casual address. Heard dozens of times daily.",
    cefrMin: "A1",
    tags: ["slang", "daily-life"],
  },
  {
    id: "uk_mano",
    type: "expression",
    contentPt: "Mano / Mana",
    contentL1: "Бро / Братику / Сестро",
    explanation: "Short for 'irmão/irmã' (brother/sister). Used as 'bro/sis' between close friends. 'Olha, mano' (Слухай, братику). Like Ukrainian 'бро' or 'братику'. Very common in Lisbon, especially in multicultural neighbourhoods.",
    cefrMin: "A2",
    tags: ["slang", "daily-life"],
  },
  {
    id: "uk_mandar_vir",
    type: "expression",
    contentPt: "Mandar vir",
    contentL1: "Бурчати / Замовити (два значення!)",
    explanation: "Two completely different meanings: 1) 'To complain': 'Ele está sempre a mandar vir' (Він постійно бурчить) — like Ukrainian 'бурчати' or 'нарікати'. 2) 'To order': 'Manda vir mais uma cerveja' (Замов ще одне пиво). Context tells you which.",
    cefrMin: "B1",
    tags: ["slang", "daily-life"],
  },
  {
    id: "uk_ta_se_bem",
    type: "expression",
    contentPt: "Tá-se bem",
    contentL1: "Нормально! / Добре! / Окей!",
    explanation: "Contraction of 'está-se bem' — 'it's all good'. 'Vamos ao cinema?' — 'Tá-se bem!' (Підемо в кіно? — Добре!). Like Ukrainian 'добре' or 'окей'. Very casual, very common agreement.",
    cefrMin: "A1",
    tags: ["slang", "daily-life"],
  },
  // --- ANCIENT PROVERBS ---
  {
    id: "uk_agua_pedra",
    type: "expression",
    contentPt: "Água mole em pedra dura, tanto bate até que fura",
    contentL1: "Крапля камінь довбає",
    explanation: "Literally: 'Soft water on hard stone, hits until it pierces.' Identical to Ukrainian 'Крапля камінь довбає' (A drop hollows the stone). Both from Latin (Ovid). Persistence wins. One of the oldest shared proverbs between Portuguese and Ukrainian cultures.",
    cefrMin: "B1",
    tags: ["proverb", "wisdom"],
  },
  {
    id: "uk_cao_gato",
    type: "expression",
    contentPt: "Quem não tem cão, caça com gato",
    contentL1: "Як нема коня, то й віслюк — лицар",
    explanation: "Literally: 'Who doesn't have a dog, hunts with a cat.' Make do with what you have. Ukrainian says 'Як нема коня, то й віслюк — лицар' (When there's no horse, even a donkey is a knight). Both celebrate resourcefulness with limited means.",
    cefrMin: "B1",
    tags: ["proverb", "culture"],
  },
  {
    id: "uk_grao_galinha",
    type: "expression",
    contentPt: "Grão a grão, enche a galinha o papo",
    contentL1: "По зернятку і курка клює",
    explanation: "Literally: 'Grain by grain, the hen fills her crop.' Small things add up. Ukrainian says 'По зернятку і курка клює' (Grain by grain, the hen pecks). Remarkably close — same image (a hen and grain), same wisdom. Used when someone dismisses a small gain.",
    cefrMin: "B1",
    tags: ["proverb", "wisdom"],
  },
  {
    id: "uk_pepino",
    type: "expression",
    contentPt: "De pequenino se torce o pepino",
    contentL1: "Гни дерево, поки молоде",
    explanation: "Literally: 'You bend the cucumber when it's small.' Habits are formed young. Ukrainian says 'Гни дерево, поки молоде' (Bend the tree while it's young). Same principle — education and discipline must start early. Used by babusyas and avós alike.",
    cefrMin: "B1",
    tags: ["proverb", "education"],
  },
  {
    id: "uk_tripas_coracao",
    type: "expression",
    contentPt: "Fazer das tripas coração",
    contentL1: "Зібрати волю в кулак / Здолати себе",
    explanation: "Literally: 'To make heart out of guts.' To summon courage when you have none. Like Ukrainian 'зібрати волю в кулак' (to clench your will into a fist). Origin linked to Porto — residents sent good meat to the ships and ate tripe, hence Porto's nickname 'cidade dos tripeiros'.",
    cefrMin: "B1",
    tags: ["proverb", "history"],
  },
  {
    id: "uk_ver_navios",
    type: "expression",
    contentPt: "Ficar a ver navios",
    contentL1: "Залишитися з нічим / Залишитися ні з чим",
    explanation: "Literally: 'To be left watching ships.' To be left empty-handed. Origin: during the Age of Discoveries, women waited on docks for ships that never returned. Like Ukrainian 'залишитися ні з чим'. 'Fiquei a ver navios' (залишився ні з чим).",
    cefrMin: "B1",
    tags: ["proverb", "history"],
  },
  {
    id: "uk_engolir_sapos",
    type: "expression",
    contentPt: "Engolir sapos",
    contentL1: "Ковтнути образу / Стерпіти",
    explanation: "Literally: 'To swallow frogs.' To endure insults silently. Like Ukrainian 'ковтнути образу' (to swallow an insult). 'No trabalho, tenho de engolir muitos sapos' (На роботі доводиться багато терпіти). Ancient proverb, still used daily.",
    cefrMin: "B1",
    tags: ["proverb", "daily-life"],
  },
  {
    id: "uk_burros_agua",
    type: "expression",
    contentPt: "Dar com os burros na água",
    contentL1: "Сісти в калюжу / Провалитися",
    explanation: "Literally: 'To end up with the donkeys in the water.' To fail. Origin: donkey drivers crossing rivers — cargo was lost when donkeys fell in. Like Ukrainian 'сісти в калюжу' (to sit in a puddle). 'Tentei mas dei com os burros na água' (Спробував, але сів у калюжу).",
    cefrMin: "B1",
    tags: ["proverb", "daily-life"],
  },
  {
    id: "uk_rossio_betesga",
    type: "expression",
    contentPt: "Meter o Rossio na Betesga",
    contentL1: "Впхнути невпхнуване / Квадратура кола",
    explanation: "Literally: 'To fit the Rossio (Lisbon's grand square) into the Betesga (a tiny alley).' Attempting the impossible. Like Ukrainian 'квадратура кола' (squaring the circle). A purely Lisbon-born proverb from the Middle Ages, still used today.",
    cefrMin: "B2",
    tags: ["proverb", "lisbon"],
  },
  {
    id: "uk_mar_lugar",
    type: "expression",
    contentPt: "Quem vai ao mar, perde o lugar",
    contentL1: "Хто встав — той програв",
    explanation: "Literally: 'Who goes to sea, loses their place.' If you leave, someone takes your spot. Like Ukrainian 'Хто встав — той програв' (Who stood up — lost). Maritime origin — fishermen lost their tavern seat. Used for parking, queues, any contested position.",
    cefrMin: "A2",
    tags: ["proverb", "daily-life"],
  },
  // --- DAILY IDIOMS ---
  {
    id: "uk_ora_essa",
    type: "expression",
    contentPt: "Ora essa!",
    contentL1: "Та що ви! / Нема за що!",
    explanation: "Exclamation of modest denial when thanked. 'Obrigado pela ajuda!' — 'Ora essa!' (Дякую за допомогу! — Та нема за що!). Like Ukrainian 'нема за що'. Can also express surprise: 'Ora essa, quem diria!' (Ну треба ж, хто б подумав!).",
    cefrMin: "A2",
    tags: ["daily-life", "etiquette"],
  },
  {
    id: "uk_descansado",
    type: "expression",
    contentPt: "Fica descansado / Fica descansada",
    contentL1: "Не хвилюйся / Будь спокійний",
    explanation: "Literally: 'Be rested/at ease.' Means 'don't worry, I've got it.' 'Fica descansado, eu trato disso' (Не хвилюйся, я все вирішу). Like Ukrainian 'не хвилюйся' or 'будь спокійний'.",
    cefrMin: "A2",
    tags: ["daily-life", "conversation"],
  },
  {
    id: "uk_nao_faz_mal",
    type: "expression",
    contentPt: "Não faz mal",
    contentL1: "Нічого страшного / Не біда",
    explanation: "Literally: 'It doesn't do harm.' Standard response when someone apologises for a minor thing. 'Desculpa o atraso!' — 'Não faz mal!' (Вибач за запізнення! — Нічого страшного!). Exact equivalent of Ukrainian 'нічого страшного'.",
    cefrMin: "A1",
    tags: ["daily-life", "etiquette"],
  },
  {
    id: "uk_deixa_la",
    type: "expression",
    contentPt: "Deixa lá",
    contentL1: "Забий / Ладно / Неважливо",
    explanation: "'Deixa lá' = 'let it go / forget it.' 'Queres que te pague?' — 'Deixa lá!' (Хочеш я заплачу? — Забий!). Can also console: 'Deixa lá, amanhã corre melhor' (Забий, завтра буде краще). Like Ukrainian 'забий' or 'ладно'.",
    cefrMin: "A1",
    tags: ["daily-life", "conversation"],
  },
  {
    id: "uk_e_o_que_e",
    type: "expression",
    contentPt: "É o que é",
    contentL1: "Що є, те є / Так воно є",
    explanation: "'It is what it is' — philosophical acceptance. 'O preço subiu? É o que é.' (Ціна зросла? Так воно є.) Spoken with a shrug. Like Ukrainian 'що поробиш'. Portuguese fatalism alongside resourcefulness.",
    cefrMin: "A2",
    tags: ["daily-life", "culture"],
  },
  {
    id: "uk_olha_la",
    type: "expression",
    contentPt: "Olha lá / Ouve lá",
    contentL1: "Слухай / Гей / Скажи-но",
    explanation: "'Olha lá' (look here) and 'ouve lá' (listen here) get attention or start a question. 'Olha lá, sabes onde fica o correio?' (Слухай, знаєш де пошта?). Like Ukrainian 'слухай'. Not rude — the standard way to approach someone.",
    cefrMin: "A1",
    tags: ["daily-life", "conversation"],
  },
  {
    id: "uk_entao",
    type: "expression",
    contentPt: "Então?",
    contentL1: "Ну що? / Ну як? / І?",
    explanation: "'Então?' is the universal Portuguese greeting-question. 'Então, tudo bem?' (Ну що, все добре?). Also prompts: 'Então, o que queres fazer?' (Ну, що хочеш робити?). Like Ukrainian 'ну що?' or 'ну як?'. Short, warm, multipurpose.",
    cefrMin: "A1",
    tags: ["daily-life", "conversation"],
  },
  {
    id: "uk_se_calhar",
    type: "expression",
    contentPt: "Se calhar",
    contentL1: "Може бути / Мабуть / Можливо",
    explanation: "Literally: 'if it falls (that way).' Means 'maybe/perhaps.' 'Se calhar vou ao cinema' (Може бути піду в кіно). More common than 'talvez' in everyday PT-EU speech. Like Ukrainian 'може бути' or 'мабуть'. Note: unlike 'talvez', this does NOT trigger the subjunctive.",
    cefrMin: "A2",
    tags: ["daily-life", "grammar"],
  },
  {
    id: "uk_com_certeza",
    type: "expression",
    contentPt: "Com certeza",
    contentL1: "Звісно / Звичайно (але обережно!)",
    explanation: "'Com certeza' means 'certainly'. BUT in PT-EU it is often polite but non-committal — like saying 'звісно' without really meaning it. A Portuguese 'com certeza' can mean 'I'll think about it' (and forget). Ukrainians take 'звичайно' more literally. Watch for this cultural trap.",
    cefrMin: "A2",
    tags: ["daily-life", "etiquette"],
  },
];
