import type { L1Profile } from "../types.js";

export const ukProfile: L1Profile = {
  code: "uk",
  name: "Ukrainian",
  nativeName: "Українська",
  writingDirection: "ltr",
  hasLatinScript: false,
  transfer: {
    cognates: [
      "музика (música — music)",
      "культура (cultura — culture)",
      "проблема (problema — problem)",
      "університет (universidade — university)",
      "документ (documento — document)",
      "група (grupo — group)",
      "момент (momento — moment)",
      "система (sistema — system)",
      "інформація (informação — information)",
      "демократія (democracia — democracy)",
      "енергія (energia — energy)",
      "транспорт (transporte — transport)",
      "телефон (telefone — telephone)",
      "кафе (café — coffee/café)",
      "ресторан (restaurante — restaurant)",
      "театр (teatro — theatre)",
    ],
    falseFriends: [
      { word: "mal", l1Meaning: "малий (malyy) might suggest 'small'", ptMeaning: "mal means 'badly/evil' — small = pequeno" },
      { word: "massa", l1Meaning: "маса (masa) — mass/bulk in Ukrainian", ptMeaning: "massa means 'dough/pasta' primarily" },
      { word: "nota", l1Meaning: "нота (nota) — musical note in Ukrainian", ptMeaning: "nota means 'grade/mark' AND 'banknote' as well as musical note" },
      { word: "pasta", l1Meaning: "паста (pasta) — paste/toothpaste", ptMeaning: "pasta means 'folder/briefcase' — paste = massa" },
      { word: "sala", l1Meaning: "сало (salo) — cured pork fatback, national dish", ptMeaning: "sala means 'room/living room'" },
      { word: "lista", l1Meaning: "лист (lyst) — leaf/letter/sheet", ptMeaning: "lista means 'list/menu' — leaf = folha, letter = carta" },
      { word: "manga", l1Meaning: "манга — Japanese comics", ptMeaning: "manga primarily means 'sleeve' — also means mango fruit" },
      { word: "prima", l1Meaning: "примa (prima) — prima donna", ptMeaning: "prima means 'female cousin'" },
      { word: "forma", l1Meaning: "форма (forma) — uniform/shape", ptMeaning: "forma means 'form/shape/mould' — uniform = farda" },
      { word: "bar", l1Meaning: "бар (bar) — same meaning", ptMeaning: "bar means a drinking establishment — true cognate" },
      { word: "campo", l1Meaning: "sounds like компот (kompot) — stewed fruit drink", ptMeaning: "campo means 'field/countryside'" },
      { word: "dom", l1Meaning: "дім (dim) — home/house", ptMeaning: "dom means 'Mr/Sir' (title) or 'gift' — house = casa" },
      { word: "comer", l1Meaning: "sounds like комер — no Ukrainian meaning", ptMeaning: "comer means 'to eat'" },
      { word: "largo", l1Meaning: "ларго — musical term (broadly)", ptMeaning: "largo means 'wide' or 'public square'" },
      { word: "mar", l1Meaning: "мар — no standard meaning (мара = ghost)", ptMeaning: "mar means 'sea/ocean'" },
      { word: "ser", l1Meaning: "сер — sounds like сірий (grey)", ptMeaning: "ser means 'to be' (identity/permanent)" },
      { word: "caro", l1Meaning: "sounds like каро — no meaning", ptMeaning: "caro means 'expensive' or 'dear'" },
      { word: "porta", l1Meaning: "порта — sounds like порт (port)", ptMeaning: "porta means 'door' — port = porto" },
      { word: "gato", l1Meaning: "sounds like ґато — no meaning (кіт = cat)", ptMeaning: "gato means 'cat'" },
      { word: "banco", l1Meaning: "банко — sounds like банк (bank)", ptMeaning: "banco means 'bank' AND 'bench'" },
      { word: "cola", l1Meaning: "кола (kola) — cola drink or колo (wheel)", ptMeaning: "cola means 'glue' — cola drink = Coca-Cola" },
      { word: "conta", l1Meaning: "конта — no Ukrainian word", ptMeaning: "conta means 'bill/account/story'" },
      { word: "data", l1Meaning: "дата (data) — date — same!", ptMeaning: "data means 'date' — true cognate" },
      { word: "prato", l1Meaning: "прато — no meaning", ptMeaning: "prato means 'plate/dish' — do not confuse with prato (course of a meal)" },
      { word: "rua", l1Meaning: "sounds like руа — no Ukrainian word", ptMeaning: "rua means 'street' — the most common word on signs in Portugal" },
      { word: "mesa", l1Meaning: "sounds like меса — no standard Ukrainian meaning", ptMeaning: "mesa means 'table' — 'à mesa' = at the table" },
      { word: "fato", l1Meaning: "sounds like факт (fakt) — fact", ptMeaning: "fato means 'suit (clothing)' or 'fact' — suit meaning is more common in daily life" },
      { word: "pé", l1Meaning: "sounds like пе — no meaning", ptMeaning: "pé means 'foot' — 'a pé' = on foot, 'em pé' = standing" },
      { word: "quarto", l1Meaning: "sounds like кварта — a quarter/unit", ptMeaning: "quarto means 'bedroom' or 'fourth' — кімната in Ukrainian" },
      { word: "vaga", l1Meaning: "вага (vaha) means 'weight/scales' in Ukrainian", ptMeaning: "vaga means 'vacancy' or 'wave' — weight = peso" },
      { word: "praia", l1Meaning: "sounds like прая — no Ukrainian meaning", ptMeaning: "praia means 'beach'" },
      { word: "loja", l1Meaning: "ложа (lozha) means 'theatre box/lodge'", ptMeaning: "loja means 'shop/store' — theatre box = camarote" },
      { word: "carta", l1Meaning: "карта (karta) means 'map/card' in Ukrainian", ptMeaning: "carta means 'letter (post)' — map = mapa, card = cartão" },
      { word: "passo", l1Meaning: "sounds like пас — pass (in football)", ptMeaning: "passo means 'step/pace' — 'passo a passo' = step by step" },
      { word: "morada", l1Meaning: "sounds like морада — no Ukrainian meaning", ptMeaning: "morada means 'address (home)' — essential for Portuguese bureaucracy" },
      { word: "ficha", l1Meaning: "фішка (fishka) means 'chip/token' in Ukrainian", ptMeaning: "ficha means 'form/plug/token' — ficha de inscrição = registration form" },
      { word: "cabeça", l1Meaning: "sounds like кабеса — no Ukrainian meaning", ptMeaning: "cabeça means 'head' — 'dor de cabeça' = headache" },
      { word: "roupa", l1Meaning: "sounds like рупа — no Ukrainian meaning", ptMeaning: "roupa means 'clothing/clothes'" },
      { word: "cozinha", l1Meaning: "sounds like козина — no standard Ukrainian meaning", ptMeaning: "cozinha means 'kitchen' — cozinhar = to cook" },
      { word: "direito", l1Meaning: "sounds like директ — no standard meaning", ptMeaning: "direito means 'right (direction)' AND 'law/right' — 'à direita' = to the right, 'direitos' = rights" },
    ],
    phoneticDifficulties: [
      {
        sound: "ão",
        ipa: "/ɐ̃w̃/",
        description: "Nasal diphthong -ão",
        tip: "Ukrainian has no nasal vowels. Open your mouth for 'a', lower the soft palate for nasal airflow, then glide to a nasal 'u'. This moving nasal sound has no Ukrainian parallel. Practice: pão, mão, não.",
        mouthPosition: "nasal_ao",
      },
      {
        sound: "ã/õ/ẽ",
        ipa: "/ɐ̃/ /õ/ /ẽ/",
        description: "Nasal vowels",
        tip: "Ukrainian never nasalizes vowels. Lower your soft palate to send air through both mouth and nose while holding the vowel. 'Maçã' (apple), 'limão' (lemon), 'irmã' (sister).",
        mouthPosition: "nasal_vowel",
      },
      {
        sound: "lh",
        ipa: "/ʎ/",
        description: "Palatal lateral lh",
        tip: "Ukrainian has soft ль which is close. PT-EU 'lh' is a true palatal lateral — tongue flat against the hard palate. 'Trabalho' (work), 'filho' (son). Your soft ль is good preparation.",
        mouthPosition: "palatal_lateral",
      },
      {
        sound: "nh",
        ipa: "/ɲ/",
        description: "Palatal nasal nh",
        tip: "Similar to Ukrainian нь. Place the tongue against the palate while nasalizing. 'Vinho' (wine), 'amanhã' (tomorrow), 'Espanha' (Spain).",
        mouthPosition: "palatal_nasal",
      },
      {
        sound: "r/rr",
        ipa: "/ʁ/",
        description: "Uvular R (initial and double)",
        tip: "Ukrainian р is a trilled alveolar R. PT-EU initial R and double RR are uvular — at the back of the throat. Do NOT trill! Think of the French R. 'Rato' (mouse), 'carro' (car).",
        mouthPosition: "uvular_r",
      },
      {
        sound: "r (tap)",
        ipa: "/ɾ/",
        description: "Alveolar tap between vowels",
        tip: "A single quick flap, lighter than Ukrainian р. Just one touch. 'Caro' (expensive), 'para' (for), 'cero' (zero).",
        mouthPosition: "alveolar_tap",
      },
      {
        sound: "open/closed e",
        ipa: "/ɛ/ vs /e/",
        description: "Two e sounds that change meaning",
        tip: "Ukrainian has a similar e/є distinction. PT-EU 'é' is open (/ɛ/, café), 'ê' is closed (/e/, você). 'Avó' (grandmother) vs 'avô' (grandfather).",
        mouthPosition: "open_e",
      },
      {
        sound: "open/closed o",
        ipa: "/ɔ/ vs /o/",
        description: "Two o sounds",
        tip: "Open 'ó' (/ɔ/) vs closed 'ô' (/o/). Ukrainian distinguishes о and a similar open vowel. Use accent marks as guides.",
        mouthPosition: "open_o",
      },
      {
        sound: "reduced vowels",
        ipa: "/ɨ/ /ə/",
        description: "Unstressed vowels nearly vanish",
        tip: "Ukrainian reduces vowels less than Russian but more than many languages. PT-EU goes very far — 'Portugal' sounds like 'Purtugal'. Lean into this instinct.",
      },
      {
        sound: "s/z/ʃ/ʒ",
        ipa: "/s/ /z/ /ʃ/ /ʒ/",
        description: "Four sibilants",
        tip: "Ukrainian has с/з/ш/ж — perfect match! PT-EU distribution differs: final 's' = /ʃ/, 's' between vowels = /z/, 'j' always = /ʒ/. Same sounds, different spelling rules.",
        mouthPosition: "sibilant_s",
      },
      {
        sound: "v/b distinction",
        ipa: "/v/ vs /b/",
        description: "V is labiodental, B is bilabial",
        tip: "Ukrainian в and б are already distinct. Apply the same to PT-EU: 'vela' (candle) vs 'bela' (beautiful). Natural advantage.",
        mouthPosition: "labiodental_v",
      },
      {
        sound: "dark L",
        ipa: "/ɫ/",
        description: "Velarized L at syllable end",
        tip: "Ukrainian has hard л similar to PT-EU dark L. Use it for final positions: 'Portugal', 'sol' (sun), 'mal' (badly).",
      },
      {
        sound: "consonant clusters",
        ipa: "/pr/ /tr/ /pl/ /str/",
        description: "Initial consonant clusters",
        tip: "Good news: Ukrainian also has initial clusters (зустріч, здрастуй). PT-EU clusters are simpler: 'prato' (plate), 'três' (three), 'construção' (construction). Your Ukrainian cluster experience helps.",
      },
      {
        sound: "word-final -e",
        ipa: "/ɨ/ or silent",
        description: "Final -e nearly disappears",
        tip: "Ukrainian final -е is always clearly pronounced. PT-EU final -e is barely a whisper or vanishes entirely. 'Cidade' sounds like 'cidadɨ' or even 'cidad'. This is a major rhythm difference.",
      },
      {
        sound: "diphthongs",
        ipa: "/ej/ /ow/ /aj/ /oj/",
        description: "Oral diphthongs (ei, ou, ai, oi)",
        tip: "Ukrainian has few true diphthongs. PT-EU has many: 'primeiro' (ei), 'outro' (ou), 'pai' (ai), 'noite' (oi). The two vowels glide smoothly in a single syllable — do not break them into separate syllables.",
      },
    ],
    grammarGaps: [
      {
        concept: "Articles (o/a, um/uma)",
        explanation: "Every noun requires a definite or indefinite article",
        l1Comparison: "Ukrainian has no articles. You must always say 'o livro' (the book), not just 'livro'. The article reveals gender and definiteness. This is the single biggest grammar adjustment.",
      },
      {
        concept: "Only 2 genders (no neuter)",
        explanation: "Portuguese has masculine (o) and feminine (a) only",
        l1Comparison: "Ukrainian has three genders (він/вона/воно). PT-EU has two — neuter disappeared. Gender assignments differ: 'сонце' (neuter sun) → 'o sol' (masculine). Learn each noun with its article.",
      },
      {
        concept: "No case system",
        explanation: "Portuguese uses prepositions and word order instead of cases",
        l1Comparison: "Ukrainian has 7 cases (називний → кличний). PT-EU uses none — prepositions do the work: 'de' for genitive, 'a/para' for dative. A major simplification once you adjust.",
      },
      {
        concept: "Ser vs Estar",
        explanation: "Two verbs for 'to be'",
        l1Comparison: "Ukrainian бути is rarely used in present tense ('Я студент'). PT-EU always requires 'to be', choosing between 'ser' (identity) and 'estar' (state): 'Sou ucraniano' vs 'Estou cansado'.",
      },
      {
        concept: "Verb conjugation (tenses, not aspects)",
        explanation: "6 persons × 12+ tenses across 3 moods",
        l1Comparison: "Ukrainian uses 2 aspects (доконаний/недоконаний) × 3 tenses. PT-EU replaces aspects with many tenses. The pretérito perfeito/imperfeito distinction is the closest to Ukrainian aspect.",
      },
      {
        concept: "Subjunctive mood",
        explanation: "Required for doubt, desire, emotion, uncertainty",
        l1Comparison: "Ukrainian умовний спосіб (using б/би) is simpler. PT-EU has present, past, and future subjunctive — all fully conjugated: 'Espero que venhas', 'Se eu fosse', 'Quando for'.",
      },
      {
        concept: "Personal infinitive",
        explanation: "Infinitive conjugated for person — unique to Portuguese",
        l1Comparison: "No Ukrainian equivalent. 'Para nós fazermos' (for us to do) replaces a full subordinate clause. This is a uniquely Portuguese construction.",
      },
      {
        concept: "Preposition contractions",
        explanation: "Mandatory: em+o=no, de+a=da, a+o=ao, por+o=pelo",
        l1Comparison: "Ukrainian prepositions never contract with other words. PT-EU contractions are mandatory and frequent: 'no' (em + o), 'da' (de + a), 'ao' (a + o).",
      },
      {
        concept: "Object pronoun placement",
        explanation: "Before or after the verb depending on context",
        l1Comparison: "Ukrainian has relatively free pronoun placement. PT-EU has strict rules: after the verb by default ('Dá-me'), before with negation ('Não me dás'). Mesoclisis in future: 'Dir-lhe-ei'.",
      },
      {
        concept: "Tu vs Você vs O Senhor",
        explanation: "Three formality levels for 'you'",
        l1Comparison: "Ukrainian ти/Ви gives two levels. PT-EU has three: 'tu' (like ти), 'você' (neutral/can be awkward), 'o senhor' (formal, like Ви). In Portugal, 'tu' is default among peers.",
      },
      {
        concept: "Definite article with names",
        explanation: "'A Maria', 'o João' — articles before proper names",
        l1Comparison: "Ukrainian never uses articles. PT-EU requires them even before names: 'A Maria vem amanhã'. This applies to all names in spoken Portuguese.",
      },
      {
        concept: "Continuous with 'estar a + infinitive'",
        explanation: "'Estou a trabalhar' = I am working",
        l1Comparison: "Ukrainian uses imperfective aspect for ongoing actions. PT-EU uses the construction 'estar a + infinitive'. The gerund form ('estou trabalhando') is Brazilian, not European.",
      },
      {
        concept: "Reflexive verbs",
        explanation: "Many common verbs require a reflexive pronoun: levantar-se, sentar-se, chamar-se",
        l1Comparison: "Ukrainian has reflexive -ся/-сь verbs (одягатися, сідати). PT-EU reflexives work similarly but the pronoun is separate and moves: 'Chamo-me Ana' (after verb), 'Não me chamo' (before with negation). In Ukrainian -ся is always suffixed.",
      },
      {
        concept: "Definite article with possessives",
        explanation: "'O meu carro' — article + possessive + noun",
        l1Comparison: "Ukrainian has no articles at all: 'моя машина' (my car). PT-EU requires both article AND possessive: 'o meu carro'. Dropping the article ('meu carro') sounds Brazilian. In Portugal always include it.",
      },
      {
        concept: "Haver vs Ter",
        explanation: "'Há' for existence, 'ter' for possession and as perfect auxiliary",
        l1Comparison: "Ukrainian uses 'є' for existence and 'у мене є' for possession. PT-EU splits differently: 'Há muitas pessoas' (there are many people — haver, impersonal) vs 'Tenho um carro' (I have a car — ter). 'Ter' also forms the compound past: 'Tenho feito' (I have been doing).",
      },
    ],
    skipBasics: false,
    startingCEFR: "A1",
  },
};
