import type { CulturalRef } from "../types.js";

export const frCulturalRefs: readonly CulturalRef[] = [
  {
    id: "fr_desenrascar",
    type: "expression",
    contentPt: "Desenrascar-se",
    contentL1: "Se débrouiller / se démerder",
    explanation: "Proche de 'se débrouiller' mais élevé au rang de philosophie nationale. Implique une improvisation créative sous pression, pas juste se débrouiller.",
    cefrMin: "A2",
    tags: ["culture", "daily-life"],
  },
  {
    id: "fr_saudade",
    type: "expression",
    contentPt: "Saudade",
    contentL1: "Nostalgie profonde (intraduisible)",
    explanation: "Plus profond que 'nostalgie'. Un manque doux-amer pour quelqu'un, quelque chose ou un moment. Comme 'le mal du pays' mais pas limité au lieu. Central dans l'identité portugaise.",
    cefrMin: "B1",
    tags: ["culture", "emotion"],
  },
  {
    id: "fr_bica",
    type: "reference",
    contentPt: "Uma bica",
    contentL1: "Un expresso (à Lisbonne)",
    explanation: "A Lisbonne, on ne dit pas 'um café', on dit 'uma bica'. A Porto, c'est 'um cimbalino'. Le même expresso, deux mots selon la ville.",
    cefrMin: "A1",
    tags: ["food", "daily-life", "lisbon"],
  },
  {
    id: "fr_galao",
    type: "reference",
    contentPt: "Um galão / uma meia de leite",
    contentL1: "Un café au lait (dans un grand verre / dans une tasse)",
    explanation: "Le galão se sert dans un grand verre, avec beaucoup de lait. La meia de leite, c'est moitié café, moitié lait, dans une tasse. Ni l'un ni l'autre n'est un 'café au lait' exactement.",
    cefrMin: "A1",
    tags: ["food", "daily-life"],
  },
  {
    id: "fr_pastel_nata",
    type: "reference",
    contentPt: "Pastel de nata",
    contentL1: "Tartelette aux oeufs (pâte feuilletée)",
    explanation: "Le dessert national. Pâte feuilletée croustillante, crème aux oeufs caramélisée. Inventé par les moines de Belém. On ne dit jamais 'pastéis de Belém' sauf pour ceux de la pâtisserie historique.",
    cefrMin: "A1",
    tags: ["food", "culture", "lisbon"],
  },
  {
    id: "fr_francesinha",
    type: "reference",
    contentPt: "Francesinha",
    contentL1: "La 'petite française' (sandwich de Porto)",
    explanation: "Le nom signifie littéralement 'petite française' ! Inspiré du croque-monsieur mais poussé à l'extrême : pain, viandes multiples, fromage fondu, sauce piquante à la bière. Spécialité de Porto.",
    cefrMin: "A2",
    tags: ["food", "culture", "porto"],
  },
  {
    id: "fr_bacalhau",
    type: "reference",
    contentPt: "Bacalhau",
    contentL1: "Morue séchée et salée",
    explanation: "Les Portugais disent avoir 365 recettes de morue, une pour chaque jour. Ce n'est pas du poisson frais : c'est de la morue salée séchée qu'on fait tremper. Le plat national non officiel.",
    cefrMin: "A2",
    tags: ["food", "culture"],
  },
  {
    id: "fr_fado",
    type: "reference",
    contentPt: "O fado",
    contentL1: "Le fado (musique traditionnelle)",
    explanation: "Comme la chanson française a Piaf et Brel, le fado a Amália Rodrigues et Mariza. Mais le fado est plus qu'un genre : c'est l'expression musicale de la saudade. Patrimoine UNESCO depuis 2011.",
    cefrMin: "B1",
    tags: ["culture", "music"],
  },
  {
    id: "fr_fixe",
    type: "expression",
    contentPt: "Fixe!",
    contentL1: "Cool ! / Génial !",
    explanation: "L'équivalent de 'cool' ou 'génial'. Très courant chez les jeunes. Ne pas confondre avec 'fixo' (fixe/permanent). Prononciation : /ˈfiʃ/.",
    cefrMin: "A1",
    tags: ["slang", "daily-life"],
  },
  {
    id: "fr_dois_beijos",
    type: "reference",
    contentPt: "Dar dois beijinhos",
    contentL1: "Faire la bise (deux bisous)",
    explanation: "Comme en France, les Portugais font deux bises pour se saluer. Mais attention : on commence par la joue droite au Portugal (souvent par la gauche en France). Entre hommes, c'est une poignée de main.",
    cefrMin: "A1",
    tags: ["culture", "social"],
  },
  {
    id: "fr_chavena",
    type: "reference",
    contentPt: "Uma chávena de chá",
    contentL1: "Une tasse de thé",
    explanation: "En PT-EU on dit 'chávena' pour tasse (pas 'xícara', qui est brésilien). Le mot vient du persan via les routes commerciales portugaises. L'heure du thé existe aussi au Portugal.",
    cefrMin: "A2",
    tags: ["daily-life", "vocabulary"],
  },
  {
    id: "fr_autocarro",
    type: "reference",
    contentPt: "Autocarro / comboio / elétrico",
    contentL1: "Bus / train / tramway",
    explanation: "Les transports en PT-EU ont des mots différents du brésilien. Bus = autocarro (pas 'ônibus'), train = comboio (pas 'trem'), tramway = elétrico. A Lisbonne, le fameux elétrico 28.",
    cefrMin: "A1",
    tags: ["daily-life", "vocabulary", "lisbon"],
  },
  {
    id: "fr_nas_tintas",
    type: "expression",
    contentPt: "Estar-se nas tintas",
    contentL1: "S'en foutre / s'en ficher",
    explanation: "Littéralement 'être dans les peintures'. Signifie qu'on s'en moque complètement. Très courant, légèrement grossier. Comme 's'en ficher' en un peu plus fort.",
    cefrMin: "B1",
    tags: ["slang", "emotion"],
  },
  {
    id: "fr_pois",
    type: "expression",
    contentPt: "Pois... / Pois, pois...",
    contentL1: "Bon... / Ouais... / Ben oui...",
    explanation: "Le mot de remplissage portugais par excellence. Équivalent de 'bon ben...' ou 'ouais...' en français. Peut exprimer l'accord, la résignation, ou juste remplir le silence.",
    cefrMin: "A2",
    tags: ["daily-life", "conversation"],
  },
  {
    id: "fr_tu_voce",
    type: "reference",
    contentPt: "Tu / Você / O Senhor, A Senhora",
    contentL1: "Tu / Vous (mais avec trois niveaux)",
    explanation: "Le français a tu/vous. Le PT-EU a trois niveaux : tu (famille, amis), você (courant mais peut être impoli dans le nord), o senhor/a senhora (formel). Au nord du Portugal, 'você' est presque insultant — on utilise le prénom + 3e personne.",
    cefrMin: "A2",
    tags: ["culture", "grammar", "social"],
  },
  {
    id: "fr_tasca",
    type: "reference",
    contentPt: "Uma tasca / um restaurante típico",
    contentL1: "Un bistrot / une taverne",
    explanation: "L'équivalent du bistrot français. Petits restaurants familiaux avec des plats du jour copieux et bon marché. Le menu est souvent affiché au mur. La vraie cuisine portugaise.",
    cefrMin: "A2",
    tags: ["food", "daily-life", "culture"],
  },
  {
    id: "fr_lusofonia",
    type: "reference",
    contentPt: "A lusofonia",
    contentL1: "La lusophonie (comme la francophonie)",
    explanation: "Le portugais est la 6e langue la plus parlée au monde. Comme la francophonie, la lusophonie relie Portugal, Brésil, Angola, Mozambique, Cap-Vert, Guinée-Bissau, Timor-Leste, Sao Tomé. Mais PT-EU est distinct du brésilien.",
    cefrMin: "B1",
    tags: ["culture", "language"],
  },
  {
    id: "fr_football",
    type: "reference",
    contentPt: "O futebol: Benfica, Sporting, Porto",
    contentL1: "Le football : les trois grands clubs",
    explanation: "Le football est la passion nationale, comme en France. Mais il n'y a que trois grands clubs : Benfica et Sporting (Lisbonne), et FC Porto. Demander 'és de que clube?' c'est demander une allégeance à vie.",
    cefrMin: "A2",
    tags: ["culture", "sports"],
  },
  {
    id: "fr_obrigado",
    type: "expression",
    contentPt: "Obrigado / Obrigada",
    contentL1: "Merci (mais genré)",
    explanation: "En français, 'merci' ne change pas. En PT-EU, un homme dit 'obrigado', une femme dit 'obrigada'. Littéralement 'obligé(e)'. Ne vous trompez pas de genre !",
    cefrMin: "A1",
    tags: ["daily-life", "grammar"],
  },
  {
    id: "fr_se_faz_favor",
    type: "expression",
    contentPt: "Se faz favor / Faz favor",
    contentL1: "S'il vous plaît",
    explanation: "En PT-EU on dit 'se faz favor' (et pas 'por favor' qui est plus courant au Brésil, bien qu'accepté). Au restaurant, on appelle le serveur avec 'faz favor!' et pas en claquant des doigts.",
    cefrMin: "A1",
    tags: ["daily-life", "social"],
  },
  {
    id: "fr_25_abril",
    type: "reference",
    contentPt: "25 de Abril — Revolução dos Cravos",
    contentL1: "25 avril — la Révolution des OEillets (1974)",
    explanation: "Le moment fondateur du Portugal moderne. Le 25 avril 1974, un coup d'État militaire pacifique a renversé la dictature de Salazar/Caetano. Les soldats ont mis des oeillets rouges dans leurs fusils. Comme Mai 68 en France, mais avec un vrai changement de régime. Le pont principal de Lisbonne porte ce nom.",
    cefrMin: "B1",
    tags: ["history", "culture", "identity"],
  },
  {
    id: "fr_pronto",
    type: "expression",
    contentPt: "Pronto!",
    contentL1: "Voilà ! / Bon ! / C'est fait !",
    explanation: "Un des mots les plus entendus au Portugal. Sert à signaler qu'on a fini ('Pronto, acabei!'), à avancer une conversation ('Pronto, vamos lá'), ou à remplir un silence. L'équivalent de 'voilà' ou 'bon ben' en français.",
    cefrMin: "A1",
    tags: ["daily-life", "conversation"],
  },
  {
    id: "fr_tuga",
    type: "expression",
    contentPt: "Tuga",
    contentL1: "Portugais(e) (familier / affectueux)",
    explanation: "L'argot affectueux pour dire 'portugais'. Les Portugais l'utilisent eux-mêmes, ce n'est pas péjoratif. 'Coisas de tuga' = 'trucs de Portugais'. Le mot savant est 'lusitano' (de Lusitania, la province romaine).",
    cefrMin: "B1",
    tags: ["slang", "identity"],
  },
  {
    id: "fr_repas",
    type: "reference",
    contentPt: "Pequeno-almoço, almoço, lanche, jantar",
    contentL1: "Petit-déjeuner, déjeuner, goûter, dîner",
    explanation: "Les horaires de repas diffèrent de la France. Pequeno-almoço (petit-dej) : léger, café + pastéis. Almoço (déjeuner, 12h30-14h) : le repas principal, copieux. Lanche (goûter, ~16h) : café et gâteau. Jantar (dîner, 20h-21h) : peut être aussi copieux que le déjeuner. Dîner avant 19h30 est très tôt.",
    cefrMin: "A1",
    tags: ["food", "daily-life", "culture"],
  },
  {
    id: "fr_lisboa_porto",
    type: "reference",
    contentPt: "Lisboa vs Porto",
    contentL1: "Lisbonne vs Porto (la rivalité culturelle)",
    explanation: "Comme Paris-Marseille mais plus intense. Lisbonne (lisboetas) est la capitale cosmopolite. Porto (portuenses/tripeiros) est fièrement ouvrière et indépendante. Les habitants de Porto s'appellent 'tripeiros' (mangeurs de tripes) — un honneur historique. Nourriture, accent, football (Benfica vs FC Porto) : tout diffère.",
    cefrMin: "B1",
    tags: ["culture", "lisbon", "porto", "identity"],
  },
  {
    id: "fr_santos_populares",
    type: "reference",
    contentPt: "Santos Populares — Festas de Junho",
    contentL1: "Les fêtes populaires de Juin",
    explanation: "Tout le mois de juin, le Portugal fête les saints populaires : Santo António (Lisbonne, 13 juin), São João (Porto, 24 juin), São Pedro (29 juin). Sardines grillées, caldo verde, vin, danses dans la rue, marteaux en plastique (São João). C'est la plus grande fête de l'année, plus importante que le Nouvel An pour beaucoup.",
    cefrMin: "A2",
    tags: ["culture", "traditions", "lisbon", "porto"],
  },
  // --- ARGOT MODERNE ---
  {
    id: "fr_bue",
    type: "expression",
    contentPt: "Bué",
    contentL1: "Grave / trop / vachement",
    explanation: "Argot portugais universel pour 'beaucoup' ou 'très'. 'Isto é bué fixe' = 'C'est grave bien'. Vient du kimbundu (Angola), arrivé à Lisbonne par les vagues migratoires post-coloniales. Même registre que 'grave' ou 'trop' en français familier — informel uniquement.",
    cefrMin: "A2",
    tags: ["slang", "daily-life"],
  },
  {
    id: "fr_cena",
    type: "expression",
    contentPt: "Cena",
    contentL1: "Truc / machin / le délire",
    explanation: "Le mot fourre-tout des jeunes Portugais. Littéralement 'scène', mais utilisé pour tout : 'Aquela cena' = 'ce truc-là'. 'É uma cena estranha' = 'C'est un délire bizarre'. 'Que cena!' = 'Quel truc !'. Exactement comme 'truc' ou 'machin' en français quand on ne trouve pas le mot juste.",
    cefrMin: "A2",
    tags: ["slang", "daily-life"],
  },
  {
    id: "fr_tipo",
    type: "expression",
    contentPt: "Tipo...",
    contentL1: "Genre... / style...",
    explanation: "Utilisé comme le 'genre' français : un tic de langage. 'Ele era tipo... estranho' = 'Il était genre... bizarre'. Aussi = 'un mec' ('aquele tipo' = 'ce type-là'). Les jeunes Portugais mettent 'tipo' partout, exactement comme les Français avec 'genre'. Agace les générations précédentes dans les deux langues.",
    cefrMin: "A2",
    tags: ["slang", "conversation"],
  },
  {
    id: "fr_ganda",
    type: "expression",
    contentPt: "Ganda!",
    contentL1: "De ouf ! / Énorme !",
    explanation: "Contraction de 'grande'. Intensificateur argotique. 'Ganda festa!' = 'Fête de ouf !'. 'Ganda maluco' = 'Quel taré' (affectueux). Peut être positif ('ganda golo!' — quel but !) ou négatif ('ganda confusão' — quel bordel). Très lisboète, très oral.",
    cefrMin: "B1",
    tags: ["slang", "daily-life"],
  },
  {
    id: "fr_bazar",
    type: "expression",
    contentPt: "Bazar",
    contentL1: "Se barrer / se casser / se tirer",
    explanation: "Argot pour 'partir'. 'Vou bazar' = 'Je me casse'. Du persan/arabe via le romani. En français, 'se barrer' a exactement le même registre — très familier, entre amis. Aussi : 'pirar-se' (se tailler), 'ir à vida' (s'en aller).",
    cefrMin: "B1",
    tags: ["slang"],
  },
  {
    id: "fr_curtir",
    type: "expression",
    contentPt: "Curtir",
    contentL1: "Kiffer / apprécier",
    explanation: "'Curto muito isso' = 'Je kiffe trop ça'. 'Curtir a vida' = 'profiter de la vie'. Aussi : 'curtir com alguém' = 'conclure avec quelqu'un' (sens romantique). Le contexte distingue les deux sens. Verbe absent des manuels mais omniprésent dans la vraie vie.",
    cefrMin: "A2",
    tags: ["slang", "daily-life"],
  },
  {
    id: "fr_na_boa",
    type: "expression",
    contentPt: "Na boa",
    contentL1: "Tranquille / pas de souci / cool",
    explanation: "'Na boa' est le 'tranquille' portugais. 'Posso chegar mais tarde?' — 'Na boa.' Très courant, décontracté. Aussi adjectif : 'Ele é na boa' = 'Il est tranquille / relax'. Même énergie que 'no worries' ou 'pas de souci'.",
    cefrMin: "A2",
    tags: ["slang", "daily-life"],
  },
  {
    id: "fr_mano",
    type: "expression",
    contentPt: "Mano / Mana",
    contentL1: "Frérot / soeurette",
    explanation: "De 'irmão/irmã'. Utilisé exactement comme 'frérot' en français. 'Eh mano, tudo bem?' = 'Eh frérot, ça va ?'. 'Mana' est la version féminine. Moins courant que 'pá' mais plus affectueux. Marque une relation de proximité.",
    cefrMin: "A2",
    tags: ["slang", "daily-life"],
  },
  {
    id: "fr_ta_se_bem",
    type: "expression",
    contentPt: "Tá-se bem",
    contentL1: "Ça va / c'est bon / tranquille",
    explanation: "Contraction de 'está-se bem'. Façon décontractée de dire que tout va bien. 'Comment ça va ?' — 'Tá-se bem'. 'Tá-se' seul = 'OK, ça marche'. Très oral, jamais écrit. L'équivalent du 'ça va' français qui répond à tout.",
    cefrMin: "A2",
    tags: ["slang", "conversation"],
  },
  {
    id: "fr_o_pa",
    type: "expression",
    contentPt: "Ó pá!",
    contentL1: "Mec ! / Eh oh ! / Hé !",
    explanation: "L'interjection portugaise par excellence. Pour interpeller ('Ó pá, viens !'), exprimer la surprise ('Ó pá, j'y crois pas !'), ou commencer n'importe quelle phrase entre amis. Vient de 'rapaz' (garçon) raccourci en 'pá'. Équivalent de 'mec' ou 'meuf' en français.",
    cefrMin: "A2",
    tags: ["slang", "daily-life"],
  },
  {
    id: "fr_mandar_vir",
    type: "expression",
    contentPt: "Mandar vir",
    contentL1: "Râler / commander (selon le contexte)",
    explanation: "Double sens piège. 'Ele está sempre a mandar vir' = 'Il est toujours à râler'. MAIS au restaurant, 'Manda vir umas sardinhas' = 'Commande des sardines'. C'est le contexte qui décide. Aussi : 'mandar bocas' = lancer des piques / faire des remarques.",
    cefrMin: "B1",
    tags: ["slang", "daily-life"],
  },
  {
    id: "fr_chavalos",
    type: "expression",
    contentPt: "Chavalos / Putos",
    contentL1: "Les gamins / les gosses",
    explanation: "'Os chavalos' et 'os putos' = 'les gamins'. Attention : 'puto/a' n'est PAS grossier au Portugal (contrairement à l'espagnol). Une mère qui dit 'os meus putos' parle simplement de ses enfants. 'O puto é esperto' = 'Le gamin est malin'. Faux ami explosif pour les hispanophones, mais pas pour les francophones.",
    cefrMin: "B1",
    tags: ["slang", "false-friends"],
  },
  // --- PROVERBES ANCIENS ---
  {
    id: "fr_quem_nao_tem_cao",
    type: "expression",
    contentPt: "Quem não tem cão, caça com gato",
    contentL1: "Faute de grives, on mange des merles",
    explanation: "Littéralement : 'Qui n'a pas de chien chasse avec un chat'. Proverbe ancestral qui résume l'esprit du 'desenrascanço' — on fait avec ce qu'on a. L'équivalent français 'Faute de grives, on mange des merles' est parfait, mais le proverbe portugais a une image plus vivante. Utilisé quotidiennement.",
    cefrMin: "B1",
    tags: ["proverb", "culture"],
  },
  {
    id: "fr_agua_mole",
    type: "expression",
    contentPt: "Água mole em pedra dura, tanto bate até que fura",
    contentL1: "Petit à petit, l'oiseau fait son nid",
    explanation: "Littéralement : 'L'eau douce sur pierre dure, à tant frapper elle la perce'. Proverbe sur la persévérance, comme le français 'Petit à petit, l'oiseau fait son nid'. D'origine latine ('gutta cavat lapidem'). Très utilisé pour encourager quelqu'un qui se décourage.",
    cefrMin: "B1",
    tags: ["proverb", "culture"],
  },
  {
    id: "fr_fazer_tripas_coracao",
    type: "expression",
    contentPt: "Fazer das tripas coração",
    contentL1: "Se faire violence / se surpasser",
    explanation: "Littéralement : 'Faire du coeur avec les tripes'. Trouver du courage malgré la peur ou l'épuisement. Porto est la 'cidade das tripas' — la légende dit que les habitants donnèrent toute la bonne viande aux explorateurs et firent de leur mieux avec les restes. Image brutale, profondément portugaise.",
    cefrMin: "B1",
    tags: ["proverb", "culture", "porto"],
  },
  {
    id: "fr_ficar_ver_navios",
    type: "expression",
    contentPt: "Ficar a ver navios",
    contentL1: "Rester le bec dans l'eau / poser un lapin",
    explanation: "Littéralement : 'Rester à regarder les navires'. Des Découvertes — les familles scrutaient l'horizon pour des bateaux qui ne revenaient jamais. Maintenant : être planté là, se faire poser un lapin, rester les mains vides. 'Ils m'ont invité mais je suis resté à voir les navires'. L'image maritime porte 500 ans de mélancolie.",
    cefrMin: "B2",
    tags: ["proverb", "history", "emotion"],
  },
  {
    id: "fr_grao_a_grao",
    type: "expression",
    contentPt: "Grão a grão, enche a galinha o papo",
    contentL1: "Les petits ruisseaux font les grandes rivières",
    explanation: "Littéralement : 'Grain à grain, la poule remplit son jabot'. Les petits efforts s'accumulent. Utilisé pour l'épargne, l'apprentissage, tout processus long. L'imagerie rurale reflète le Portugal agricole. Proches du français 'Les petits ruisseaux font les grandes rivières'.",
    cefrMin: "B1",
    tags: ["proverb", "culture"],
  },
  {
    id: "fr_engolir_sapos",
    type: "expression",
    contentPt: "Engolir sapos",
    contentL1: "Avaler des couleuvres",
    explanation: "Littéralement : 'Avaler des crapauds'. Endurer des insultes ou humiliations sans répondre. Le français a la même image : 'avaler des couleuvres' (avaler des serpents). La version portugaise utilise des crapauds — tout aussi viscéral. 'J'ai dû avaler beaucoup de crapauds à ce boulot'.",
    cefrMin: "B1",
    tags: ["proverb", "emotion"],
  },
  {
    id: "fr_de_pequenino",
    type: "expression",
    contentPt: "De pequenino se torce o pepino",
    contentL1: "C'est en forgeant qu'on devient forgeron (mais pour l'éducation)",
    explanation: "Littéralement : 'C'est petit qu'on tord le concombre'. On façonne les enfants quand ils sont jeunes — après c'est trop tard. Utilisé par les grands-parents pour justifier une éducation stricte. Plus direct que le français 'Il faut battre le fer tant qu'il est chaud', car il parle spécifiquement de l'enfance.",
    cefrMin: "B1",
    tags: ["proverb", "education"],
  },
  {
    id: "fr_quem_vai_ao_mar",
    type: "expression",
    contentPt: "Quem vai ao mar, perde o lugar",
    contentL1: "Qui va à la chasse perd sa place",
    explanation: "Littéralement : 'Qui va à la mer perd sa place'. Proverbe identique au français 'Qui va à la chasse perd sa place' — mais la version portugaise utilise 'a mer' au lieu de 'la chasse'. L'imagerie maritime, encore et toujours. Si tu pars, quelqu'un d'autre prend ta place.",
    cefrMin: "A2",
    tags: ["proverb", "daily-life"],
  },
  // --- EXPRESSIONS QUOTIDIENNES ---
  {
    id: "fr_nao_faz_mal",
    type: "expression",
    contentPt: "Não faz mal",
    contentL1: "C'est pas grave / y'a pas de mal",
    explanation: "Littéralement : 'Ça ne fait pas de mal'. La réponse standard quand quelqu'un s'excuse. 'Pardon, je suis en retard' — 'Não faz mal'. Plus chaleureux que 'pas de problème', comme 'y'a pas de mal' en français. Entendu des dizaines de fois par jour au Portugal.",
    cefrMin: "A1",
    tags: ["daily-life", "conversation"],
  },
  {
    id: "fr_deixa_la",
    type: "expression",
    contentPt: "Deixa lá",
    contentL1: "Laisse tomber / t'inquiète",
    explanation: "Littéralement : 'Laisse ça là'. Pour rassurer ('Deixa lá, não faz mal' = 'T'inquiète, c'est rien') ou pour esquiver un sujet ('Deixa lá, não interessa' = 'Laisse tomber, c'est pas important'). Le ton décide tout. Indispensable dans la conversation courante.",
    cefrMin: "A1",
    tags: ["daily-life", "conversation"],
  },
  {
    id: "fr_e_o_que_e",
    type: "expression",
    contentPt: "É o que é",
    contentL1: "C'est comme ça / c'est la vie",
    explanation: "Un haussement d'épaules philosophique. 'Le trafic à Lisbonne est horrible.' — 'É o que é.' Acceptation résignée de ce qu'on ne peut pas changer. Lié au concept de 'fado' (destin). Le français 'c'est la vie' capture l'idée, mais la version portugaise est encore plus fataliste.",
    cefrMin: "A2",
    tags: ["daily-life", "conversation", "culture"],
  },
  {
    id: "fr_entao",
    type: "expression",
    contentPt: "Então?",
    contentL1: "Alors ? / Et alors ? / Bon alors ?",
    explanation: "'Então?' est un salut complet au Portugal. Deux amis qui se croisent : 'Então, tudo bem?' = 'Alors, ça va ?'. Pour relancer : 'Então? Tu t'es décidé ?' Pour la surprise : 'Então?! Qu'est-ce qui s'est passé ?'. L'intonation change tout — exactement comme 'alors' en français.",
    cefrMin: "A1",
    tags: ["daily-life", "conversation"],
  },
  {
    id: "fr_se_calhar",
    type: "expression",
    contentPt: "Se calhar",
    contentL1: "Peut-être / il se peut que",
    explanation: "'Se calhar' est le 'peut-être' du quotidien en PT-EU. Plus naturel que 'talvez' à l'oral. 'Se calhar vou amanhã' = 'J'irai peut-être demain'. Littéralement 'si ça se trouve'. Utiliser 'se calhar' au lieu de 'talvez' dans la conversation courante est un marqueur de fluidité.",
    cefrMin: "A2",
    tags: ["daily-life", "conversation"],
  },
  {
    id: "fr_ora_essa",
    type: "expression",
    contentPt: "Ora essa!",
    contentL1: "Mais bien sûr ! / Je vous en prie ! / Voyons !",
    explanation: "Un 'mais bien sûr !' emphatique ou un 'je vous en prie !' chaleureux. 'Merci pour l'aide !' — 'Ora essa !' (De rien !). Peut aussi exprimer une indignation légère. Vieux jeu mais toujours très vivant. La générosité portugaise en deux mots.",
    cefrMin: "A2",
    tags: ["daily-life", "etiquette"],
  },
  {
    id: "fr_olha_la",
    type: "expression",
    contentPt: "Olha lá...",
    contentL1: "Dis donc... / Écoute... / Hé",
    explanation: "Littéralement 'regarde là-bas' mais fonctionne comme 'dis donc' ou 'écoute' pour capter l'attention. 'Olha lá, je peux te poser une question ?' Peut être confrontational : 'Olha lá, pour qui tu te prends ?' Le ton fait tout — comme 'dis donc' en français.",
    cefrMin: "A2",
    tags: ["daily-life", "conversation"],
  },
];
