import type { CulturalRef } from "../types.js";

export const frCulturalRefs: readonly CulturalRef[] = [
  {
    id: "fr_desenrascar",
    type: "expression",
    contentPt: "Desenrascar-se",
    contentL1: "Se débrouiller / se démerder",
    explanation: "Proche de 'se débrouiller' mais élevé au rang de philosophie nationale. Implique une improvisation créative sous pression, pas juste se débrouiller.",
    cefrMin: "A2",
    tags: ["culture", "daily-life"],
  },
  {
    id: "fr_saudade",
    type: "expression",
    contentPt: "Saudade",
    contentL1: "Nostalgie profonde (intraduisible)",
    explanation: "Plus profond que 'nostalgie'. Un manque doux-amer pour quelqu'un, quelque chose ou un moment. Comme 'le mal du pays' mais pas limité au lieu. Central dans l'identité portugaise.",
    cefrMin: "B1",
    tags: ["culture", "emotion"],
  },
  {
    id: "fr_bica",
    type: "reference",
    contentPt: "Uma bica",
    contentL1: "Un expresso (à Lisbonne)",
    explanation: "A Lisbonne, on ne dit pas 'um café', on dit 'uma bica'. A Porto, c'est 'um cimbalino'. Le même expresso, deux mots selon la ville.",
    cefrMin: "A1",
    tags: ["food", "daily-life", "lisbon"],
  },
  {
    id: "fr_galao",
    type: "reference",
    contentPt: "Um galão / uma meia de leite",
    contentL1: "Un café au lait (dans un grand verre / dans une tasse)",
    explanation: "Le galão se sert dans un grand verre, avec beaucoup de lait. La meia de leite, c'est moitié café, moitié lait, dans une tasse. Ni l'un ni l'autre n'est un 'café au lait' exactement.",
    cefrMin: "A1",
    tags: ["food", "daily-life"],
  },
  {
    id: "fr_pastel_nata",
    type: "reference",
    contentPt: "Pastel de nata",
    contentL1: "Tartelette aux oeufs (pâte feuilletée)",
    explanation: "Le dessert national. Pâte feuilletée croustillante, crème aux oeufs caramélisée. Inventé par les moines de Belém. On ne dit jamais 'pastéis de Belém' sauf pour ceux de la pâtisserie historique.",
    cefrMin: "A1",
    tags: ["food", "culture", "lisbon"],
  },
  {
    id: "fr_francesinha",
    type: "reference",
    contentPt: "Francesinha",
    contentL1: "La 'petite française' (sandwich de Porto)",
    explanation: "Le nom signifie littéralement 'petite française' ! Inspiré du croque-monsieur mais poussé à l'extrême : pain, viandes multiples, fromage fondu, sauce piquante à la bière. Spécialité de Porto.",
    cefrMin: "A2",
    tags: ["food", "culture", "porto"],
  },
  {
    id: "fr_bacalhau",
    type: "reference",
    contentPt: "Bacalhau",
    contentL1: "Morue séchée et salée",
    explanation: "Les Portugais disent avoir 365 recettes de morue, une pour chaque jour. Ce n'est pas du poisson frais : c'est de la morue salée séchée qu'on fait tremper. Le plat national non officiel.",
    cefrMin: "A2",
    tags: ["food", "culture"],
  },
  {
    id: "fr_fado",
    type: "reference",
    contentPt: "O fado",
    contentL1: "Le fado (musique traditionnelle)",
    explanation: "Comme la chanson française a Piaf et Brel, le fado a Amália Rodrigues et Mariza. Mais le fado est plus qu'un genre : c'est l'expression musicale de la saudade. Patrimoine UNESCO depuis 2011.",
    cefrMin: "B1",
    tags: ["culture", "music"],
  },
  {
    id: "fr_fixe",
    type: "expression",
    contentPt: "Fixe!",
    contentL1: "Cool ! / Génial !",
    explanation: "L'équivalent de 'cool' ou 'génial'. Très courant chez les jeunes. Ne pas confondre avec 'fixo' (fixe/permanent). Prononciation : /ˈfiʃ/.",
    cefrMin: "A1",
    tags: ["slang", "daily-life"],
  },
  {
    id: "fr_dois_beijos",
    type: "reference",
    contentPt: "Dar dois beijinhos",
    contentL1: "Faire la bise (deux bisous)",
    explanation: "Comme en France, les Portugais font deux bises pour se saluer. Mais attention : on commence par la joue droite au Portugal (souvent par la gauche en France). Entre hommes, c'est une poignée de main.",
    cefrMin: "A1",
    tags: ["culture", "social"],
  },
  {
    id: "fr_chavena",
    type: "reference",
    contentPt: "Uma chávena de chá",
    contentL1: "Une tasse de thé",
    explanation: "En PT-EU on dit 'chávena' pour tasse (pas 'xícara', qui est brésilien). Le mot vient du persan via les routes commerciales portugaises. L'heure du thé existe aussi au Portugal.",
    cefrMin: "A2",
    tags: ["daily-life", "vocabulary"],
  },
  {
    id: "fr_autocarro",
    type: "reference",
    contentPt: "Autocarro / comboio / eléctrico",
    contentL1: "Bus / train / tramway",
    explanation: "Les transports en PT-EU ont des mots différents du brésilien. Bus = autocarro (pas 'ônibus'), train = comboio (pas 'trem'), tramway = eléctrico. A Lisbonne, le fameux eléctrico 28.",
    cefrMin: "A1",
    tags: ["daily-life", "vocabulary", "lisbon"],
  },
  {
    id: "fr_nas_tintas",
    type: "expression",
    contentPt: "Estar-se nas tintas",
    contentL1: "S'en foutre / s'en ficher",
    explanation: "Littéralement 'être dans les peintures'. Signifie qu'on s'en moque complètement. Très courant, légèrement grossier. Comme 's'en ficher' en un peu plus fort.",
    cefrMin: "B1",
    tags: ["slang", "emotion"],
  },
  {
    id: "fr_pois",
    type: "expression",
    contentPt: "Pois... / Pois, pois...",
    contentL1: "Bon... / Ouais... / Ben oui...",
    explanation: "Le mot de remplissage portugais par excellence. Équivalent de 'bon ben...' ou 'ouais...' en français. Peut exprimer l'accord, la résignation, ou juste remplir le silence.",
    cefrMin: "A2",
    tags: ["daily-life", "conversation"],
  },
  {
    id: "fr_tu_voce",
    type: "reference",
    contentPt: "Tu / Você / O Senhor, A Senhora",
    contentL1: "Tu / Vous (mais avec trois niveaux)",
    explanation: "Le français a tu/vous. Le PT-EU a trois niveaux : tu (famille, amis), você (courant mais peut être impoli dans le nord), o senhor/a senhora (formel). Au nord du Portugal, 'você' est presque insultant — on utilise le prénom + 3e personne.",
    cefrMin: "A2",
    tags: ["culture", "grammar", "social"],
  },
  {
    id: "fr_tasca",
    type: "reference",
    contentPt: "Uma tasca / um restaurante típico",
    contentL1: "Un bistrot / une taverne",
    explanation: "L'équivalent du bistrot français. Petits restaurants familiaux avec des plats du jour copieux et bon marché. Le menu est souvent affiché au mur. La vraie cuisine portugaise.",
    cefrMin: "A2",
    tags: ["food", "daily-life", "culture"],
  },
  {
    id: "fr_lusofonia",
    type: "reference",
    contentPt: "A lusofonia",
    contentL1: "La lusophonie (comme la francophonie)",
    explanation: "Le portugais est la 6e langue la plus parlée au monde. Comme la francophonie, la lusophonie relie Portugal, Brésil, Angola, Mozambique, Cap-Vert, Guinée-Bissau, Timor-Leste, Sao Tomé. Mais PT-EU est distinct du brésilien.",
    cefrMin: "B1",
    tags: ["culture", "language"],
  },
  {
    id: "fr_football",
    type: "reference",
    contentPt: "O futebol: Benfica, Sporting, Porto",
    contentL1: "Le football : les trois grands clubs",
    explanation: "Le football est la passion nationale, comme en France. Mais il n'y a que trois grands clubs : Benfica et Sporting (Lisbonne), et FC Porto. Demander 'és de que clube?' c'est demander une allégeance à vie.",
    cefrMin: "A2",
    tags: ["culture", "sports"],
  },
  {
    id: "fr_obrigado",
    type: "expression",
    contentPt: "Obrigado / Obrigada",
    contentL1: "Merci (mais genré)",
    explanation: "En français, 'merci' ne change pas. En PT-EU, un homme dit 'obrigado', une femme dit 'obrigada'. Littéralement 'obligé(e)'. Ne vous trompez pas de genre !",
    cefrMin: "A1",
    tags: ["daily-life", "grammar"],
  },
  {
    id: "fr_se_faz_favor",
    type: "expression",
    contentPt: "Se faz favor / Faz favor",
    contentL1: "S'il vous plaît",
    explanation: "En PT-EU on dit 'se faz favor' (et pas 'por favor' qui est plus courant au Brésil, bien qu'accepté). Au restaurant, on appelle le serveur avec 'faz favor!' et pas en claquant des doigts.",
    cefrMin: "A1",
    tags: ["daily-life", "social"],
  },
  {
    id: "fr_25_abril",
    type: "reference",
    contentPt: "25 de Abril — Revolução dos Cravos",
    contentL1: "25 avril — la Révolution des OEillets (1974)",
    explanation: "Le moment fondateur du Portugal moderne. Le 25 avril 1974, un coup d'État militaire pacifique a renversé la dictature de Salazar/Caetano. Les soldats ont mis des oeillets rouges dans leurs fusils. Comme Mai 68 en France, mais avec un vrai changement de régime. Le pont principal de Lisbonne porte ce nom.",
    cefrMin: "B1",
    tags: ["history", "culture", "identity"],
  },
  {
    id: "fr_pronto",
    type: "expression",
    contentPt: "Pronto!",
    contentL1: "Voilà ! / Bon ! / C'est fait !",
    explanation: "Un des mots les plus entendus au Portugal. Sert à signaler qu'on a fini ('Pronto, acabei!'), à avancer une conversation ('Pronto, vamos lá'), ou à remplir un silence. L'équivalent de 'voilà' ou 'bon ben' en français.",
    cefrMin: "A1",
    tags: ["daily-life", "conversation"],
  },
  {
    id: "fr_tuga",
    type: "expression",
    contentPt: "Tuga",
    contentL1: "Portugais(e) (familier / affectueux)",
    explanation: "L'argot affectueux pour dire 'portugais'. Les Portugais l'utilisent eux-mêmes, ce n'est pas péjoratif. 'Coisas de tuga' = 'trucs de Portugais'. Le mot savant est 'lusitano' (de Lusitania, la province romaine).",
    cefrMin: "B1",
    tags: ["slang", "identity"],
  },
  {
    id: "fr_repas",
    type: "reference",
    contentPt: "Pequeno-almoço, almoço, lanche, jantar",
    contentL1: "Petit-déjeuner, déjeuner, goûter, dîner",
    explanation: "Les horaires de repas diffèrent de la France. Pequeno-almoço (petit-dej) : léger, café + pastéis. Almoço (déjeuner, 12h30-14h) : le repas principal, copieux. Lanche (goûter, ~16h) : café et gâteau. Jantar (dîner, 20h-21h) : peut être aussi copieux que le déjeuner. Dîner avant 19h30 est très tôt.",
    cefrMin: "A1",
    tags: ["food", "daily-life", "culture"],
  },
  {
    id: "fr_lisboa_porto",
    type: "reference",
    contentPt: "Lisboa vs Porto",
    contentL1: "Lisbonne vs Porto (la rivalité culturelle)",
    explanation: "Comme Paris-Marseille mais plus intense. Lisbonne (lisboetas) est la capitale cosmopolite. Porto (portuenses/tripeiros) est fièrement ouvrière et indépendante. Les habitants de Porto s'appellent 'tripeiros' (mangeurs de tripes) — un honneur historique. Nourriture, accent, football (Benfica vs FC Porto) : tout diffère.",
    cefrMin: "B1",
    tags: ["culture", "lisbon", "porto", "identity"],
  },
  {
    id: "fr_santos_populares",
    type: "reference",
    contentPt: "Santos Populares — Festas de Junho",
    contentL1: "Les fêtes populaires de Juin",
    explanation: "Tout le mois de juin, le Portugal fête les saints populaires : Santo António (Lisbonne, 13 juin), São João (Porto, 24 juin), São Pedro (29 juin). Sardines grillées, caldo verde, vin, danses dans la rue, marteaux en plastique (São João). C'est la plus grande fête de l'année, plus importante que le Nouvel An pour beaucoup.",
    cefrMin: "A2",
    tags: ["culture", "traditions", "lisbon", "porto"],
  },
];
