import type { L1Profile } from "../types.js";

export const frProfile: L1Profile = {
  code: "fr",
  name: "French",
  nativeName: "Français",
  writingDirection: "ltr",
  hasLatinScript: true,
  transfer: {
    cognates: [
      "important", "différent", "moment", "problème", "forme",
      "culture", "nature", "structure", "situation", "possible",
      "information", "communication", "tradition", "religion", "nation",
      "gouvernement", "document", "président", "université", "animal",
      "hôpital", "général", "social", "capital", "principal",
      "normal", "idéal", "nécessaire", "populaire", "origine",
    ],
    falseFriends: [
      { word: "souper", l1Meaning: "to have supper / dinner", ptMeaning: "sopa means 'soup' (not a meal, a dish)" },
      { word: "bureau", l1Meaning: "office / desk", ptMeaning: "burro means 'donkey' — the office is 'escritório'" },
      { word: "rester", l1Meaning: "to stay / remain", ptMeaning: "restar means 'to remain (quantity)' — to stay is 'ficar'" },
      { word: "librairie", l1Meaning: "bookshop", ptMeaning: "livraria means 'bookshop' too, but 'biblioteca' is the library" },
      { word: "journal", l1Meaning: "newspaper / diary", ptMeaning: "jornal means 'newspaper' only — a diary is 'diário'" },
      { word: "patron", l1Meaning: "boss / pattern", ptMeaning: "patrão means 'boss' — but 'patron' doesn't mean 'pattern' in PT" },
      { word: "coin", l1Meaning: "corner / wedge", ptMeaning: "cão means 'dog' — the corner is 'canto' or 'esquina'" },
      { word: "boucher", l1Meaning: "butcher", ptMeaning: "bochecha means 'cheek' — the butcher is 'talhante' or 'carniceiro'" },
      { word: "figure", l1Meaning: "face / figure", ptMeaning: "figura means 'figure/appearance' but 'fazer figura' means 'to make an impression'" },
      { word: "encore", l1Meaning: "again / still", ptMeaning: "the PT-EU word is 'ainda' — 'encore' doesn't exist in Portuguese" },
      { word: "chat", l1Meaning: "cat", ptMeaning: "no PT cognate — cat is 'gato'. 'Chat' in PT means online chat (anglicism)" },
      { word: "tasse", l1Meaning: "cup", ptMeaning: "taça means 'trophy' or 'wine glass' — a cup is 'chávena' (PT-EU)" },
      { word: "sale", l1Meaning: "dirty", ptMeaning: "sala means 'room/living room' — dirty is 'sujo'" },
      { word: "gare", l1Meaning: "train station", ptMeaning: "gare exists but is rarer — 'estação' is standard in PT-EU" },
      { word: "serviette", l1Meaning: "towel / napkin", ptMeaning: "servir means 'to serve' — a napkin is 'guardanapo', a towel is 'toalha'" },
      { word: "chance", l1Meaning: "luck", ptMeaning: "in PT, 'chance' means 'opportunity' more than luck — luck is 'sorte'" },
      { word: "ennuyer", l1Meaning: "to bore / annoy", ptMeaning: "enojar (archaic) means 'to disgust' — to bore is 'aborrecer'" },
      { word: "pousser", l1Meaning: "to push / to grow", ptMeaning: "pousar means 'to land/rest' — to push is 'empurrar'" },
      { word: "assister", l1Meaning: "to attend / witness", ptMeaning: "assistir means 'to watch' (TV, a game) — to assist is 'ajudar'" },
      { word: "attendre", l1Meaning: "to wait", ptMeaning: "atender means 'to answer (phone)' or 'to serve (customer)' — to wait is 'esperar'" },
      { word: "enveloppe", l1Meaning: "envelope", ptMeaning: "envelope is the same, but 'envolver' means 'to involve/wrap', not 'to envelop'" },
      { word: "résumer", l1Meaning: "to summarize", ptMeaning: "resumir means 'to summarize' too — but 'résumé' in PT is 'resumo', not a CV" },
      { word: "phrase", l1Meaning: "sentence", ptMeaning: "frase means 'sentence' — this is a true cognate, rare case of alignment" },
      { word: "balcon", l1Meaning: "balcony", ptMeaning: "balcão means 'counter/bar' — a balcony is 'varanda'" },
      { word: "blesser", l1Meaning: "to injure/wound", ptMeaning: "no PT cognate — to injure is 'ferir' or 'magoar'" },
      { word: "depuis", l1Meaning: "since / from (time)", ptMeaning: "depois means 'after / afterwards' — since is 'desde'" },
      { word: "carte", l1Meaning: "map / menu / card", ptMeaning: "carta means 'letter' — a map is 'mapa', a menu is 'ementa', a card is 'cartão'" },
      { word: "chambre", l1Meaning: "bedroom", ptMeaning: "câmara means 'municipal council' or 'camera' — a bedroom is 'quarto'" },
      { word: "enfant", l1Meaning: "child", ptMeaning: "infante means 'prince / princess' (royal title) — a child is 'criança'" },
      { word: "constipé", l1Meaning: "constipated", ptMeaning: "constipado means 'having a cold' — constipated is 'com obstipação'" },
      { word: "nouvelle", l1Meaning: "news / novella", ptMeaning: "novela means 'soap opera / TV series' — news is 'notícia', short story is 'conto'" },
      { word: "défendre", l1Meaning: "to forbid", ptMeaning: "defender means 'to defend / protect' — to forbid is 'proibir'" },
      { word: "louer", l1Meaning: "to rent / to hire", ptMeaning: "louvar means 'to praise / to worship' — to rent is 'alugar'" },
      { word: "tromper", l1Meaning: "to deceive / to cheat on", ptMeaning: "tromba means 'trunk (elephant) / snout / sulky face' — to deceive is 'enganar'" },
      { word: "toilette", l1Meaning: "toilet / washroom", ptMeaning: "toalha means 'towel' — a toilet/washroom is 'casa de banho'" },
      { word: "procès", l1Meaning: "trial / lawsuit", ptMeaning: "processo means 'process' broadly — a trial/lawsuit is 'julgamento'" },
      { word: "entretien", l1Meaning: "maintenance / interview", ptMeaning: "entretenimento means 'entertainment' — maintenance is 'manutenção', interview is 'entrevista'" },
      { word: "couvert", l1Meaning: "place setting / cutlery", ptMeaning: "coberto means 'covered / indoor' — cutlery is 'talheres' (though 'couvert' is borrowed for cover charge)" },
      { word: "prétendre", l1Meaning: "to claim / to assert", ptMeaning: "pretender means 'to intend / to want' — to claim is 'afirmar' or 'alegar'" },
      { word: "pièce", l1Meaning: "room / play / coin", ptMeaning: "peça means 'piece / part / play' — but a room is 'quarto' or 'divisão', a coin is 'moeda'" },
    ],
    phoneticDifficulties: [
      { sound: "ão", ipa: "/ɐ̃w̃/", description: "Nasal diphthong", tip: "French has nasal vowels, but -ão adds a glide — it's not flat like -on. Start with mouth open, nasalize, then close to a /w/." },
      { sound: "lh", ipa: "/ʎ/", description: "Palatal lateral", tip: "Like the old French 'ill' in 'fille'. Tongue flat on the hard palate. Modern French lost this sound but you may recall it." },
      { sound: "nh", ipa: "/ɲ/", description: "Palatal nasal", tip: "Exactly like French 'gn' in 'champagne' or 'montagne'. This one transfers perfectly." },
      { sound: "r/rr", ipa: "/ʁ/", description: "Uvular R (initial and double)", tip: "Good news — the PT-EU initial R is very similar to the French R. The rolled /r/ between vowels (caro) is the harder one for you." },
      { sound: "r (intervocalic)", ipa: "/ɾ/", description: "Alveolar tap between vowels", tip: "Single 'r' between vowels is a quick tap, like a very fast 'd'. Not the French back-of-throat R. 'Caro' vs 'carro'." },
      { sound: "b vs v", ipa: "/b/ /v/", description: "Distinct b and v", tip: "French distinguishes these too, so this should transfer. Keep /b/ bilabial and /v/ labiodental." },
      { sound: "s/z/ç", ipa: "/s/ /z/ /ʃ/ /ʒ/", description: "Sibilant system", tip: "PT-EU has 4 sibilants where French has 3. The 's' before a consonant or at word-end becomes /ʃ/ (like 'ch' in French)." },
      { sound: "open vs closed e", ipa: "/ɛ/ vs /e/", description: "Vowel height distinction", tip: "French has this too (fête vs fée). In PT-EU, 'é' is open /ɛ/, 'ê' is closed /e/. The accent marks help." },
      { sound: "open vs closed o", ipa: "/ɔ/ vs /o/", description: "Vowel height distinction", tip: "Like French 'or' vs 'eau'. PT-EU 'ó' is open /ɔ/, 'ô' is closed /o/. The accent marks are your guide." },
      { sound: "ã/õ/ẽ/ĩ/ũ", ipa: "/ɐ̃/ /õ/ /ẽ/ /ĩ/ /ũ/", description: "Full nasal vowel set", tip: "French has 3-4 nasal vowels. PT-EU has 5. Your instinct for nasalization transfers — just extend it to 'i' and 'u'." },
      { sound: "unstressed vowels", ipa: "/ɨ/ /ɐ/", description: "Vowel reduction in unstressed syllables", tip: "Like French schwa but more extreme. Unstressed 'e' nearly vanishes, unstressed 'o' becomes /u/. This makes PT-EU sound 'swallowed' to French ears." },
      { sound: "word-final consonants", ipa: "varied", description: "Final consonant behavior", tip: "PT-EU final 's' becomes /ʃ/, final 'l' becomes /ɫ/ (dark L). French drops finals — PT-EU transforms them." },
      { sound: "ch = /ʃ/", ipa: "/ʃ/", description: "CH is always 'sh'", tip: "Good news — PT-EU 'ch' is /ʃ/, exactly like French 'ch' in 'chat'. Chave = /ʃav/. This transfers perfectly." },
      { sound: "ge/gi = /ʒ/", ipa: "/ʒ/", description: "Soft G is 'zh'", tip: "Same as French: G before 'e' or 'i' = /ʒ/. 'Gelo' sounds like French 'je' + 'lo'. Perfect transfer." },
      { sound: "word stress", ipa: "variable", description: "Variable stress position", tip: "French is always final-stressed. PT-EU stress can fall on any of the last three syllables and changes meaning: 'sabia' (she knew) vs 'sabiá' (thrush bird). Accent marks help but aren't always present." },
    ],
    grammarGaps: [
      { concept: "Ser vs Estar", explanation: "Two verbs for 'être' — ser for essence/identity, estar for state/location", l1Comparison: "French has only 'être'. In PT-EU, 'ele é alto' (he's tall, always) vs 'ele está doente' (he's sick, now)." },
      { concept: "Personal infinitive", explanation: "The infinitive conjugated for person: 'para eu fazer', 'para eles fazerem'", l1Comparison: "Doesn't exist in French or any other Romance language. Unique to Portuguese. Replaces some subjunctive uses." },
      { concept: "Future subjunctive", explanation: "Used in 'when/if' clauses about the future: 'quando eu for'", l1Comparison: "French uses indicative or present subjunctive here. PT-EU has a dedicated future subjunctive tense." },
      { concept: "Pretérito perfeito vs imperfeito", explanation: "Simple past vs imperfect — 'fiz' vs 'fazia'", l1Comparison: "Maps roughly to passé composé vs imparfait, but PT-EU simple past is one word (fiz), not two (j'ai fait)." },
      { concept: "Compound tenses with ter", explanation: "PT-EU uses 'ter' (to have) as auxiliary, not 'haver'", l1Comparison: "French uses 'avoir' and 'être'. PT-EU only uses 'ter'. No auxiliary switching with movement verbs." },
      { concept: "Object pronoun placement", explanation: "Pronouns go after the verb (enclisis) by default, before in subordinate clauses (proclisis)", l1Comparison: "French always puts them before. PT-EU default is after: 'dou-te' (I give you). In negation/subordination, they move before." },
      { concept: "Mesoclisis", explanation: "Pronoun inserted inside the future/conditional verb: 'dar-te-ei' (I will give you)", l1Comparison: "No French equivalent at all. The pronoun splits the verb. Formal/literary but tested at B2+." },
      { concept: "Por vs para", explanation: "Two prepositions where French uses 'pour' or 'par'", l1Comparison: "French 'pour' = para (purpose/destination). French 'par' = por (cause/agent). But many exceptions exist." },
      { concept: "Definite article with possessives", explanation: "'O meu livro' — article + possessive + noun", l1Comparison: "French drops the article: 'mon livre'. PT-EU keeps both: 'o meu livro'. Omitting it sounds Brazilian." },
      { concept: "Contractions", explanation: "Prepositions fuse with articles: de + o = do, em + a = na, a + o = ao", l1Comparison: "French has du/au/des. PT-EU has more: do/da/no/na/ao/pelo. They're mandatory, never optional." },
      { concept: "Tu vs você vs o senhor", explanation: "Three formality levels for 'you'", l1Comparison: "French has tu/vous. PT-EU has tu (informal), você (middle), o senhor/a senhora (formal). Você takes 3rd-person verbs." },
      { concept: "Subjunctive triggers", explanation: "Subjunctive required after doubt, desire, emotion, and certain conjunctions", l1Comparison: "French subjonctif exists but is used less. PT-EU uses it more, including after 'talvez', 'embora', 'antes que'." },
      { concept: "Reflexive verbs", explanation: "Many common verbs require a reflexive pronoun (se)", l1Comparison: "French has reflexive verbs too (se lever, s'asseoir), but PT-EU uses them even more: levantar-se, sentar-se, chamar-se (to be called), lembrar-se (to remember), ir-se embora (to leave)." },
      { concept: "Continuous with 'estar a + infinitive'", explanation: "Ongoing actions use 'estar a + infinitive', not gerund", l1Comparison: "French uses 'être en train de + infinitive'. PT-EU uses 'estar a + infinitive': 'Estou a comer' (I am eating). The gerund form ('estou comendo') is Brazilian, not European." },
      { concept: "Diminutives -inho/-inha", explanation: "Extremely productive diminutive suffix used constantly in daily speech", l1Comparison: "French diminutives are rare and lexicalized (maisonnette, fillette). PT-EU adds -inho/-inha to almost anything: cafezinho, pouquinho, devagarzinho, obrigadinho. It expresses affection, softening, or smallness." },
    ],
    skipBasics: false,
    startingCEFR: "A1",
  },
};
