import type { CulturalRef } from "../types.js";

export const trCulturalRefs: readonly CulturalRef[] = [
  {
    id: "tr_saudade",
    type: "expression",
    contentPt: "Saudade",
    contentL1: "Hüzun / Özlem",
    explanation: "Turkish 'hüzun' (melancholy, as Orhan Pamuk describes Istanbul) and 'özlem' (longing) together approximate saudade. Both cultures value melancholy as an emotion worth expressing, not hiding.",
    cefrMin: "B1",
    tags: ["culture", "emotion"],
  },
  {
    id: "tr_cha_cay",
    type: "reference",
    contentPt: "Chá vs Café",
    contentL1: "Çay vs Kahve",
    explanation: "Turkey's tea culture (çay) and Portugal's coffee culture (café) are both central to social life. Both cultures have a dedicated ritual: Turks drink çay in tulip glasses, Portuguese stand at the balcão for a quick bica. The social function is identical.",
    cefrMin: "A1",
    tags: ["food", "daily-life"],
  },
  {
    id: "tr_fixe",
    type: "expression",
    contentPt: "Fixe!",
    contentL1: "Harika! / Süper!",
    explanation: "'Fixe' means 'cool'. Use it like harika or süper. 'Que fixe!' = Ne kadar harika!",
    cefrMin: "A1",
    tags: ["slang", "daily-life"],
  },
  {
    id: "tr_pois",
    type: "expression",
    contentPt: "Pois...",
    contentL1: "Şey... / Yani... / Haa...",
    explanation: "'Pois' is the most versatile Portuguese filler. Like Turkish 'yani' or 'şey', it fills pauses and expresses agreement or hesitation.",
    cefrMin: "A1",
    tags: ["conversation", "daily-life"],
  },
  {
    id: "tr_pasteis",
    type: "reference",
    contentPt: "Pastéis de nata",
    contentL1: "Sütü tatlı (su böreği gibi, ama tatlı)",
    explanation: "Flaky custard tarts. Turkish speakers can think of the flaky layers like börek but filled with sweet custard instead. Found everywhere in Portugal for about one euro.",
    cefrMin: "A1",
    tags: ["food", "culture"],
  },
  {
    id: "tr_fado",
    type: "reference",
    contentPt: "Fado",
    contentL1: "Türk halk müziği gibi (arabesk benzeri)",
    explanation: "Fado's emotional depth parallels Turkish arabesk or halk müziği. Both value raw emotional expression, fate, and heartbreak. Amália Rodrigues is fado's greatest voice.",
    cefrMin: "B1",
    tags: ["music", "culture"],
  },
  {
    id: "tr_hospitality",
    type: "reference",
    contentPt: "Hospitalidade portuguesa",
    contentL1: "Misafirperverlik (misafir hakkı gibi)",
    explanation: "Portuguese hospitality rivals Turkish misafirperverlik. Both cultures insist on feeding guests generously and making them feel at home. 'Fique à vontade' (make yourself at home) is the Portuguese version of 'Buyurun, evinizde gibi hissedin'.",
    cefrMin: "A2",
    tags: ["culture", "hospitality"],
  },
  {
    id: "tr_bacalhau",
    type: "reference",
    contentPt: "Bacalhau",
    contentL1: "Tuzlu balık (365 tarif)",
    explanation: "Salt cod is Portugal's national dish. Turkish cuisine also uses preserved fish (lakerda, çiroz). The salt-curing tradition is shared across Mediterranean cultures.",
    cefrMin: "A2",
    tags: ["food", "culture"],
  },
  {
    id: "tr_25_abril",
    type: "reference",
    contentPt: "25 de Abril — Revolução dos Cravos",
    contentL1: "Karanfil Devrimi (1974)",
    explanation: "On April 25, 1974, Portugal peacefully overthrew its dictatorship with carnations in rifle barrels. This defines modern Portugal the way Atatürk's republic defines modern Turkey.",
    cefrMin: "B1",
    tags: ["history", "identity"],
  },
  {
    id: "tr_pronto",
    type: "expression",
    contentPt: "Pronto!",
    contentL1: "Tamam! / Hazır!",
    explanation: "'Pronto' = done/ready/OK then. Like tamam or hazır. 'Pronto, vamos!' = Tamam, gidelim!",
    cefrMin: "A1",
    tags: ["daily-life", "conversation"],
  },
  {
    id: "tr_azulejo",
    type: "reference",
    contentPt: "Azulejos",
    contentL1: "Çini (Türk çini geleneği gibi)",
    explanation: "Portuguese blue and white tiles share roots with Ottoman çini tiles. Both traditions were influenced by Islamic art. The Arabic word 'al-zulayj' gave both azulejo and züleyha/çini their origin.",
    cefrMin: "A2",
    tags: ["art", "culture", "history"],
  },
  {
    id: "tr_santos",
    type: "reference",
    contentPt: "Festas dos Santos Populares",
    contentL1: "Halk festivalleri (bayram gibi)",
    explanation: "June street festivals with sardines, music, and dancing. The communal celebration spirit resembles Turkish bayram celebrations where everyone eats and socializes together.",
    cefrMin: "A2",
    tags: ["culture", "festivals"],
  },
  {
    id: "tr_family",
    type: "reference",
    contentPt: "Família é tudo",
    contentL1: "Aile her şeydir",
    explanation: "Like Turkish culture, Portuguese culture is deeply family-oriented. Sunday lunches are sacred. Elders are respected. The family structure will feel very familiar.",
    cefrMin: "A2",
    tags: ["culture", "family"],
  },
  {
    id: "tr_desenrascar",
    type: "expression",
    contentPt: "Desenrascar-se",
    contentL1: "İşin içinden çıkmak / Çare bulmak",
    explanation: "The art of improvising solutions. Like Turkish 'işin içinden çıkmak'. Both cultures celebrate creative problem-solving.",
    cefrMin: "B1",
    tags: ["culture", "daily-life"],
  },
  {
    id: "tr_nas_tintas",
    type: "expression",
    contentPt: "Estar-se nas tintas",
    contentL1: "Umurumda değil / Bana ne",
    explanation: "Literally 'to be in the paints' — couldn't care less. Like 'umurumda değil'. Very common, mildly rude.",
    cefrMin: "B1",
    tags: ["slang", "emotion"],
  },
  {
    id: "tr_moorish_ottoman",
    type: "reference",
    contentPt: "Herança moura — paralelos otomanos",
    contentL1: "Mağribi miras — Osmanlı paralelleri",
    explanation: "Portugal was under Moorish rule for 500 years. Southern Portugal — the Algarve (from Arabic al-Gharb, 'the west') — preserves Islamic architecture, geometric tile patterns, and Arabic-origin words. Turkish speakers will recognise the horseshoe arches, the hammam-like thermal baths, and the shared Arabic vocabulary: 'aldeia' (köy), 'alfândega' (gümrük), 'azulejo' (çini). The Moorish castle in Sintra and the old town of Silves feel like walking through a Mediterranean Ottoman district.",
    cefrMin: "B1",
    tags: ["history", "architecture", "culture"],
  },
  {
    id: "tr_kahve_bica",
    type: "reference",
    contentPt: "Café à portuguesa",
    contentL1: "Türk kahvesi gibi kısa, güçlü, ayakta",
    explanation: "Portuguese coffee culture is surprisingly close to Turkish kahve culture: strong, served small, drunk fast, often standing. A 'bica' (Lisbon espresso) is downed in two sips at the counter — no lingering. 'Galão' (milky coffee in a glass) is the exception. Portugal shares Turkey's disdain for American-style weak coffee. And like Turkey, every neighbourhood has its local café where regulars gather daily.",
    cefrMin: "A1",
    tags: ["food", "daily-life", "culture"],
  },
  {
    id: "tr_churrasco_kebap",
    type: "reference",
    contentPt: "Churrasco, frango assado e sardinhas",
    contentL1: "Mangal, ızgara tavuk ve sardalya — kebap benzeri",
    explanation: "Portuguese grilled food culture mirrors Turkish mangal culture: charcoal-grilled chicken (frango assado) is everywhere and cheap, sardines (sardinhas) are grilled on the street during June festivals, and 'churrasqueiras' (grill restaurants) are the nation's fast food. The flavours differ — Portuguese use piri-piri instead of sumac and cumin — but the ritual of gathering around a grill is identical. 'Frango da Guia' in the Algarve is the Portuguese equivalent of Adana kebap: a regional speciality worth travelling for.",
    cefrMin: "A2",
    tags: ["food", "culture", "daily-life"],
  },
  // --- MODERN SLANG ---
  {
    id: "tr_bue",
    type: "expression",
    contentPt: "Bué",
    contentL1: "Aşırı / Çok fazla / Mega",
    explanation: "'Bué' means 'a lot' or 'very' — from Kimbundu (Angolan language). 'Bué fixe' (aşırı harika), 'bué caro' (aşırı pahalı), 'bué gente' (çok fazla insan). Used constantly by young Portuguese. Functions like Turkish 'aşırı' as a casual intensifier.",
    cefrMin: "A2",
    tags: ["slang", "daily-life"],
  },
  {
    id: "tr_cena",
    type: "expression",
    contentPt: "Cena",
    contentL1: "Şey / Olay / Mevzu",
    explanation: "Originally means 'scene' but in PT-EU slang it means 'thing/stuff/situation'. 'Que cena!' (Ne olay!), 'é uma cena estranha' (garip bir şey). Like Turkish 'şey' or 'mevzu' when you can't name the thing. 'Dá-me aquela cena' (şu şeyi ver).",
    cefrMin: "A2",
    tags: ["slang", "daily-life"],
  },
  {
    id: "tr_tipo",
    type: "expression",
    contentPt: "Tipo...",
    contentL1: "Hani... / Yani... / Şey...",
    explanation: "The Portuguese filler word, used exactly like Turkish 'hani' or 'yani'. 'Ele é tipo alto' (hani, uzun boylu). Young Portuguese pepper every sentence with 'tipo', just like Turkish youth overuse 'yani'. Not appropriate in formal speech.",
    cefrMin: "A2",
    tags: ["slang", "conversation"],
  },
  {
    id: "tr_ganda",
    type: "expression",
    contentPt: "Ganda / Granda",
    contentL1: "Efsane! / Müthiş!",
    explanation: "Contraction of 'grande' — used as an intensifier. 'Ganda filme!' (Efsane film!), 'Granda maluco!' (Müthiş deli!). Like Turkish 'efsane' or 'müthiş' in youth slang. Colloquial Lisbon slang, slightly vulgar — don't use with your müdür.",
    cefrMin: "B1",
    tags: ["slang"],
  },
  {
    id: "tr_bazar",
    type: "expression",
    contentPt: "Bazar",
    contentL1: "Gitmek / Kaçmak / Tüymek",
    explanation: "'Bazar' means 'to leave/bounce'. 'Vou bazar' (Ben gidiyorum / tüyüyorum). Informal, like Turkish 'tüymek' in casual speech. Nothing to do with the Turkish 'pazar' (market). The more formal version is 'ir-se embora'.",
    cefrMin: "B1",
    tags: ["slang", "daily-life"],
  },
  {
    id: "tr_curtir",
    type: "expression",
    contentPt: "Curtir",
    contentL1: "Keyif almak / Sevmek / Takılmak",
    explanation: "'Curtir' means to enjoy or to be into something. 'Curto bué música portuguesa' (Portekiz müziğini çok seviyorum). 'Vamos curtir a noite' (Gece takılalım). Also used for liking someone romantically. Like 'keyif almak' or 'takılmak'.",
    cefrMin: "A2",
    tags: ["slang", "daily-life"],
  },
  {
    id: "tr_na_boa",
    type: "expression",
    contentPt: "Na boa",
    contentL1: "Sorun yok / Rahat ol",
    explanation: "'Na boa' means 'no worries / it's all good'. 'Podes usar o meu carro, na boa' (Arabamı kullanabilirsin, sorun yok). Also used as a question: 'Tás na boa?' (İyi misin?). Like 'sorun yok' or 'rahat ol' — one of the most useful casual phrases.",
    cefrMin: "A1",
    tags: ["slang", "daily-life"],
  },
  {
    id: "tr_o_pa",
    type: "expression",
    contentPt: "Ó pá!",
    contentL1: "Lan! / Moruk! / Ulan!",
    explanation: "The quintessential Portuguese interjection. 'Ó pá, não acredito!' (Lan, inanamıyorum!). Used between friends, like 'lan' or 'moruk'. Short for 'rapaz' (boy). Can express surprise, frustration, or just be a casual address. Turkish speakers will find this very natural.",
    cefrMin: "A1",
    tags: ["slang", "daily-life"],
  },
  {
    id: "tr_mano",
    type: "expression",
    contentPt: "Mano / Mana",
    contentL1: "Kardeş / Abi / Abla",
    explanation: "Short for 'irmão/irmã' (brother/sister). Used as 'bro/sis' between close friends. 'Olha, mano, ouve lá...' (Bak kardeş, dinle...). Turkish speakers will find this very familiar — Turkish also uses 'abi', 'abla', 'kardeş' between friends.",
    cefrMin: "A2",
    tags: ["slang", "daily-life"],
  },
  {
    id: "tr_mandar_vir",
    type: "expression",
    contentPt: "Mandar vir",
    contentL1: "Söylenmek / Sipariş vermek (iki anlamı var!)",
    explanation: "Has two completely different meanings depending on context. 1) 'To complain/rant': 'Ele está sempre a mandar vir com tudo' (Her şeye söylenir durur). 2) 'To order': 'Manda vir mais uma cerveja' (Bir bira daha ısmarla). Context always makes it clear.",
    cefrMin: "B1",
    tags: ["slang", "daily-life"],
  },
  {
    id: "tr_ta_se_bem",
    type: "expression",
    contentPt: "Tá-se bem",
    contentL1: "Tamam! / Olur!",
    explanation: "Contraction of 'está-se bem' — 'it's all good'. Used to accept a proposal. 'Vamos ao cinema?' — 'Tá-se bem!' (Sinemaya gidelim mi? — Olur!). Very casual, very common. Like Turkish 'olur' or 'tamam'.",
    cefrMin: "A1",
    tags: ["slang", "daily-life"],
  },
  // --- ANCIENT PROVERBS / PROVÉRBIOS ---
  {
    id: "tr_agua_pedra",
    type: "expression",
    contentPt: "Água mole em pedra dura, tanto bate até que fura",
    contentL1: "Damlaya damlaya göl olur",
    explanation: "Literally: 'Soft water on hard stone, hits until it pierces.' Persistence wins. Turkish has 'Damlaya damlaya göl olur' (Drop by drop, a lake forms). Both celebrate patient persistence — sabır in Turkish, paciência in Portuguese.",
    cefrMin: "B1",
    tags: ["proverb", "wisdom"],
  },
  {
    id: "tr_cao_gato",
    type: "expression",
    contentPt: "Quem não tem cão, caça com gato",
    contentL1: "Tilkinin dönüp dolaşacağı yer kürkçü dükkânıdır",
    explanation: "Literally: 'Who doesn't have a dog, hunts with a cat.' Make do with what you have. The proverb form of 'desenrascar-se'. Turkish culture also values resourcefulness — 'çare bulmak' captures the same spirit of finding a way through.",
    cefrMin: "B1",
    tags: ["proverb", "culture"],
  },
  {
    id: "tr_grao_galinha",
    type: "expression",
    contentPt: "Grão a grão, enche a galinha o papo",
    contentL1: "Ağaca balta vurmuşlar, 'sapı bedenimden' demiş",
    explanation: "Literally: 'Grain by grain, the hen fills her crop.' Small things add up. Turkish has many proverbs about patience and persistence. 'Az az, uz uz' (little by little, far far). Both celebrate the value of consistent small effort over time.",
    cefrMin: "B1",
    tags: ["proverb", "wisdom"],
  },
  {
    id: "tr_pepino",
    type: "expression",
    contentPt: "De pequenino se torce o pepino",
    contentL1: "Ağaç yaşken eğilir",
    explanation: "Literally: 'You bend the cucumber when it's small.' Habits are formed young. Turkish has the near-identical 'Ağaç yaşken eğilir' (A tree bends while it's young). Both cultures believe early education shapes character permanently. Used by parents and teachers across both countries.",
    cefrMin: "B1",
    tags: ["proverb", "education"],
  },
  {
    id: "tr_tripas_coracao",
    type: "expression",
    contentPt: "Fazer das tripas coração",
    contentL1: "Dişini sıkmak / Cesaretini toplamak",
    explanation: "Literally: 'To make heart out of guts.' To summon courage when you have none. Like Turkish 'dişini sıkmak' (to grit your teeth). Origin may be linked to Porto, whose residents ate only tripe after sending good meat to the discovery fleets — hence Porto's nickname 'cidade dos tripeiros'.",
    cefrMin: "B1",
    tags: ["proverb", "history", "porto"],
  },
  {
    id: "tr_ver_navios",
    type: "expression",
    contentPt: "Ficar a ver navios",
    contentL1: "Elde avuçta bir şey kalmamak / Eli boş kalmak",
    explanation: "Literally: 'To be left watching ships.' To be left empty-handed or stood up. Origin: during the Age of Discoveries, women waited for ships that never returned. Like Turkish 'eli boş kalmak' (to be left with empty hands).",
    cefrMin: "B1",
    tags: ["proverb", "history", "discoveries"],
  },
  {
    id: "tr_engolir_sapos",
    type: "expression",
    contentPt: "Engolir sapos",
    contentL1: "Yutmak / Sineye çekmek",
    explanation: "Literally: 'To swallow frogs.' To endure insults without reacting. Like Turkish 'sineye çekmek' (to take it to the chest = to accept silently). 'No trabalho, tenho de engolir muitos sapos' (İşte çok şey sineye çekmem gerekiyor).",
    cefrMin: "B1",
    tags: ["proverb", "daily-life"],
  },
  {
    id: "tr_burros_agua",
    type: "expression",
    contentPt: "Dar com os burros na água",
    contentL1: "İşi berbat etmek / Çuvallamak",
    explanation: "Literally: 'To end up with the donkeys in the water.' To fail completely. Like Turkish 'çuvallamak' (to bungle it). Origin: donkeys falling into rivers while crossing, losing all the cargo.",
    cefrMin: "B1",
    tags: ["proverb", "daily-life"],
  },
  {
    id: "tr_rossio_betesga",
    type: "expression",
    contentPt: "Meter o Rossio na Betesga",
    contentL1: "Deveyi hendekten atlatmak (imkânsızı denemek)",
    explanation: "Literally: 'To fit the Rossio (Lisbon's grand square) into the Betesga (a tiny alley nearby).' Attempting the impossible. Turkish has 'deveyi hendekten atlatmak' (to get the camel over the ditch). A purely Lisbon-born proverb from the Middle Ages, still alive today.",
    cefrMin: "B2",
    tags: ["proverb", "lisbon", "history"],
  },
  {
    id: "tr_mar_lugar",
    type: "expression",
    contentPt: "Quem vai ao mar, perde o lugar",
    contentL1: "Giden ağam, gelen paşam",
    explanation: "Literally: 'Who goes to sea, loses their place.' If you leave, someone else takes your spot. Maritime origin. Turkish has 'Giden ağam, gelen paşam' (The one who left was my ağa, the one who came is my paşa). Used today for parking spots, seats, any contested position.",
    cefrMin: "A2",
    tags: ["proverb", "maritime", "daily-life"],
  },
  // --- DAILY IDIOMS ---
  {
    id: "tr_ora_essa",
    type: "expression",
    contentPt: "Ora essa!",
    contentL1: "Estağfurullah! / Ne demek!",
    explanation: "An exclamation of modest denial when thanked. 'Obrigado pela ajuda!' — 'Ora essa!' (Yardımın için teşekkürler! — Estağfurullah!). Like Turkish 'ne demek' or 'estağfurullah' — both cultures value modesty when receiving thanks.",
    cefrMin: "A2",
    tags: ["daily-life", "etiquette"],
  },
  {
    id: "tr_descansado",
    type: "expression",
    contentPt: "Está descansado / Fica descansado",
    contentL1: "Merak etme / Rahat ol",
    explanation: "Literally: 'Be rested/at ease.' Means 'don't worry, I've got it covered.' 'Fica descansado, eu trato disso' (Merak etme, ben hallederim). Like 'merak etme'. Feminine form: 'Fica descansada'.",
    cefrMin: "A2",
    tags: ["daily-life", "conversation"],
  },
  {
    id: "tr_nao_faz_mal",
    type: "expression",
    contentPt: "Não faz mal",
    contentL1: "Önemli değil / Sorun değil",
    explanation: "Literally: 'It doesn't do harm.' The standard response when someone apologizes. 'Desculpa o atraso!' — 'Não faz mal!' (Gecikmek için özür dilerim! — Önemli değil!). Like 'önemli değil'. One of the first phrases you will hear and need.",
    cefrMin: "A1",
    tags: ["daily-life", "etiquette"],
  },
  {
    id: "tr_deixa_la",
    type: "expression",
    contentPt: "Deixa lá",
    contentL1: "Boş ver / Takma kafana",
    explanation: "'Deixa lá' means 'let it go / forget about it.' 'Queres que te pague?' — 'Deixa lá!' (Ödeyeyim mi? — Boş ver!). Can also be consoling: 'Deixa lá, amanhã corre melhor' (Boş ver, yarın daha iyi olur). Like 'boş ver' — deeply natural for Turkish speakers.",
    cefrMin: "A1",
    tags: ["daily-life", "conversation"],
  },
  {
    id: "tr_e_o_que_e",
    type: "expression",
    contentPt: "É o que é",
    contentL1: "Ne yapalım / Olan oldu / Kader",
    explanation: "The Portuguese 'it is what it is.' 'O preço subiu? É o que é.' (Fiyat mı arttı? Ne yapalım). Like Turkish 'ne yapalım' or 'kader'. Both cultures have this fatalistic acceptance — Portuguese call it 'destino', Turks call it 'kader'.",
    cefrMin: "A2",
    tags: ["daily-life", "culture"],
  },
  {
    id: "tr_olha_la",
    type: "expression",
    contentPt: "Olha lá / Ouve lá",
    contentL1: "Bak / Dinle / Pardon",
    explanation: "'Olha lá' (look here) and 'ouve lá' (listen here) get attention or start a question. 'Olha lá, sabes onde fica o correio?' (Bak, postane nerede biliyor musun?). Like 'bak' or 'dinle'. Not rude — it's the standard way to approach someone.",
    cefrMin: "A1",
    tags: ["daily-life", "conversation"],
  },
  {
    id: "tr_entao",
    type: "expression",
    contentPt: "Então?",
    contentL1: "Ee? / Peki? / N'aber?",
    explanation: "'Então?' is the universal Portuguese greeting-question. 'Então, tudo bem?' (N'aber, iyi misin?). Also used to prompt: 'Então, o que queres fazer?' (Peki, ne yapmak istiyorsun?). Like Turkish 'ee?' or 'n'aber?' — short, warm, multipurpose.",
    cefrMin: "A1",
    tags: ["daily-life", "conversation"],
  },
  {
    id: "tr_se_calhar",
    type: "expression",
    contentPt: "Se calhar",
    contentL1: "Belki / Herhalde",
    explanation: "Literally: 'if it falls (that way).' Means 'maybe / perhaps.' 'Se calhar vou ao cinema amanhã' (Belki yarın sinemaya giderim). More common than 'talvez' in everyday speech. Like 'belki' or 'herhalde'. Note: in PT-EU this does NOT trigger the subjunctive, unlike 'talvez'.",
    cefrMin: "A2",
    tags: ["daily-life", "grammar"],
  },
  {
    id: "tr_com_certeza",
    type: "expression",
    contentPt: "Com certeza",
    contentL1: "Tabii ki / Elbette (ama dikkat: gerçek olmayabilir!)",
    explanation: "'Com certeza' means 'certainly.' BUT in PT-EU it is often used as a polite but non-committal agreement — like saying 'tabii ki' but not really meaning it. A Portuguese 'com certeza' can mean 'I'll think about it' (and forget). Similar to how Turkish 'inşallah' sometimes means 'probably not'.",
    cefrMin: "A2",
    tags: ["daily-life", "etiquette", "culture"],
  },
];
