import type { CulturalRef } from "../types.js";

export const trCulturalRefs: readonly CulturalRef[] = [
  {
    id: "tr_saudade",
    type: "expression",
    contentPt: "Saudade",
    contentL1: "Hüzun / Özlem",
    explanation: "Turkish 'hüzun' (melancholy, as Orhan Pamuk describes Istanbul) and 'özlem' (longing) together approximate saudade. Both cultures value melancholy as an emotion worth expressing, not hiding.",
    cefrMin: "B1",
    tags: ["culture", "emotion"],
  },
  {
    id: "tr_cha_cay",
    type: "reference",
    contentPt: "Chá vs Café",
    contentL1: "Çay vs Kahve",
    explanation: "Turkey's tea culture (çay) and Portugal's coffee culture (café) are both central to social life. Both cultures have a dedicated ritual: Turks drink çay in tulip glasses, Portuguese stand at the balcão for a quick bica. The social function is identical.",
    cefrMin: "A1",
    tags: ["food", "daily-life"],
  },
  {
    id: "tr_fixe",
    type: "expression",
    contentPt: "Fixe!",
    contentL1: "Harika! / Süper!",
    explanation: "'Fixe' means 'cool'. Use it like harika or süper. 'Que fixe!' = Ne kadar harika!",
    cefrMin: "A1",
    tags: ["slang", "daily-life"],
  },
  {
    id: "tr_pois",
    type: "expression",
    contentPt: "Pois...",
    contentL1: "Şey... / Yani... / Haa...",
    explanation: "'Pois' is the most versatile Portuguese filler. Like Turkish 'yani' or 'şey', it fills pauses and expresses agreement or hesitation.",
    cefrMin: "A1",
    tags: ["conversation", "daily-life"],
  },
  {
    id: "tr_pasteis",
    type: "reference",
    contentPt: "Pastéis de nata",
    contentL1: "Sütü tatlı (su böreği gibi, ama tatlı)",
    explanation: "Flaky custard tarts. Turkish speakers can think of the flaky layers like börek but filled with sweet custard instead. Found everywhere in Portugal for about one euro.",
    cefrMin: "A1",
    tags: ["food", "culture"],
  },
  {
    id: "tr_fado",
    type: "reference",
    contentPt: "Fado",
    contentL1: "Türk halk müziği gibi (arabesk benzeri)",
    explanation: "Fado's emotional depth parallels Turkish arabesk or halk müziği. Both value raw emotional expression, fate, and heartbreak. Amália Rodrigues is fado's greatest voice.",
    cefrMin: "B1",
    tags: ["music", "culture"],
  },
  {
    id: "tr_hospitality",
    type: "reference",
    contentPt: "Hospitalidade portuguesa",
    contentL1: "Misafirperverlik (misafir hakkı gibi)",
    explanation: "Portuguese hospitality rivals Turkish misafirperverlik. Both cultures insist on feeding guests generously and making them feel at home. 'Fique à vontade' (make yourself at home) is the Portuguese version of 'Buyurun, evinizde gibi hissedin'.",
    cefrMin: "A2",
    tags: ["culture", "hospitality"],
  },
  {
    id: "tr_bacalhau",
    type: "reference",
    contentPt: "Bacalhau",
    contentL1: "Tuzlu balık (365 tarif)",
    explanation: "Salt cod is Portugal's national dish. Turkish cuisine also uses preserved fish (lakerda, çiroz). The salt-curing tradition is shared across Mediterranean cultures.",
    cefrMin: "A2",
    tags: ["food", "culture"],
  },
  {
    id: "tr_25_abril",
    type: "reference",
    contentPt: "25 de Abril — Revolução dos Cravos",
    contentL1: "Karanfil Devrimi (1974)",
    explanation: "On April 25, 1974, Portugal peacefully overthrew its dictatorship with carnations in rifle barrels. This defines modern Portugal the way Atatürk's republic defines modern Turkey.",
    cefrMin: "B1",
    tags: ["history", "identity"],
  },
  {
    id: "tr_pronto",
    type: "expression",
    contentPt: "Pronto!",
    contentL1: "Tamam! / Hazır!",
    explanation: "'Pronto' = done/ready/OK then. Like tamam or hazır. 'Pronto, vamos!' = Tamam, gidelim!",
    cefrMin: "A1",
    tags: ["daily-life", "conversation"],
  },
  {
    id: "tr_azulejo",
    type: "reference",
    contentPt: "Azulejos",
    contentL1: "Çini (Türk çini geleneği gibi)",
    explanation: "Portuguese blue and white tiles share roots with Ottoman çini tiles. Both traditions were influenced by Islamic art. The Arabic word 'al-zulayj' gave both azulejo and züleyha/çini their origin.",
    cefrMin: "A2",
    tags: ["art", "culture", "history"],
  },
  {
    id: "tr_santos",
    type: "reference",
    contentPt: "Festas dos Santos Populares",
    contentL1: "Halk festivalleri (bayram gibi)",
    explanation: "June street festivals with sardines, music, and dancing. The communal celebration spirit resembles Turkish bayram celebrations where everyone eats and socializes together.",
    cefrMin: "A2",
    tags: ["culture", "festivals"],
  },
  {
    id: "tr_family",
    type: "reference",
    contentPt: "Família é tudo",
    contentL1: "Aile her şeydir",
    explanation: "Like Turkish culture, Portuguese culture is deeply family-oriented. Sunday lunches are sacred. Elders are respected. The family structure will feel very familiar.",
    cefrMin: "A2",
    tags: ["culture", "family"],
  },
  {
    id: "tr_desenrascar",
    type: "expression",
    contentPt: "Desenrascar-se",
    contentL1: "İşin içinden çıkmak / Çare bulmak",
    explanation: "The art of improvising solutions. Like Turkish 'işin içinden çıkmak'. Both cultures celebrate creative problem-solving.",
    cefrMin: "B1",
    tags: ["culture", "daily-life"],
  },
  {
    id: "tr_nas_tintas",
    type: "expression",
    contentPt: "Estar-se nas tintas",
    contentL1: "Umurumda değil / Bana ne",
    explanation: "Literally 'to be in the paints' — couldn't care less. Like 'umurumda değil'. Very common, mildly rude.",
    cefrMin: "B1",
    tags: ["slang", "emotion"],
  },
];
