import type { L1Profile } from "../types.js";

export const trProfile: L1Profile = {
  code: "tr",
  name: "Turkish",
  nativeName: "Türkçe",
  writingDirection: "ltr",
  hasLatinScript: true,
  transfer: {
    cognates: [
      "müzik (música — music, via French)",
      "kültür (cultura — culture, via French)",
      "problem (problema — problem)",
      "üniversite (universidade — university)",
      "grup (grupo — group)",
      "sistem (sistema — system)",
      "demokrat (democrata — democrat)",
      "enerji (energia — energy)",
      "telefon (telefone — telephone)",
      "restoran (restaurante — restaurant)",
      "tiyatro (teatro — theatre)",
      "kahve (café — coffee, both from Arabic qahwa)",
      "liman (via Portuguese-Ottoman trade — port/harbour)",
      "fırtına (fortuna — storm, from Portuguese maritime contact)",
    ],
    falseFriends: [
      { word: "araba", l1Meaning: "araba means 'car' in Turkish", ptMeaning: "no PT cognate — car = carro; 'árabe' means 'Arab'" },
      { word: "ev", l1Meaning: "ev means 'house/home' in Turkish", ptMeaning: "sounds like Portuguese 'eu' (I/me) — house = casa" },
      { word: "masa", l1Meaning: "masa means 'table' in Turkish", ptMeaning: "massa means 'dough/pasta' — table = mesa (close!)" },
      { word: "para", l1Meaning: "para means 'money' in Turkish", ptMeaning: "para means 'for/to' (preposition) — money = dinheiro" },
      { word: "salon", l1Meaning: "salon means 'living room' in Turkish", ptMeaning: "salão means 'large hall/salon' — living room = sala" },
      { word: "mal", l1Meaning: "mal means 'goods/property/livestock' in Turkish", ptMeaning: "mal means 'badly/evil'" },
      { word: "bar", l1Meaning: "bar means 'bar/pub' in both languages", ptMeaning: "bar — true cognate, same meaning" },
      { word: "cam", l1Meaning: "cam means 'glass (material)' in Turkish", ptMeaning: "no direct PT cognate — glass = vidro" },
      { word: "su", l1Meaning: "su means 'water' in Turkish", ptMeaning: "sounds like 'seu' (your) — water = água" },
      { word: "dos", l1Meaning: "dos means 'back (anatomy)' in Turkish (from French)", ptMeaning: "dos means 'two' or 'of the' (de + os)" },
      { word: "sol", l1Meaning: "sol means 'left (direction)' in Turkish", ptMeaning: "sol means 'sun' — left = esquerda" },
      { word: "ay", l1Meaning: "ay means 'moon/month' in Turkish", ptMeaning: "sounds like 'ai' (ouch!) — moon = lua, month = mês" },
      { word: "comer", l1Meaning: "no Turkish cognate", ptMeaning: "comer means 'to eat'" },
      { word: "largo", l1Meaning: "no Turkish cognate", ptMeaning: "largo means 'wide' or 'public square' — wide = geniş in Turkish" },
      { word: "gato", l1Meaning: "no Turkish cognate (kedi = cat)", ptMeaning: "gato means 'cat'" },
      { word: "porta", l1Meaning: "no Turkish cognate (kapı = door)", ptMeaning: "porta means 'door'" },
      { word: "banco", l1Meaning: "banka means 'bank' in Turkish", ptMeaning: "banco means 'bank' AND 'bench' — two meanings" },
      { word: "dar", l1Meaning: "dar means 'narrow/tight' in Turkish", ptMeaning: "dar means 'to give' — narrow = estreito" },
      { word: "ser", l1Meaning: "ser means 'head/leader' in old Turkish", ptMeaning: "ser means 'to be' (identity/permanent)" },
      { word: "pena", l1Meaning: "no Turkish cognate (kalem/tüy)", ptMeaning: "pena means 'feather' or 'pity' or 'penalty'" },
      { word: "cola", l1Meaning: "kola means 'cola drink' or 'arm' in Turkish", ptMeaning: "cola means 'glue' — also slang for cheating on a test" },
      { word: "caro", l1Meaning: "no Turkish cognate (pahalı = expensive)", ptMeaning: "caro means 'expensive' or 'dear'" },
      { word: "conta", l1Meaning: "no Turkish cognate (hesap = bill)", ptMeaning: "conta means 'bill/account/story'" },
      { word: "data", l1Meaning: "data — no Turkish cognate (tarih = date)", ptMeaning: "data means 'date'" },
    ],
    phoneticDifficulties: [
      {
        sound: "ão",
        ipa: "/ɐ̃w̃/",
        description: "Nasal diphthong -ão",
        tip: "Turkish has no nasal vowels at all. This is completely new: open your mouth for 'a', lower the soft palate for nasal airflow, then glide to a nasal 'u'. Practice: pão, mão, não.",
        mouthPosition: "nasal_ao",
      },
      {
        sound: "ã/õ/ẽ",
        ipa: "/ɐ̃/ /õ/ /ẽ/",
        description: "Nasal vowels",
        tip: "Turkish vowels are always oral. PT-EU nasalizes vowels by sending air through the nose — this changes word meaning. 'Lã' (wool) vs 'lá' (there). No Turkish equivalent exists.",
        mouthPosition: "nasal_vowel",
      },
      {
        sound: "r/rr",
        ipa: "/ʁ/",
        description: "Uvular R (initial and double)",
        tip: "Turkish R is alveolar (like a tap or trill). PT-EU initial R and double RR are uvular — back of the throat. Think of the gargling sound. 'Rato' (mouse), 'carro' (car).",
        mouthPosition: "uvular_r",
      },
      {
        sound: "r (tap)",
        ipa: "/ɾ/",
        description: "Alveolar tap between vowels",
        tip: "Single 'r' between vowels is a quick tap — similar to Turkish R in most positions. 'Caro' (expensive), 'para' (for). This one is easy for Turkish speakers.",
        mouthPosition: "alveolar_tap",
      },
      {
        sound: "lh",
        ipa: "/ʎ/",
        description: "Palatal lateral lh",
        tip: "No Turkish equivalent. Press the middle of your tongue against the hard palate while making an L. 'Trabalho' (work), 'filho' (son), 'olho' (eye).",
        mouthPosition: "palatal_lateral",
      },
      {
        sound: "nh",
        ipa: "/ɲ/",
        description: "Palatal nasal nh",
        tip: "Like English 'ny' in 'canyon'. Not like Turkish 'n'. The tongue touches the palate while nasalizing. 'Vinho' (wine), 'amanhã' (tomorrow).",
        mouthPosition: "palatal_nasal",
      },
      {
        sound: "consonant clusters",
        ipa: "/pr/ /tr/ /pl/ /str/",
        description: "Initial consonant clusters",
        tip: "Turkish avoids initial clusters (tren is a loanword). PT-EU has many: 'prato' (plate), 'três' (three), 'construção' (construction). Do not insert a vowel between consonants.",
      },
      {
        sound: "v/b distinction",
        ipa: "/v/ vs /b/",
        description: "V and B are different sounds",
        tip: "Turkish has both v and b. Apply the same in PT-EU: 'v' is always labiodental (teeth on lip). 'Vaca' (cow) vs 'boca' (mouth). Natural advantage for Turkish speakers.",
        mouthPosition: "labiodental_v",
      },
      {
        sound: "open/closed vowels",
        ipa: "/ɛ/ vs /e/, /ɔ/ vs /o/",
        description: "Vowel quality contrasts",
        tip: "Turkish has vowel harmony but not open/closed pairs like PT-EU. 'É' (open /ɛ/) vs 'ê' (closed /e/) change meaning: 'avó' (grandmother) vs 'avô' (grandfather). Watch the accent marks.",
        mouthPosition: "open_e",
      },
      {
        sound: "reduced vowels",
        ipa: "/ɨ/ /ə/",
        description: "Unstressed vowels nearly vanish",
        tip: "Turkish pronounces every vowel clearly. PT-EU swallows unstressed vowels — 'telefonema' sounds like 'tlfnema'. This is the biggest rhythm challenge for Turkish speakers.",
      },
      {
        sound: "s/z/ʃ/ʒ",
        ipa: "/s/ /z/ /ʃ/ /ʒ/",
        description: "Four sibilants",
        tip: "Turkish has s and ş (and z). PT-EU adds /ʒ/ (voiced 'sh'): 'j' and 'g' before e/i = /ʒ/. Final 's' = /ʃ/. Between vowels 's' = /z/. Turkish ş maps to PT-EU /ʃ/.",
        mouthPosition: "sibilant_sh",
      },
    ],
    grammarGaps: [
      {
        concept: "Articles (o/a, um/uma)",
        explanation: "Every noun requires a definite or indefinite article matching gender",
        l1Comparison: "Turkish has no articles (bir = 'one' serves as a loose indefinite). PT-EU requires articles: 'o livro' (the book), 'uma casa' (a house). The article also tells you the noun's gender.",
      },
      {
        concept: "Grammatical gender",
        explanation: "Every noun is masculine or feminine",
        l1Comparison: "Turkish has no grammatical gender at all (no 'he/she' distinction — just 'o'). PT-EU assigns gender to everything: 'o sol' (sun, m), 'a lua' (moon, f). Even adjectives change: bonito/bonita.",
      },
      {
        concept: "SVO word order",
        explanation: "Subject-Verb-Object is the default",
        l1Comparison: "Turkish is SOV (Ali kitabı okudu = Ali book-acc read). PT-EU is SVO: 'O Ali leu o livro' (Ali read the book). The verb moves to the middle position.",
      },
      {
        concept: "Prepositions (not postpositions)",
        explanation: "de, em, a, para, com, por — come BEFORE the noun",
        l1Comparison: "Turkish uses postpositions and suffixes (masanın üstünde = table-of on-its). PT-EU prepositions precede the noun: 'em cima da mesa' (on top of the table). Reverse the order.",
      },
      {
        concept: "Verb conjugation",
        explanation: "6 person forms per tense, 3 verb classes (-ar, -er, -ir)",
        l1Comparison: "Turkish is agglutinative — suffixes stack. PT-EU conjugates with stem changes and endings: eu falo, tu falas, ele fala. The pattern is fusional (single ending = person + tense), not agglutinative.",
      },
      {
        concept: "Ser vs Estar",
        explanation: "Two verbs for 'to be'",
        l1Comparison: "Turkish uses suffixes or 'olmak' for 'to be'. PT-EU splits: 'Sou turco' (I am Turkish — ser, identity) vs 'Estou cansado' (I am tired — estar, state). Critical distinction.",
      },
      {
        concept: "Subjunctive mood",
        explanation: "Required for doubt, desire, emotion",
        l1Comparison: "Turkish uses different suffixes (-se/-sa for conditional). PT-EU subjunctive is a full parallel verb paradigm required after many expressions: 'Espero que venhas' (I hope you come).",
      },
      {
        concept: "Personal infinitive",
        explanation: "Infinitive conjugated for person — unique to Portuguese",
        l1Comparison: "Turkish uses verbal nouns (-mek/-mak). PT-EU personal infinitive conjugates: 'Para nós fazermos' (for us to do). No Turkish equivalent.",
      },
      {
        concept: "Plural formation",
        explanation: "Add -s or -es (mostly regular)",
        l1Comparison: "Turkish uses -ler/-lar with vowel harmony. PT-EU is simpler: usually add -s ('livro' → 'livros'). Watch for -ão words: 'coração' → 'corações'. Articles change too: o → os.",
      },
      {
        concept: "Relative clauses with 'que'",
        explanation: "'Que' introduces all relative clauses",
        l1Comparison: "Turkish uses participle suffixes (-en, -dığı) before the noun. PT-EU uses a relative pronoun 'que' AFTER the noun: 'o homem que fala' (the man who speaks). The clause structure reverses.",
      },
      {
        concept: "Object pronoun placement",
        explanation: "Before or after the verb depending on triggers",
        l1Comparison: "Turkish puts objects before the verb. PT-EU has complex rules: 'Dá-me' (give me, after) vs 'Não me dás' (you don't give me, before). The pronoun floats based on what precedes the verb.",
      },
      {
        concept: "Tu vs Você vs O Senhor",
        explanation: "Three formality levels for 'you'",
        l1Comparison: "Turkish has sen/siz (like tu/vous). PT-EU adds a middle level: 'tu' (intimate, like sen), 'você' (neutral), 'o senhor' (formal, like siz). In Portugal, 'tu' is standard among peers.",
      },
      {
        concept: "Preposition contractions",
        explanation: "Mandatory: em+o=no, de+a=da, a+o=ao, por+o=pelo",
        l1Comparison: "Turkish suffixes always remain separate morphemes. PT-EU merges prepositions with articles: 'no' (em + o), 'da' (de + a). These contractions are mandatory.",
      },
    ],
    skipBasics: false,
    startingCEFR: "A1",
  },
};
