import type { CulturalRef } from "../types.js";

export const ruCulturalRefs: readonly CulturalRef[] = [
  {
    id: "ru_saudade",
    type: "expression",
    contentPt: "Saudade",
    contentL1: "Тоска (toska)",
    explanation: "Russian 'тоска' is one of the closest equivalents to Portuguese 'saudade'. Both describe a deep, bittersweet longing. Nabokov called toska untranslatable; Portuguese say the same about saudade. This emotional kinship connects the two cultures.",
    cefrMin: "B1",
    tags: ["culture", "emotion"],
  },
  {
    id: "ru_fado",
    type: "reference",
    contentPt: "Fado",
    contentL1: "Русский романс",
    explanation: "Fado's emotional depth parallels Russian romance songs. Both traditions value melancholy and raw emotion in performance. Amália Rodrigues is to fado what Pyotr Leshchenko is to Russian romance.",
    cefrMin: "B1",
    tags: ["music", "culture"],
  },
  {
    id: "ru_bacalhau",
    type: "reference",
    contentPt: "Bacalhau",
    contentL1: "Солёная рыба (как вобла)",
    explanation: "Salt cod is Portugal's national dish — 365 recipes. Russians know preserved fish well. 'Bacalhau à Brás' (shredded cod with eggs and potatoes) is the most popular preparation.",
    cefrMin: "A2",
    tags: ["food", "culture"],
  },
  {
    id: "ru_fixe",
    type: "expression",
    contentPt: "Fixe!",
    contentL1: "Класс! / Круто!",
    explanation: "'Fixe' means 'cool'. Use it like класс or круто. 'Que fixe!' = How cool!",
    cefrMin: "A1",
    tags: ["slang", "daily-life"],
  },
  {
    id: "ru_pois",
    type: "expression",
    contentPt: "Pois...",
    contentL1: "Ну... / Ну да...",
    explanation: "'Pois' is the most versatile Portuguese filler. Like Russian ну, it fills pauses and expresses resignation. 'Pois pois' = ну-ну.",
    cefrMin: "A1",
    tags: ["conversation", "daily-life"],
  },
  {
    id: "ru_25_abril",
    type: "reference",
    contentPt: "25 de Abril — Revolução dos Cravos",
    contentL1: "Революция гвоздик (1974)",
    explanation: "On April 25, 1974, Portugal peacefully overthrew its 48-year dictatorship. Soldiers put carnations in their rifles. The Portuguese Communist Party played a role in post-revolution politics, creating a brief Cold War connection.",
    cefrMin: "B1",
    tags: ["history", "identity"],
  },
  {
    id: "ru_pasteis",
    type: "reference",
    contentPt: "Pastéis de nata",
    contentL1: "Яичные корзиночки",
    explanation: "Flaky custard tarts found everywhere for about one euro. Similar to Russian корзиночки but lighter and caramelized. Eat warm with cinnamon.",
    cefrMin: "A1",
    tags: ["food", "culture"],
  },
  {
    id: "ru_vinho",
    type: "reference",
    contentPt: "Vinho do Porto",
    contentL1: "Портвейн (уже знаком)",
    explanation: "Russians already know портвейн. Portugal has a vast wine culture beyond port: Vinho Verde, Douro reds, Alentejo wines. Wine is cheaper than water at restaurants.",
    cefrMin: "A2",
    tags: ["food", "culture"],
  },
  {
    id: "ru_pronto",
    type: "expression",
    contentPt: "Pronto!",
    contentL1: "Готово! / Ну вот!",
    explanation: "'Pronto' = done/ready/OK then. Like готово or ну вот. One of the most common words in everyday Portuguese.",
    cefrMin: "A1",
    tags: ["daily-life", "conversation"],
  },
  {
    id: "ru_desenrascar",
    type: "expression",
    contentPt: "Desenrascar-se",
    contentL1: "Выкрутиться",
    explanation: "The art of improvising a solution. Like Russian выкрутиться. Both cultures celebrate resourcefulness and getting out of tight spots creatively.",
    cefrMin: "B1",
    tags: ["culture", "daily-life"],
  },
  {
    id: "ru_santos",
    type: "reference",
    contentPt: "Festas dos Santos Populares",
    contentL1: "Народные гулянья (как Масленица)",
    explanation: "Every June, streets fill with grilled sardines, music, and dancing. The communal spirit resembles Масленица — everyone celebrates together outdoors.",
    cefrMin: "A2",
    tags: ["culture", "festivals"],
  },
  {
    id: "ru_tu_voce",
    type: "reference",
    contentPt: "Tu vs O Senhor",
    contentL1: "Ты vs Вы",
    explanation: "Like Russian ты/Вы, Portuguese has 'tu' (informal) and 'o senhor' (formal). 'Você' in Portugal can sound cold — avoid it. Russian speakers understand this social hierarchy naturally.",
    cefrMin: "A1",
    tags: ["social", "etiquette"],
  },
  {
    id: "ru_family",
    type: "reference",
    contentPt: "Família é tudo",
    contentL1: "Семья — главное",
    explanation: "Like Russian culture, Portuguese culture values family deeply. Sunday lunches are mandatory. Grandparents are central to childcare. The warmth will feel familiar.",
    cefrMin: "A2",
    tags: ["culture", "family"],
  },
  {
    id: "ru_lisbon_porto",
    type: "reference",
    contentPt: "Lisboa vs Porto",
    contentL1: "Как Москва vs Питер",
    explanation: "Lisbon and Porto rival like Moscow and St. Petersburg. Lisbon is the cosmopolitan capital; Porto is culturally proud and independent.",
    cefrMin: "B1",
    tags: ["culture", "cities"],
  },
  {
    id: "ru_nas_tintas",
    type: "expression",
    contentPt: "Estar-se nas tintas",
    contentL1: "Мне всё равно / пофиг",
    explanation: "Literally 'to be in the paints' — couldn't care less. Like пофиг. Very common in everyday speech.",
    cefrMin: "B1",
    tags: ["slang", "emotion"],
  },
];
