import type { CulturalRef } from "../types.js";

export const ruCulturalRefs: readonly CulturalRef[] = [
  {
    id: "ru_saudade",
    type: "expression",
    contentPt: "Saudade",
    contentL1: "Тоска (toska)",
    explanation: "Russian 'тоска' is one of the closest equivalents to Portuguese 'saudade'. Both describe a deep, bittersweet longing. Nabokov called toska untranslatable; Portuguese say the same about saudade. This emotional kinship connects the two cultures.",
    cefrMin: "B1",
    tags: ["culture", "emotion"],
  },
  {
    id: "ru_fado",
    type: "reference",
    contentPt: "Fado",
    contentL1: "Русский романс",
    explanation: "Fado's emotional depth parallels Russian romance songs. Both traditions value melancholy and raw emotion in performance. Amália Rodrigues is to fado what Pyotr Leshchenko is to Russian romance.",
    cefrMin: "B1",
    tags: ["music", "culture"],
  },
  {
    id: "ru_bacalhau",
    type: "reference",
    contentPt: "Bacalhau",
    contentL1: "Солёная рыба (как вобла)",
    explanation: "Salt cod is Portugal's national dish — 365 recipes. Russians know preserved fish well. 'Bacalhau à Brás' (shredded cod with eggs and potatoes) is the most popular preparation.",
    cefrMin: "A2",
    tags: ["food", "culture"],
  },
  {
    id: "ru_fixe",
    type: "expression",
    contentPt: "Fixe!",
    contentL1: "Класс! / Круто!",
    explanation: "'Fixe' means 'cool'. Use it like класс or круто. 'Que fixe!' = How cool!",
    cefrMin: "A1",
    tags: ["slang", "daily-life"],
  },
  {
    id: "ru_pois",
    type: "expression",
    contentPt: "Pois...",
    contentL1: "Ну... / Ну да...",
    explanation: "'Pois' is the most versatile Portuguese filler. Like Russian ну, it fills pauses and expresses resignation. 'Pois pois' = ну-ну.",
    cefrMin: "A1",
    tags: ["conversation", "daily-life"],
  },
  {
    id: "ru_25_abril",
    type: "reference",
    contentPt: "25 de Abril — Revolução dos Cravos",
    contentL1: "Революция гвоздик (1974)",
    explanation: "On April 25, 1974, Portugal peacefully overthrew its 48-year dictatorship. Soldiers put carnations in their rifles. The Portuguese Communist Party played a role in post-revolution politics, creating a brief Cold War connection.",
    cefrMin: "B1",
    tags: ["history", "identity"],
  },
  {
    id: "ru_pasteis",
    type: "reference",
    contentPt: "Pastéis de nata",
    contentL1: "Яичные корзиночки",
    explanation: "Flaky custard tarts found everywhere for about one euro. Similar to Russian корзиночки but lighter and caramelized. Eat warm with cinnamon.",
    cefrMin: "A1",
    tags: ["food", "culture"],
  },
  {
    id: "ru_vinho",
    type: "reference",
    contentPt: "Vinho do Porto",
    contentL1: "Портвейн (уже знаком)",
    explanation: "Russians already know портвейн. Portugal has a vast wine culture beyond port: Vinho Verde, Douro reds, Alentejo wines. Wine is cheaper than water at restaurants.",
    cefrMin: "A2",
    tags: ["food", "culture"],
  },
  {
    id: "ru_pronto",
    type: "expression",
    contentPt: "Pronto!",
    contentL1: "Готово! / Ну вот!",
    explanation: "'Pronto' = done/ready/OK then. Like готово or ну вот. One of the most common words in everyday Portuguese.",
    cefrMin: "A1",
    tags: ["daily-life", "conversation"],
  },
  {
    id: "ru_desenrascar",
    type: "expression",
    contentPt: "Desenrascar-se",
    contentL1: "Выкрутиться",
    explanation: "The art of improvising a solution. Like Russian выкрутиться. Both cultures celebrate resourcefulness and getting out of tight spots creatively.",
    cefrMin: "B1",
    tags: ["culture", "daily-life"],
  },
  {
    id: "ru_santos",
    type: "reference",
    contentPt: "Festas dos Santos Populares",
    contentL1: "Народные гулянья (как Масленица)",
    explanation: "Every June, streets fill with grilled sardines, music, and dancing. The communal spirit resembles Масленица — everyone celebrates together outdoors.",
    cefrMin: "A2",
    tags: ["culture", "festivals"],
  },
  {
    id: "ru_tu_voce",
    type: "reference",
    contentPt: "Tu vs O Senhor",
    contentL1: "Ты vs Вы",
    explanation: "Like Russian ты/Вы, Portuguese has 'tu' (informal) and 'o senhor' (formal). 'Você' in Portugal can sound cold — avoid it. Russian speakers understand this social hierarchy naturally.",
    cefrMin: "A1",
    tags: ["social", "etiquette"],
  },
  {
    id: "ru_family",
    type: "reference",
    contentPt: "Família é tudo",
    contentL1: "Семья — главное",
    explanation: "Like Russian culture, Portuguese culture values family deeply. Sunday lunches are mandatory. Grandparents are central to childcare. The warmth will feel familiar.",
    cefrMin: "A2",
    tags: ["culture", "family"],
  },
  {
    id: "ru_lisbon_porto",
    type: "reference",
    contentPt: "Lisboa vs Porto",
    contentL1: "Как Москва vs Питер",
    explanation: "Lisbon and Porto rival like Moscow and St. Petersburg. Lisbon is the cosmopolitan capital; Porto is culturally proud and independent.",
    cefrMin: "B1",
    tags: ["culture", "cities"],
  },
  {
    id: "ru_nas_tintas",
    type: "expression",
    contentPt: "Estar-se nas tintas",
    contentL1: "Мне всё равно / пофиг",
    explanation: "Literally 'to be in the paints' — couldn't care less. Like пофиг. Very common in everyday speech.",
    cefrMin: "B1",
    tags: ["slang", "emotion"],
  },
  {
    id: "ru_algarve_community",
    type: "reference",
    contentPt: "Russos no Algarve",
    contentL1: "Русская община в Алгарве",
    explanation: "The Algarve has a well-established Russian-speaking community, especially in Albufeira, Vilamoura, and Lagos. Russian-language services, shops, and real estate agencies exist. Many Russians chose Portugal for Golden Visa residency, and the community has its own social networks and events. Learning Portuguese there means navigating between tourist English, local Algarvio dialect, and Russian neighbours.",
    cefrMin: "A2",
    tags: ["community", "practical", "algarve"],
  },
  {
    id: "ru_cha_samovar",
    type: "reference",
    contentPt: "Chá — a mesma palavra, outra cultura",
    contentL1: "Чай — то же слово, другая культура",
    explanation: "Russian чай and Portuguese chá share the same Chinese root — both borrowed the Cantonese 'cha' through overland trade routes. But tea culture is opposite: Russian tea is strong, from a samovar, drunk all day with sugar. Portuguese chá is light, herbal or black, drunk in the afternoon. Coffee dominates in Portugal — the morning ritual is a quick 'bica' (espresso) at the counter, not a long seated чаепитие.",
    cefrMin: "A1",
    tags: ["food", "daily-life", "history"],
  },
  {
    id: "ru_bureaucracy",
    type: "reference",
    contentPt: "Burocracia portuguesa",
    contentL1: "Бюрократия — знакомо, но по-своему",
    explanation: "Russians understand bureaucracy deeply. Portuguese bureaucracy is similarly paper-heavy: NIF (налоговый номер), NISS (social security), título de residência, atestado de morada. The key difference: Portuguese offices close for lunch and move slowly, but staff are friendly. 'Finanças' (tax office) and 'Segurança Social' are the two buildings you will visit most. Bring every document you own — originals and copies. 'Apostilha' (apostille) is a word you will learn fast.",
    cefrMin: "A2",
    tags: ["practical", "daily-life", "bureaucracy"],
  },
  // --- MODERN SLANG ---
  {
    id: "ru_bue",
    type: "expression",
    contentPt: "Bué",
    contentL1: "Дофига / Очень / Кучу",
    explanation: "'Bué' means 'a lot' or 'very' in PT-EU slang, from Kimbundu (Angolan). 'Bué fixe' (очень круто), 'bué gente' (дофига народу). Like Russian 'дофига' or 'кучу'. Used by anyone under 40, ubiquitous in Lisbon.",
    cefrMin: "A2",
    tags: ["slang", "daily-life"],
  },
  {
    id: "ru_cena",
    type: "expression",
    contentPt: "Cena",
    contentL1: "Штука / Вещь / Фигня",
    explanation: "Originally 'scene' but in PT-EU slang means 'thing/stuff/situation'. 'Que cena!' (Ну и фигня!), 'é uma cena estranha' (странная штука). Like Russian 'штука' or 'фигня'. Universal placeholder — 'dá-me aquela cena' (дай мне ту штуку).",
    cefrMin: "A2",
    tags: ["slang", "daily-life"],
  },
  {
    id: "ru_tipo",
    type: "expression",
    contentPt: "Tipo...",
    contentL1: "Типа... / Ну как бы...",
    explanation: "The Portuguese filler word, like Russian 'типа' or 'ну как бы'. 'Ele é tipo alto' (Он типа высокий). Every young Portuguese person uses it constantly. The Russian 'типа' even sounds similar to 'tipo'.",
    cefrMin: "A2",
    tags: ["slang", "conversation"],
  },
  {
    id: "ru_ganda",
    type: "expression",
    contentPt: "Ganda / Granda",
    contentL1: "Мощный / Зачётный / Офигенный",
    explanation: "Contraction of 'grande' — intensifier meaning 'great/massive'. 'Ganda filme!' (Мощный фильм!), 'granda maluco!' (офигенный чувак!). Like Russian 'мощный' or 'зачётный'. Lisbon street slang, not for formal situations.",
    cefrMin: "B1",
    tags: ["slang"],
  },
  {
    id: "ru_bazar",
    type: "expression",
    contentPt: "Bazar",
    contentL1: "Свалить / Слинять",
    explanation: "'Bazar' means 'to leave/bounce'. 'Vou bazar' (я сваливаю). Like Russian 'свалить' or 'слинять'. Nothing to do with a marketplace. 'Ele bazou' (он свалил). Quick, informal departure.",
    cefrMin: "B1",
    tags: ["slang", "daily-life"],
  },
  {
    id: "ru_curtir",
    type: "expression",
    contentPt: "Curtir",
    contentL1: "Кайфовать / Тащиться / Нравиться",
    explanation: "'Curtir' means to enjoy, to be into something. 'Curto bué este sítio' (мне тут очень нравится). Also romantic: 'Ela curte-o' (она на него запала). Like Russian 'кайфовать' or 'тащиться'. Versatile — works for food, music, places, people.",
    cefrMin: "A2",
    tags: ["slang", "daily-life"],
  },
  {
    id: "ru_na_boa",
    type: "expression",
    contentPt: "Na boa",
    contentL1: "Без проблем / Нормально / На расслабоне",
    explanation: "'Na boa' = 'no worries / it's all good'. 'Podes ficar, na boa' (Можешь остаться, без проблем). Also a question: 'Tás na boa?' (Ты нормально?). Like Russian 'без проблем' or 'на расслабоне'. One of the most useful casual phrases.",
    cefrMin: "A1",
    tags: ["slang", "daily-life"],
  },
  {
    id: "ru_o_pa",
    type: "expression",
    contentPt: "Ó pá!",
    contentL1: "Чувак! / Блин! / Э!",
    explanation: "The quintessential Portuguese interjection. 'Ó pá, não acredito!' (Блин, не верю!). Used between friends like Russian 'чувак!' or 'блин!'. Short for 'rapaz'. Expresses surprise, frustration, or casual address. Heard dozens of times daily.",
    cefrMin: "A1",
    tags: ["slang", "daily-life"],
  },
  {
    id: "ru_mano",
    type: "expression",
    contentPt: "Mano / Mana",
    contentL1: "Бро / Братан / Сестра",
    explanation: "Short for 'irmão/irmã' (brother/sister). Used as 'bro/sis' between close friends. 'Olha, mano' (Слушай, братан). Like Russian 'братан' or 'бро'. Very common in Lisbon, especially in multicultural neighbourhoods.",
    cefrMin: "A2",
    tags: ["slang", "daily-life"],
  },
  {
    id: "ru_mandar_vir",
    type: "expression",
    contentPt: "Mandar vir",
    contentL1: "Бухтеть / Заказать (два значения!)",
    explanation: "Two completely different meanings: 1) 'To complain': 'Ele está sempre a mandar vir' (Он всё время бухтит) — like Russian 'бухтеть' or 'ворчать'. 2) 'To order': 'Manda vir mais uma cerveja' (Закажи ещё одно пиво). Context tells you which.",
    cefrMin: "B1",
    tags: ["slang", "daily-life"],
  },
  {
    id: "ru_ta_se_bem",
    type: "expression",
    contentPt: "Tá-se bem",
    contentL1: "Нормально! / Пойдёт! / Лады!",
    explanation: "Contraction of 'está-se bem' — 'it's all good'. 'Vamos ao cinema?' — 'Tá-se bem!' (Пойдём в кино? — Лады!). Like Russian 'лады' or 'пойдёт'. Very casual, very common agreement.",
    cefrMin: "A1",
    tags: ["slang", "daily-life"],
  },
  // --- ANCIENT PROVERBS ---
  {
    id: "ru_agua_pedra",
    type: "expression",
    contentPt: "Água mole em pedra dura, tanto bate até que fura",
    contentL1: "Капля камень точит",
    explanation: "Literally: 'Soft water on hard stone, hits until it pierces.' Identical to Russian 'Капля камень точит' (A drop wears the stone). Both from Latin (Ovid). Persistence wins. One of the oldest shared proverbs — same wisdom, same image, across three thousand kilometres.",
    cefrMin: "B1",
    tags: ["proverb", "wisdom"],
  },
  {
    id: "ru_cao_gato",
    type: "expression",
    contentPt: "Quem não tem cão, caça com gato",
    contentL1: "На безрыбье и рак — рыба",
    explanation: "Literally: 'Who doesn't have a dog, hunts with a cat.' Make do with what you have. The Russian 'На безрыбье и рак — рыба' (When there's no fish, even a crayfish is a fish) carries the same wisdom. Both celebrate resourcefulness.",
    cefrMin: "B1",
    tags: ["proverb", "culture"],
  },
  {
    id: "ru_grao_galinha",
    type: "expression",
    contentPt: "Grão a grão, enche a galinha o papo",
    contentL1: "Копейка рубль бережёт",
    explanation: "Literally: 'Grain by grain, the hen fills her crop.' Small things add up. The Russian 'Копейка рубль бережёт' (A kopek saves a ruble) uses money instead of grain but the message is identical: don't dismiss the small gains.",
    cefrMin: "B1",
    tags: ["proverb", "wisdom"],
  },
  {
    id: "ru_pepino",
    type: "expression",
    contentPt: "De pequenino se torce o pepino",
    contentL1: "Учи дитя, пока поперёк лавки лежит",
    explanation: "Literally: 'You bend the cucumber when it's small.' Habits are formed young. Russian says 'Учи дитя, пока поперёк лавки лежит' (Teach the child while it lies across the bench). Same idea — education must start early. Used by babushkas and avós alike.",
    cefrMin: "B1",
    tags: ["proverb", "education"],
  },
  {
    id: "ru_tripas_coracao",
    type: "expression",
    contentPt: "Fazer das tripas coração",
    contentL1: "Собрать волю в кулак / Превозмочь себя",
    explanation: "Literally: 'To make heart out of guts.' To summon courage when you have none. Like Russian 'собрать волю в кулак' (to clench your will into a fist). Origin linked to Porto — residents sent good meat to the ships and ate only tripe, hence Porto's nickname 'cidade dos tripeiros'.",
    cefrMin: "B1",
    tags: ["proverb", "history"],
  },
  {
    id: "ru_ver_navios",
    type: "expression",
    contentPt: "Ficar a ver navios",
    contentL1: "Остаться с носом / Остаться ни с чем",
    explanation: "Literally: 'To be left watching ships.' To be left empty-handed. Origin: during the Age of Discoveries, women waited on docks for ships that never returned. Like Russian 'остаться с носом' (to be left with just your nose) or 'остаться ни с чем'.",
    cefrMin: "B1",
    tags: ["proverb", "history"],
  },
  {
    id: "ru_engolir_sapos",
    type: "expression",
    contentPt: "Engolir sapos",
    contentL1: "Проглотить обиду / Стерпеть",
    explanation: "Literally: 'To swallow frogs.' To endure insults silently. Like Russian 'проглотить обиду' (to swallow an insult). 'No trabalho, tenho de engolir muitos sapos' (На работе приходится много терпеть). Ancient proverb, still used daily in both languages.",
    cefrMin: "B1",
    tags: ["proverb", "daily-life"],
  },
  {
    id: "ru_burros_agua",
    type: "expression",
    contentPt: "Dar com os burros na água",
    contentL1: "Сесть в лужу / Облажаться",
    explanation: "Literally: 'To end up with the donkeys in the water.' To fail. Origin: donkey drivers crossing rivers — cargo was lost when donkeys fell in. Like Russian 'сесть в лужу' (to sit in a puddle). 'Tentei mas dei com os burros na água' (Попытался, но сел в лужу).",
    cefrMin: "B1",
    tags: ["proverb", "daily-life"],
  },
  {
    id: "ru_rossio_betesga",
    type: "expression",
    contentPt: "Meter o Rossio na Betesga",
    contentL1: "Впихнуть невпихуемое / Объять необъятное",
    explanation: "Literally: 'To fit the Rossio (Lisbon's grand square) into the Betesga (a tiny alley).' Attempting the impossible. Like Russian 'объять необъятное' (to embrace the unembraceable — from Kozma Prutkov). A purely Lisbon-born proverb from the Middle Ages, still alive today.",
    cefrMin: "B2",
    tags: ["proverb", "lisbon"],
  },
  {
    id: "ru_mar_lugar",
    type: "expression",
    contentPt: "Quem vai ao mar, perde o lugar",
    contentL1: "Кто встал — тот потерял",
    explanation: "Literally: 'Who goes to sea, loses their place.' If you leave, someone takes your spot. Almost identical to Russian 'Кто встал — тот потерял' (Who got up — lost their place). Maritime origin — fishermen lost their tavern seat. Used today for parking, queues, any contested position.",
    cefrMin: "A2",
    tags: ["proverb", "daily-life"],
  },
  // --- DAILY IDIOMS ---
  {
    id: "ru_ora_essa",
    type: "expression",
    contentPt: "Ora essa!",
    contentL1: "Да что вы! / Не за что!",
    explanation: "Exclamation of modest denial when thanked. 'Obrigado pela ajuda!' — 'Ora essa!' (Спасибо за помощь! — Да не за что!). Like Russian 'не за что' or 'да что вы'. Can also express surprise: 'Ora essa, quem diria!' (Ну надо же, кто бы подумал!).",
    cefrMin: "A2",
    tags: ["daily-life", "etiquette"],
  },
  {
    id: "ru_descansado",
    type: "expression",
    contentPt: "Fica descansado / Fica descansada",
    contentL1: "Не переживай / Будь спокоен",
    explanation: "Literally: 'Be rested/at ease.' Means 'don't worry, I've got it.' 'Fica descansado, eu trato disso' (Не переживай, я всё решу). Like Russian 'не переживай' or 'будь спокоен'. Used constantly to reassure.",
    cefrMin: "A2",
    tags: ["daily-life", "conversation"],
  },
  {
    id: "ru_nao_faz_mal",
    type: "expression",
    contentPt: "Não faz mal",
    contentL1: "Ничего страшного / Не беда",
    explanation: "Literally: 'It doesn't do harm.' Standard response when someone apologises for a minor thing. 'Desculpa o atraso!' — 'Não faz mal!' (Извини за опоздание! — Ничего страшного!). Exact equivalent of Russian 'ничего страшного'.",
    cefrMin: "A1",
    tags: ["daily-life", "etiquette"],
  },
  {
    id: "ru_deixa_la",
    type: "expression",
    contentPt: "Deixa lá",
    contentL1: "Забей / Ладно / Неважно",
    explanation: "'Deixa lá' = 'let it go / forget it.' 'Queres que te pague?' — 'Deixa lá!' (Хочешь я заплачу? — Забей!). Can also console: 'Deixa lá, amanhã corre melhor' (Забей, завтра будет лучше). Like Russian 'забей' or 'ладно'.",
    cefrMin: "A1",
    tags: ["daily-life", "conversation"],
  },
  {
    id: "ru_e_o_que_e",
    type: "expression",
    contentPt: "É o que é",
    contentL1: "Что есть, то есть / Так и есть",
    explanation: "'It is what it is' — philosophical acceptance. 'O preço subiu? É o que é.' (Цена выросла? Что есть, то есть.) Spoken with a shrug. Like Russian 'что поделаешь'. Captures Portuguese fatalism alongside resourcefulness.",
    cefrMin: "A2",
    tags: ["daily-life", "culture"],
  },
  {
    id: "ru_olha_la",
    type: "expression",
    contentPt: "Olha lá / Ouve lá",
    contentL1: "Слушай / Эй / Скажи-ка",
    explanation: "'Olha lá' (look here) and 'ouve lá' (listen here) get attention or start a question. 'Olha lá, sabes onde fica o correio?' (Слушай, знаешь где почта?). Like Russian 'слушай' or 'скажи-ка'. Not rude — the standard way to approach someone.",
    cefrMin: "A1",
    tags: ["daily-life", "conversation"],
  },
  {
    id: "ru_entao",
    type: "expression",
    contentPt: "Então?",
    contentL1: "Ну что? / Ну как? / И?",
    explanation: "'Então?' is the universal Portuguese greeting-question. 'Então, tudo bem?' (Ну что, всё нормально?). Also prompts: 'Então, o que queres fazer?' (Ну, что хочешь делать?). Like Russian 'ну что?' or 'ну как?'. Short, warm, multipurpose.",
    cefrMin: "A1",
    tags: ["daily-life", "conversation"],
  },
  {
    id: "ru_se_calhar",
    type: "expression",
    contentPt: "Se calhar",
    contentL1: "Может быть / Наверное / Пожалуй",
    explanation: "Literally: 'if it falls (that way).' Means 'maybe/perhaps.' 'Se calhar vou ao cinema' (Может быть пойду в кино). More common than 'talvez' in everyday PT-EU speech. Like Russian 'может быть' or 'наверное'. Note: unlike 'talvez', this does NOT trigger the subjunctive.",
    cefrMin: "A2",
    tags: ["daily-life", "grammar"],
  },
  {
    id: "ru_com_certeza",
    type: "expression",
    contentPt: "Com certeza",
    contentL1: "Конечно / Разумеется (но осторожно!)",
    explanation: "'Com certeza' means 'certainly'. BUT in PT-EU it is often polite but non-committal — like saying 'конечно' without really meaning it. A Portuguese 'com certeza' can mean 'I'll think about it' (and forget). Russians take 'конечно' more literally. Watch for this cultural trap.",
    cefrMin: "A2",
    tags: ["daily-life", "etiquette"],
  },
];
