import type { L1Profile } from "../types.js";

export const ruProfile: L1Profile = {
  code: "ru",
  name: "Russian",
  nativeName: "Русский",
  writingDirection: "ltr",
  hasLatinScript: false,
  transfer: {
    cognates: [
      "музыка (música — music)",
      "культура (cultura — culture)",
      "проблема (problema — problem)",
      "университет (universidade — university)",
      "документ (documento — document)",
      "группа (grupo — group)",
      "момент (momento — moment)",
      "система (sistema — system)",
      "информация (informação — information)",
      "демократия (democracia — democracy)",
      "энергия (energia — energy)",
      "транспорт (transporte — transport)",
      "телефон (telefone — telephone)",
      "кафе (café — coffee/café)",
      "ресторан (restaurante — restaurant)",
      "театр (teatro — theatre)",
    ],
    falseFriends: [
      { word: "mal", l1Meaning: "маленький (malenky) might suggest 'small'", ptMeaning: "mal means 'badly/evil' — small = pequeno" },
      { word: "massa", l1Meaning: "масса (massa) — mass/bulk in Russian", ptMeaning: "massa means 'dough/pasta' primarily — also 'mass'" },
      { word: "nota", l1Meaning: "нота (nota) — musical note in Russian", ptMeaning: "nota means 'grade/mark' AND 'banknote' as well as musical note" },
      { word: "pasta", l1Meaning: "паста (pasta) — paste/toothpaste in Russian", ptMeaning: "pasta means 'folder/briefcase' — paste = massa" },
      { word: "sala", l1Meaning: "сала (sala) — lard/fatback in Russian", ptMeaning: "sala means 'room/living room'" },
      { word: "lista", l1Meaning: "лист (list) — leaf/sheet of paper in Russian", ptMeaning: "lista means 'list/menu' — leaf = folha" },
      { word: "cama", l1Meaning: "кама — not a common Russian word", ptMeaning: "cama means 'bed'" },
      { word: "campo", l1Meaning: "sounds like компот (kompot) — stewed fruit drink", ptMeaning: "campo means 'field/countryside'" },
      { word: "bar", l1Meaning: "бар (bar) — same meaning in both", ptMeaning: "bar means a drinking establishment — true cognate" },
      { word: "manga", l1Meaning: "манга (manga) — Japanese comics", ptMeaning: "manga primarily means 'sleeve' — also means mango fruit" },
      { word: "prima", l1Meaning: "прима (prima) — prima donna / lead actress", ptMeaning: "prima means 'female cousin' — lead = protagonista" },
      { word: "forma", l1Meaning: "форма (forma) — uniform/shape in Russian", ptMeaning: "forma means 'form/shape/mould' — uniform = farda" },
    ],
    phoneticDifficulties: [
      {
        sound: "ão",
        ipa: "/ɐ̃w̃/",
        description: "Nasal diphthong -ão",
        tip: "Russian has no nasal vowels. Open your mouth for 'a', lower the soft palate to let air through the nose, then glide to a nasal 'u'. This is a moving nasal sound. Practice: pão, mão, não.",
        mouthPosition: "nasal_ao",
      },
      {
        sound: "ã/õ/ẽ",
        ipa: "/ɐ̃/ /õ/ /ẽ/",
        description: "Nasal vowels",
        tip: "Russian never nasalizes vowels (unlike Old Church Slavonic which did). Lower the soft palate while holding the vowel — air must flow through both mouth and nose simultaneously. 'Maçã', 'limão', 'irmã'.",
        mouthPosition: "nasal_vowel",
      },
      {
        sound: "lh",
        ipa: "/ʎ/",
        description: "Palatal lateral lh",
        tip: "Russian has soft ль which is close but not identical. PT-EU 'lh' is a true lateral with the tongue flat against the palate. 'Trabalho' (work), 'filho' (son), 'olho' (eye).",
        mouthPosition: "palatal_lateral",
      },
      {
        sound: "nh",
        ipa: "/ɲ/",
        description: "Palatal nasal nh",
        tip: "Similar to Russian нь (soft n), but produced further back. 'Vinho' (wine), 'amanhã' (tomorrow), 'Espanha' (Spain).",
        mouthPosition: "palatal_nasal",
      },
      {
        sound: "r/rr",
        ipa: "/ʁ/",
        description: "Uvular R (initial and double)",
        tip: "Russian uses a trilled alveolar R (р). PT-EU initial R and double RR are uvular — at the back of the throat. You must NOT trill — think of the French or German R. 'Rato' (mouse), 'carro' (car).",
        mouthPosition: "uvular_r",
      },
      {
        sound: "r (tap)",
        ipa: "/ɾ/",
        description: "Alveolar tap between vowels",
        tip: "Single 'r' between vowels is a quick single flap — lighter than the Russian trilled р. Just one touch of the tongue. 'Caro' (expensive), 'para' (for).",
        mouthPosition: "alveolar_tap",
      },
      {
        sound: "open/closed e",
        ipa: "/ɛ/ vs /e/",
        description: "Two distinct e sounds",
        tip: "Russian reduces vowels (аканье) but doesn't distinguish open/closed e. PT-EU does: 'é' is open (/ɛ/, café), 'ê' is closed (/e/, você). This changes meaning.",
        mouthPosition: "open_e",
      },
      {
        sound: "open/closed o",
        ipa: "/ɔ/ vs /o/",
        description: "Two distinct o sounds",
        tip: "Russian unstressed o becomes a (/ɐ/). PT-EU keeps open ó (/ɔ/) vs closed ô (/o/) distinct: 'avó' (grandmother) vs 'avô' (grandfather). Accent marks guide you.",
        mouthPosition: "open_o",
      },
      {
        sound: "reduced vowels",
        ipa: "/ɨ/ /ə/",
        description: "Unstressed vowels nearly vanish",
        tip: "Good news: Russian also reduces vowels (аканье/иканье). PT-EU goes even further — 'telefonema' sounds like 'tlfnema'. Your instinct for vowel reduction is an advantage.",
      },
      {
        sound: "s/z/ʃ/ʒ",
        ipa: "/s/ /z/ /ʃ/ /ʒ/",
        description: "Four sibilants",
        tip: "Russian has all four (с/з/ш/ж). Good match! PT-EU patterns differ: final 's' = /ʃ/, 's' between vowels = /z/, 'j' = /ʒ/. The sounds are the same — only the spelling rules differ.",
        mouthPosition: "sibilant_s",
      },
      {
        sound: "v/b distinction",
        ipa: "/v/ vs /b/",
        description: "V is labiodental, B is bilabial",
        tip: "Russian also distinguishes в and б perfectly. Apply the same distinction in PT-EU. 'Vela' (candle) vs 'bela' (beautiful).",
        mouthPosition: "labiodental_v",
      },
      {
        sound: "dark L",
        ipa: "/ɫ/",
        description: "Velarized L at end of syllables",
        tip: "Russian has hard л which is very similar. PT-EU final L is dark/velarized: 'Portugal', 'sol' (sun). Your Russian л is an advantage here.",
      },
    ],
    grammarGaps: [
      {
        concept: "Articles (o/a, um/uma)",
        explanation: "Every noun requires a definite or indefinite article",
        l1Comparison: "Russian has no articles at all. This is the single biggest grammar shock: you must always say 'o livro' (the book), 'uma casa' (a house). The article tells you gender and number.",
      },
      {
        concept: "Only 2 genders (no neuter)",
        explanation: "Portuguese has masculine (o) and feminine (a) only",
        l1Comparison: "Russian has masculine, feminine, and neuter (он/она/оно). PT-EU dropped neuter. Gender assignments often differ: 'книга' (f in Russian) → 'o livro' (m in PT).",
      },
      {
        concept: "No case system",
        explanation: "Portuguese uses prepositions and word order instead of cases",
        l1Comparison: "Russian has 6 cases (именительный → предложный). PT-EU has none — prepositions replace them: 'de' for genitive, 'a/para' for dative. Word order matters more.",
      },
      {
        concept: "Ser vs Estar",
        explanation: "Two verbs for 'to be'",
        l1Comparison: "Russian быть is rarely used in present tense ('Я студент'). PT-EU always uses a 'to be' verb, and chooses between two: 'Sou estudante' (ser — identity) vs 'Estou cansado' (estar — state).",
      },
      {
        concept: "Verb conjugation (not aspects)",
        explanation: "Each person has a distinct form; 12+ tenses across 3 moods",
        l1Comparison: "Russian uses 2 aspects (совершенный/несовершенный) × 3 tenses. PT-EU uses 1 aspect × many tenses: pretérito perfeito, imperfeito, mais-que-perfeito, futuro... The tense system replaces what aspects do in Russian.",
      },
      {
        concept: "Subjunctive mood",
        explanation: "Required for doubt, desire, emotion, uncertainty",
        l1Comparison: "Russian сослагательное наклонение (бы + past) is simpler. PT-EU has present, past, and future subjunctive — each with full conjugation: 'Espero que venhas' (present subj.), 'Se eu fosse' (past subj.).",
      },
      {
        concept: "Personal infinitive",
        explanation: "Infinitive conjugated for person — unique to Portuguese",
        l1Comparison: "Doesn't exist in Russian. 'Para nós fazermos' (for us to do) replaces a subordinate clause with чтобы. Once learned, it actually simplifies complex sentences.",
      },
      {
        concept: "Preposition contractions",
        explanation: "Mandatory: em+o=no, de+a=da, a+o=ao, por+o=pelo",
        l1Comparison: "Russian prepositions never contract. PT-EU prepositions merge with articles: 'Estou no café' (em + o = no). You cannot say 'em o' — the contraction is mandatory.",
      },
      {
        concept: "Object pronoun placement",
        explanation: "Before or after the verb depending on triggers",
        l1Comparison: "Russian has relatively free pronoun placement. PT-EU defaults to after the verb ('Dá-me'), moves before with negation ('Não me dás'), and has mesoclisis in future/conditional: 'Dir-lhe-ei'.",
      },
      {
        concept: "Tu vs Você vs O Senhor",
        explanation: "Three formality levels for 'you'",
        l1Comparison: "Russian ты/Вы gives two levels. PT-EU has three: 'tu' (like ты), 'você' (neutral but can be awkward in Portugal), 'o senhor/a senhora' (formal, like Вы). In Portugal, 'tu' is standard among peers.",
      },
      {
        concept: "Continuous with 'estar a + infinitive'",
        explanation: "'Estou a trabalhar' = I am working",
        l1Comparison: "Russian uses imperfective aspect for ongoing actions. PT-EU uses 'estar a + infinitive': 'Estou a ler' (I am reading). The Brazilian form 'estou lendo' uses a gerund — not PT-EU.",
      },
      {
        concept: "Definite article with names",
        explanation: "'A Maria', 'o João' — articles before proper names",
        l1Comparison: "Russian never uses articles with names. PT-EU always does: 'A Maria vem amanhã' (Maria is coming tomorrow). This is standard in spoken Portuguese.",
      },
    ],
    skipBasics: false,
    startingCEFR: "A1",
  },
};
