import type { L1Profile } from "../types.js";

export const ruProfile: L1Profile = {
  code: "ru",
  name: "Russian",
  nativeName: "Русский",
  writingDirection: "ltr",
  hasLatinScript: false,
  transfer: {
    cognates: [
      "музыка (música — music)",
      "культура (cultura — culture)",
      "проблема (problema — problem)",
      "университет (universidade — university)",
      "документ (documento — document)",
      "группа (grupo — group)",
      "момент (momento — moment)",
      "система (sistema — system)",
      "информация (informação — information)",
      "демократия (democracia — democracy)",
      "энергия (energia — energy)",
      "транспорт (transporte — transport)",
      "телефон (telefone — telephone)",
      "кафе (café — coffee/café)",
      "ресторан (restaurante — restaurant)",
      "театр (teatro — theatre)",
    ],
    falseFriends: [
      { word: "mal", l1Meaning: "маленький (malenky) might suggest 'small'", ptMeaning: "mal means 'badly/evil' — small = pequeno" },
      { word: "massa", l1Meaning: "масса (massa) — mass/bulk in Russian", ptMeaning: "massa means 'dough/pasta' primarily — also 'mass'" },
      { word: "nota", l1Meaning: "нота (nota) — musical note in Russian", ptMeaning: "nota means 'grade/mark' AND 'banknote' as well as musical note" },
      { word: "pasta", l1Meaning: "паста (pasta) — paste/toothpaste in Russian", ptMeaning: "pasta means 'folder/briefcase' — paste = massa" },
      { word: "sala", l1Meaning: "сала (sala) — lard/fatback in Russian", ptMeaning: "sala means 'room/living room'" },
      { word: "lista", l1Meaning: "лист (list) — leaf/sheet of paper in Russian", ptMeaning: "lista means 'list/menu' — leaf = folha" },
      { word: "cama", l1Meaning: "кама — not a common Russian word", ptMeaning: "cama means 'bed'" },
      { word: "campo", l1Meaning: "sounds like компот (kompot) — stewed fruit drink", ptMeaning: "campo means 'field/countryside'" },
      { word: "bar", l1Meaning: "бар (bar) — same meaning in both", ptMeaning: "bar means a drinking establishment — true cognate" },
      { word: "manga", l1Meaning: "манга (manga) — Japanese comics", ptMeaning: "manga primarily means 'sleeve' — also means mango fruit" },
      { word: "prima", l1Meaning: "прима (prima) — prima donna / lead actress", ptMeaning: "prima means 'female cousin' — lead = protagonista" },
      { word: "forma", l1Meaning: "форма (forma) — uniform/shape in Russian", ptMeaning: "forma means 'form/shape/mould' — uniform = farda" },
      { word: "comer", l1Meaning: "sounds like комер (komer) — no standard Russian word", ptMeaning: "comer means 'to eat'" },
      { word: "largo", l1Meaning: "sounds like 'largo' in music — broadly", ptMeaning: "largo means 'wide' or 'public square' — broadly = amplamente" },
      { word: "mar", l1Meaning: "мар — no standard meaning", ptMeaning: "mar means 'sea/ocean'" },
      { word: "ser", l1Meaning: "сер — sounds like 'grey' (серый)", ptMeaning: "ser means 'to be' (identity/permanent)" },
      { word: "dom", l1Meaning: "дом (dom) means 'house/home' in Russian", ptMeaning: "dom means 'Mr/Sir' (title) or 'gift/talent' — house = casa" },
      { word: "caro", l1Meaning: "каро — no meaning", ptMeaning: "caro means 'expensive' or 'dear'" },
      { word: "porta", l1Meaning: "порта — no standard meaning (порт = port)", ptMeaning: "porta means 'door' — port = porto" },
      { word: "gato", l1Meaning: "sounds like гад (gad) — 'reptile/vermin'", ptMeaning: "gato means 'cat'" },
      { word: "banco", l1Meaning: "банко — sounds like банк (bank)", ptMeaning: "banco means 'bank' AND 'bench' — both meanings" },
      { word: "cola", l1Meaning: "кола (kola) — cola drink", ptMeaning: "cola means 'glue' — also slang for cheating on a test" },
      { word: "conta", l1Meaning: "конта — no standard Russian word", ptMeaning: "conta means 'bill/account/story'" },
      { word: "data", l1Meaning: "дата (data) — date in both languages", ptMeaning: "data means 'date' — true cognate but in PT also used for computer data" },
      { word: "rua", l1Meaning: "sounds like руа — no standard Russian word", ptMeaning: "rua means 'street' — the most common word you'll see on signs" },
      { word: "mesa", l1Meaning: "sounds like месса (messa) — Catholic mass", ptMeaning: "mesa means 'table' — mass = missa" },
      { word: "fato", l1Meaning: "sounds like факт (fakt) — fact", ptMeaning: "fato means 'suit (clothing)' or 'fact' — suit meaning is more common in daily life" },
      { word: "pé", l1Meaning: "sounds like пе — no meaning", ptMeaning: "pé means 'foot' — 'a pé' = on foot, 'em pé' = standing" },
      { word: "quarto", l1Meaning: "sounds like кварта — a musical interval", ptMeaning: "quarto means 'bedroom' or 'fourth' — bedroom = комната" },
      { word: "vaga", l1Meaning: "sounds like вага — no standard Russian word", ptMeaning: "vaga means 'vacancy' or 'wave' — you'll see it on parking signs and job listings" },
      { word: "praia", l1Meaning: "sounds like прая — no Russian meaning", ptMeaning: "praia means 'beach' — essential for life in Portugal" },
      { word: "loja", l1Meaning: "ложа (lozha) means 'theatre box/lodge' in Russian", ptMeaning: "loja means 'shop/store' — theatre box = camarote" },
      { word: "carta", l1Meaning: "карта (karta) means 'map/card' in Russian", ptMeaning: "carta means 'letter (post)' — map = mapa, card = cartão" },
      { word: "passo", l1Meaning: "sounds like пас (pas) — pass (in football)", ptMeaning: "passo means 'step/pace' — 'passo a passo' = step by step" },
      { word: "morada", l1Meaning: "sounds like мор — no standard meaning", ptMeaning: "morada means 'address (home)' — you'll need this for official forms in Portugal" },
      { word: "ficha", l1Meaning: "фишка (fishka) means 'chip/token' in Russian", ptMeaning: "ficha means 'form/plug/token' — ficha de inscrição = registration form" },
      { word: "cabeça", l1Meaning: "sounds like кабеса — no Russian meaning", ptMeaning: "cabeça means 'head' — 'dor de cabeça' = headache" },
      { word: "roupa", l1Meaning: "sounds like рупа — no Russian meaning", ptMeaning: "roupa means 'clothing/clothes' — 'roupa interior' = underwear" },
      { word: "cozinha", l1Meaning: "sounds like козинак (kozinak) — nut brittle sweet", ptMeaning: "cozinha means 'kitchen' — cozinhar = to cook" },
      { word: "direito", l1Meaning: "sounds like директ — no standard meaning", ptMeaning: "direito means 'right (direction)' AND 'law/right' — 'à direita' = to the right, 'direitos' = rights" },
    ],
    phoneticDifficulties: [
      {
        sound: "ão",
        ipa: "/ɐ̃w̃/",
        description: "Nasal diphthong -ão",
        tip: "Russian has no nasal vowels. Open your mouth for 'a', lower the soft palate to let air through the nose, then glide to a nasal 'u'. This is a moving nasal sound. Practice: pão, mão, não.",
        mouthPosition: "nasal_ao",
      },
      {
        sound: "ã/õ/ẽ",
        ipa: "/ɐ̃/ /õ/ /ẽ/",
        description: "Nasal vowels",
        tip: "Russian never nasalizes vowels (unlike Old Church Slavonic which did). Lower the soft palate while holding the vowel — air must flow through both mouth and nose simultaneously. 'Maçã', 'limão', 'irmã'.",
        mouthPosition: "nasal_vowel",
      },
      {
        sound: "lh",
        ipa: "/ʎ/",
        description: "Palatal lateral lh",
        tip: "Russian has soft ль which is close but not identical. PT-EU 'lh' is a true lateral with the tongue flat against the palate. 'Trabalho' (work), 'filho' (son), 'olho' (eye).",
        mouthPosition: "palatal_lateral",
      },
      {
        sound: "nh",
        ipa: "/ɲ/",
        description: "Palatal nasal nh",
        tip: "Similar to Russian нь (soft n), but produced further back. 'Vinho' (wine), 'amanhã' (tomorrow), 'Espanha' (Spain).",
        mouthPosition: "palatal_nasal",
      },
      {
        sound: "r/rr",
        ipa: "/ʁ/",
        description: "Uvular R (initial and double)",
        tip: "Russian uses a trilled alveolar R (р). PT-EU initial R and double RR are uvular — at the back of the throat. You must NOT trill — think of the French or German R. 'Rato' (mouse), 'carro' (car).",
        mouthPosition: "uvular_r",
      },
      {
        sound: "r (tap)",
        ipa: "/ɾ/",
        description: "Alveolar tap between vowels",
        tip: "Single 'r' between vowels is a quick single flap — lighter than the Russian trilled р. Just one touch of the tongue. 'Caro' (expensive), 'para' (for).",
        mouthPosition: "alveolar_tap",
      },
      {
        sound: "open/closed e",
        ipa: "/ɛ/ vs /e/",
        description: "Two distinct e sounds",
        tip: "Russian reduces vowels (аканье) but doesn't distinguish open/closed e. PT-EU does: 'é' is open (/ɛ/, café), 'ê' is closed (/e/, você). This changes meaning.",
        mouthPosition: "open_e",
      },
      {
        sound: "open/closed o",
        ipa: "/ɔ/ vs /o/",
        description: "Two distinct o sounds",
        tip: "Russian unstressed o becomes a (/ɐ/). PT-EU keeps open ó (/ɔ/) vs closed ô (/o/) distinct: 'avó' (grandmother) vs 'avô' (grandfather). Accent marks guide you.",
        mouthPosition: "open_o",
      },
      {
        sound: "reduced vowels",
        ipa: "/ɨ/ /ə/",
        description: "Unstressed vowels nearly vanish",
        tip: "Good news: Russian also reduces vowels (аканье/иканье). PT-EU goes even further — 'telefonema' sounds like 'tlfnema'. Your instinct for vowel reduction is an advantage.",
      },
      {
        sound: "s/z/ʃ/ʒ",
        ipa: "/s/ /z/ /ʃ/ /ʒ/",
        description: "Four sibilants",
        tip: "Russian has all four (с/з/ш/ж). Good match! PT-EU patterns differ: final 's' = /ʃ/, 's' between vowels = /z/, 'j' = /ʒ/. The sounds are the same — only the spelling rules differ.",
        mouthPosition: "sibilant_s",
      },
      {
        sound: "v/b distinction",
        ipa: "/v/ vs /b/",
        description: "V is labiodental, B is bilabial",
        tip: "Russian also distinguishes в and б perfectly. Apply the same distinction in PT-EU. 'Vela' (candle) vs 'bela' (beautiful).",
        mouthPosition: "labiodental_v",
      },
      {
        sound: "dark L",
        ipa: "/ɫ/",
        description: "Velarized L at end of syllables",
        tip: "Russian has hard л which is very similar. PT-EU final L is dark/velarized: 'Portugal', 'sol' (sun). Your Russian л is an advantage here.",
      },
      {
        sound: "consonant clusters",
        ipa: "/pr/ /tr/ /pl/ /str/",
        description: "Initial consonant clusters",
        tip: "Good news: Russian also has initial clusters (встреча, здравствуй). PT-EU clusters are simpler: 'prato' (plate), 'três' (three), 'construção' (construction). Your experience with Russian clusters is an advantage.",
      },
      {
        sound: "word-final -e",
        ipa: "/ɨ/ or silent",
        description: "Final -e nearly disappears",
        tip: "Russian final -е is always pronounced. PT-EU final -e is barely a whisper or drops entirely. 'Cidade' sounds like 'cidadɨ' or even 'cidad'. This is a major difference from Russian clear endings.",
      },
      {
        sound: "diphthongs",
        ipa: "/ej/ /ow/ /aj/ /oj/",
        description: "Oral diphthongs (ei, ou, ai, oi)",
        tip: "Russian has few true diphthongs. PT-EU has many: 'primeiro' (ei), 'outro' (ou), 'pai' (ai), 'noite' (oi). The two vowels glide into each other in a single syllable — do not separate them.",
      },
    ],
    grammarGaps: [
      {
        concept: "Articles (o/a, um/uma)",
        explanation: "Every noun requires a definite or indefinite article",
        l1Comparison: "Russian has no articles at all. This is the single biggest grammar shock: you must always say 'o livro' (the book), 'uma casa' (a house). The article tells you gender and number.",
      },
      {
        concept: "Only 2 genders (no neuter)",
        explanation: "Portuguese has masculine (o) and feminine (a) only",
        l1Comparison: "Russian has masculine, feminine, and neuter (он/она/оно). PT-EU dropped neuter. Gender assignments often differ: 'книга' (f in Russian) → 'o livro' (m in PT).",
      },
      {
        concept: "No case system",
        explanation: "Portuguese uses prepositions and word order instead of cases",
        l1Comparison: "Russian has 6 cases (именительный → предложный). PT-EU has none — prepositions replace them: 'de' for genitive, 'a/para' for dative. Word order matters more.",
      },
      {
        concept: "Ser vs Estar",
        explanation: "Two verbs for 'to be'",
        l1Comparison: "Russian быть is rarely used in present tense ('Я студент'). PT-EU always uses a 'to be' verb, and chooses between two: 'Sou estudante' (ser — identity) vs 'Estou cansado' (estar — state).",
      },
      {
        concept: "Verb conjugation (not aspects)",
        explanation: "Each person has a distinct form; 12+ tenses across 3 moods",
        l1Comparison: "Russian uses 2 aspects (совершенный/несовершенный) × 3 tenses. PT-EU uses 1 aspect × many tenses: pretérito perfeito, imperfeito, mais-que-perfeito, futuro... The tense system replaces what aspects do in Russian.",
      },
      {
        concept: "Subjunctive mood",
        explanation: "Required for doubt, desire, emotion, uncertainty",
        l1Comparison: "Russian сослагательное наклонение (бы + past) is simpler. PT-EU has present, past, and future subjunctive — each with full conjugation: 'Espero que venhas' (present subj.), 'Se eu fosse' (past subj.).",
      },
      {
        concept: "Personal infinitive",
        explanation: "Infinitive conjugated for person — unique to Portuguese",
        l1Comparison: "Doesn't exist in Russian. 'Para nós fazermos' (for us to do) replaces a subordinate clause with чтобы. Once learned, it actually simplifies complex sentences.",
      },
      {
        concept: "Preposition contractions",
        explanation: "Mandatory: em+o=no, de+a=da, a+o=ao, por+o=pelo",
        l1Comparison: "Russian prepositions never contract. PT-EU prepositions merge with articles: 'Estou no café' (em + o = no). You cannot say 'em o' — the contraction is mandatory.",
      },
      {
        concept: "Object pronoun placement",
        explanation: "Before or after the verb depending on triggers",
        l1Comparison: "Russian has relatively free pronoun placement. PT-EU defaults to after the verb ('Dá-me'), moves before with negation ('Não me dás'), and has mesoclisis in future/conditional: 'Dir-lhe-ei'.",
      },
      {
        concept: "Tu vs Você vs O Senhor",
        explanation: "Three formality levels for 'you'",
        l1Comparison: "Russian ты/Вы gives two levels. PT-EU has three: 'tu' (like ты), 'você' (neutral but can be awkward in Portugal), 'o senhor/a senhora' (formal, like Вы). In Portugal, 'tu' is standard among peers.",
      },
      {
        concept: "Continuous with 'estar a + infinitive'",
        explanation: "'Estou a trabalhar' = I am working",
        l1Comparison: "Russian uses imperfective aspect for ongoing actions. PT-EU uses 'estar a + infinitive': 'Estou a ler' (I am reading). The Brazilian form 'estou lendo' uses a gerund — not PT-EU.",
      },
      {
        concept: "Definite article with names",
        explanation: "'A Maria', 'o João' — articles before proper names",
        l1Comparison: "Russian never uses articles with names. PT-EU always does: 'A Maria vem amanhã' (Maria is coming tomorrow). This is standard in spoken Portuguese.",
      },
      {
        concept: "Reflexive verbs",
        explanation: "Many common verbs require a reflexive pronoun: levantar-se, sentar-se, chamar-se",
        l1Comparison: "Russian has reflexive -ся/-сь verbs (одеваться, садиться). PT-EU reflexives work similarly but the pronoun is separate and moves: 'Chamo-me Ana' (after verb), 'Não me chamo' (before with negation). In Russian -ся is always suffixed.",
      },
      {
        concept: "Definite article with possessives",
        explanation: "'O meu carro' — article + possessive + noun",
        l1Comparison: "Russian has no articles at all: 'моя машина' (my car). PT-EU requires both article AND possessive: 'o meu carro'. Dropping the article ('meu carro') sounds Brazilian. In Portugal always include it.",
      },
      {
        concept: "Haver vs Ter",
        explanation: "'Há' for existence, 'ter' for possession and as perfect auxiliary",
        l1Comparison: "Russian uses 'есть' for existence and 'у меня' for possession. PT-EU splits differently: 'Há muitas pessoas' (there are many people — haver, impersonal) vs 'Tenho um carro' (I have a car — ter). 'Ter' also forms the compound past: 'Tenho feito' (I have been doing).",
      },
    ],
    skipBasics: false,
    startingCEFR: "A1",
  },
};
