import type { CulturalRef } from "../types.js";

export const esCulturalRefs: readonly CulturalRef[] = [
  {
    id: "es_desenrascar",
    type: "expression",
    contentPt: "Desenrascar-se",
    contentL1: "Apañárselas / buscarse la vida",
    explanation: "Like 'apañárselas' but elevated to national identity. Portuguese people are proud of their ability to 'desenrascar' — it's their version of improvisation, and they consider it a defining national trait.",
    cefrMin: "A2",
    tags: ["culture", "daily-life"],
  },
  {
    id: "es_saudade",
    type: "expression",
    contentPt: "Saudade",
    contentL1: "Añoranza / nostalgia (pero no exactamente)",
    explanation: "The famous untranslatable word. 'Añoranza' is close but misses the bittersweet pleasure of longing. Saudade can be for a person, a place, a time, even something you never had. Central to fado, literature, and daily conversation.",
    cefrMin: "B1",
    tags: ["culture", "emotion", "fado"],
  },
  {
    id: "es_portuñol_trap",
    type: "reference",
    contentPt: "Portuñol / Portunhol",
    contentL1: "La mezcla español-portugués",
    explanation: "The biggest trap for Spanish speakers: speaking 'Portuñol' — mixing Spanish grammar with Portuguese words. Portuguese people understand it but find it disrespectful. Commit to Portuguese fully. Key rules: don't add -ción (use -ção), don't use 'yo' (use 'eu'), don't use gerunds for continuous (use 'estar a + infinitivo').",
    cefrMin: "A1",
    tags: ["learning-strategy", "common-mistakes"],
  },
  {
    id: "es_pteu_vs_ptbr",
    type: "reference",
    contentPt: "Português europeu vs brasileiro",
    contentL1: "Las dos grandes variantes del portugués",
    explanation: "Many Spanish speakers learn Brazilian Portuguese first (music, telenovelas). PT-EU is very different: pronunciation swallows vowels (BR pronounces them all), 'tu' is standard (BR uses 'você'), continuous uses 'estar a + infinitivo' (BR uses gerund), vocabulary differs (autocarro vs ônibus, telemóvel vs celular, pequeno-almoço vs café da manhã). Using BR in Portugal is understood but sounds foreign.",
    cefrMin: "A1",
    tags: ["pt-eu-vs-br", "learning-strategy"],
  },
  {
    id: "es_coffee_culture",
    type: "reference",
    contentPt: "Uma bica / um galão / um pingo",
    contentL1: "Un café solo / un café con leche / un cortado",
    explanation: "Portuguese coffee culture is sacred. In Lisbon: 'bica' (espresso), NOT 'café'. In Porto: 'cimbalino'. 'Galão' = large milky coffee in a glass. 'Pingo' = espresso with a drop of milk. 'Meia de leite' = half coffee half milk. Never say 'café con leche' — that's Spanish.",
    cefrMin: "A1",
    tags: ["food", "daily-life", "lisbon", "porto"],
  },
  {
    id: "es_pequeno_almoco",
    type: "reference",
    contentPt: "Pequeno-almoço",
    contentL1: "Desayuno",
    explanation: "Breakfast is 'pequeno-almoço' — literally 'small lunch'. NOT 'desayuno'. Lunch is 'almoço' and dinner is 'jantar'. Meal times are similar to Spain but portions are more modest. A typical pequeno-almoço: coffee, toast (torrada), butter and jam.",
    cefrMin: "A1",
    tags: ["food", "daily-life", "vocabulary"],
  },
  {
    id: "es_fixe_vs_guay",
    type: "expression",
    contentPt: "Fixe!",
    contentL1: "Guay! / Mola!",
    explanation: "The Portuguese 'guay'. 'Isto é muito fixe!' = '¡Esto mola mucho!'. Used constantly by all ages. Not to be confused with 'fixo' (fixed/permanent). Also: 'giro/a' means 'cute/cool' in PT-EU — in Spanish 'giro' only means 'turn'.",
    cefrMin: "A1",
    tags: ["slang", "daily-life"],
  },
  {
    id: "es_bue_fixe",
    type: "expression",
    contentPt: "Bué",
    contentL1: "Muy / un montón / mazo",
    explanation: "Portuguese slang for 'a lot' or 'very'. 'Isto é bué fixe' = 'Esto mola mazo'. Originally from Angolan Portuguese (quimbundo), now universal among young Portuguese. Informal only.",
    cefrMin: "A2",
    tags: ["slang", "daily-life"],
  },
  {
    id: "es_o_pa",
    type: "expression",
    contentPt: "Ó pá!",
    contentL1: "Tío! / Oye! / Macho!",
    explanation: "The Portuguese 'tío'. Used constantly to address friends, express surprise, or emphasize something. 'Ó pá, não acredito!' = 'Tío, no me lo creo!'. Very informal, very Portuguese.",
    cefrMin: "A2",
    tags: ["slang", "daily-life"],
  },
  {
    id: "es_tu_voce",
    type: "reference",
    contentPt: "Tu (informal) vs Você (formal/distante)",
    contentL1: "Tú vs Usted... pero diferente",
    explanation: "In Portugal, 'tu' is standard for everyone you know (like Spanish 'tú'). 'Você' is NOT the default — it's formal/distant and can sound cold or even rude with friends. This confuses Spanish speakers who learned Brazilian Portuguese, where 'você' is the default. In PT-EU: use 'tu' with friends, family, peers. Use 'o senhor / a senhora' (not 'você') for formality.",
    cefrMin: "A2",
    tags: ["grammar", "formality", "pt-eu-vs-br"],
  },
  {
    id: "es_fado_vs_flamenco",
    type: "reference",
    contentPt: "Fado",
    contentL1: "El género musical portugués (no es flamenco)",
    explanation: "Fado is to Portugal what flamenco is to Spain — but the feeling is completely different. Flamenco is passionate and fiery; fado is melancholic and intimate. Born in Lisbon's Alfama neighborhood. Amália Rodrigues is the queen. UNESCO Intangible Cultural Heritage since 2011. Never compare it to flamenco — Portuguese people take this personally.",
    cefrMin: "B1",
    tags: ["culture", "music", "lisbon"],
  },
  {
    id: "es_football_rivalry",
    type: "reference",
    contentPt: "Portugal vs Espanha — a rivalidade ibérica",
    contentL1: "La rivalidad ibérica en fútbol",
    explanation: "Football is the national obsession. Portugal-Spain matches are huge. Know the big three: Benfica (Lisbon), Sporting (Lisbon), Porto. Saying 'Cristiano Ronaldo is Spanish' is the fastest way to offend a Portuguese person. Also: it's 'futebol', not 'fútbol'.",
    cefrMin: "A2",
    tags: ["culture", "sports"],
  },
  {
    id: "es_polvo_trap",
    type: "joke",
    contentPt: "Quero polvo grelhado",
    contentL1: "Quiero pulpo a la parrilla (no polvo!)",
    explanation: "The classic false friend joke. Ordering 'polvo' in Portugal gets you grilled octopus (a delicacy). In Spanish, 'polvo' means 'dust'. Even funnier: in Spanish slang 'echar un polvo' is very vulgar — in Portuguese 'polvo' is completely innocent. Octopus is everywhere in Portuguese cuisine.",
    cefrMin: "A2",
    tags: ["false-friends", "food", "humor"],
  },
  {
    id: "es_bacalhau",
    type: "reference",
    contentPt: "Bacalhau — o fiel amigo",
    contentL1: "El bacalao — pero elevado a religión",
    explanation: "Portugal has 365 bacalhau (cod) recipes — one for each day. It's called 'o fiel amigo' (the faithful friend). Bacalhau à Brás, Bacalhau com natas, Bacalhau à Gomes de Sá. Spain eats cod too, but Portugal's obsession is on another level. Always 'bacalhau', never 'bacalao'.",
    cefrMin: "A2",
    tags: ["food", "culture"],
  },
  {
    id: "es_pastel_nata",
    type: "reference",
    contentPt: "Pastel de nata",
    contentL1: "Tarta de crema portuguesa",
    explanation: "The iconic custard tart. NOT 'pastel de Belém' — that's the trademarked name used only by the original shop in Belém. Everywhere else it's 'pastel de nata'. Plural: 'pastéis de nata'. Eat it warm, sprinkled with cinnamon. The correct way to order: 'Dois pastéis de nata e uma bica, por favor.'",
    cefrMin: "A1",
    tags: ["food", "culture", "lisbon"],
  },
  {
    id: "es_chatear",
    type: "expression",
    contentPt: "Estás a chatear-me!",
    contentL1: "Estás molestándome! (no 'chateando')",
    explanation: "Massive false friend trap. In Spanish, 'chatear' can mean 'to chat online'. In PT-EU, 'chatear' means 'to annoy/bore'. 'Não me chateies!' = 'Don't annoy me!'. 'Chato/a' = boring person. To chat online = conversar, falar.",
    cefrMin: "A2",
    tags: ["false-friends", "daily-life"],
  },
  {
    id: "es_constipacao",
    type: "joke",
    contentPt: "Estou constipado/a",
    contentL1: "Estoy resfriado/a (NO estoy estreñido/a!)",
    explanation: "Another hilarious false friend. 'Constipação' in Portuguese means 'common cold'. NOT constipation. Saying 'estou constipado' at a pharmacy gets you cold medicine, not laxatives. Constipation = obstipação.",
    cefrMin: "A2",
    tags: ["false-friends", "health", "humor"],
  },
  {
    id: "es_estar_nas_tintas",
    type: "expression",
    contentPt: "Estar-se nas tintas",
    contentL1: "Pasarse por el forro / dar igual",
    explanation: "Literally 'to be in the paints'. Means 'to not give a damn'. 'Estou-me nas tintas para isso' = 'Me da completamente igual'. Common, mildly rude. Similar energy to 'me la suda' in Spanish.",
    cefrMin: "B1",
    tags: ["slang", "emotion"],
  },
  {
    id: "es_azulejos",
    type: "reference",
    contentPt: "Azulejos",
    contentL1: "Azulejos — mismo nombre, arte diferente",
    explanation: "Both Spain and Portugal have azulejo traditions, but Portugal elevated it to a national art form. Blue-and-white tile panels cover churches, train stations, and houses. 'Azulejo' comes from Arabic 'al-zulaij'. In PT-EU they're everywhere — in Spain they're mainly in Andalusia.",
    cefrMin: "B1",
    tags: ["culture", "art", "architecture"],
  },
  {
    id: "es_autocarro_comboio",
    type: "reference",
    contentPt: "Autocarro, comboio, elétrico",
    contentL1: "Autobús, tren, tranvía",
    explanation: "Transport vocabulary is different. Bus = autocarro (not autobús). Train = comboio (not tren). Tram = elétrico (not tranvía). Station = estação (same root). The Lisbon tram 28 is iconic. 'Comboio' literally means 'convoy'.",
    cefrMin: "A1",
    tags: ["vocabulary", "transport", "daily-life"],
  },
  {
    id: "es_pois",
    type: "expression",
    contentPt: "Pois...",
    contentL1: "Pues... / Ya... / Bueno...",
    explanation: "The most Portuguese filler word. 'Pois' can mean 'yes', 'well', 'indeed', 'exactly', or just fill silence. 'Pois é' = 'That's how it is'. 'Pois pois' = 'Yeah yeah' (agreement). 'Pois...' with trailing tone = 'Well...' (doubt). Master 'pois' and you sound Portuguese.",
    cefrMin: "A2",
    tags: ["expression", "daily-life", "filler"],
  },
  {
    id: "es_humor",
    type: "reference",
    contentPt: "O humor português — seco e autoirónico",
    contentL1: "El humor portugués — seco y autoirónico",
    explanation: "Portuguese humor is dry, self-deprecating, and deadpan — very different from Spanish humor which tends to be louder and more physical. Portuguese people joke about their own country being small, poor, or overlooked. 'Portugal é como um filho mais novo da Europa' (Portugal is like Europe's youngest child). Understanding this irony is key to fitting in.",
    cefrMin: "B2",
    tags: ["culture", "humor", "social"],
  },
  {
    id: "es_telemóvel",
    type: "reference",
    contentPt: "Telemóvel",
    contentL1: "Móvil / celular",
    explanation: "Mobile phone = telemóvel (NOT 'móvil' or 'celular'). Computer = computador (NOT 'ordenador' or 'computadora'). Mouse = rato (same word as 'mouse the animal'). Screen = ecrã (NOT 'pantalla'). Password = palavra-passe. Tech vocabulary is almost entirely different from Spanish.",
    cefrMin: "A1",
    tags: ["vocabulary", "technology"],
  },
  {
    id: "es_tasca",
    type: "reference",
    contentPt: "A tasca / o tasco",
    contentL1: "El bar de barrio / la taberna",
    explanation: "A tasca is a traditional no-frills Portuguese restaurant/bar. Cheap, generous portions, handwritten menus, football on TV, the owner knows everyone. Like a Spanish 'tasca' or 'taberna' but with bacalhau and bifanas. 'Vamos à tasca?' is the Portuguese equivalent of 'Vamos de cañas?'.",
    cefrMin: "A2",
    tags: ["food", "daily-life", "culture"],
  },
  {
    id: "es_bifana",
    type: "reference",
    contentPt: "Bifana",
    contentL1: "Bocadillo de cerdo (pero diferente)",
    explanation: "Portugal's answer to the bocadillo. Thin pork steak marinated in garlic and white wine, served in a bread roll (papo-seco). Best eaten at a tasca or feira. Also try: francesinha (Porto's calorie bomb — a sandwich covered in melted cheese and spicy sauce).",
    cefrMin: "A2",
    tags: ["food", "culture"],
  },
  // --- ARGOT MODERNO ---
  {
    id: "es_cena",
    type: "expression",
    contentPt: "Cena",
    contentL1: "Rollo / movida / cosa",
    explanation: "El comodín de los jóvenes portugueses. Literalmente 'escena', pero se usa para todo: 'Aquela cena' = 'ese rollo'. 'É uma cena estranha' = 'Es una movida rara'. 'Que cena!' = 'Vaya movida'. Funciona exactamente como 'rollo' o 'movida' en español cuando no encuentras la palabra justa. Ojo: 'cena' = 'escena/cosa', NO 'cena' (dinner = jantar).",
    cefrMin: "A2",
    tags: ["slang", "daily-life"],
  },
  {
    id: "es_tipo",
    type: "expression",
    contentPt: "Tipo...",
    contentL1: "O sea... / como que...",
    explanation: "Se usa exactamente como el 'o sea' español: muletilla de relleno. 'Ele era tipo... estranho' = 'Él era o sea... raro'. También = 'un tío' ('aquele tipo' = 'ese tipo'). Los jóvenes portugueses meten 'tipo' en cada frase, como los españoles con 'o sea'. Misma irritación generacional en ambos países.",
    cefrMin: "A2",
    tags: ["slang", "conversation"],
  },
  {
    id: "es_ganda",
    type: "expression",
    contentPt: "Ganda!",
    contentL1: "Vaya! / Menudo! / Pedazo de!",
    explanation: "Contracción de 'grande'. Intensificador coloquial. 'Ganda festa!' = 'Menuda fiesta!'. 'Ganda maluco' = 'Pedazo de loco' (cariñoso). Positivo ('ganda golo!' — pedazo de gol) o negativo ('ganda confusão' — menudo lío). Muy lisboeta. Similar a 'menudo/a' en español.",
    cefrMin: "B1",
    tags: ["slang", "daily-life"],
  },
  {
    id: "es_bazar_slang",
    type: "expression",
    contentPt: "Bazar",
    contentL1: "Pirarse / largarse",
    explanation: "Argot para 'irse'. 'Vou bazar' = 'Me voy a pirar'. Del persa/árabe a través del romaní. En español, 'pirarse' o 'largarse' tienen el mismo registro: muy informal, entre amigos. También: 'pirar-se' (pirarse), 'ir à vida' (irse a hacer puñetas).",
    cefrMin: "B1",
    tags: ["slang"],
  },
  {
    id: "es_curtir",
    type: "expression",
    contentPt: "Curtir",
    contentL1: "Molar / flipar / enrollarse con",
    explanation: "'Curto muito isso' = 'Eso me mola mucho'. 'Curtir a vida' = 'disfrutar de la vida'. Ojo: 'curtir com alguém' = 'enrollarse con alguien'. El contexto distingue. En español 'curtir' solo significa 'curtir cuero' — cuidado con este falso amigo.",
    cefrMin: "A2",
    tags: ["slang", "daily-life", "false-friends"],
  },
  {
    id: "es_na_boa",
    type: "expression",
    contentPt: "Na boa",
    contentL1: "Tranqui / sin problema / guay",
    explanation: "'Na boa' es el 'tranqui' portugués. '¿Puedo llegar tarde?' — 'Na boa.' Muy común, totalmente casual. También adjetivo: 'Ele é na boa' = 'Es tranquilo/buen rollo'. Misma energía que 'tranqui' o 'sin problema' en español.",
    cefrMin: "A2",
    tags: ["slang", "daily-life"],
  },
  {
    id: "es_mano",
    type: "expression",
    contentPt: "Mano / Mana",
    contentL1: "Hermano / Tronco / Colega",
    explanation: "De 'irmão/irmã'. Se usa como 'tronco' o 'hermano' en español. 'Eh mano, tudo bem?' = 'Eh hermano, ¿qué tal?'. 'Mana' es la versión femenina. Menos común que 'pá' pero más cercano. OJO: en portugués 'mano' no es 'mano' (mão) — trampa de portuñol.",
    cefrMin: "A2",
    tags: ["slang", "daily-life", "false-friends"],
  },
  {
    id: "es_ta_se_bem",
    type: "expression",
    contentPt: "Tá-se bem",
    contentL1: "Todo bien / va bien / tranqui",
    explanation: "Contracción de 'está-se bem'. Forma relajada de decir que todo va bien. '¿Qué tal?' — 'Tá-se bem'. 'Tá-se' solo = 'OK, vale'. Muy oral, nunca escrito. El equivalente del '¿qué tal? — bien' español.",
    cefrMin: "A2",
    tags: ["slang", "conversation"],
  },
  {
    id: "es_mandar_vir",
    type: "expression",
    contentPt: "Mandar vir",
    contentL1: "Quejarse / pedir (depende del contexto)",
    explanation: "Doble significado traicionero. 'Ele está sempre a mandar vir' = 'Siempre está quejándose'. PERO en un restaurante, 'Manda vir umas sardinhas' = 'Pide unas sardinas'. El contexto decide. También: 'mandar bocas' = lanzar pullitas / hacer comentarios.",
    cefrMin: "B1",
    tags: ["slang", "daily-life"],
  },
  {
    id: "es_chavalos",
    type: "expression",
    contentPt: "Chavalos / Putos",
    contentL1: "Chavales / Crios",
    explanation: "'Os chavalos' y 'os putos' = 'los chavales'. IMPORTANTÍSIMO: 'puto/a' NO es un insulto en Portugal (al contrario que en español). Una madre diciendo 'os meus putos' habla de sus hijos. 'O puto é esperto' = 'El chaval es listo'. Este falso amigo ha causado más malentendidos que cualquier otro entre españoles y portugueses.",
    cefrMin: "B1",
    tags: ["slang", "false-friends"],
  },
  {
    id: "es_granda_maluco",
    type: "expression",
    contentPt: "Granda maluco!",
    contentL1: "Pedazo de loco! / Qué bestia!",
    explanation: "Expresión cariñosa-admirativa. 'Granda maluco!' se usa cuando alguien hace algo atrevido o genial, no cuando está realmente loco. En español: 'Pedazo de loco, cómo hiciste eso!'. 'Maluco' en PT-EU es más suave que 'loco' en español — puede ser cumplido.",
    cefrMin: "B1",
    tags: ["slang", "daily-life"],
  },
  // --- PROVERBIOS ANTIGUOS ---
  {
    id: "es_quem_nao_tem_cao",
    type: "expression",
    contentPt: "Quem não tem cão, caça com gato",
    contentL1: "A falta de pan, buenas son tortas",
    explanation: "Literalmente: 'Quien no tiene perro, caza con gato'. Proverbio ancestral que resume el 'desenrascanço' — arreglarse con lo que hay. El español tiene 'A falta de pan, buenas son tortas'. El portugués tiene una imagen más vivida. Se usa todos los días.",
    cefrMin: "B1",
    tags: ["proverb", "culture"],
  },
  {
    id: "es_agua_mole",
    type: "expression",
    contentPt: "Água mole em pedra dura, tanto bate até que fura",
    contentL1: "Gota a gota se llena la bota / La gota horada la piedra",
    explanation: "Literalmente: 'Agua blanda en piedra dura, tanto golpea que la perfora'. Sobre persistencia. Idéntico al español 'La gota horada la piedra'. Ambos vienen del latín 'gutta cavat lapidem'. Los dos idiomas conservaron el mismo proverbio latino — prueba de raíces compartidas.",
    cefrMin: "B1",
    tags: ["proverb", "culture"],
  },
  {
    id: "es_fazer_tripas_coracao",
    type: "expression",
    contentPt: "Fazer das tripas coração",
    contentL1: "Echarle huevos / hacer de tripas corazón",
    explanation: "Literalmente: 'Hacer corazón con las tripas'. El español tiene exactamente la misma expresión: 'hacer de tripas corazón'. Misma imagen, mismo significado (sacar coraje de donde no hay). Porto es la 'cidade das tripas' — la leyenda dice que dieron toda la buena carne a los exploradores y se quedaron con las vísceras.",
    cefrMin: "B1",
    tags: ["proverb", "culture", "porto"],
  },
  {
    id: "es_ficar_ver_navios",
    type: "expression",
    contentPt: "Ficar a ver navios",
    contentL1: "Quedarse con un palmo de narices / quedarse plantado",
    explanation: "Literalmente: 'Quedarse mirando barcos'. De la era de los Descubrimientos — familias mirando el horizonte esperando barcos que nunca volvieron. Ahora: quedarse plantado, con las manos vacías. 'Me invitaron pero me quedé mirando barcos'. Imagen marítima con 500 años de melancolía.",
    cefrMin: "B2",
    tags: ["proverb", "history", "emotion"],
  },
  {
    id: "es_grao_a_grao",
    type: "expression",
    contentPt: "Grão a grão, enche a galinha o papo",
    contentL1: "Grano a grano, llena la gallina el buche",
    explanation: "Literalmente idéntico: 'Grano a grano, la gallina llena el buche'. Los pequeños esfuerzos se acumulan. El español lo traduce casi palabra por palabra. Uno de esos proverbios que demuestran cuán cerca están el portugués y el español — y a la vez cuán diferente es la pronunciación.",
    cefrMin: "B1",
    tags: ["proverb", "culture"],
  },
  {
    id: "es_meter_rossio_betesga",
    type: "expression",
    contentPt: "Meter o Rossio na Betesga",
    contentL1: "Intentar meter un océano en un vaso",
    explanation: "Literalmente: 'Meter el Rossio en la Betesga'. El Rossio es la gran plaza central de Lisboa; la Betesga era un callejón estrecho. Intentar meter uno en el otro es absurdo — equivale a 'meter el mar en un dedal'. Sin equivalente exacto en español, porque es referencia geográfica lisboeta medieval.",
    cefrMin: "B2",
    tags: ["proverb", "lisbon", "history"],
  },
  {
    id: "es_engolir_sapos",
    type: "expression",
    contentPt: "Engolir sapos",
    contentL1: "Tragar sapos / tragarse los insultos",
    explanation: "Literalmente: 'Tragar sapos'. Aguantar insultos sin responder. El español tiene 'tragar sapos' o 'tragar bilis'. Misma imagen, misma rana. 'Tuve que tragar muchos sapos en ese trabajo'. Uno de esos momentos en que el portugués y español son casi idénticos.",
    cefrMin: "B1",
    tags: ["proverb", "emotion"],
  },
  {
    id: "es_quem_vai_ao_mar",
    type: "expression",
    contentPt: "Quem vai ao mar, perde o lugar",
    contentL1: "Quien fue a Sevilla, perdió su silla",
    explanation: "Literalmente: 'Quien va al mar, pierde su sitio'. El español tiene 'Quien fue a Sevilla, perdió su silla'. Mismo concepto, diferente referencia geográfica: los portugueses dicen 'el mar' (siempre el mar), los españoles dicen 'Sevilla'. Si te vas, alguien toma tu puesto.",
    cefrMin: "A2",
    tags: ["proverb", "daily-life"],
  },
  // --- EXPRESIONES COTIDIANAS ---
  {
    id: "es_nao_faz_mal",
    type: "expression",
    contentPt: "Não faz mal",
    contentL1: "No pasa nada / no importa",
    explanation: "Literalmente: 'No hace mal'. La respuesta estándar cuando alguien se disculpa. 'Perdona, llegué tarde' — 'Não faz mal'. Más cálido que 'no hay problema', como 'no pasa nada' en español. Se escucha decenas de veces al día en Portugal.",
    cefrMin: "A1",
    tags: ["daily-life", "conversation"],
  },
  {
    id: "es_deixa_la",
    type: "expression",
    contentPt: "Deixa lá",
    contentL1: "Déjalo / no te preocupes / da igual",
    explanation: "Literalmente: 'Déjalo ahí'. Para tranquilizar ('Deixa lá, não faz mal' = 'Déjalo, no pasa nada') o para esquivar un tema ('Deixa lá, não interessa' = 'Déjalo, da igual'). El tono lo decide todo. Esencial en la conversación portuguesa.",
    cefrMin: "A1",
    tags: ["daily-life", "conversation"],
  },
  {
    id: "es_e_o_que_e",
    type: "expression",
    contentPt: "É o que é",
    contentL1: "Es lo que es / Así son las cosas",
    explanation: "Encogimiento de hombros filosófico. 'El tráfico de Lisboa es horrible.' — 'É o que é.' Aceptación resignada. Conectado al concepto de 'fado' (destino). El español 'es lo que es' es idéntico — otra prueba de la cercanía entre las dos lenguas. Pero ojo: en PT-EU se pronuncia /ɛ u kɛ ɛ/, no como en español.",
    cefrMin: "A2",
    tags: ["daily-life", "conversation", "culture"],
  },
  {
    id: "es_entao",
    type: "expression",
    contentPt: "Então?",
    contentL1: "Entonces? / Qué hay? / Y bueno?",
    explanation: "'Então?' es un saludo completo en Portugal. Dos amigos se encuentran: 'Então, tudo bem?' = '¿Qué hay, todo bien?'. Para empujar: 'Então? Te decidiste?'. Sorpresa: 'Então?! Qué pasó?'. La entonación lo cambia todo. OJO: 'então' suena parecido a 'entonces' pero funciona más como '¿y qué?' en español informal.",
    cefrMin: "A1",
    tags: ["daily-life", "conversation"],
  },
  {
    id: "es_se_calhar",
    type: "expression",
    contentPt: "Se calhar",
    contentL1: "A lo mejor / igual / puede que",
    explanation: "'Se calhar' es el 'a lo mejor' del día a día en PT-EU. Más natural que 'talvez' hablando. 'Se calhar vou amanhã' = 'A lo mejor voy mañana'. Literalmente 'si se da el caso'. Usar 'se calhar' en vez de 'talvez' te hace sonar fluido — los manuales enseñan 'talvez' pero la gente dice 'se calhar'.",
    cefrMin: "A2",
    tags: ["daily-life", "conversation"],
  },
  {
    id: "es_ora_essa",
    type: "expression",
    contentPt: "Ora essa!",
    contentL1: "Faltaría más! / Hombre, claro!",
    explanation: "Un enfático 'faltaría más!' o 'de nada!'. '¡Gracias por la ayuda!' — 'Ora essa!' (¡Faltaría más!). También expresa indignación suave. Anticuado pero vivo. La hospitalidad portuguesa concentrada en dos palabras. El español 'faltaría más' captura exactamente el espíritu.",
    cefrMin: "A2",
    tags: ["daily-life", "etiquette"],
  },
  {
    id: "es_olha_la",
    type: "expression",
    contentPt: "Olha lá...",
    contentL1: "Oye... / Mira... / A ver...",
    explanation: "Literalmente 'mira allí' pero funciona como 'oye' o 'mira' para captar la atención. 'Olha lá, ¿puedo preguntarte algo?' Puede ser confrontacional: 'Olha lá, ¿quién te crees que eres?'. Mismo doble filo que 'mira' en español — cariñoso o agresivo según el tono.",
    cefrMin: "A2",
    tags: ["daily-life", "conversation"],
  },
];
