import type { CulturalRef } from "../types.js";

export const esCulturalRefs: readonly CulturalRef[] = [
  {
    id: "es_desenrascar",
    type: "expression",
    contentPt: "Desenrascar-se",
    contentL1: "Apañárselas / buscarse la vida",
    explanation: "Like 'apañárselas' but elevated to national identity. Portuguese people are proud of their ability to 'desenrascar' — it's their version of improvisation, and they consider it a defining national trait.",
    cefrMin: "A2",
    tags: ["culture", "daily-life"],
  },
  {
    id: "es_saudade",
    type: "expression",
    contentPt: "Saudade",
    contentL1: "Añoranza / nostalgia (pero no exactamente)",
    explanation: "The famous untranslatable word. 'Añoranza' is close but misses the bittersweet pleasure of longing. Saudade can be for a person, a place, a time, even something you never had. Central to fado, literature, and daily conversation.",
    cefrMin: "B1",
    tags: ["culture", "emotion", "fado"],
  },
  {
    id: "es_portuñol_trap",
    type: "reference",
    contentPt: "Portuñol / Portunhol",
    contentL1: "La mezcla español-portugués",
    explanation: "The biggest trap for Spanish speakers: speaking 'Portuñol' — mixing Spanish grammar with Portuguese words. Portuguese people understand it but find it disrespectful. Commit to Portuguese fully. Key rules: don't add -ción (use -ção), don't use 'yo' (use 'eu'), don't use gerunds for continuous (use 'estar a + infinitivo').",
    cefrMin: "A1",
    tags: ["learning-strategy", "common-mistakes"],
  },
  {
    id: "es_pteu_vs_ptbr",
    type: "reference",
    contentPt: "Português europeu vs brasileiro",
    contentL1: "Las dos grandes variantes del portugués",
    explanation: "Many Spanish speakers learn Brazilian Portuguese first (music, telenovelas). PT-EU is very different: pronunciation swallows vowels (BR pronounces them all), 'tu' is standard (BR uses 'você'), continuous uses 'estar a + infinitivo' (BR uses gerund), vocabulary differs (autocarro vs ônibus, telemóvel vs celular, pequeno-almoço vs café da manhã). Using BR in Portugal is understood but sounds foreign.",
    cefrMin: "A1",
    tags: ["pt-eu-vs-br", "learning-strategy"],
  },
  {
    id: "es_coffee_culture",
    type: "reference",
    contentPt: "Uma bica / um galão / um pingo",
    contentL1: "Un café solo / un café con leche / un cortado",
    explanation: "Portuguese coffee culture is sacred. In Lisbon: 'bica' (espresso), NOT 'café'. In Porto: 'cimbalino'. 'Galão' = large milky coffee in a glass. 'Pingo' = espresso with a drop of milk. 'Meia de leite' = half coffee half milk. Never say 'café con leche' — that's Spanish.",
    cefrMin: "A1",
    tags: ["food", "daily-life", "lisbon", "porto"],
  },
  {
    id: "es_pequeno_almoco",
    type: "reference",
    contentPt: "Pequeno-almoço",
    contentL1: "Desayuno",
    explanation: "Breakfast is 'pequeno-almoço' — literally 'small lunch'. NOT 'desayuno'. Lunch is 'almoço' and dinner is 'jantar'. Meal times are similar to Spain but portions are more modest. A typical pequeno-almoço: coffee, toast (torrada), butter and jam.",
    cefrMin: "A1",
    tags: ["food", "daily-life", "vocabulary"],
  },
  {
    id: "es_fixe_vs_guay",
    type: "expression",
    contentPt: "Fixe!",
    contentL1: "Guay! / Mola!",
    explanation: "The Portuguese 'guay'. 'Isto é muito fixe!' = '¡Esto mola mucho!'. Used constantly by all ages. Not to be confused with 'fixo' (fixed/permanent). Also: 'giro/a' means 'cute/cool' in PT-EU — in Spanish 'giro' only means 'turn'.",
    cefrMin: "A1",
    tags: ["slang", "daily-life"],
  },
  {
    id: "es_bue_fixe",
    type: "expression",
    contentPt: "Bué",
    contentL1: "Muy / un montón / mazo",
    explanation: "Portuguese slang for 'a lot' or 'very'. 'Isto é bué fixe' = 'Esto mola mazo'. Originally from Angolan Portuguese (quimbundo), now universal among young Portuguese. Informal only.",
    cefrMin: "A2",
    tags: ["slang", "daily-life"],
  },
  {
    id: "es_o_pa",
    type: "expression",
    contentPt: "Ó pá!",
    contentL1: "Tío! / Oye! / Macho!",
    explanation: "The Portuguese 'tío'. Used constantly to address friends, express surprise, or emphasize something. 'Ó pá, não acredito!' = 'Tío, no me lo creo!'. Very informal, very Portuguese.",
    cefrMin: "A2",
    tags: ["slang", "daily-life"],
  },
  {
    id: "es_tu_voce",
    type: "reference",
    contentPt: "Tu (informal) vs Você (formal/distante)",
    contentL1: "Tú vs Usted... pero diferente",
    explanation: "In Portugal, 'tu' is standard for everyone you know (like Spanish 'tú'). 'Você' is NOT the default — it's formal/distant and can sound cold or even rude with friends. This confuses Spanish speakers who learned Brazilian Portuguese, where 'você' is the default. In PT-EU: use 'tu' with friends, family, peers. Use 'o senhor / a senhora' (not 'você') for formality.",
    cefrMin: "A2",
    tags: ["grammar", "formality", "pt-eu-vs-br"],
  },
  {
    id: "es_fado_vs_flamenco",
    type: "reference",
    contentPt: "Fado",
    contentL1: "El género musical portugués (no es flamenco)",
    explanation: "Fado is to Portugal what flamenco is to Spain — but the feeling is completely different. Flamenco is passionate and fiery; fado is melancholic and intimate. Born in Lisbon's Alfama neighborhood. Amália Rodrigues is the queen. UNESCO Intangible Cultural Heritage since 2011. Never compare it to flamenco — Portuguese people take this personally.",
    cefrMin: "B1",
    tags: ["culture", "music", "lisbon"],
  },
  {
    id: "es_football_rivalry",
    type: "reference",
    contentPt: "Portugal vs Espanha — a rivalidade ibérica",
    contentL1: "La rivalidad ibérica en fútbol",
    explanation: "Football is the national obsession. Portugal-Spain matches are huge. Know the big three: Benfica (Lisbon), Sporting (Lisbon), Porto. Saying 'Cristiano Ronaldo is Spanish' is the fastest way to offend a Portuguese person. Also: it's 'futebol', not 'fútbol'.",
    cefrMin: "A2",
    tags: ["culture", "sports"],
  },
  {
    id: "es_polvo_trap",
    type: "joke",
    contentPt: "Quero polvo grelhado",
    contentL1: "Quiero pulpo a la parrilla (no polvo!)",
    explanation: "The classic false friend joke. Ordering 'polvo' in Portugal gets you grilled octopus (a delicacy). In Spanish, 'polvo' means 'dust'. Even funnier: in Spanish slang 'echar un polvo' is very vulgar — in Portuguese 'polvo' is completely innocent. Octopus is everywhere in Portuguese cuisine.",
    cefrMin: "A2",
    tags: ["false-friends", "food", "humor"],
  },
  {
    id: "es_bacalhau",
    type: "reference",
    contentPt: "Bacalhau — o fiel amigo",
    contentL1: "El bacalao — pero elevado a religión",
    explanation: "Portugal has 365 bacalhau (cod) recipes — one for each day. It's called 'o fiel amigo' (the faithful friend). Bacalhau à Brás, Bacalhau com natas, Bacalhau à Gomes de Sá. Spain eats cod too, but Portugal's obsession is on another level. Always 'bacalhau', never 'bacalao'.",
    cefrMin: "A2",
    tags: ["food", "culture"],
  },
  {
    id: "es_pastel_nata",
    type: "reference",
    contentPt: "Pastel de nata",
    contentL1: "Tarta de crema portuguesa",
    explanation: "The iconic custard tart. NOT 'pastel de Belém' — that's the trademarked name used only by the original shop in Belém. Everywhere else it's 'pastel de nata'. Plural: 'pastéis de nata'. Eat it warm, sprinkled with cinnamon. The correct way to order: 'Dois pastéis de nata e uma bica, por favor.'",
    cefrMin: "A1",
    tags: ["food", "culture", "lisbon"],
  },
  {
    id: "es_chatear",
    type: "expression",
    contentPt: "Estás a chatear-me!",
    contentL1: "Estás molestándome! (no 'chateando')",
    explanation: "Massive false friend trap. In Spanish, 'chatear' can mean 'to chat online'. In PT-EU, 'chatear' means 'to annoy/bore'. 'Não me chateies!' = 'Don't annoy me!'. 'Chato/a' = boring person. To chat online = conversar, falar.",
    cefrMin: "A2",
    tags: ["false-friends", "daily-life"],
  },
  {
    id: "es_constipacao",
    type: "joke",
    contentPt: "Estou constipado/a",
    contentL1: "Estoy resfriado/a (NO estoy estreñido/a!)",
    explanation: "Another hilarious false friend. 'Constipação' in Portuguese means 'common cold'. NOT constipation. Saying 'estou constipado' at a pharmacy gets you cold medicine, not laxatives. Constipation = obstipação.",
    cefrMin: "A2",
    tags: ["false-friends", "health", "humor"],
  },
  {
    id: "es_estar_nas_tintas",
    type: "expression",
    contentPt: "Estar-se nas tintas",
    contentL1: "Pasarse por el forro / dar igual",
    explanation: "Literally 'to be in the paints'. Means 'to not give a damn'. 'Estou-me nas tintas para isso' = 'Me da completamente igual'. Common, mildly rude. Similar energy to 'me la suda' in Spanish.",
    cefrMin: "B1",
    tags: ["slang", "emotion"],
  },
  {
    id: "es_azulejos",
    type: "reference",
    contentPt: "Azulejos",
    contentL1: "Azulejos — mismo nombre, arte diferente",
    explanation: "Both Spain and Portugal have azulejo traditions, but Portugal elevated it to a national art form. Blue-and-white tile panels cover churches, train stations, and houses. 'Azulejo' comes from Arabic 'al-zulaij'. In PT-EU they're everywhere — in Spain they're mainly in Andalusia.",
    cefrMin: "B1",
    tags: ["culture", "art", "architecture"],
  },
  {
    id: "es_autocarro_comboio",
    type: "reference",
    contentPt: "Autocarro, comboio, eléctrico",
    contentL1: "Autobús, tren, tranvía",
    explanation: "Transport vocabulary is different. Bus = autocarro (not autobús). Train = comboio (not tren). Tram = eléctrico (not tranvía). Station = estação (same root). The Lisbon tram 28 is iconic. 'Comboio' literally means 'convoy'.",
    cefrMin: "A1",
    tags: ["vocabulary", "transport", "daily-life"],
  },
  {
    id: "es_pois",
    type: "expression",
    contentPt: "Pois...",
    contentL1: "Pues... / Ya... / Bueno...",
    explanation: "The most Portuguese filler word. 'Pois' can mean 'yes', 'well', 'indeed', 'exactly', or just fill silence. 'Pois é' = 'That's how it is'. 'Pois pois' = 'Yeah yeah' (agreement). 'Pois...' with trailing tone = 'Well...' (doubt). Master 'pois' and you sound Portuguese.",
    cefrMin: "A2",
    tags: ["expression", "daily-life", "filler"],
  },
  {
    id: "es_humor",
    type: "reference",
    contentPt: "O humor português — seco e autoirónico",
    contentL1: "El humor portugués — seco y autoirónico",
    explanation: "Portuguese humor is dry, self-deprecating, and deadpan — very different from Spanish humor which tends to be louder and more physical. Portuguese people joke about their own country being small, poor, or overlooked. 'Portugal é como um filho mais novo da Europa' (Portugal is like Europe's youngest child). Understanding this irony is key to fitting in.",
    cefrMin: "B2",
    tags: ["culture", "humor", "social"],
  },
  {
    id: "es_telemóvel",
    type: "reference",
    contentPt: "Telemóvel",
    contentL1: "Móvil / celular",
    explanation: "Mobile phone = telemóvel (NOT 'móvil' or 'celular'). Computer = computador (NOT 'ordenador' or 'computadora'). Mouse = rato (same word as 'mouse the animal'). Screen = ecrã (NOT 'pantalla'). Password = palavra-passe. Tech vocabulary is almost entirely different from Spanish.",
    cefrMin: "A1",
    tags: ["vocabulary", "technology"],
  },
  {
    id: "es_tasca",
    type: "reference",
    contentPt: "A tasca / o tasco",
    contentL1: "El bar de barrio / la taberna",
    explanation: "A tasca is a traditional no-frills Portuguese restaurant/bar. Cheap, generous portions, handwritten menus, football on TV, the owner knows everyone. Like a Spanish 'tasca' or 'taberna' but with bacalhau and bifanas. 'Vamos à tasca?' is the Portuguese equivalent of 'Vamos de cañas?'.",
    cefrMin: "A2",
    tags: ["food", "daily-life", "culture"],
  },
  {
    id: "es_bifana",
    type: "reference",
    contentPt: "Bifana",
    contentL1: "Bocadillo de cerdo (pero diferente)",
    explanation: "Portugal's answer to the bocadillo. Thin pork steak marinated in garlic and white wine, served in a bread roll (papo-seco). Best eaten at a tasca or feira. Also try: francesinha (Porto's calorie bomb — a sandwich covered in melted cheese and spicy sauce).",
    cefrMin: "A2",
    tags: ["food", "culture"],
  },
];
