import type { L1Profile } from "../types.js";

export const esProfile: L1Profile = {
  code: "es",
  name: "Spanish",
  nativeName: "Español",
  writingDirection: "ltr",
  hasLatinScript: true,
  transfer: {
    cognates: [
      "familia", "importante", "diferente", "momento", "problema",
      "forma", "parte", "punto", "ejemplo", "gobierno",
      "trabajo", "primero", "ciudad", "historia", "general",
      "verdad", "necesario", "palabra", "nacional", "música",
      "cultura", "natural", "futuro", "probable", "estudante",
      "universidade", "hospital", "animal", "possível", "estrutura",
    ],
    falseFriends: [
      { word: "oficina", l1Meaning: "office (despacho)", ptMeaning: "oficina means 'workshop' or 'garage' (office = escritório)" },
      { word: "polvo", l1Meaning: "dust / powder", ptMeaning: "polvo means 'octopus' (dust = pó)" },
      { word: "largo", l1Meaning: "long", ptMeaning: "largo means 'wide' (long = comprido)" },
      { word: "borracha", l1Meaning: "drunk woman", ptMeaning: "borracha means 'rubber / eraser' (drunk = bêbada)" },
      { word: "salsa", l1Meaning: "sauce", ptMeaning: "salsa means 'parsley' (sauce = molho)" },
      { word: "exquisito", l1Meaning: "exquisite / delicious", ptMeaning: "esquisito means 'weird / strange' (delicious = delicioso)" },
      { word: "propina", l1Meaning: "tip / gratuity", ptMeaning: "propina means 'tuition fee' (tip = gorjeta)" },
      { word: "vaso", l1Meaning: "drinking glass", ptMeaning: "vaso means 'flowerpot / vase' (glass = copo)" },
      { word: "rato", l1Meaning: "a while / moment", ptMeaning: "rato means 'mouse' (a while = um bocado)" },
      { word: "cola", l1Meaning: "glue / tail", ptMeaning: "cola means 'glue' but also 'cheat sheet' (tail = cauda / rabo)" },
      { word: "acordar", l1Meaning: "to agree / to remember", ptMeaning: "acordar means 'to wake up' (to agree = concordar)" },
      { word: "cena", l1Meaning: "dinner", ptMeaning: "cena means 'scene' (dinner = jantar)" },
      { word: "tienda", l1Meaning: "shop / store", ptMeaning: "tenda means 'tent' (shop = loja)" },
      { word: "suceso", l1Meaning: "event / happening", ptMeaning: "sucesso means 'success' (event = acontecimento)" },
      { word: "ropa", l1Meaning: "clothes", ptMeaning: "roupa means 'clothes' too — but 'ropa' doesn't exist in PT" },
      { word: "carro", l1Meaning: "car", ptMeaning: "carro means 'car' too — same! But 'coche' doesn't exist in PT" },
      { word: "ligar", l1Meaning: "to tie / to link", ptMeaning: "ligar means 'to call (phone)' or 'to care about' (não ligo = I don't care)" },
      { word: "apagar", l1Meaning: "to turn off / extinguish", ptMeaning: "apagar means the same, but also 'to erase / delete'" },
      { word: "contestar", l1Meaning: "to answer / reply", ptMeaning: "contestar means 'to contest / dispute' (to answer = responder)" },
      { word: "grifo", l1Meaning: "faucet / tap (in some regions)", ptMeaning: "grifo doesn't exist — tap = torneira" },
      { word: "mala", l1Meaning: "bad (feminine)", ptMeaning: "mala means 'suitcase' (bad = má)" },
      { word: "pasta", l1Meaning: "paste / pasta", ptMeaning: "pasta means 'folder / briefcase' (paste = massa)" },
      { word: "pronto", l1Meaning: "soon / quickly", ptMeaning: "pronto means 'ready / done' (soon = em breve)" },
      { word: "pipa", l1Meaning: "pipe (smoking)", ptMeaning: "pipa means 'kite' or 'barrel' (pipe = cachimbo)" },
      { word: "talher", l1Meaning: "(no Spanish cognate)", ptMeaning: "talher means 'cutlery' — Spanish speakers often guess 'taller' (workshop)" },
      { word: "esperto", l1Meaning: "(no direct cognate)", ptMeaning: "esperto means 'clever / smart' — NOT 'expert' (expert = especialista / perito)" },
      { word: "embaraçada", l1Meaning: "embarrassed (sounds like embarazada)", ptMeaning: "embaraçada means 'embarrassed' — NOT 'pregnant' (pregnant = grávida)" },
      { word: "pelado", l1Meaning: "peeled / bald", ptMeaning: "pelado means 'naked / nude' (bald = careca)" },
      { word: "esquisito", l1Meaning: "(sounds like exquisito)", ptMeaning: "esquisito means 'weird / strange' — never 'delicious'" },
      { word: "presunto", l1Meaning: "(sounds like presunto = alleged)", ptMeaning: "presunto means 'cured ham' (alleged = presumido / suposto)" },
      { word: "janela", l1Meaning: "(no Spanish cognate)", ptMeaning: "janela means 'window' — Spanish uses 'ventana'" },
      { word: "cão", l1Meaning: "(no Spanish cognate)", ptMeaning: "cão means 'dog' — Spanish uses 'perro' (cão is archaic in Spanish)" },
      { word: "fraco", l1Meaning: "(sounds like flaco = thin)", ptMeaning: "fraco means 'weak' — NOT 'thin' (thin = magro)" },
      { word: "nojo", l1Meaning: "(no Spanish cognate)", ptMeaning: "nojo means 'disgust' — don't confuse with 'enojo' (anger)" },
      { word: "doido", l1Meaning: "(no Spanish cognate)", ptMeaning: "doido means 'crazy / mad' — informal, very common in PT-EU" },
      { word: "giro", l1Meaning: "turn / spin", ptMeaning: "giro means 'cute / cool' in PT-EU (turn = volta)" },
      { word: "constipação", l1Meaning: "(sounds like constipación)", ptMeaning: "constipação means 'common cold' — NOT constipation (constipation = obstipação)" },
      { word: "pegar", l1Meaning: "to stick / to hit", ptMeaning: "pegar means 'to grab / to catch' (to stick = colar, to hit = bater)" },
      { word: "tinto", l1Meaning: "red (wine)", ptMeaning: "tinto means 'red (wine)' — same! But 'café tinto' in Colombia = black coffee, NOT in PT" },
      { word: "chatear", l1Meaning: "to chat (informal)", ptMeaning: "chatear means 'to annoy / to bore' (to chat = conversar)" },
    ],
    phoneticDifficulties: [
      {
        sound: "b/v",
        ipa: "/b/ vs /v/",
        description: "Distinct b and v",
        tip: "Unlike Spanish, PT-EU always distinguishes b (bilabial stop) from v (labiodental fricative). 'Bola' and 'vola' are different. Bite your lower lip for v.",
      },
      {
        sound: "ão",
        ipa: "/ɐ̃w̃/",
        description: "Nasal diphthong -ão",
        tip: "Spanish has no nasal vowels. Start with an open 'a', nasalize it, then glide to a nasal 'u'. Pão, mão, não — practice these three daily.",
      },
      {
        sound: "õe",
        ipa: "/õj̃/",
        description: "Nasal diphthong -ões",
        tip: "The plural of -ão words. Nasalize an 'o' and glide to a nasal 'i'. Corações, limões, aviões.",
      },
      {
        sound: "ã/ã",
        ipa: "/ɐ̃/",
        description: "Nasal vowel ã",
        tip: "Let air through your nose while saying 'a'. maçã, irmã, manhã. Spanish has nothing like this.",
      },
      {
        sound: "reduced vowels",
        ipa: "/ɨ/ /ə/",
        description: "Unstressed vowels nearly vanish",
        tip: "PT-EU swallows unstressed vowels — 'telefonema' sounds like 'tlfnema'. Spanish pronounces every vowel clearly; PT-EU does not. This is the biggest rhythm difference.",
      },
      {
        sound: "open/closed e",
        ipa: "/ɛ/ vs /e/",
        description: "Two e sounds",
        tip: "PT-EU distinguishes open 'é' (/ɛ/ as in 'café') from closed 'ê' (/e/ as in 'você'). Spanish has only one 'e'. This changes word meaning: 'avó' (grandmother) vs 'avô' (grandfather).",
      },
      {
        sound: "open/closed o",
        ipa: "/ɔ/ vs /o/",
        description: "Two o sounds",
        tip: "Open 'ó' (/ɔ/ as in 'avó') vs closed 'ô' (/o/ as in 'avô'). The accent mark tells you which. Spanish has only one 'o'.",
      },
      {
        sound: "s/z/ç",
        ipa: "/s/ /z/ /ʃ/ /ʒ/",
        description: "Sibilant system",
        tip: "PT-EU has 4 sibilants where Spanish has 1-2. 's' between vowels = /z/ (casa = /kaza/). Final 's' = /ʃ/ (as in English 'sh'). 'ç' = /s/. Before voiced consonants 's' = /ʒ/.",
      },
      {
        sound: "final -l",
        ipa: "/ɫ/",
        description: "Dark L at end of syllables",
        tip: "PT-EU final 'l' is very dark/velarized, almost like a 'w' in some dialects. 'Portugal' has a thick final L, not the light Spanish 'l'.",
      },
      {
        sound: "r/rr",
        ipa: "/ɾ/ vs /ʁ/",
        description: "Two R sounds",
        tip: "Single 'r' between vowels = tap /ɾ/ (like Spanish). Initial 'r' and 'rr' = uvular /ʁ/ (French-like, back of throat). NOT the Spanish trilled rr.",
      },
      {
        sound: "lh",
        ipa: "/ʎ/",
        description: "Palatal lateral lh",
        tip: "Like the old Castilian 'll' before yeísmo. Tongue on the palate. 'Trabalho', 'filho', 'olho'. Keep the lateral quality — don't turn it into 'y'.",
      },
      {
        sound: "nh",
        ipa: "/ɲ/",
        description: "Palatal nasal nh",
        tip: "Equivalent to Spanish 'ñ'. Written 'nh' in PT. 'Espanha' = 'España'. Same sound, different spelling.",
      },
      {
        sound: "b/v distinction",
        ipa: "/b/ vs /v/",
        description: "B and V are different sounds",
        tip: "Spanish merges b/v into one sound. PT-EU keeps them distinct: 'bola' (ball) has a bilabial /b/, 'vela' (candle) has a labiodental /v/ with lip-teeth contact. Practice: 'beber' vs 'viver'.",
      },
      {
        sound: "word-final -e",
        ipa: "/ɨ/ or silent",
        description: "Final -e is nearly silent",
        tip: "Spanish pronounces final 'e' clearly. PT-EU reduces it to a barely audible /ɨ/ or drops it entirely. 'Cidade' sounds like 'cidadɨ' or 'cidad'. This is why PT-EU sounds 'Slavic' to Spanish ears.",
      },
      {
        sound: "nasal diphthongs -ões/-ães",
        ipa: "/õj̃ʃ/ /ɐ̃j̃ʃ/",
        description: "Complex nasal diphthongs in plurals",
        tip: "Spanish plurals are simple (-es). PT-EU nasalizes AND diphthongizes: 'coração' → 'corações' /kuɾɐsõj̃ʃ/. The -ões ending has no Spanish parallel. Practice: limão → limões, pão → pães.",
      },
    ],
    grammarGaps: [
      {
        concept: "Personal infinitive",
        explanation: "Infinitive conjugated for person: falar, falares, falar, falarmos, falardes, falarem",
        l1Comparison: "Doesn't exist in Spanish — unique to Portuguese. Used after prepositions and in subordinate clauses: 'Para eles entenderem' (for them to understand).",
      },
      {
        concept: "Continuous tenses",
        explanation: "'Estar a + infinitive' for ongoing actions",
        l1Comparison: "Spanish uses gerund (estoy haciendo). PT-EU uses 'estou a fazer'. The gerund form ('estou fazendo') is Brazilian, not European.",
      },
      {
        concept: "Haver vs Ter",
        explanation: "'Ter' is both 'to have' and the past auxiliary",
        l1Comparison: "Spanish splits: 'tener' (possession) vs 'haber' (auxiliary). PT-EU uses 'ter' for both: 'Eu tenho feito' (I have done).",
      },
      {
        concept: "Object pronoun placement",
        explanation: "Complex enclisis/proclisis rules differ from Spanish",
        l1Comparison: "Spanish puts pronouns before conjugated verbs (lo hago). PT-EU defaults to after (faço-o) unless a trigger word (não, que, etc.) forces proclisis.",
      },
      {
        concept: "Mesoclisis",
        explanation: "Pronoun inserted inside future/conditional verb forms",
        l1Comparison: "Spanish has nothing like this. 'Dir-lhe-ei' = I will tell him/her. The pronoun splits the verb. Formal/literary but tested at B2+.",
      },
      {
        concept: "Future subjunctive",
        explanation: "Actively used in PT-EU for future uncertain events",
        l1Comparison: "Spanish has it but it's dead (only in legal/literary text). PT-EU uses it daily: 'Quando eu for' (when I go), 'Se quiseres' (if you want).",
      },
      {
        concept: "Pretérito perfeito simples vs composto",
        explanation: "Simple past = completed action; compound past = repeated/ongoing past",
        l1Comparison: "In Spanish, 'he comido' (compound) = recent past. In PT-EU, 'tenho comido' = I have been eating (repeatedly). 'Comi' = I ate (once). Different semantic split.",
      },
      {
        concept: "Por vs Para",
        explanation: "Similar to Spanish but not identical usage",
        l1Comparison: "PT-EU 'por' absorbs some uses that Spanish gives to 'para'. 'Obrigado por vir' vs 'Gracias por venir'. Most transfers work, but exceptions exist.",
      },
      {
        concept: "Preposition 'em'",
        explanation: "Used where Spanish uses 'en', but contracts with articles",
        l1Comparison: "'Em' contracts: em + o = no, em + a = na, em + um = num. Spanish 'en' never contracts. 'Estou no café' (I'm at the café).",
      },
      {
        concept: "Definite article with possessives",
        explanation: "PT-EU uses article + possessive: 'o meu carro'",
        l1Comparison: "Spanish drops the article: 'mi coche'. PT-EU keeps it: 'o meu carro'. Omitting it sounds Brazilian or archaic.",
      },
      {
        concept: "Contractions ao/do/no/pelo",
        explanation: "Mandatory contractions of prepositions with articles",
        l1Comparison: "Spanish has 'al' (a + el) and 'del' (de + el). PT-EU has many more: ao, do, no, pelo, na, da, numa, duma, etc.",
      },
      {
        concept: "Diminutives: -inho vs -ito",
        explanation: "Portuguese uses -inho/-inha as the main diminutive",
        l1Comparison: "Spanish uses -ito/-ita. PT-EU uses -inho/-inha: 'cafezinho', 'pouquinho'. -ito exists in PT but is rare.",
      },
      {
        concept: "Tu vs Você",
        explanation: "PT-EU uses 'tu' as the default informal pronoun",
        l1Comparison: "In Portugal, 'tu' is standard informal (like Spanish 'tú'). 'Você' is formal/distant, almost rude in some regions. In Brazil it's the opposite. This confuses Spanish speakers who learned Brazilian Portuguese.",
      },
      {
        concept: "Infinitive vs subjunctive after prepositions",
        explanation: "PT-EU often uses infinitive where Spanish uses subjunctive",
        l1Comparison: "'Antes de eu sair' (before I leave) — PT uses personal infinitive. Spanish would use subjunctive: 'antes de que yo salga'. This simplifies things once you learn it.",
      },
      {
        concept: "Definite article with names",
        explanation: "PT-EU uses articles before proper names: 'a Maria', 'o João'",
        l1Comparison: "Standard Spanish doesn't: 'María viene'. PT-EU: 'A Maria vem'. Some Spanish dialects do this too, but it's universal in PT-EU.",
      },
    ],
    skipBasics: true,
    startingCEFR: "A2",
  },
};
