import type { CulturalRef } from "../types.js";

export const bnCulturalRefs: readonly CulturalRef[] = [
  {
    id: "bn_portuguese_bengal",
    type: "reference",
    contentPt: "Os portugueses em Bengala",
    contentL1: "বাংলায় পর্তুগিজরা — ৫০০ বছরের ইতিহাস",
    explanation: "The Portuguese established trading posts in Bengal in the early 1500s. Hooghly (Ugolim) and Bandel were major Portuguese settlements. The Bandel Church (1599) still stands. This 500-year connection left dozens of Portuguese loanwords in Bengali that you use every day without knowing their origin.",
    cefrMin: "A2",
    tags: ["history", "culture"],
  },
  {
    id: "bn_loanwords",
    type: "reference",
    contentPt: "Palavras portuguesas no bengali",
    contentL1: "বাংলায় পর্তুগিজ শব্দ — জানালা, চাবি, বালতি, আলমারি",
    explanation: "Bengali has borrowed many everyday words from Portuguese: janela/জানালা (window), chave/চাবি (key), balde/বালতি (bucket), armário/আলমারি (wardrobe), mesa/মেজ (table), camisa/কামিজ (shirt), sabão/সাবান (soap), toalha/তোয়ালে (towel). You already speak some Portuguese!",
    cefrMin: "A1",
    tags: ["vocabulary", "history", "language"],
  },
  {
    id: "bn_cha_tea",
    type: "reference",
    contentPt: "Chá — a ligação mais antiga",
    contentL1: "চা — সবচেয়ে পুরোনো সংযোগ",
    explanation: "The Portuguese word 'chá' and Bengali 'চা' share the same Chinese root. Portuguese traders brought tea to Europe via their Asian trade routes. When you order 'um chá' in Portugal, you're speaking the same word you use at home.",
    cefrMin: "A1",
    tags: ["food", "daily-life", "history"],
  },
  {
    id: "bn_saudade",
    type: "expression",
    contentPt: "Saudade",
    contentL1: "গভীর বিরহ ও মনকেমন — কোনো সরাসরি অনুবাদ নেই",
    explanation: "The untranslatable Portuguese word for deep, bittersweet longing. Bengali has 'mon-kemon' (মনকেমন) — that restless, melancholic feeling. Saudade is similar but deeper: it's longing for something you love, mixed with the sweetness of having known it. Rabindranath's poems capture this feeling too.",
    cefrMin: "B1",
    tags: ["culture", "emotion"],
  },
  {
    id: "bn_fixe",
    type: "expression",
    contentPt: "Fixe!",
    contentL1: "দারুণ! / মারাত্মক!",
    explanation: "The Portuguese slang for 'cool/awesome'. Used constantly in informal speech. 'O filme foi fixe!' (The movie was cool!). Think of it like Bengali 'darun' or 'jhakkas'.",
    cefrMin: "A1",
    tags: ["slang", "daily-life"],
  },
  {
    id: "bn_desenrascar",
    type: "expression",
    contentPt: "Desenrascar-se",
    contentL1: "জোগাড় করা — সমস্যার সমাধান বের করা",
    explanation: "The quintessential Portuguese concept of improvising a solution. Very similar to Bengali 'jogaar' (জোগাড়) — finding a creative way out when resources are limited. Both cultures value this resourcefulness as a point of national pride.",
    cefrMin: "A2",
    tags: ["culture", "daily-life"],
  },
  {
    id: "bn_football",
    type: "reference",
    contentPt: "O futebol em Portugal",
    contentL1: "পর্তুগালে ফুটবল — ক্রিকেটের মতো আবেগ",
    explanation: "What cricket is to Bangladesh, football is to Portugal. The three big clubs — Benfica, Sporting, Porto — divide families and friendships. Everyone has an opinion. Cristiano Ronaldo is a national hero. Match days transform the country.",
    cefrMin: "A1",
    tags: ["culture", "sport"],
  },
  {
    id: "bn_family",
    type: "reference",
    contentPt: "A família portuguesa",
    contentL1: "পর্তুগিজ পরিবার — বাংলার মতোই",
    explanation: "Portuguese family values closely mirror Bengali ones: deep respect for elders, multi-generational households are common, Sunday lunch with the extended family is sacred, and children often live at home until marriage. Food is the center of family life in both cultures.",
    cefrMin: "A2",
    tags: ["culture", "family", "social"],
  },
  {
    id: "bn_rice_culture",
    type: "reference",
    contentPt: "Arroz — a base da comida",
    contentL1: "ভাত — দুই সংস্কৃতির মিল",
    explanation: "Like Bengali cuisine, Portuguese cooking revolves around rice. 'Arroz de...' (rice with...) is a huge category: arroz de pato (duck rice), arroz de marisco (seafood rice), arroz de tomate. The Portuguese also eat rice at almost every meal, just like Bengalis eat bhaat.",
    cefrMin: "A1",
    tags: ["food", "culture"],
  },
  {
    id: "bn_sweets",
    type: "reference",
    contentPt: "Doces portugueses — ovos e açúcar",
    contentL1: "পর্তুগিজ মিষ্টি — ডিম আর চিনি",
    explanation: "Portugal has a massive sweet tooth, like Bengal. 'Doces conventuais' (convent sweets) use egg yolks and sugar — similar richness to Bengali mishti (sweets). Try pastéis de nata, ovos moles, and toucinho do céu. The Portuguese sweet tradition influenced desserts across Asia, including Bengal.",
    cefrMin: "A2",
    tags: ["food", "culture"],
  },
  {
    id: "bn_bica_cafe",
    type: "reference",
    contentPt: "Uma bica / um galão",
    contentL1: "এসপ্রেসো / দুধ কফি",
    explanation: "In Lisbon, espresso is 'uma bica', in Porto 'um cimbalino'. A 'galão' is a large milky coffee in a tall glass. Portuguese coffee is strong espresso, quite different from the milk tea (cha) that dominates in Bengal. But both cultures revolve around their hot drink of choice.",
    cefrMin: "A1",
    tags: ["food", "daily-life"],
  },
  {
    id: "bn_pois",
    type: "expression",
    contentPt: "Pois...",
    contentL1: "আচ্ছা... / হুম... / তাই...",
    explanation: "The most versatile Portuguese word. 'Pois' can mean 'yeah', 'well', 'indeed', 'right' — depending entirely on intonation. Like Bengali 'achcha' — it fills gaps, acknowledges, agrees, or politely dismisses. Mastering 'pois' is a fluency milestone.",
    cefrMin: "A1",
    tags: ["conversation", "daily-life"],
  },
  {
    id: "bn_fado",
    type: "reference",
    contentPt: "Fado — a alma da música portuguesa",
    contentL1: "ফাদো — পর্তুগিজ সংগীতের আত্মা",
    explanation: "Portugal's soul music — melancholic songs about fate, saudade, longing, and the sea. If you love Rabindra Sangeet (Tagore's songs) for its emotional depth, fado will resonate with you. Both traditions value the singer's ability to convey raw emotion. UNESCO Intangible Heritage since 2011.",
    cefrMin: "A2",
    tags: ["music", "culture"],
  },
  {
    id: "bn_tu_voce",
    type: "reference",
    contentPt: "Tu vs Você vs O Senhor",
    contentL1: "তুই/তুমি/আপনি — সম্মানের স্তর",
    explanation: "Like Bengali's তুই/তুমি/আপনি (tui/tumi/apni) levels, Portuguese has formality tiers: 'tu' (informal, like tumi), 'você' (semi-formal, sometimes awkward), 'o senhor/a senhora' (formal, like apni). Start formal with older people, let them invite you to use 'tu'. Bengali speakers have an advantage understanding this system.",
    cefrMin: "A1",
    tags: ["social", "grammar", "etiquette"],
  },
  {
    id: "bn_pasteis_nata",
    type: "reference",
    contentPt: "Pastéis de nata",
    contentL1: "পাস্তেইশ দে নাতা — পর্তুগালের সবচেয়ে বিখ্যাত মিষ্টি",
    explanation: "Portugal's most famous pastry — a flaky crust filled with egg custard, baked until caramelized. Eat warm, sprinkled with cinnamon and powdered sugar. Found in every pastelaria. The original secret recipe comes from the Jerónimos monastery in Belém. If you love mishti doi's richness, you'll love these.",
    cefrMin: "A1",
    tags: ["food", "culture"],
  },
  {
    id: "bn_estar_a_fazer",
    type: "expression",
    contentPt: "Estou a fazer (not estou fazendo)",
    contentL1: "আমি করছি — ইউরোপীয় পর্তুগিজ রীতি",
    explanation: "European Portuguese uses 'estar a + infinitive' for ongoing actions: 'Estou a comer' (I am eating). Brazilian Portuguese uses the gerund: 'Estou comendo'. This is the most noticeable PT-EU vs PT-BR difference and marks you as a European Portuguese learner.",
    cefrMin: "A1",
    tags: ["grammar", "pt-eu-vs-br"],
  },
  {
    id: "bn_colonialism_shared",
    type: "reference",
    contentPt: "Histórias coloniais cruzadas",
    contentL1: "ঔপনিবেশিক ইতিহাসের মিল",
    explanation: "Both Bengal and Portugal have complex colonial histories. Portugal was a colonizer in Asia (Goa, Macau, Timor, Bengal trading posts) while also being on Europe's periphery. This creates interesting conversations about identity, language, and cultural exchange. Approach with nuance — there's shared history, not shared perspectives.",
    cefrMin: "B2",
    tags: ["history", "culture", "identity"],
  },
  {
    id: "bn_nas_tintas",
    type: "expression",
    contentPt: "Estar-se nas tintas",
    contentL1: "আমার কিছু আসে যায় না",
    explanation: "Literally 'to be in the paints'. Means you couldn't care less. 'Estou-me nas tintas para isso' (I don't give a damn about that). Very common, mildly rude. Similar to Bengali 'amar kichu ashe jay na'.",
    cefrMin: "B1",
    tags: ["slang", "emotion"],
  },
  {
    id: "bn_santos_populares",
    type: "reference",
    contentPt: "Festas dos Santos Populares",
    contentL1: "সান্তোশ পপুলারেশ — জুন মাসের রাস্তার উৎসব",
    explanation: "Every June, Portugal erupts in street festivals. Santo António (Lisbon, June 13) features parades, grilled sardines, and dancing. São João (Porto, June 24) involves hitting strangers on the head with plastic hammers. The community energy, street food, and open celebrations will remind you of Durga Puja's pandal-hopping atmosphere.",
    cefrMin: "A2",
    tags: ["culture", "festivals"],
  },
  {
    id: "bn_25_abril",
    type: "reference",
    contentPt: "25 de Abril — Revolução dos Cravos",
    contentL1: "২৫শে এপ্রিল — কার্নেশন বিপ্লব (১৯৭৪)",
    explanation: "On April 25, 1974, Portugal peacefully overthrew its 41-year dictatorship. Soldiers put red carnations in their rifle barrels. Like Bangladesh's Liberation War (1971), this is a defining moment of national identity. The date is a national holiday, the main bridge in Lisbon bears its name, and the revolutionary song 'Grândola, Vila Morena' still moves people to tears.",
    cefrMin: "B1",
    tags: ["history", "culture", "identity"],
  },
  {
    id: "bn_lisbon_porto",
    type: "reference",
    contentPt: "Lisboa vs Porto",
    contentL1: "লিসবন বনাম পোর্তো — ঢাকা বনাম চট্টগ্রামের মতো",
    explanation: "Lisbon and Porto have a friendly rivalry like Dhaka and Chittagong. Lisbon (lisboetas) is the cosmopolitan capital; Porto (tripeiros, 'tripe-eaters') is proudly industrial and independent-minded. They have different words for espresso (bica vs cimbalino), different food traditions, and fierce football rivalries (Benfica/Sporting vs FC Porto).",
    cefrMin: "B1",
    tags: ["culture", "cities"],
  },
  {
    id: "bn_bacalhau",
    type: "reference",
    contentPt: "Bacalhau — o prato nacional",
    contentL1: "বাকালহাউ — পর্তুগালের জাতীয় খাবার (শুটকি মাছের মতো)",
    explanation: "Bacalhau (salt cod) is Portugal's national dish — they claim 365 recipes, one for each day. It's dried, salted cod that must be soaked before cooking. Bengal has its own dried fish tradition (shutki maach). The concept of preserving fish with salt connects the two cuisines, though the flavors differ completely.",
    cefrMin: "A2",
    tags: ["food", "culture"],
  },
  {
    id: "bn_pronto",
    type: "expression",
    contentPt: "Pronto!",
    contentL1: "হয়ে গেছে! / চলো! / ব্যাস!",
    explanation: "'Pronto' is everywhere in Portuguese conversation. It means 'done!', 'ready!', 'OK then!'. Used to wrap up a thought ('Pronto, vamos!' — OK, let's go) or signal completion ('Pronto, acabei!' — Done, finished!). Like Bengali 'hoyegeche' or 'byash'. Mastering 'pronto' makes you sound natural instantly.",
    cefrMin: "A1",
    tags: ["conversation", "daily-life"],
  },
  {
    id: "bn_autocarro",
    type: "reference",
    contentPt: "Autocarro / comboio / telemóvel",
    contentL1: "বাস / ট্রেন / মোবাইল (ইউরোপীয় পর্তুগিজ শব্দ)",
    explanation: "PT-EU and PT-BR use different everyday words. Bus: autocarro (PT-EU) vs ônibus (PT-BR). Train: comboio vs trem. Mobile phone: telemóvel vs celular. Breakfast: pequeno-almoço vs café da manhã. Bathroom: casa de banho vs banheiro. If you learned any Portuguese from Brazilian sources, be aware of these differences.",
    cefrMin: "A1",
    tags: ["vocabulary", "pt-eu-vs-br"],
  },
  {
    id: "bn_hospitality",
    type: "expression",
    contentPt: "Fique à vontade",
    contentL1: "স্বচ্ছন্দে থাকুন / নিজের বাড়ি মনে করুন",
    explanation: "'Fique à vontade' means 'make yourself comfortable' — the Portuguese version of 'nijer baari mone korun'. Portuguese hospitality is warm and genuine. Guests are always offered food and drink; refusing feels rude. Bengali speakers will find this familiar. A Portuguese home always has food ready for unexpected visitors.",
    cefrMin: "A2",
    tags: ["culture", "hospitality", "daily-life"],
  },
  {
    id: "bn_bue",
    type: "expression",
    contentPt: "Bué",
    contentL1: "অনেক / খুব — bué = অনেক বেশি",
    explanation: "'Bué' means 'a lot' or 'very' in PT-EU slang. 'Bué fixe' (really cool), 'bué caro' (really expensive). From Kimbundu (Angolan language). Used constantly by young Portuguese. Like Bengali 'onek' or 'khub' — a universal intensifier. 'Há bué gente aqui' (There are loads of people here).",
    cefrMin: "A2",
    tags: ["slang", "daily-life"],
  },
  {
    id: "bn_cena",
    type: "expression",
    contentPt: "Cena",
    contentL1: "জিনিস / ব্যাপার — cena = that thing",
    explanation: "Originally means 'scene' but in slang it means 'thing', 'stuff', 'situation'. 'Que cena!' (What a scene!), 'é uma cena' (it's a thing/issue). Like Bengali 'jinish' or 'byapar' used vaguely. When a Portuguese person says 'tenho uma cena para te contar', it could be gossip, news, or literally anything.",
    cefrMin: "A2",
    tags: ["slang", "daily-life"],
  },
  {
    id: "bn_tipo",
    type: "expression",
    contentPt: "Tipo...",
    contentL1: "মানে... / যেমন... — tipo = like..., you know...",
    explanation: "'Tipo' is the PT-EU filler word, exactly like English 'like' or Bengali 'mane' / 'jemon'. 'Ele é tipo estranho' (He's like weird), 'tipo, não sei' (like, I don't know). Young Portuguese use it constantly. If you pepper your speech with 'tipo', you will sound authentically Portuguese.",
    cefrMin: "A2",
    tags: ["slang", "conversation"],
  },
  {
    id: "bn_ganda",
    type: "expression",
    contentPt: "Ganda!",
    contentL1: "দারুণ! / ঝাক্কাস! — ganda = massive, amazing",
    explanation: "'Ganda' (or 'granda') means 'great', 'massive', 'amazing' in Lisbon slang. 'Ganda jogo!' (Great match!), 'ganda maluco!' (you legend!). Raw, emphatic street-level praise. Like Bengali 'darun' or 'jhakkas' — enthusiastic, not polite, but deeply genuine.",
    cefrMin: "B1",
    tags: ["slang", "emotion"],
  },
  {
    id: "bn_bazar",
    type: "expression",
    contentPt: "Bazar!",
    contentL1: "চলে যাওয়া / পালানো — bazar = to leave fast",
    explanation: "'Bazar' in PT-EU slang means 'to leave', 'to bounce'. 'Vou bazar' (I'm out), 'ele bazou' (he bolted). From Romani, nothing to do with a marketplace. Like Bengali 'chole jaoa' or 'palano'. Informal, used among friends when you're heading out.",
    cefrMin: "B1",
    tags: ["slang", "daily-life"],
  },
  {
    id: "bn_curtir",
    type: "expression",
    contentPt: "Curtir",
    contentL1: "মজা করা / উপভোগ করা — curtir = to enjoy",
    explanation: "'Curtir' means 'to enjoy', 'to have fun'. 'Vamos curtir!' (Let's enjoy!), 'curto bué isso' (I really like that). Also slang for 'making out'. Like Bengali 'moja kora' or 'upobhog kora'. One of the most versatile and common slang verbs in young Portuguese speech.",
    cefrMin: "A2",
    tags: ["slang", "daily-life"],
  },
  {
    id: "bn_na_boa",
    type: "expression",
    contentPt: "Na boa",
    contentL1: "ঠিক আছে / কোনো সমস্যা নেই — na boa = all good",
    explanation: "'Na boa' means 'all good', 'no worries'. 'Estás bem?' — 'Na boa!' (You OK? — All good!). Like Bengali 'thik achhe' or 'kono shomoshsha nei'. One of the most used casual expressions in Portugal — effortlessly positive and relaxed.",
    cefrMin: "A1",
    tags: ["slang", "daily-life", "conversation"],
  },
  {
    id: "bn_o_pa",
    type: "expression",
    contentPt: "Ó pá!",
    contentL1: "এই যে! / ওরে! — casual address among friends",
    explanation: "'Ó pá' (from 'rapaz', boy) is how Portuguese address friends, express surprise, or get attention. 'Ó pá, que se passa?' (Hey, what's up?). Like Bengali 'ei je' or 'ore'. Casual, friendly, only for peers. Never use with strangers or elders.",
    cefrMin: "A2",
    tags: ["slang", "conversation"],
  },
  {
    id: "bn_agua_mole",
    type: "expression",
    contentPt: "Água mole em pedra dura, tanto bate até que fura",
    contentL1: "ধৈর্য ধরলে ফল পাওয়া যায় — ফোঁটা ফোঁটা জল জমে সাগর",
    explanation: "'Soft water on hard stone, keeps hitting until it pierces.' Persistence wins. Like Bengali 'phonta phonta jol jome shagor' (drop by drop the ocean forms). One of the oldest Portuguese proverbs, used daily to encourage patience — in learning, work, or bureaucracy.",
    cefrMin: "B1",
    tags: ["proverb", "wisdom", "ancient"],
  },
  {
    id: "bn_quem_nao_tem_cao",
    type: "expression",
    contentPt: "Quem não tem cão, caça com gato",
    contentL1: "যা আছে তাই দিয়ে কাজ চালাও — জোগাড়ের প্রবাদ",
    explanation: "'If you don't have a dog, hunt with a cat.' Make do with what you have. This ancient Portuguese proverb is the proverbial form of 'jogaar' — use whatever resources are available. It proves that 'desenrascar-se' is not modern slang but centuries-old philosophy.",
    cefrMin: "B1",
    tags: ["proverb", "wisdom", "ancient"],
  },
  {
    id: "bn_grao_a_grao",
    type: "expression",
    contentPt: "Grão a grão, enche a galinha o papo",
    contentL1: "দানায় দানায় মুরগির পেট ভরে — ধীরে ধীরে হয়",
    explanation: "'Grain by grain, the hen fills her crop.' Small efforts accumulate. Used when advising patience — saving money, learning Portuguese, building a life in a new country. This proverb has been in Portuguese since at least the 15th century and remains in everyday use.",
    cefrMin: "B1",
    tags: ["proverb", "wisdom", "ancient"],
  },
  {
    id: "bn_fazer_tripas_coracao",
    type: "expression",
    contentPt: "Fazer das tripas coração",
    contentL1: "সাহস করা / মন শক্ত করা — to summon courage",
    explanation: "'Make a heart out of tripe' — to push through something difficult. When facing a terrible queue at AIMA, a hard exam, or a painful conversation: 'vou fazer das tripas coração'. Like Bengali 'shahosh kora' or 'mon shokto kora'. Ancient, visceral, and still alive in daily speech.",
    cefrMin: "B1",
    tags: ["proverb", "emotion", "ancient"],
  },
  {
    id: "bn_ficar_ver_navios",
    type: "expression",
    contentPt: "Ficar a ver navios",
    contentL1: "হাতে কিছু না আসা — empty-handed, left waiting",
    explanation: "'To stay watching ships' — to be left with nothing. From the Age of Discoveries when families watched ships sail away, many never returning. 'Fiquei a ver navios' (I was left empty-handed). Like Bengali 'haate kichu na aasha'. A poetic expression with 500 years of maritime melancholy.",
    cefrMin: "B2",
    tags: ["proverb", "history", "ancient"],
  },
  {
    id: "bn_deixa_la",
    type: "expression",
    contentPt: "Deixa lá",
    contentL1: "যাক গে / থাক — never mind",
    explanation: "'Let it go' or 'never mind'. Used constantly: when something minor goes wrong ('Deixa lá, não faz mal' — Never mind, no worries), to comfort someone, or to drop a subject. Like Bengali 'jak ge' or 'thak'. One of the most comforting phrases in Portuguese.",
    cefrMin: "A1",
    tags: ["daily-life", "conversation"],
  },
  {
    id: "bn_se_calhar",
    type: "expression",
    contentPt: "Se calhar",
    contentL1: "হয়তো / সম্ভবত — se calhar = maybe (PT-EU)",
    explanation: "'Perhaps', 'maybe'. PT-EU uses 'se calhar' where PT-BR uses 'talvez'. 'Se calhar amanhã chove' (Maybe it'll rain tomorrow). Like Bengali 'hoyto'. Using 'se calhar' instead of 'talvez' immediately marks you as a European Portuguese speaker — a key PT-EU/PT-BR difference.",
    cefrMin: "A2",
    tags: ["daily-life", "conversation", "pt-eu-vs-br"],
  },
  {
    id: "bn_e_o_que_e",
    type: "expression",
    contentPt: "É o que é",
    contentL1: "যা তাই / এমনই — it is what it is",
    explanation: "'It is what it is.' The ultimate Portuguese expression of resigned acceptance. When rent goes up, bureaucracy is slow, the train is late: 'é o que é'. Like Bengali 'ja tai' or 'emoni'. Philosophical acceptance without drama — perfectly captures the Portuguese temperament.",
    cefrMin: "A1",
    tags: ["daily-life", "conversation", "philosophy"],
  },
  {
    id: "bn_engolir_sapos",
    type: "expression",
    contentPt: "Engolir sapos",
    contentL1: "তেতো গিলতে হচ্ছে — to swallow bitterness",
    explanation: "'To swallow frogs' — enduring something unpleasant without complaining. When your boss is unfair, when bureaucracy grinds you down: 'tenho de engolir sapos'. Like Bengali 'teto gilte hochhe' (swallowing bitterness). Ancient, visceral, still used daily.",
    cefrMin: "B1",
    tags: ["proverb", "emotion", "ancient"],
  },
  {
    id: "bn_nao_faz_mal",
    type: "expression",
    contentPt: "Não faz mal",
    contentL1: "কিছু হয়নি / সমস্যা নেই — no worries",
    explanation: "'It doesn't matter' / 'No worries'. The most common response to an apology. Someone bumps you: 'Desculpe!' — 'Não faz mal!' Like Bengali 'kichu hoyni'. You will hear and use this phrase multiple times every single day in Portugal.",
    cefrMin: "A1",
    tags: ["daily-life", "conversation"],
  },
  {
    id: "bn_mandar_vir",
    type: "expression",
    contentPt: "Mandar vir",
    contentL1: "বকা দেওয়া / ধমক — to tell someone off",
    explanation: "'To send someone coming' — to scold or complain aggressively. 'A minha mãe mandou-me vir' (My mum told me off). Like Bengali 'boka deoa' or 'dhomok'. Very common in everyday Portuguese, from family arguments to workplace frustrations.",
    cefrMin: "B1",
    tags: ["slang", "emotion", "daily-life"],
  },
  {
    id: "bn_mais_vale_passaro",
    type: "expression",
    contentPt: "Mais vale um pássaro na mão do que dois a voar",
    contentL1: "হাতের একটা পাখি ভালো উড়ন্ত দুটোর চেয়ে",
    explanation: "'A bird in the hand is worth two flying.' Don't risk what you have for uncertain gains. Exists in Bengali too but the Portuguese version uses 'a voar' (flying) rather than 'in the bush', giving it a maritime, poetic feel. Used constantly in daily advice about jobs, money, and relationships.",
    cefrMin: "B1",
    tags: ["proverb", "wisdom", "ancient"],
  },
];
