import type { CulturalRef } from "../types.js";

export const bnCulturalRefs: readonly CulturalRef[] = [
  {
    id: "bn_portuguese_bengal",
    type: "reference",
    contentPt: "Os portugueses em Bengala",
    contentL1: "বাংলায় পর্তুগিজরা — ৫০০ বছরের ইতিহাস",
    explanation: "The Portuguese established trading posts in Bengal in the early 1500s. Hooghly (Ugolim) and Bandel were major Portuguese settlements. The Bandel Church (1599) still stands. This 500-year connection left dozens of Portuguese loanwords in Bengali that you use every day without knowing their origin.",
    cefrMin: "A2",
    tags: ["history", "culture"],
  },
  {
    id: "bn_loanwords",
    type: "reference",
    contentPt: "Palavras portuguesas no bengali",
    contentL1: "বাংলায় পর্তুগিজ শব্দ — জানালা, চাবি, বালতি, আলমারি",
    explanation: "Bengali has borrowed many everyday words from Portuguese: janela/জানালা (window), chave/চাবি (key), balde/বালতি (bucket), armário/আলমারি (wardrobe), mesa/মেজ (table), camisa/কামিজ (shirt), sabão/সাবান (soap), toalha/তোয়ালে (towel). You already speak some Portuguese!",
    cefrMin: "A1",
    tags: ["vocabulary", "history", "language"],
  },
  {
    id: "bn_cha_tea",
    type: "reference",
    contentPt: "Chá — a ligação mais antiga",
    contentL1: "চা — সবচেয়ে পুরোনো সংযোগ",
    explanation: "The Portuguese word 'chá' and Bengali 'চা' share the same Chinese root. Portuguese traders brought tea to Europe via their Asian trade routes. When you order 'um chá' in Portugal, you're speaking the same word you use at home.",
    cefrMin: "A1",
    tags: ["food", "daily-life", "history"],
  },
  {
    id: "bn_saudade",
    type: "expression",
    contentPt: "Saudade",
    contentL1: "গভীর বিরহ ও মনকেমন — কোনো সরাসরি অনুবাদ নেই",
    explanation: "The untranslatable Portuguese word for deep, bittersweet longing. Bengali has 'mon-kemon' (মনকেমন) — that restless, melancholic feeling. Saudade is similar but deeper: it's longing for something you love, mixed with the sweetness of having known it. Rabindranath's poems capture this feeling too.",
    cefrMin: "B1",
    tags: ["culture", "emotion"],
  },
  {
    id: "bn_fixe",
    type: "expression",
    contentPt: "Fixe!",
    contentL1: "দারুণ! / মারাত্মক!",
    explanation: "The Portuguese slang for 'cool/awesome'. Used constantly in informal speech. 'O filme foi fixe!' (The movie was cool!). Think of it like Bengali 'darun' or 'jhakkas'.",
    cefrMin: "A1",
    tags: ["slang", "daily-life"],
  },
  {
    id: "bn_desenrascar",
    type: "expression",
    contentPt: "Desenrascar-se",
    contentL1: "জোগাড় করা — সমস্যার সমাধান বের করা",
    explanation: "The quintessential Portuguese concept of improvising a solution. Very similar to Bengali 'jogaar' (জোগাড়) — finding a creative way out when resources are limited. Both cultures value this resourcefulness as a point of national pride.",
    cefrMin: "A2",
    tags: ["culture", "daily-life"],
  },
  {
    id: "bn_football",
    type: "reference",
    contentPt: "O futebol em Portugal",
    contentL1: "পর্তুগালে ফুটবল — ক্রিকেটের মতো আবেগ",
    explanation: "What cricket is to Bangladesh, football is to Portugal. The three big clubs — Benfica, Sporting, Porto — divide families and friendships. Everyone has an opinion. Cristiano Ronaldo is a national hero. Match days transform the country.",
    cefrMin: "A1",
    tags: ["culture", "sport"],
  },
  {
    id: "bn_family",
    type: "reference",
    contentPt: "A família portuguesa",
    contentL1: "পর্তুগিজ পরিবার — বাংলার মতোই",
    explanation: "Portuguese family values closely mirror Bengali ones: deep respect for elders, multi-generational households are common, Sunday lunch with the extended family is sacred, and children often live at home until marriage. Food is the center of family life in both cultures.",
    cefrMin: "A2",
    tags: ["culture", "family", "social"],
  },
  {
    id: "bn_rice_culture",
    type: "reference",
    contentPt: "Arroz — a base da comida",
    contentL1: "ভাত — দুই সংস্কৃতির মিল",
    explanation: "Like Bengali cuisine, Portuguese cooking revolves around rice. 'Arroz de...' (rice with...) is a huge category: arroz de pato (duck rice), arroz de marisco (seafood rice), arroz de tomate. The Portuguese also eat rice at almost every meal, just like Bengalis eat bhaat.",
    cefrMin: "A1",
    tags: ["food", "culture"],
  },
  {
    id: "bn_sweets",
    type: "reference",
    contentPt: "Doces portugueses — ovos e açúcar",
    contentL1: "পর্তুগিজ মিষ্টি — ডিম আর চিনি",
    explanation: "Portugal has a massive sweet tooth, like Bengal. 'Doces conventuais' (convent sweets) use egg yolks and sugar — similar richness to Bengali mishti (sweets). Try pastéis de nata, ovos moles, and toucinho do céu. The Portuguese sweet tradition influenced desserts across Asia, including Bengal.",
    cefrMin: "A2",
    tags: ["food", "culture"],
  },
  {
    id: "bn_bica_cafe",
    type: "reference",
    contentPt: "Uma bica / um galão",
    contentL1: "এসপ্রেসো / দুধ কফি",
    explanation: "In Lisbon, espresso is 'uma bica', in Porto 'um cimbalino'. A 'galão' is a large milky coffee in a tall glass. Portuguese coffee is strong espresso, quite different from the milk tea (cha) that dominates in Bengal. But both cultures revolve around their hot drink of choice.",
    cefrMin: "A1",
    tags: ["food", "daily-life"],
  },
  {
    id: "bn_pois",
    type: "expression",
    contentPt: "Pois...",
    contentL1: "আচ্ছা... / হুম... / তাই...",
    explanation: "The most versatile Portuguese word. 'Pois' can mean 'yeah', 'well', 'indeed', 'right' — depending entirely on intonation. Like Bengali 'achcha' — it fills gaps, acknowledges, agrees, or politely dismisses. Mastering 'pois' is a fluency milestone.",
    cefrMin: "A1",
    tags: ["conversation", "daily-life"],
  },
  {
    id: "bn_fado",
    type: "reference",
    contentPt: "Fado — a alma da música portuguesa",
    contentL1: "ফাদো — পর্তুগিজ সংগীতের আত্মা",
    explanation: "Portugal's soul music — melancholic songs about fate, saudade, longing, and the sea. If you love Rabindra Sangeet (Tagore's songs) for its emotional depth, fado will resonate with you. Both traditions value the singer's ability to convey raw emotion. UNESCO Intangible Heritage since 2011.",
    cefrMin: "A2",
    tags: ["music", "culture"],
  },
  {
    id: "bn_tu_voce",
    type: "reference",
    contentPt: "Tu vs Você vs O Senhor",
    contentL1: "তুই/তুমি/আপনি — সম্মানের স্তর",
    explanation: "Like Bengali's তুই/তুমি/আপনি (tui/tumi/apni) levels, Portuguese has formality tiers: 'tu' (informal, like tumi), 'você' (semi-formal, sometimes awkward), 'o senhor/a senhora' (formal, like apni). Start formal with older people, let them invite you to use 'tu'. Bengali speakers have an advantage understanding this system.",
    cefrMin: "A1",
    tags: ["social", "grammar", "etiquette"],
  },
  {
    id: "bn_pasteis_nata",
    type: "reference",
    contentPt: "Pastéis de nata",
    contentL1: "পাস্তেইশ দে নাতা — পর্তুগালের সবচেয়ে বিখ্যাত মিষ্টি",
    explanation: "Portugal's most famous pastry — a flaky crust filled with egg custard, baked until caramelized. Eat warm, sprinkled with cinnamon and powdered sugar. Found in every pastelaria. The original secret recipe comes from the Jerónimos monastery in Belém. If you love mishti doi's richness, you'll love these.",
    cefrMin: "A1",
    tags: ["food", "culture"],
  },
  {
    id: "bn_estar_a_fazer",
    type: "expression",
    contentPt: "Estou a fazer (not estou fazendo)",
    contentL1: "আমি করছি — ইউরোপীয় পর্তুগিজ রীতি",
    explanation: "European Portuguese uses 'estar a + infinitive' for ongoing actions: 'Estou a comer' (I am eating). Brazilian Portuguese uses the gerund: 'Estou comendo'. This is the most noticeable PT-EU vs PT-BR difference and marks you as a European Portuguese learner.",
    cefrMin: "A1",
    tags: ["grammar", "pt-eu-vs-br"],
  },
  {
    id: "bn_colonialism_shared",
    type: "reference",
    contentPt: "Histórias coloniais cruzadas",
    contentL1: "ঔপনিবেশিক ইতিহাসের মিল",
    explanation: "Both Bengal and Portugal have complex colonial histories. Portugal was a colonizer in Asia (Goa, Macau, Timor, Bengal trading posts) while also being on Europe's periphery. This creates interesting conversations about identity, language, and cultural exchange. Approach with nuance — there's shared history, not shared perspectives.",
    cefrMin: "B2",
    tags: ["history", "culture", "identity"],
  },
  {
    id: "bn_nas_tintas",
    type: "expression",
    contentPt: "Estar-se nas tintas",
    contentL1: "আমার কিছু আসে যায় না",
    explanation: "Literally 'to be in the paints'. Means you couldn't care less. 'Estou-me nas tintas para isso' (I don't give a damn about that). Very common, mildly rude. Similar to Bengali 'amar kichu ashe jay na'.",
    cefrMin: "B1",
    tags: ["slang", "emotion"],
  },
  {
    id: "bn_santos_populares",
    type: "reference",
    contentPt: "Festas dos Santos Populares",
    contentL1: "সান্তোশ পপুলারেশ — জুন মাসের রাস্তার উৎসব",
    explanation: "Every June, Portugal erupts in street festivals. Santo António (Lisbon, June 13) features parades, grilled sardines, and dancing. São João (Porto, June 24) involves hitting strangers on the head with plastic hammers. The community energy, street food, and open celebrations will remind you of Durga Puja's pandal-hopping atmosphere.",
    cefrMin: "A2",
    tags: ["culture", "festivals"],
  },
  {
    id: "bn_25_abril",
    type: "reference",
    contentPt: "25 de Abril — Revolução dos Cravos",
    contentL1: "২৫শে এপ্রিল — কার্নেশন বিপ্লব (১৯৭৪)",
    explanation: "On April 25, 1974, Portugal peacefully overthrew its 41-year dictatorship. Soldiers put red carnations in their rifle barrels. Like Bangladesh's Liberation War (1971), this is a defining moment of national identity. The date is a national holiday, the main bridge in Lisbon bears its name, and the revolutionary song 'Grândola, Vila Morena' still moves people to tears.",
    cefrMin: "B1",
    tags: ["history", "culture", "identity"],
  },
  {
    id: "bn_lisbon_porto",
    type: "reference",
    contentPt: "Lisboa vs Porto",
    contentL1: "লিসবন বনাম পোর্তো — ঢাকা বনাম চট্টগ্রামের মতো",
    explanation: "Lisbon and Porto have a friendly rivalry like Dhaka and Chittagong. Lisbon (lisboetas) is the cosmopolitan capital; Porto (tripeiros, 'tripe-eaters') is proudly industrial and independent-minded. They have different words for espresso (bica vs cimbalino), different food traditions, and fierce football rivalries (Benfica/Sporting vs FC Porto).",
    cefrMin: "B1",
    tags: ["culture", "cities"],
  },
  {
    id: "bn_bacalhau",
    type: "reference",
    contentPt: "Bacalhau — o prato nacional",
    contentL1: "বাকালহাউ — পর্তুগালের জাতীয় খাবার (শুটকি মাছের মতো)",
    explanation: "Bacalhau (salt cod) is Portugal's national dish — they claim 365 recipes, one for each day. It's dried, salted cod that must be soaked before cooking. Bengal has its own dried fish tradition (shutki maach). The concept of preserving fish with salt connects the two cuisines, though the flavors differ completely.",
    cefrMin: "A2",
    tags: ["food", "culture"],
  },
  {
    id: "bn_pronto",
    type: "expression",
    contentPt: "Pronto!",
    contentL1: "হয়ে গেছে! / চলো! / ব্যাস!",
    explanation: "'Pronto' is everywhere in Portuguese conversation. It means 'done!', 'ready!', 'OK then!'. Used to wrap up a thought ('Pronto, vamos!' — OK, let's go) or signal completion ('Pronto, acabei!' — Done, finished!). Like Bengali 'hoyegeche' or 'byash'. Mastering 'pronto' makes you sound natural instantly.",
    cefrMin: "A1",
    tags: ["conversation", "daily-life"],
  },
  {
    id: "bn_autocarro",
    type: "reference",
    contentPt: "Autocarro / comboio / telemóvel",
    contentL1: "বাস / ট্রেন / মোবাইল (ইউরোপীয় পর্তুগিজ শব্দ)",
    explanation: "PT-EU and PT-BR use different everyday words. Bus: autocarro (PT-EU) vs ônibus (PT-BR). Train: comboio vs trem. Mobile phone: telemóvel vs celular. Breakfast: pequeno-almoço vs café da manhã. Bathroom: casa de banho vs banheiro. If you learned any Portuguese from Brazilian sources, be aware of these differences.",
    cefrMin: "A1",
    tags: ["vocabulary", "pt-eu-vs-br"],
  },
  {
    id: "bn_hospitality",
    type: "expression",
    contentPt: "Fique à vontade",
    contentL1: "স্বচ্ছন্দে থাকুন / নিজের বাড়ি মনে করুন",
    explanation: "'Fique à vontade' means 'make yourself comfortable' — the Portuguese version of 'nijer baari mone korun'. Portuguese hospitality is warm and genuine. Guests are always offered food and drink; refusing feels rude. Bengali speakers will find this familiar. A Portuguese home always has food ready for unexpected visitors.",
    cefrMin: "A2",
    tags: ["culture", "hospitality", "daily-life"],
  },
];
