import type { L1Profile } from "../types.js";

export const bnProfile: L1Profile = {
  code: "bn",
  name: "Bengali",
  nativeName: "বাংলা",
  writingDirection: "ltr",
  hasLatinScript: false,
  transfer: {
    cognates: [
      "almari (আলমারি, from armário — wardrobe)",
      "baldi (বালতি, from balde — bucket)",
      "chaabi (চাবি, from chave — key)",
      "kamiz (কামিজ, from camisa — shirt)",
      "istiri (ইস্ত্রি, from engomar — to iron)",
      "janela (জানালা, from janela — window)",
      "mesa (মেজ, from mesa — table)",
      "sabão (সাবান, from sabão — soap)",
      "toalha (তোয়ালে, from toalha — towel)",
      "padre (পাদ্রি, from padre — priest/father)",
      "igreja (ইগ্রেজ, from igreja — church)",
      "cadeira (কেদারা, from cadeira — chair)",
      "pão (পাউরুটি, from pão — bread)",
      "copos (কাপ, from copo — glass/cup)",
      "peça (পেসা/পয়সা, influenced by peça — piece/coin)",
      "fita (ফিতা/ফিতে, from fita — ribbon/tape)",
      "ananás (আনারস, from ananás — pineapple)",
      "caju (কাজু, from caju — cashew)",
      "cobra (কোবরা, from cobra — snake)",
      "varanda (ভেরান্দা, from varanda — veranda/balcony)",
      "leilão (নিলাম, from leilão — auction)",
      "pistola (পিস্তল, from pistola — pistol/gun)",
      "garrafa (বোতল, from Portuguese trade — bottle)",
      "biscoito (বিস্কুট, from biscoito — biscuit/cookie)",
      "prego (পেরেক, from prego — nail/tack)",
      "armazém (গুদাম, from Portuguese trade — warehouse/godown)",
      "tanque (ট্যাঙ্ক, from tanque — tank/reservoir)",
      "câmara (কামরা, from câmara — room/chamber)",
      "pagode (প্যাগোডা, from pagode — pagoda/temple)",
      "bandeira (বান্দেরা, from bandeira — flag)",
    ],
    falseFriends: [
      { word: "bola", l1Meaning: "বলা (bola) — said/spoke (past tense of bolaa)", ptMeaning: "bola means 'ball' — not related to speaking" },
      { word: "mala", l1Meaning: "মালা (mala) — garland/necklace", ptMeaning: "mala means 'suitcase/bag'" },
      { word: "dia", l1Meaning: "দিয়া (diya) — gave / an oil lamp", ptMeaning: "dia means 'day' — 'bom dia' (good morning)" },
      { word: "bar", l1Meaning: "বার (baar) — time/occasion ('ek baar' = one time)", ptMeaning: "bar means a drinking establishment" },
      { word: "cama", l1Meaning: "কাম (kaam) — work/task", ptMeaning: "cama means 'bed' — nothing to do with work" },
      { word: "rato", l1Meaning: "রাত (raat) — night", ptMeaning: "rato means 'mouse'" },
      { word: "logo", l1Meaning: "লোক (lok) — people", ptMeaning: "logo means 'soon/immediately' or 'therefore'" },
      { word: "mata", l1Meaning: "মাতা (mata) — mother", ptMeaning: "mata means 'forest' or 'kills' (3rd person of matar)" },
      { word: "pata", l1Meaning: "পাতা (pata) — leaf/page", ptMeaning: "pata means 'paw' or 'animal leg'" },
      { word: "gola", l1Meaning: "গোলা (gola) — sphere/round ball/throat", ptMeaning: "gola means 'collar' (of a shirt)" },
      { word: "lata", l1Meaning: "লতা (lata) — vine/creeper (also a common name)", ptMeaning: "lata means 'tin can'" },
      { word: "ganga", l1Meaning: "গঙ্গা (Ganga) — the sacred river", ptMeaning: "ganga means 'denim/jeans' or 'bargain'" },
      { word: "sala", l1Meaning: "শালা (shala) — school / brother-in-law / mild insult", ptMeaning: "sala means 'room/living room' — no negative connotation" },
      { word: "mal", l1Meaning: "মাল (maal) — goods/property/wealth", ptMeaning: "mal means 'badly' or 'evil'" },
      { word: "pai", l1Meaning: "পাই (pai) — a fraction / type of measurement", ptMeaning: "pai means 'father'" },
      { word: "vida", l1Meaning: "বিদায় (biday) — farewell/departure", ptMeaning: "vida means 'life' — opposite association" },
      { word: "nota", l1Meaning: "নোট (note) — banknote (English loan)", ptMeaning: "nota means 'grade/mark' as well as 'banknote'" },
      { word: "campo", l1Meaning: "ক্যাম্প (camp) — camping (English loan)", ptMeaning: "campo means 'field/countryside'" },
      { word: "carro", l1Meaning: "করো (koro) — do! (imperative)", ptMeaning: "carro means 'car'" },
      { word: "massa", l1Meaning: "মশলা (moshla) — spice/spice blend", ptMeaning: "massa means 'dough/pasta' — nothing to do with spices" },
      { word: "manga", l1Meaning: "ম্যাংগো — sounds like mango fruit", ptMeaning: "manga primarily means 'sleeve' — also means mango in Portuguese, but sleeve is the first meaning" },
      { word: "todo", l1Meaning: "থোড়া (thora) — a little/some", ptMeaning: "todo means 'all/everything' — essentially the opposite" },
      { word: "faca", l1Meaning: "ফাঁকা (faka) — empty/hollow/idle", ptMeaning: "faca means 'knife'" },
      { word: "sumo", l1Meaning: "সুমো (sumo) — wrestler/large vehicle", ptMeaning: "sumo means 'juice' — 'sumo de laranja' is orange juice" },
      { word: "mola", l1Meaning: "মোল (mol) — price/value/worth", ptMeaning: "mola means 'spring (coil)' or 'clothespin'" },
      { word: "seda", l1Meaning: "সিধা/সোজা (sidha/shoja) — straight/simple", ptMeaning: "seda means 'silk'" },
      { word: "roda", l1Meaning: "রোড়া (roda) — obstacle/pebble in the road", ptMeaning: "roda means 'wheel' or 'circle'" },
      { word: "dar", l1Meaning: "দর (dor) — price/rate", ptMeaning: "dar means 'to give'" },
      { word: "pato", l1Meaning: "পাট (paat) — jute/floor mat", ptMeaning: "pato means 'duck'" },
      { word: "dor", l1Meaning: "দোর (dor) — rope/thread", ptMeaning: "dor means 'pain/ache'" },
      { word: "terra", l1Meaning: "তার (taar) — his/her or wire/thread", ptMeaning: "terra means 'earth/land/homeland'" },
      { word: "meta", l1Meaning: "মিঠা (mitha) — sweet/sugary", ptMeaning: "meta means 'goal/target'" },
      { word: "fora", l1Meaning: "ফোর (four) — boundary hit in cricket", ptMeaning: "fora means 'outside/out'" },
      { word: "sol", l1Meaning: "সোল (sole) — stale/day-old food", ptMeaning: "sol means 'sun'" },
      { word: "saco", l1Meaning: "শাক (shaak) — leafy vegetables/greens", ptMeaning: "saco means 'bag/sack'" },
      { word: "mato", l1Meaning: "মত (mot) — opinion/like (suffix)", ptMeaning: "mato means 'bush/wilderness' or 'I kill'" },
      { word: "fino", l1Meaning: "sounds like English 'fine' (ফাইন) used in Bengali", ptMeaning: "fino means 'thin/refined' — also a small draught beer in Lisbon" },
      { word: "cara", l1Meaning: "কারা (kara) — who (interrogative) / prison", ptMeaning: "cara means 'face' or 'guy' (informal)" },
      { word: "calo", l1Meaning: "কাল (kal) — tomorrow/yesterday", ptMeaning: "calo means 'callus' or 'I shut up' (from calar)" },
      { word: "gato", l1Meaning: "sounds like Bengali গাটো — no direct meaning", ptMeaning: "gato means 'cat' — often confused with 'gaata' (body in Hindi/Bengali)" },
    ],
    phoneticDifficulties: [
      { sound: "ão", ipa: "/ɐ̃w̃/", description: "Nasal diphthong", tip: "Bengali has nasal vowels (চন্দ্রবিন্দু) — use that instinct but add a glide at the end. Start nasal, then round your lips into a 'w'. Practice: 'pão', 'não', 'mão'." },
      { sound: "ã / õ / ẽ", ipa: "/ɐ̃/ /õ/ /ẽ/", description: "Nasal vowels", tip: "Bengali nasalization (চন্দ্রবিন্দু ঁ) is your advantage! PT-EU nasals work the same way — let air through your nose while holding the vowel." },
      { sound: "r/rr", ipa: "/ʁ/", description: "Uvular R", tip: "Not like Bengali র (ra) — PT-EU initial R and double RR are uvular, produced at the back of the throat. Think of gargling gently. Single 'r' between vowels is a tap like Bengali ড়." },
      { sound: "v/b distinction", ipa: "/v/ /b/", description: "V and B are different sounds", tip: "Bengali often merges ভ (bh/v) and ব (b). In PT-EU, 'v' is always labiodental — bite your lower lip. 'Vaca' (cow) has a clear buzzing V, never a B." },
      { sound: "lh", ipa: "/ʎ/", description: "Palatal lateral", tip: "No Bengali equivalent. Press the middle of your tongue against the hard palate while making an L. 'Trabalho' (work), 'filho' (son). Like Italian 'gli'." },
      { sound: "nh", ipa: "/ɲ/", description: "Palatal nasal", tip: "No Bengali equivalent. Like English 'ny' in 'canyon'. Tongue touches the palate while nasalizing. 'Amanhã' (tomorrow), 'vinho' (wine)." },
      { sound: "open/closed vowels", ipa: "/ɛ/ vs /e/, /ɔ/ vs /o/", description: "Vowel quality changes meaning", tip: "Bengali distinguishes some vowel qualities (এ vs ঐ). PT-EU does too: 'avó' /ɔ/ (grandmother) vs 'avô' /o/ (grandfather). Listen for the jaw position — open vowels drop the jaw." },
      { sound: "reduced vowels", ipa: "/ɨ/ or silent", description: "Unstressed vowels nearly vanish", tip: "Unstressed 'e' often becomes /ɨ/ or disappears entirely. 'Telefone' sounds like 'tl-fon'. Bengali doesn't reduce vowels this much — train your ear for the rhythm." },
      { sound: "f", ipa: "/f/", description: "Labiodental fricative", tip: "Bengali has ফ (ph) which is aspirated, not fricative. PT-EU /f/ requires your upper teeth on your lower lip with continuous airflow. 'Fazer' (to do), 'falar' (to speak)." },
      { sound: "s / z / sh distinction", ipa: "/s/ /z/ /ʃ/", description: "Three sibilants", tip: "Bengali has শ/ষ/স. PT-EU 's' at end of syllable becomes 'sh' (/ʃ/) in Lisbon dialect: 'os livros' sounds like 'osh livroosh'. Between vowels 's' becomes 'z': 'casa' = 'caza'." },
      { sound: "word stress", ipa: "variable", description: "Stress changes meaning", tip: "Bengali stress is more predictable. PT-EU stress can fall on different syllables and changes meaning: 'sabia' (she knew) vs 'sabiá' (a bird). Written accents mark irregular stress." },
      { sound: "consonant clusters", ipa: "various", description: "Complex clusters", tip: "PT-EU allows clusters like 'pr-', 'tr-', 'str-', '-lps' that Bengali doesn't have. Practice slowly: 'pra-to' (plate), 'es-tru-tu-ra' (structure)." },
      { sound: "dark L", ipa: "/ɫ/", description: "Velarized L at end of syllables", tip: "Bengali ল is always light/clear. PT-EU 'l' at end of a syllable becomes dark and thick, almost like a 'w'. 'Portugal', 'sol' (sun), 'mal' (badly) all have this heavy final L." },
      { sound: "diphthongs ei/ou/ai", ipa: "/ej/ /ow/ /aj/", description: "Oral diphthongs", tip: "Bengali has diphthongs too (ঐ, ঔ). PT-EU has similar glides: 'primeiro' (first) has /ej/, 'pouco' (little) has /ow/. Keep the glide within one syllable, don't split into two." },
      { sound: "ge/gi/j", ipa: "/ʒ/", description: "Soft G and J are 'zh'", tip: "Bengali has no /ʒ/ sound. PT-EU 'j' and 'g' before 'e/i' sound like the 's' in English 'pleasure'. 'Gente' (people) = 'zhent', 'janeiro' (January) = 'zhaneyru'." },
    ],
    grammarGaps: [
      { concept: "Articles (o/a, um/uma)", explanation: "Every noun needs a definite or indefinite article", l1Comparison: "Bengali has no articles. In PT-EU you must always say 'o livro' (the book), 'uma casa' (a house). The article also tells you the gender." },
      { concept: "Grammatical gender", explanation: "Every noun is masculine or feminine", l1Comparison: "Bengali has no grammatical gender for objects. PT-EU assigns gender to everything: 'o sol' (the sun, m), 'a lua' (the moon, f). Memorize the article with each noun." },
      { concept: "Word order (SVO)", explanation: "Subject-Verb-Object is the default", l1Comparison: "Bengali is SOV (subject-object-verb): 'আমি ভাত খাই' (I rice eat). PT-EU is SVO: 'Eu como arroz' (I eat rice). The verb moves to the middle." },
      { concept: "Verb conjugation", explanation: "6 different forms per tense for each person", l1Comparison: "Bengali conjugates for person and politeness too, so the concept is familiar. But PT-EU has 3 verb classes (-ar, -er, -ir) and many more tenses. The forms are entirely different." },
      { concept: "Subjunctive mood", explanation: "A whole verb mood for doubt, desire, emotion, hypothetical", l1Comparison: "Bengali doesn't have a subjunctive. Think of it as a special verb form used after 'I hope that...', 'I doubt that...', 'it's possible that...'. Triggered by specific words and phrases." },
      { concept: "Ser vs Estar", explanation: "Two verbs for 'to be'", l1Comparison: "Bengali has হওয়া (howa) as one verb. PT-EU splits: 'ser' for identity/permanent traits ('Eu sou professor'), 'estar' for states/temporary conditions ('Estou cansado'). This distinction doesn't exist in Bengali." },
      { concept: "Prepositions vs Postpositions", explanation: "Prepositions come BEFORE the noun", l1Comparison: "Bengali uses postpositions (after the noun): 'টেবিলের উপরে' (table-of on-top). PT-EU puts them before: 'em cima da mesa' (on top of the table). Reverse the order." },
      { concept: "Plural formation", explanation: "Add -s or -es (usually)", l1Comparison: "Bengali plurals are more complex (গুলো, েরা, etc.). PT-EU is simpler: usually just add -s ('livro' -> 'livros'). But watch for words ending in -ão, -l, -r which have irregular plurals." },
      { concept: "Relative clauses with 'que'", explanation: "'Que' introduces all relative clauses", l1Comparison: "Bengali uses যে (je) similarly. PT-EU uses 'que' for 'who', 'which', 'that': 'O homem que vi' (the man that I saw). Simpler than Bengali in having one word for all." },
      { concept: "Personal infinitive", explanation: "Infinitive conjugated for person", l1Comparison: "Unique to Portuguese — no equivalent in Bengali or most languages. 'Para nós fazermos' (for us to do). It replaces a full clause in formal/written language." },
      { concept: "Object pronoun placement", explanation: "Pronouns go before or after the verb", l1Comparison: "Bengali puts objects before the verb. PT-EU object pronouns can go before ('Não te vi' — I didn't see you) or after ('Vi-te' — I saw you) depending on the sentence structure." },
      { concept: "Definite vs Indefinite usage", explanation: "Specific rules for when to use/omit articles", l1Comparison: "Bengali has no articles, so every usage decision is new. PT-EU uses 'o/a' with known things, 'um/uma' with new things, and sometimes no article at all (professions, materials). This takes extensive practice." },
      { concept: "Tu vs Você vs O Senhor", explanation: "Three formality levels for 'you'", l1Comparison: "Bengali has তুই/তুমি/আপনি (tui/tumi/apni) — three levels just like PT-EU. 'Tu' is intimate (like তুই), 'você' is neutral (like তুমি), 'o senhor/a senhora' is formal (like আপনি). Bengali speakers have a natural advantage understanding this social hierarchy." },
      { concept: "Reflexive verbs", explanation: "Many common verbs require a reflexive pronoun (se)", l1Comparison: "Bengali has some reflexive constructions ('নিজে') but PT-EU uses them constantly: levantar-se (get up), sentar-se (sit down), chamar-se (be called), deitar-se (lie down). The pronoun changes with the subject." },
      { concept: "Compound tenses with ter", explanation: "ter + past participle: 'tenho feito' (I have done)", l1Comparison: "Bengali uses compound verbs ('করে ফেলেছি') for completed actions. PT-EU builds compound tenses with 'ter': tenho falado, tinha comido, terei feito. The past participle stays the same regardless of gender/number." },
    ],
    skipBasics: false,
    startingCEFR: "A1",
  },
};
