import type { L1Profile } from "../types.js";

export const bnProfile: L1Profile = {
  code: "bn",
  name: "Bengali",
  nativeName: "বাংলা",
  writingDirection: "ltr",
  hasLatinScript: false,
  transfer: {
    cognates: [
      "almari (আলমারি, from armário — wardrobe)",
      "baldi (বালতি, from balde — bucket)",
      "chaabi (চাবি, from chave — key)",
      "kamiz (কামিজ, from camisa — shirt)",
      "istiri (ইস্ত্রি, from engomar — to iron)",
      "janela (জানালা, from janela — window)",
      "mesa (মেজ, from mesa — table)",
      "sabão (সাবান, from sabão — soap)",
      "toalha (তোয়ালে, from toalha — towel)",
      "padre (পাদ্রি, from padre — priest/father)",
      "igreja (ইগ্রেজ, from igreja — church)",
      "cadeira (কেদারা, from cadeira — chair)",
      "pão (পাউরুটি, from pão — bread)",
      "copos (কাপ, from copo — glass/cup)",
      "peça (পেসা/পয়সা, influenced by peça — piece/coin)",
    ],
    falseFriends: [
      { word: "janela", l1Meaning: "জানালা (window) — same meaning!", ptMeaning: "janela means 'window' — Bengali borrowed this directly from Portuguese. One of the easiest words." },
      { word: "mesa", l1Meaning: "মেজ (table) — same meaning!", ptMeaning: "mesa means 'table' — another direct Portuguese loanword in Bengali. The pronunciation is almost identical." },
      { word: "chaabi/chave", l1Meaning: "চাবি (key) — same meaning!", ptMeaning: "chave means 'key' — Bengali চাবি comes from Portuguese chave. In PT-EU it's pronounced 'shav'." },
      { word: "balde", l1Meaning: "বালতি (bucket) — same meaning!", ptMeaning: "balde means 'bucket' — Bengali বালতি preserves the Portuguese word almost unchanged." },
      { word: "ananas", l1Meaning: "আনারস (pineapple) — same root!", ptMeaning: "ananás means 'pineapple' — both words come from the Tupi 'nanas' via Portuguese traders." },
      { word: "camisa", l1Meaning: "কামিজ (shirt/top) — same root!", ptMeaning: "camisa means 'shirt' — the Bengali কামিজ is a direct Portuguese loanword. The garment style differs but the word is the same." },
      { word: "almari", l1Meaning: "আলমারি (wardrobe/cabinet)", ptMeaning: "armário means 'wardrobe/cabinet' — Bengali আলমারি preserves the Portuguese word. Note: in PT-EU it's armário, not almari." },
      { word: "sabão", l1Meaning: "সাবান (soap) — same meaning!", ptMeaning: "sabão means 'soap' — Bengali সাবান is directly from Portuguese. Pronounced 'suh-bown' in PT-EU." },
    ],
    phoneticDifficulties: [
      { sound: "ão", ipa: "/ɐ̃w̃/", description: "Nasal diphthong", tip: "Bengali has nasal vowels (চন্দ্রবিন্দু) — use that instinct but add a glide at the end. Start nasal, then round your lips into a 'w'. Practice: 'pão', 'não', 'mão'." },
      { sound: "ã / õ / ẽ", ipa: "/ɐ̃/ /õ/ /ẽ/", description: "Nasal vowels", tip: "Bengali nasalization (চন্দ্রবিন্দু ঁ) is your advantage! PT-EU nasals work the same way — let air through your nose while holding the vowel." },
      { sound: "r/rr", ipa: "/ʁ/", description: "Uvular R", tip: "Not like Bengali র (ra) — PT-EU initial R and double RR are uvular, produced at the back of the throat. Think of gargling gently. Single 'r' between vowels is a tap like Bengali ড়." },
      { sound: "v/b distinction", ipa: "/v/ /b/", description: "V and B are different sounds", tip: "Bengali often merges ভ (bh/v) and ব (b). In PT-EU, 'v' is always labiodental — bite your lower lip. 'Vaca' (cow) has a clear buzzing V, never a B." },
      { sound: "lh", ipa: "/ʎ/", description: "Palatal lateral", tip: "No Bengali equivalent. Press the middle of your tongue against the hard palate while making an L. 'Trabalho' (work), 'filho' (son). Like Italian 'gli'." },
      { sound: "nh", ipa: "/ɲ/", description: "Palatal nasal", tip: "No Bengali equivalent. Like English 'ny' in 'canyon'. Tongue touches the palate while nasalizing. 'Amanhã' (tomorrow), 'vinho' (wine)." },
      { sound: "open/closed vowels", ipa: "/ɛ/ vs /e/, /ɔ/ vs /o/", description: "Vowel quality changes meaning", tip: "Bengali distinguishes some vowel qualities (এ vs ঐ). PT-EU does too: 'avó' /ɔ/ (grandmother) vs 'avô' /o/ (grandfather). Listen for the jaw position — open vowels drop the jaw." },
      { sound: "reduced vowels", ipa: "/ɨ/ or silent", description: "Unstressed vowels nearly vanish", tip: "Unstressed 'e' often becomes /ɨ/ or disappears entirely. 'Telefone' sounds like 'tl-fon'. Bengali doesn't reduce vowels this much — train your ear for the rhythm." },
      { sound: "f", ipa: "/f/", description: "Labiodental fricative", tip: "Bengali has ফ (ph) which is aspirated, not fricative. PT-EU /f/ requires your upper teeth on your lower lip with continuous airflow. 'Fazer' (to do), 'falar' (to speak)." },
      { sound: "s / z / sh distinction", ipa: "/s/ /z/ /ʃ/", description: "Three sibilants", tip: "Bengali has শ/ষ/স. PT-EU 's' at end of syllable becomes 'sh' (/ʃ/) in Lisbon dialect: 'os livros' sounds like 'osh livroosh'. Between vowels 's' becomes 'z': 'casa' = 'caza'." },
      { sound: "word stress", ipa: "variable", description: "Stress changes meaning", tip: "Bengali stress is more predictable. PT-EU stress can fall on different syllables and changes meaning: 'sabia' (she knew) vs 'sabiá' (a bird). Written accents mark irregular stress." },
      { sound: "consonant clusters", ipa: "various", description: "Complex clusters", tip: "PT-EU allows clusters like 'pr-', 'tr-', 'str-', '-lps' that Bengali doesn't have. Practice slowly: 'pra-to' (plate), 'es-tru-tu-ra' (structure)." },
    ],
    grammarGaps: [
      { concept: "Articles (o/a, um/uma)", explanation: "Every noun needs a definite or indefinite article", l1Comparison: "Bengali has no articles. In PT-EU you must always say 'o livro' (the book), 'uma casa' (a house). The article also tells you the gender." },
      { concept: "Grammatical gender", explanation: "Every noun is masculine or feminine", l1Comparison: "Bengali has no grammatical gender for objects. PT-EU assigns gender to everything: 'o sol' (the sun, m), 'a lua' (the moon, f). Memorize the article with each noun." },
      { concept: "Word order (SVO)", explanation: "Subject-Verb-Object is the default", l1Comparison: "Bengali is SOV (subject-object-verb): 'আমি ভাত খাই' (I rice eat). PT-EU is SVO: 'Eu como arroz' (I eat rice). The verb moves to the middle." },
      { concept: "Verb conjugation", explanation: "6 different forms per tense for each person", l1Comparison: "Bengali conjugates for person and politeness too, so the concept is familiar. But PT-EU has 3 verb classes (-ar, -er, -ir) and many more tenses. The forms are entirely different." },
      { concept: "Subjunctive mood", explanation: "A whole verb mood for doubt, desire, emotion, hypothetical", l1Comparison: "Bengali doesn't have a subjunctive. Think of it as a special verb form used after 'I hope that...', 'I doubt that...', 'it's possible that...'. Triggered by specific words and phrases." },
      { concept: "Ser vs Estar", explanation: "Two verbs for 'to be'", l1Comparison: "Bengali has হওয়া (howa) as one verb. PT-EU splits: 'ser' for identity/permanent traits ('Eu sou professor'), 'estar' for states/temporary conditions ('Estou cansado'). This distinction doesn't exist in Bengali." },
      { concept: "Prepositions vs Postpositions", explanation: "Prepositions come BEFORE the noun", l1Comparison: "Bengali uses postpositions (after the noun): 'টেবিলের উপরে' (table-of on-top). PT-EU puts them before: 'em cima da mesa' (on top of the table). Reverse the order." },
      { concept: "Plural formation", explanation: "Add -s or -es (usually)", l1Comparison: "Bengali plurals are more complex (গুলো, েরা, etc.). PT-EU is simpler: usually just add -s ('livro' -> 'livros'). But watch for words ending in -ão, -l, -r which have irregular plurals." },
      { concept: "Relative clauses with 'que'", explanation: "'Que' introduces all relative clauses", l1Comparison: "Bengali uses যে (je) similarly. PT-EU uses 'que' for 'who', 'which', 'that': 'O homem que vi' (the man that I saw). Simpler than Bengali in having one word for all." },
      { concept: "Personal infinitive", explanation: "Infinitive conjugated for person", l1Comparison: "Unique to Portuguese — no equivalent in Bengali or most languages. 'Para nós fazermos' (for us to do). It replaces a full clause in formal/written language." },
      { concept: "Object pronoun placement", explanation: "Pronouns go before or after the verb", l1Comparison: "Bengali puts objects before the verb. PT-EU object pronouns can go before ('Não te vi' — I didn't see you) or after ('Vi-te' — I saw you) depending on the sentence structure." },
      { concept: "Definite vs Indefinite usage", explanation: "Specific rules for when to use/omit articles", l1Comparison: "Bengali has no articles, so every usage decision is new. PT-EU uses 'o/a' with known things, 'um/uma' with new things, and sometimes no article at all (professions, materials). This takes extensive practice." },
    ],
    skipBasics: false,
    startingCEFR: "A1",
  },
};
