import type { CulturalRef } from "../types.js";

export const jaCulturalRefs: readonly CulturalRef[] = [
  {
    id: "ja_saudade",
    type: "expression",
    contentPt: "Saudade",
    contentL1: "懐かしさ / 切なさ / もののあはれ",
    explanation: "Japanese 'もののあはれ' (mono no aware — the bittersweet awareness of impermanence) is perhaps the closest cultural concept to saudade. Both describe a melancholy that is beautiful, not to be cured. Fado and 演歌 share this emotional register.",
    cefrMin: "B1",
    tags: ["culture", "emotion"],
  },
  {
    id: "ja_tanegashima",
    type: "reference",
    contentPt: "Os Portugueses no Japão",
    contentL1: "南蛮人 — ポルトガル人の来日 (1543)",
    explanation: "Portuguese were the first Europeans to reach Japan in 1543. They brought firearms (鉄砲), tempura, and the word 'パン' (pão = bread). Many Japanese words come from Portuguese: カステラ (castella), コンペイトウ (compota), カッパ (capa), ボタン (botão).",
    cefrMin: "A2",
    tags: ["history", "vocabulary"],
  },
  {
    id: "ja_tempura",
    type: "reference",
    contentPt: "Tempura — origem portuguesa",
    contentL1: "天ぷら = têmporas (portuguese)",
    explanation: "Japanese 天ぷら comes from Portuguese 'têmporas' — meatless days when fried fish was eaten. The Portuguese missionaries brought this cooking technique to Japan in the 16th century. When eating 天ぷら you are tasting 500 years of Portuguese-Japanese connection.",
    cefrMin: "A2",
    tags: ["food", "history", "vocabulary"],
  },
  {
    id: "ja_pan_pao",
    type: "reference",
    contentPt: "Pão",
    contentL1: "パン (pãoから来た言葉)",
    explanation: "Japanese 'パン' (pan/bread) comes directly from Portuguese 'pão'. Other Portuguese loanwords in Japanese: カルタ (carta=card), コップ (copo=cup), タバコ (tabaco), シャボン (sabão=soap). You already know more Portuguese than you think.",
    cefrMin: "A1",
    tags: ["vocabulary", "history"],
  },
  {
    id: "ja_fixe",
    type: "expression",
    contentPt: "Fixe!",
    contentL1: "すごい! / いいね!",
    explanation: "'Fixe' means 'cool'. Use it like すごい or いいね. 'Que fixe!' = めっちゃいいね!",
    cefrMin: "A1",
    tags: ["slang", "daily-life"],
  },
  {
    id: "ja_pois",
    type: "expression",
    contentPt: "Pois...",
    contentL1: "まあ... / そうだね...",
    explanation: "'Pois' is the most versatile Portuguese filler, like Japanese まあ or そうだね. It fills pauses and expresses agreement or resignation. Very similar function to あいづち (aizuchi).",
    cefrMin: "A1",
    tags: ["conversation", "daily-life"],
  },
  {
    id: "ja_pasteis",
    type: "reference",
    contentPt: "Pastéis de nata",
    contentL1: "エッグタルト (ポルトガルのオリジナル)",
    explanation: "The original egg tart — what Macau and then all of Asia adapted. Crispy, flaky pastry with caramelized custard. About one euro each. Like カステラ, this is another Portuguese-origin sweet that Japanese speakers already know indirectly.",
    cefrMin: "A1",
    tags: ["food", "culture"],
  },
  {
    id: "ja_fado",
    type: "reference",
    contentPt: "Fado",
    contentL1: "演歌のような感情的な音楽",
    explanation: "Fado shares the emotional register of Japanese 演歌 (enka) — both are about fate, loss, and longing. The solo voice, the restrained accompaniment, the valued melancholy. Amália Rodrigues is fado's greatest voice, like 美空ひばり is to enka.",
    cefrMin: "B1",
    tags: ["music", "culture"],
  },
  {
    id: "ja_25_abril",
    type: "reference",
    contentPt: "25 de Abril — Revolução dos Cravos",
    contentL1: "カーネーション革命 (1974)",
    explanation: "On April 25, 1974, Portugal peacefully overthrew its dictatorship. Soldiers put carnations in their rifles. This revolution defines modern Portugal.",
    cefrMin: "B1",
    tags: ["history", "identity"],
  },
  {
    id: "ja_pronto",
    type: "expression",
    contentPt: "Pronto!",
    contentL1: "よし! / できた!",
    explanation: "'Pronto' = done/ready/OK then. Like よし or できた. 'Pronto, vamos!' = よし、行こう!",
    cefrMin: "A1",
    tags: ["daily-life", "conversation"],
  },
  {
    id: "ja_politeness",
    type: "reference",
    contentPt: "Tu vs O Senhor",
    contentL1: "ため口 vs です/ます",
    explanation: "Like Japanese ため口/ですます, Portuguese has 'tu' (informal) and 'o senhor/a senhora' (formal). Japanese speakers will naturally understand this formality system. Avoid 'você' in Portugal — it can sound cold, like using plain form with a superior.",
    cefrMin: "A1",
    tags: ["social", "etiquette"],
  },
  {
    id: "ja_bacalhau",
    type: "reference",
    contentPt: "Bacalhau",
    contentL1: "塩鰕 (365のレシピ)",
    explanation: "Salt cod is Portugal's national ingredient — 365 recipes. Japan also has a deep tradition of preserved fish (干物, 塩进). The Japanese appreciation for umami will make bacalhau instantly appealing.",
    cefrMin: "A2",
    tags: ["food", "culture"],
  },
  {
    id: "ja_azulejo",
    type: "reference",
    contentPt: "Azulejos",
    contentL1: "タイル芸術 (染付のような青と白)",
    explanation: "Portugal's blue and white ceramic tiles echo the aesthetics of Japanese 染付 (sometsuke) blue and white ceramics. Both traditions value the beauty of blue on white. The craft has Islamic and Chinese roots that reached both cultures through different trade routes.",
    cefrMin: "A2",
    tags: ["art", "culture"],
  },
  {
    id: "ja_desenrascar",
    type: "expression",
    contentPt: "Desenrascar-se",
    contentL1: "なんとかする",
    explanation: "The art of improvising solutions. Like Japanese なんとかする. Both cultures value finding a way through when the formal path is blocked.",
    cefrMin: "B1",
    tags: ["culture", "daily-life"],
  },
  {
    id: "ja_nas_tintas",
    type: "expression",
    contentPt: "Estar-se nas tintas",
    contentL1: "どうでもいい / 知らない",
    explanation: "Literally 'to be in the paints' — couldn't care less. Like どうでもいい. Very common, mildly rude.",
    cefrMin: "B1",
    tags: ["slang", "emotion"],
  },
  {
    id: "ja_kasutera",
    type: "reference",
    contentPt: "Pão de Castela — origem do カステラ",
    contentL1: "カステラ = ポルトガルのケーキ",
    explanation: "Japanese カステラ (castella) is a direct descendant of Portuguese 'pão de Castela' (Castilian bread), brought by missionaries in the 16th century. Nagasaki's famous sponge cake preserves a recipe Portugal itself has mostly forgotten. When learning the word 'bolo' (cake), you are reconnecting with a 500-year culinary lineage.",
    cefrMin: "A2",
    tags: ["food", "history", "vocabulary"],
  },
  {
    id: "ja_futebol",
    type: "reference",
    contentPt: "Futebol — paixão nacional",
    contentL1: "サッカー — ポルトガルの国民的情熱",
    explanation: "Football in Portugal is what baseball once was in Japan — a near-religious passion that unites the whole country. Benfica, Sporting, and Porto divide loyalties like 巨人 vs 阪神. Cristiano Ronaldo is a national hero. Learning football vocabulary (golo, falta, penálti, fora de jogo) unlocks conversation with almost any Portuguese person.",
    cefrMin: "A2",
    tags: ["sport", "culture", "conversation"],
  },
  {
    id: "ja_punctuality",
    type: "reference",
    contentPt: "Pontualidade à portuguesa",
    contentL1: "ポルトガル時間 (日本との文化の違い)",
    explanation: "Japan is the world's most punctual culture. Portugal is not. 'Vamos jantar às 20h' means dinner might start at 20:30 or later. This is not rude — it is cultural. Arriving exactly on time to a Portuguese home party means you will help set up. A Japanese person's instinct for punctuality will be noticed and respected, but do not expect it in return.",
    cefrMin: "A2",
    tags: ["culture", "daily-life", "etiquette"],
  },
  // --- MODERN SLANG ---
  {
    id: "ja_bue",
    type: "expression",
    contentPt: "Bué",
    contentL1: "めっちゃ / 超 (choo)",
    explanation: "'Bué' means 'a lot' or 'very' — from Kimbundu (Angolan language). 'Bué fixe' (めっちゃいい), 'bué caro' (超高い), 'bué gente' (人がめっちゃ多い). Used constantly by young Portuguese. Functions like めっちゃ in Kansai dialect or 超 in casual Tokyo speech — a universal youth intensifier.",
    cefrMin: "A2",
    tags: ["slang", "daily-life"],
  },
  {
    id: "ja_cena",
    type: "expression",
    contentPt: "Cena",
    contentL1: "あれ / やつ / こと",
    explanation: "Originally means 'scene' but in PT-EU slang it means 'thing/stuff/situation'. 'Que cena!' (なんかすごい!), 'é uma cena estranha' (変なやつだ). Like Japanese あれ or やつ when you can't name the thing. 'Dá-me aquela cena' (あれちょうだい).",
    cefrMin: "A2",
    tags: ["slang", "daily-life"],
  },
  {
    id: "ja_tipo",
    type: "expression",
    contentPt: "Tipo...",
    contentL1: "なんか... / みたいな...",
    explanation: "The Portuguese filler word, used exactly like Japanese なんか or みたいな. 'Ele é tipo alto' (彼はなんか背が高い). Young Portuguese pepper every sentence with 'tipo', just like Japanese youth overuse なんか. Not appropriate in formal speech.",
    cefrMin: "A2",
    tags: ["slang", "conversation"],
  },
  {
    id: "ja_ganda",
    type: "expression",
    contentPt: "Ganda / Granda",
    contentL1: "やばい! / すげー!",
    explanation: "Contraction of 'grande' — used as an intensifier. 'Ganda filme!' (やばい映画!), 'Granda maluco!' (すげーやつ!). Like やばい in its positive sense. Colloquial Lisbon slang, slightly vulgar — don't use with your 上司.",
    cefrMin: "B1",
    tags: ["slang"],
  },
  {
    id: "ja_bazar",
    type: "expression",
    contentPt: "Bazar",
    contentL1: "帰る / 行く (casual: ずらかる)",
    explanation: "'Bazar' means 'to leave/bounce'. 'Vou bazar' (もう帰る/ずらかる). Informal, like Japanese 帰る in casual form or ずらかる. The more formal version is 'ir-se embora': 'Vou-me embora' (帰ります).",
    cefrMin: "B1",
    tags: ["slang", "daily-life"],
  },
  {
    id: "ja_curtir",
    type: "expression",
    contentPt: "Curtir",
    contentL1: "楽しむ / 好き (slang: ハマる)",
    explanation: "'Curtir' means to enjoy or to be into something. 'Curto bué música portuguesa' (ポルトガル音楽にハマってる). 'Vamos curtir a noite' (夜を楽しもう). Also used for liking someone romantically. Like ハマる for hobbies or 好き for people.",
    cefrMin: "A2",
    tags: ["slang", "daily-life"],
  },
  {
    id: "ja_na_boa",
    type: "expression",
    contentPt: "Na boa",
    contentL1: "大丈夫 / 問題ない",
    explanation: "'Na boa' means 'no worries / it's all good'. 'Podes usar o meu carro, na boa' (私の車使っていいよ、大丈夫). Also used as a question: 'Tás na boa?' (大丈夫?). Like 大丈夫 — one of the most useful casual phrases in both languages.",
    cefrMin: "A1",
    tags: ["slang", "daily-life"],
  },
  {
    id: "ja_o_pa",
    type: "expression",
    contentPt: "Ó pá!",
    contentL1: "おい! / ねえ!",
    explanation: "The quintessential Portuguese interjection. 'Ó pá, não acredito!' (おい、マジかよ!). Used between friends, like おい or ねえ. Short for 'rapaz' (boy). Can express surprise, frustration, or just be a casual address between mates.",
    cefrMin: "A1",
    tags: ["slang", "daily-life"],
  },
  {
    id: "ja_mano",
    type: "expression",
    contentPt: "Mano / Mana",
    contentL1: "兄弟 / 姉妹 (友達への呼びかけ)",
    explanation: "Short for 'irmão/irmã' (brother/sister). Used as 'bro/sis' between close friends. 'Olha, mano, ouve lá...' (なあ兄弟、ちょっと聞いてくれ...). Very common in Lisbon, especially among young people in multicultural neighbourhoods.",
    cefrMin: "A2",
    tags: ["slang", "daily-life"],
  },
  {
    id: "ja_mandar_vir",
    type: "expression",
    contentPt: "Mandar vir",
    contentL1: "文句を言う / 注文する (二つの意味)",
    explanation: "Has two completely different meanings depending on context. 1) 'To complain/rant': 'Ele está sempre a mandar vir com tudo' (あいつはいつも文句ばっかり). 2) 'To order': 'Manda vir mais uma cerveja' (ビールもう一杯頼んで). Context always makes it clear.",
    cefrMin: "B1",
    tags: ["slang", "daily-life"],
  },
  {
    id: "ja_ta_se_bem",
    type: "expression",
    contentPt: "Tá-se bem",
    contentL1: "いいよ! / オッケー!",
    explanation: "Contraction of 'está-se bem' — 'it's all good'. Used to accept a proposal or confirm you're fine. 'Vamos ao cinema?' — 'Tá-se bem!' (映画行く?  — いいよ!). Very casual, very common.",
    cefrMin: "A1",
    tags: ["slang", "daily-life"],
  },
  // --- ANCIENT PROVERBS / PROVÉRBIOS ---
  {
    id: "ja_agua_pedra",
    type: "expression",
    contentPt: "Água mole em pedra dura, tanto bate até que fura",
    contentL1: "石の上にも三年 / 点滴石を穿つ",
    explanation: "Literally: 'Soft water on hard stone, hits until it pierces.' Persistence wins. Japanese has the nearly identical 点滴石を穿つ (dripping water pierces stone) and the cultural equivalent 石の上にも三年 (three years on a stone). Both Portuguese and Japanese cultures value persistent effort — 根気 (patience) and perseverance.",
    cefrMin: "B1",
    tags: ["proverb", "wisdom"],
  },
  {
    id: "ja_cao_gato",
    type: "expression",
    contentPt: "Quem não tem cão, caça com gato",
    contentL1: "無い袖は振れぬ → でも工夫する",
    explanation: "Literally: 'Who doesn't have a dog, hunts with a cat.' Make do with what you have. The proverb form of 'desenrascar-se'. Japanese has 無い袖は振れぬ (can't shake a sleeve you don't have), but this Portuguese proverb adds a positive twist — you find an alternative instead of giving up.",
    cefrMin: "B1",
    tags: ["proverb", "culture"],
  },
  {
    id: "ja_grao_galinha",
    type: "expression",
    contentPt: "Grão a grão, enche a galinha o papo",
    contentL1: "塵も積もれば山となる",
    explanation: "Literally: 'Grain by grain, the hen fills her crop.' Small things add up. Almost identical to Japanese 塵も積もれば山となる (even dust, piled up, becomes a mountain). Both proverbs celebrate the value of small, consistent effort.",
    cefrMin: "B1",
    tags: ["proverb", "wisdom"],
  },
  {
    id: "ja_pepino",
    type: "expression",
    contentPt: "De pequenino se torce o pepino",
    contentL1: "三つ子の魂百まで",
    explanation: "Literally: 'You bend the cucumber when it's small.' Meaning: habits are formed young. Japan has 三つ子の魂百まで (the soul of a three-year-old lasts until a hundred). Both cultures believe early education and discipline shape the adult.",
    cefrMin: "B1",
    tags: ["proverb", "education"],
  },
  {
    id: "ja_tripas_coracao",
    type: "expression",
    contentPt: "Fazer das tripas coração",
    contentL1: "腹を決める / 歯を食いしばる",
    explanation: "Literally: 'To make heart out of guts.' To summon courage when you have none. Like Japanese 腹を決める (to set one's belly = to steel oneself) or 歯を食いしばる (to grit your teeth). Origin may be linked to Porto, whose residents sent their meat to Age of Discovery fleets and ate only tripe — hence Porto's nickname 'cidade dos tripeiros'.",
    cefrMin: "B1",
    tags: ["proverb", "history", "porto"],
  },
  {
    id: "ja_ver_navios",
    type: "expression",
    contentPt: "Ficar a ver navios",
    contentL1: "待ちぼうけを食う / 空振りに終わる",
    explanation: "Literally: 'To be left watching ships.' To be left empty-handed or stood up. Origin: during the Age of Discoveries, women waited on the docks watching ships that never returned. Like Japanese 待ちぼうけを食う (to wait for nothing). 'Fiquei a ver navios' = 待ちぼうけだった.",
    cefrMin: "B1",
    tags: ["proverb", "history", "discoveries"],
  },
  {
    id: "ja_engolir_sapos",
    type: "expression",
    contentPt: "Engolir sapos",
    contentL1: "我慢する / 泣き寝入りする",
    explanation: "Literally: 'To swallow frogs.' To endure insults or unfair situations without reacting. Like Japanese 我慢する (to endure) or 泣き寝入りする (to cry yourself to sleep = to accept injustice silently). 'No trabalho, tenho de engolir muitos sapos' (仕事で色々我慢しなきゃ).",
    cefrMin: "B1",
    tags: ["proverb", "daily-life"],
  },
  {
    id: "ja_burros_agua",
    type: "expression",
    contentPt: "Dar com os burros na água",
    contentL1: "失敗する / 水の泡になる",
    explanation: "Literally: 'To end up with the donkeys in the water.' To fail, to have your plan go wrong. Like Japanese 水の泡になる (to turn to foam on water = to come to nothing). Origin: donkey drivers crossing rivers sometimes lost their donkeys and cargo to the current.",
    cefrMin: "B1",
    tags: ["proverb", "daily-life"],
  },
  {
    id: "ja_rossio_betesga",
    type: "expression",
    contentPt: "Meter o Rossio na Betesga",
    contentL1: "無理を通す / 不可能なことを試みる",
    explanation: "Literally: 'To fit the Rossio (Lisbon's grand square) into the Betesga (a tiny alley nearby).' Attempting the impossible — cramming something huge into something tiny. A purely Lisbon-born proverb from the Middle Ages. Like trying to fit Tokyo Station into a yokocho alley.",
    cefrMin: "B2",
    tags: ["proverb", "lisbon", "history"],
  },
  {
    id: "ja_mar_lugar",
    type: "expression",
    contentPt: "Quem vai ao mar, perde o lugar",
    contentL1: "席を外せば席を失う (早い者勝ち の逆)",
    explanation: "Literally: 'Who goes to sea, loses their place.' If you leave, someone else takes your spot. Maritime origin — fishermen who went to sea lost their seat at the tavern. Used today for parking spots, restaurant seats, any contested position. The flip side of 早い者勝ち.",
    cefrMin: "A2",
    tags: ["proverb", "maritime", "daily-life"],
  },
  // --- DAILY IDIOMS ---
  {
    id: "ja_ora_essa",
    type: "expression",
    contentPt: "Ora essa!",
    contentL1: "いえいえ! / とんでもない!",
    explanation: "An exclamation of modest denial when thanked or praised. 'Obrigado pela ajuda!' — 'Ora essa!' (ありがとう! — いえいえ!). Like Japanese いえいえ or とんでもない — both cultures value modesty when receiving thanks.",
    cefrMin: "A2",
    tags: ["daily-life", "etiquette"],
  },
  {
    id: "ja_descansado",
    type: "expression",
    contentPt: "Está descansado / Fica descansado",
    contentL1: "安心して / 心配しないで",
    explanation: "Literally: 'Be rested/at ease.' Means 'don't worry about it, I've got it covered.' 'Fica descansado, eu trato disso' (心配しないで、私がやるから). Like 安心して. Feminine form: 'Fica descansada'.",
    cefrMin: "A2",
    tags: ["daily-life", "conversation"],
  },
  {
    id: "ja_nao_faz_mal",
    type: "expression",
    contentPt: "Não faz mal",
    contentL1: "大丈夫です / 気にしないで",
    explanation: "Literally: 'It doesn't do harm.' The standard response when someone apologizes. 'Desculpa o atraso!' — 'Não faz mal!' (遅れてすみません! — 大丈夫ですよ!). Like Japanese 大丈夫 or 気にしないで. One of the first phrases you will hear and need.",
    cefrMin: "A1",
    tags: ["daily-life", "etiquette"],
  },
  {
    id: "ja_deixa_la",
    type: "expression",
    contentPt: "Deixa lá",
    contentL1: "まあいいよ / いいから",
    explanation: "'Deixa lá' means 'let it go / forget about it / never mind.' 'Queres que te pague?' — 'Deixa lá!' (払おうか? — いいからいいから!). Can also be consoling: 'Deixa lá, amanhã corre melhor' (まあいいよ、明日はうまくいくよ).",
    cefrMin: "A1",
    tags: ["daily-life", "conversation"],
  },
  {
    id: "ja_e_o_que_e",
    type: "expression",
    contentPt: "É o que é",
    contentL1: "しょうがない / 仕方ない",
    explanation: "The Portuguese 'it is what it is' — a philosophical acceptance of things you can't change. 'O preço subiu? É o que é.' (値上がりした? しょうがない). Almost identical to Japanese しょうがない — both cultures have this fatalistic acceptance alongside their 'desenrascar' / なんとかする resourcefulness.",
    cefrMin: "A2",
    tags: ["daily-life", "culture"],
  },
  {
    id: "ja_olha_la",
    type: "expression",
    contentPt: "Olha lá / Ouve lá",
    contentL1: "ねえ / ちょっと / すみません",
    explanation: "'Olha lá' (look here) and 'ouve lá' (listen here) are used to get attention or start a question. 'Olha lá, sabes onde fica o correio?' (ねえ、郵便局どこか知ってる?). Like ねえ or ちょっと — the standard way to approach someone. Not rude.",
    cefrMin: "A1",
    tags: ["daily-life", "conversation"],
  },
  {
    id: "ja_entao",
    type: "expression",
    contentPt: "Então?",
    contentL1: "で? / それで? / 元気?",
    explanation: "'Então?' is the universal Portuguese greeting-question. 'Então, tudo bem?' (で、元気?). Also used to prompt: 'Então, o que queres fazer?' (で、何したい?). Like Japanese で? or それで? — short, warm, multipurpose.",
    cefrMin: "A1",
    tags: ["daily-life", "conversation"],
  },
  {
    id: "ja_se_calhar",
    type: "expression",
    contentPt: "Se calhar",
    contentL1: "たぶん / もしかしたら",
    explanation: "Literally: 'if it falls (that way).' Means 'maybe / perhaps.' 'Se calhar vou ao cinema amanhã' (たぶん明日映画行く). More common than 'talvez' in everyday speech. Like たぶん. Note: in PT-EU this does NOT trigger the subjunctive, unlike 'talvez'.",
    cefrMin: "A2",
    tags: ["daily-life", "grammar"],
  },
  {
    id: "ja_com_certeza",
    type: "expression",
    contentPt: "Com certeza",
    contentL1: "もちろん / かしこまりました (注意: 本気じゃない場合も)",
    explanation: "'Com certeza' means 'certainly / of course.' BUT be careful: in PT-EU it is often used as a polite but non-committal agreement — like saying もちろん without really meaning it. A Portuguese 'com certeza' can mean 'I'll think about it' (and then forget). Similar to how Japanese はい doesn't always mean real agreement.",
    cefrMin: "A2",
    tags: ["daily-life", "etiquette", "culture"],
  },
];
