import type { CulturalRef } from "../types.js";

export const jaCulturalRefs: readonly CulturalRef[] = [
  {
    id: "ja_saudade",
    type: "expression",
    contentPt: "Saudade",
    contentL1: "懐かしさ / 切なさ / もののあはれ",
    explanation: "Japanese 'もののあはれ' (mono no aware — the bittersweet awareness of impermanence) is perhaps the closest cultural concept to saudade. Both describe a melancholy that is beautiful, not to be cured. Fado and 演歌 share this emotional register.",
    cefrMin: "B1",
    tags: ["culture", "emotion"],
  },
  {
    id: "ja_tanegashima",
    type: "reference",
    contentPt: "Os Portugueses no Japão",
    contentL1: "南蛮人 — ポルトガル人の来日 (1543)",
    explanation: "Portuguese were the first Europeans to reach Japan in 1543. They brought firearms (鉄砲), tempura, and the word 'パン' (pão = bread). Many Japanese words come from Portuguese: カステラ (castella), コンペイトウ (compota), カッパ (capa), ボタン (botão).",
    cefrMin: "A2",
    tags: ["history", "vocabulary"],
  },
  {
    id: "ja_tempura",
    type: "reference",
    contentPt: "Tempura — origem portuguesa",
    contentL1: "天ぷら = têmporas (portuguese)",
    explanation: "Japanese 天ぷら comes from Portuguese 'têmporas' — meatless days when fried fish was eaten. The Portuguese missionaries brought this cooking technique to Japan in the 16th century. When eating 天ぷら you are tasting 500 years of Portuguese-Japanese connection.",
    cefrMin: "A2",
    tags: ["food", "history", "vocabulary"],
  },
  {
    id: "ja_pan_pao",
    type: "reference",
    contentPt: "Pão",
    contentL1: "パン (pãoから来た言葉)",
    explanation: "Japanese 'パン' (pan/bread) comes directly from Portuguese 'pão'. Other Portuguese loanwords in Japanese: カルタ (carta=card), コップ (copo=cup), タバコ (tabaco), シャボン (sabão=soap). You already know more Portuguese than you think.",
    cefrMin: "A1",
    tags: ["vocabulary", "history"],
  },
  {
    id: "ja_fixe",
    type: "expression",
    contentPt: "Fixe!",
    contentL1: "すごい! / いいね!",
    explanation: "'Fixe' means 'cool'. Use it like すごい or いいね. 'Que fixe!' = めっちゃいいね!",
    cefrMin: "A1",
    tags: ["slang", "daily-life"],
  },
  {
    id: "ja_pois",
    type: "expression",
    contentPt: "Pois...",
    contentL1: "まあ... / そうだね...",
    explanation: "'Pois' is the most versatile Portuguese filler, like Japanese まあ or そうだね. It fills pauses and expresses agreement or resignation. Very similar function to あいづち (aizuchi).",
    cefrMin: "A1",
    tags: ["conversation", "daily-life"],
  },
  {
    id: "ja_pasteis",
    type: "reference",
    contentPt: "Pastéis de nata",
    contentL1: "エッグタルト (ポルトガルのオリジナル)",
    explanation: "The original egg tart — what Macau and then all of Asia adapted. Crispy, flaky pastry with caramelized custard. About one euro each. Like カステラ, this is another Portuguese-origin sweet that Japanese speakers already know indirectly.",
    cefrMin: "A1",
    tags: ["food", "culture"],
  },
  {
    id: "ja_fado",
    type: "reference",
    contentPt: "Fado",
    contentL1: "演歌のような感情的な音楽",
    explanation: "Fado shares the emotional register of Japanese 演歌 (enka) — both are about fate, loss, and longing. The solo voice, the restrained accompaniment, the valued melancholy. Amália Rodrigues is fado's greatest voice, like 美空ひばり is to enka.",
    cefrMin: "B1",
    tags: ["music", "culture"],
  },
  {
    id: "ja_25_abril",
    type: "reference",
    contentPt: "25 de Abril — Revolução dos Cravos",
    contentL1: "カーネーション革命 (1974)",
    explanation: "On April 25, 1974, Portugal peacefully overthrew its dictatorship. Soldiers put carnations in their rifles. This revolution defines modern Portugal.",
    cefrMin: "B1",
    tags: ["history", "identity"],
  },
  {
    id: "ja_pronto",
    type: "expression",
    contentPt: "Pronto!",
    contentL1: "よし! / できた!",
    explanation: "'Pronto' = done/ready/OK then. Like よし or できた. 'Pronto, vamos!' = よし、行こう!",
    cefrMin: "A1",
    tags: ["daily-life", "conversation"],
  },
  {
    id: "ja_politeness",
    type: "reference",
    contentPt: "Tu vs O Senhor",
    contentL1: "ため口 vs です/ます",
    explanation: "Like Japanese ため口/ですます, Portuguese has 'tu' (informal) and 'o senhor/a senhora' (formal). Japanese speakers will naturally understand this formality system. Avoid 'você' in Portugal — it can sound cold, like using plain form with a superior.",
    cefrMin: "A1",
    tags: ["social", "etiquette"],
  },
  {
    id: "ja_bacalhau",
    type: "reference",
    contentPt: "Bacalhau",
    contentL1: "塩鰕 (365のレシピ)",
    explanation: "Salt cod is Portugal's national ingredient — 365 recipes. Japan also has a deep tradition of preserved fish (干物, 塩进). The Japanese appreciation for umami will make bacalhau instantly appealing.",
    cefrMin: "A2",
    tags: ["food", "culture"],
  },
  {
    id: "ja_azulejo",
    type: "reference",
    contentPt: "Azulejos",
    contentL1: "タイル芸術 (染付のような青と白)",
    explanation: "Portugal's blue and white ceramic tiles echo the aesthetics of Japanese 染付 (sometsuke) blue and white ceramics. Both traditions value the beauty of blue on white. The craft has Islamic and Chinese roots that reached both cultures through different trade routes.",
    cefrMin: "A2",
    tags: ["art", "culture"],
  },
  {
    id: "ja_desenrascar",
    type: "expression",
    contentPt: "Desenrascar-se",
    contentL1: "なんとかする",
    explanation: "The art of improvising solutions. Like Japanese なんとかする. Both cultures value finding a way through when the formal path is blocked.",
    cefrMin: "B1",
    tags: ["culture", "daily-life"],
  },
  {
    id: "ja_nas_tintas",
    type: "expression",
    contentPt: "Estar-se nas tintas",
    contentL1: "どうでもいい / 知らない",
    explanation: "Literally 'to be in the paints' — couldn't care less. Like どうでもいい. Very common, mildly rude.",
    cefrMin: "B1",
    tags: ["slang", "emotion"],
  },
];
