import type { L1Profile } from "../types.js";

export const jaProfile: L1Profile = {
  code: "ja",
  name: "Japanese",
  nativeName: "日本語",
  writingDirection: "ltr",
  hasLatinScript: false,
  transfer: {
    cognates: [
      "パン pan (pão — bread, from Portuguese missionaries)",
      "テンプラ tenpura (tempura — deep-fried food, from Portuguese 'tempero')",
      "カステラ kasutera (castella — sponge cake, from Portuguese 'pão de Castela')",
      "ボタン botan (botão — button)",
      "コップ koppu (copo — glass/cup)",
      "タバコ tabako (tabaco — tobacco)",
      "カッパ kappa (capa — cape/raincoat)",
      "シャボン shabon (sabão — soap)",
      "ビロード biródo (veludo — velvet)",
      "コンペイトウ konpeitō (confeito — sugar candy)",
      "カルタ karuta (carta — card/playing cards)",
      "ビードロ bīdoro (vidro — glass)",
      "メリヤス meriyasu (meias — socks/stockings)",
      "ジュバン juban (gibão — jacket/doublet)",
      "イギリス igirisu (inglês — English/England)",
      "フラスコ furasuko (frasco — flask)",
      "バッテラ battera (bateira — small boat, used for sushi type)",
      "チャルメラ charumera (charamela — oboe/shawm)",
      "オルガン orugan (órgão — organ, musical instrument)",
      "キリシタン kirishitan (cristão — Christian)",
      "サラサ sarasa (saraça — chintz fabric, via Portuguese India trade)",
      "ラシャ rasha (raxa — broadcloth/fine wool)",
      "ミイラ miira (mirra — myrrh, came to mean mummy)",
      "ジョウロ jōro (jarro — watering can/pitcher)",
      "キャラメル kyarameru (caramelo — caramel)",
      "マント manto (manto — cloak/mantle)",
      "サボテン saboten (sabão — cactus, folk etymology via 'soap plant')",
      "デッキ dekki (from Portuguese 'deque' — deck)",
      "カナリヤ kanariya (canário — canary bird)",
      "ブランコ buranko (balanço — swing, playground equipment)",
    ],
    falseFriends: [
      { word: "pão", l1Meaning: "パン (pan) — Japanese adopted this from Portuguese! Means bread in both", ptMeaning: "pão means bread — one of the few direct Portuguese-Japanese cognates. A true friend!" },
      { word: "copo", l1Meaning: "コップ (koppu) — also from Portuguese! Means glass/cup in both", ptMeaning: "copo means glass/cup — another true friend from the Portuguese mission period" },
      { word: "carta", l1Meaning: "カルタ (karuta) — became a card game in Japanese", ptMeaning: "carta means 'letter' primarily — playing cards = cartas de jogar" },
      { word: "dia", l1Meaning: "sounds like 'jia' — no Japanese word", ptMeaning: "dia means 'day' — 'bom dia' = good morning" },
      { word: "pai", l1Meaning: "パイ (pai) — pie (English loanword)", ptMeaning: "pai means 'father'" },
      { word: "mal", l1Meaning: "マル (maru) — circle/correct", ptMeaning: "mal means 'badly/evil'" },
      { word: "sala", l1Meaning: "サラ (sara) — plate/dish or a common name", ptMeaning: "sala means 'room/living room'" },
      { word: "bar", l1Meaning: "バー (baa) — bar/pub (same)", ptMeaning: "bar — true cognate" },
      { word: "bola", l1Meaning: "ボーラ (bōra) — no standard meaning", ptMeaning: "bola means 'ball'" },
      { word: "sol", l1Meaning: "ソル (soru) — sounds like 'to shave'", ptMeaning: "sol means 'sun'" },
      { word: "campo", l1Meaning: "カンポ — no standard Japanese meaning", ptMeaning: "campo means 'field/countryside'" },
      { word: "manga", l1Meaning: "漫画 (manga) — comics/graphic novels", ptMeaning: "manga primarily means 'sleeve' — also means mango. NOT Japanese-style comics" },
      { word: "comer", l1Meaning: "コメル — sounds like 米 (kome, rice)", ptMeaning: "comer means 'to eat' — rice = arroz" },
      { word: "largo", l1Meaning: "ラルゴ — music term (broadly)", ptMeaning: "largo means 'wide' or 'public square'" },
      { word: "mar", l1Meaning: "マル (maru) — circle/correct mark", ptMeaning: "mar means 'sea/ocean'" },
      { word: "ser", l1Meaning: "セル (seru) — cell (loanword)", ptMeaning: "ser means 'to be' (identity/permanent)" },
      { word: "ter", l1Meaning: "テル (teru) — to shine/clear up", ptMeaning: "ter means 'to have'" },
      { word: "porta", l1Meaning: "ポルタ — no standard meaning (ドア = door)", ptMeaning: "porta means 'door'" },
      { word: "banco", l1Meaning: "バンコ — no Japanese meaning (銀行 = bank)", ptMeaning: "banco means 'bank' or 'bench'" },
      { word: "gato", l1Meaning: "ガト — sounds like ガトー (gâteau/cake)", ptMeaning: "gato means 'cat' — cake = bolo" },
      { word: "cola", l1Meaning: "コーラ (kōra) — cola drink", ptMeaning: "cola means 'glue' — cola drink = Coca-Cola" },
      { word: "caro", l1Meaning: "カロ — no standard meaning (高い = expensive)", ptMeaning: "caro means 'expensive' or 'dear'" },
      { word: "dar", l1Meaning: "ダル — sounds like だるい (darui, sluggish)", ptMeaning: "dar means 'to give' — sluggish = preguiçoso" },
      { word: "conta", l1Meaning: "コンタ — sounds like コンタクト (contact)", ptMeaning: "conta means 'bill/account/story'" },
      { word: "mala", l1Meaning: "マラ — no standard meaning", ptMeaning: "mala means 'suitcase/bag'" },
      { word: "rua", l1Meaning: "ルア — sounds like ルアー (ruaa, fishing lure)", ptMeaning: "rua means 'street' — fishing lure = engodo" },
      { word: "fala", l1Meaning: "ファラ — no standard meaning", ptMeaning: "fala means 'speaks' or 'speech'" },
      { word: "cama", l1Meaning: "カマ (kama) — sickle/scythe, or 釜 (kama, cooking pot)", ptMeaning: "cama means 'bed' — sickle = foice, pot = panela" },
      { word: "nome", l1Meaning: "ノメ — sounds like 飲め (nome, 'drink!' imperative)", ptMeaning: "nome means 'name' — to drink = beber" },
      { word: "massa", l1Meaning: "マッサ — sounds like マッサージ (massage)", ptMeaning: "massa means 'dough/pasta' — massage = massagem" },
      { word: "nota", l1Meaning: "ノタ — no direct meaning", ptMeaning: "nota means 'grade/mark' AND 'banknote'" },
      { word: "pasta", l1Meaning: "パスタ (pasuta) — pasta (Italian food)", ptMeaning: "pasta means 'folder/briefcase' — pasta food = massa" },
      { word: "data", l1Meaning: "ダタ — sounds like データ (deeta, data)", ptMeaning: "data means 'date' (calendar), not digital data — dados = data" },
      { word: "pena", l1Meaning: "ペナ — sounds like ペナルティ (penalty)", ptMeaning: "pena means 'feather' AND 'pity' AND 'penalty' — all three meanings" },
      { word: "forma", l1Meaning: "フォルマ — no standard meaning (形 = shape)", ptMeaning: "forma means 'form/shape/mould'" },
      { word: "lista", l1Meaning: "リスタ — sounds like リスト (risuto, list/wrist)", ptMeaning: "lista means 'list' AND 'menu' — wrist = pulso" },
      { word: "casa", l1Meaning: "カサ (kasa) — 傘 (umbrella) or 笠 (sedge hat)", ptMeaning: "casa means 'house/home' — umbrella = guarda-chuva, hat = chapéu" },
      { word: "prima", l1Meaning: "プリマ — prima donna/ballerina", ptMeaning: "prima means 'female cousin' — primo = male cousin" },
      { word: "dom", l1Meaning: "ドム — sounds like ドーム (doomu, dome)", ptMeaning: "dom means 'Mr/Sir' (title) or 'gift/talent' — dome = cúpula" },
      { word: "taça", l1Meaning: "タサ — no standard meaning (カップ = cup)", ptMeaning: "taça means 'trophy/wine glass/goblet' — cup = chávena" },
    ],
    phoneticDifficulties: [
      {
        sound: "ão",
        ipa: "/ɐ̃w̃/",
        description: "Nasal diphthong -ão",
        tip: "Japanese has no nasal vowels (ん before vowels is a consonant). This is a completely new sound: nasalize 'a' while gliding to rounded 'u'. Keep air flowing through the nose. Practice: pão, mão, não.",
        mouthPosition: "nasal_ao",
      },
      {
        sound: "ã/õ/ẽ",
        ipa: "/ɐ̃/ /õ/ /ẽ/",
        description: "Nasal vowels",
        tip: "Japanese ん (n) is a nasal consonant, not a nasal vowel. PT-EU nasalizes the entire vowel — air flows through the nose throughout. 'Maçã' (apple), 'limão' (lemon). Entirely new articulation.",
        mouthPosition: "nasal_vowel",
      },
      {
        sound: "r/l distinction",
        ipa: "/ɾ/ vs /l/ vs /ʁ/",
        description: "Three distinct liquids where Japanese has one",
        tip: "Japanese ら行 (ra-ri-ru-re-ro) is a single flap. PT-EU has THREE: tap /ɾ/ (caro — like Japanese r), dark L /ɫ/ (sol — touch alveolar ridge, hold), uvular R /ʁ/ (rato — back of throat). Each one is different.",
        mouthPosition: "uvular_r",
      },
      {
        sound: "lh",
        ipa: "/ʎ/",
        description: "Palatal lateral lh",
        tip: "No Japanese equivalent. Press the middle of your tongue flat against the hard palate while air flows around the sides. 'Trabalho' (work), 'filho' (son). Like Italian 'gli'.",
        mouthPosition: "palatal_lateral",
      },
      {
        sound: "nh",
        ipa: "/ɲ/",
        description: "Palatal nasal nh",
        tip: "Similar to Japanese に (ni) but more palatal. Tongue on the palate while nasalizing. 'Vinho' (wine), 'amanhã' (tomorrow), 'Espanha' (Spain).",
        mouthPosition: "palatal_nasal",
      },
      {
        sound: "f/v",
        ipa: "/f/ /v/",
        description: "Labiodental fricatives",
        tip: "Japanese フ (fu) is bilabial, not labiodental. PT-EU /f/ and /v/ need upper teeth touching lower lip. /v/ adds vocal cord vibration. 'Falar' (speak) vs 'valer' (be worth).",
        mouthPosition: "labiodental_v",
      },
      {
        sound: "consonant clusters",
        ipa: "/pr/ /tr/ /pl/ /str/",
        description: "Initial consonant clusters",
        tip: "Japanese follows strict CV patterns — no clusters (English 'street' becomes ストリート). PT-EU stacks consonants: 'prato' (plate), 'três' (three). Do not insert vowels between consonants.",
      },
      {
        sound: "b/d/g",
        ipa: "/b/ /d/ /g/",
        description: "Voiced stops",
        tip: "Japanese has voiced stops (ば/だ/が). PT-EU voiced stops are similar. Your Japanese voicing is correct — 'bom' (good), 'dar' (give), 'gato' (cat). One of the easier transfers.",
      },
      {
        sound: "reduced vowels",
        ipa: "/ɨ/ /ə/",
        description: "Unstressed vowels nearly vanish",
        tip: "Japanese pronounces every mora evenly. PT-EU swallows unstressed vowels — 'telefonema' sounds like 'tlfnema'. Japanese speakers find this the hardest rhythm adjustment.",
        mouthPosition: "closed_e",
      },
      {
        sound: "s/z/ʃ/ʒ",
        ipa: "/s/ /z/ /ʃ/ /ʒ/",
        description: "Four sibilants",
        tip: "Japanese has s, z, sh (し), j (じ). PT-EU maps: final 's' = /ʃ/ (sh), 's' between vowels = /z/, 'j' = /ʒ/ (like じ but as a fricative). The sounds are familiar, just the spelling differs.",
        mouthPosition: "sibilant_sh",
      },
      {
        sound: "word stress",
        ipa: "variable",
        description: "Unpredictable stress patterns",
        tip: "Japanese uses pitch accent, not stress. PT-EU uses stress (louder + longer syllable). Stress changes meaning: 'sábia' (wise woman) vs 'sabiá' (a bird). Written accents help mark irregular stress.",
      },
      {
        sound: "open/closed vowels",
        ipa: "/ɛ/ vs /e/, /ɔ/ vs /o/",
        description: "Vowel height contrasts",
        tip: "Japanese has only 5 vowels with no open/closed distinction. PT-EU doubles e and o: 'é' (open, café) vs 'ê' (closed, você), 'ó' (open, avó) vs 'ô' (closed, avô). The accent mark guides you.",
        mouthPosition: "open_e",
      },
      {
        sound: "dark L",
        ipa: "/ɫ/",
        description: "Velarized L at end of syllables",
        tip: "Japanese has no L at all — ら行 is a flap. PT-EU final L is dark and velarized, with the back of the tongue raised. It sounds almost like a 'w'. 'Portugal', 'sol' (sun), 'mal' (badly). Distinct from the tap r.",
        mouthPosition: "alveolar_tap",
      },
      {
        sound: "diphthongs (ei, ou, ai)",
        ipa: "/ɐj/ /ow/ /aj/",
        description: "Oral diphthongs — smooth glides between vowels",
        tip: "Japanese diphthongs tend to be two separate morae (あい = a-i). PT-EU diphthongs glide within one syllable: 'pai' (father, /aj/), 'coisa' (thing, /oj/), 'eu' (I, /ew/). Keep them as single beats, not two.",
        mouthPosition: "open_e",
      },
      {
        sound: "word-final -e",
        ipa: "/ɨ/ or silent",
        description: "Final -e nearly disappears",
        tip: "Japanese always gives every mora equal weight. PT-EU final -e is barely a whisper or drops entirely. 'Cidade' sounds like 'cidadɨ' or even 'cidad'. Do not pronounce it as a full え (e).",
        mouthPosition: "closed_e",
      },
    ],
    grammarGaps: [
      {
        concept: "Articles (o/a, um/uma)",
        explanation: "Every noun requires a definite or indefinite article",
        l1Comparison: "Japanese has no articles. You must say 'o livro' (the book), not just 'livro'. Articles signal gender (masculine o / feminine a) and definiteness (the/a). No Japanese parallel exists.",
      },
      {
        concept: "Grammatical gender",
        explanation: "Every noun is masculine or feminine, affecting articles and adjectives",
        l1Comparison: "Japanese has no grammatical gender. PT-EU assigns gender to all nouns: 'o sol' (sun, m), 'a lua' (moon, f). Adjectives change too: 'bonito' (m) vs 'bonita' (f). Memorize the article with each noun.",
      },
      {
        concept: "SVO word order",
        explanation: "Subject-Verb-Object is the default",
        l1Comparison: "Japanese is SOV with particles (私は本を読んだ). PT-EU is SVO: 'Eu li o livro' (I read the book). The verb moves to the middle. No particles needed — position shows function.",
      },
      {
        concept: "Verb conjugation",
        explanation: "6 person forms × 12+ tenses across 3 moods",
        l1Comparison: "Japanese conjugates for tense and politeness but not person. PT-EU conjugates for PERSON: eu falo, tu falas, ele fala... You must match the verb to who is speaking/acting.",
      },
      {
        concept: "Ser vs Estar",
        explanation: "Two verbs for 'to be'",
        l1Comparison: "Japanese です/だ (desu/da) for description, いる/ある (iru/aru) for existence. This mirrors ser/estar somewhat: 'Sou japonês' (I am Japanese — ser/です) vs 'Estou aqui' (I am here — estar/いる).",
      },
      {
        concept: "Prepositions (not particles)",
        explanation: "de, em, a, para, com, por — come BEFORE the noun",
        l1Comparison: "Japanese uses particles AFTER nouns (に/で/の/を). PT-EU prepositions precede: 'em Lisboa' (in Lisbon), 'de Portugal' (from Portugal). They contract with articles: em+o=no.",
      },
      {
        concept: "Plural formation",
        explanation: "Add -s or -es, articles change too",
        l1Comparison: "Japanese rarely marks plurals. PT-EU always does: 'livro' → 'livros', 'o' → 'os'. Every countable noun must show number. Articles agree: 'o livro' → 'os livros'.",
      },
      {
        concept: "Subjunctive mood",
        explanation: "Required for doubt, desire, emotion",
        l1Comparison: "Japanese has no subjunctive. It uses different endings for conditionals (-たら/-ば). PT-EU requires specific verb forms: 'Espero que venhas' (I hope you come) — 'venhas' is subjunctive.",
      },
      {
        concept: "Personal infinitive",
        explanation: "Infinitive conjugated for person — unique to Portuguese",
        l1Comparison: "No Japanese equivalent. 'Para nós fazermos' (for us to do) — the infinitive gets a personal ending. This replaces what would be a full clause in Japanese.",
      },
      {
        concept: "Adjective agreement and position",
        explanation: "Adjectives agree in gender/number and usually follow the noun",
        l1Comparison: "Japanese adjectives precede nouns and never change for gender/number. PT-EU adjectives follow AND agree: 'casa bonita' (f), 'livro bonito' (m), 'casas bonitas' (f.pl).",
      },
      {
        concept: "Tu vs Você vs O Senhor",
        explanation: "Three formality levels for 'you'",
        l1Comparison: "Japanese has elaborate politeness levels (敬語). PT-EU is simpler with three levels: 'tu' (intimate), 'você' (neutral), 'o senhor/a senhora' (formal). In Portugal, 'tu' is standard among peers.",
      },
      {
        concept: "Object pronoun placement",
        explanation: "Before or after the verb depending on triggers",
        l1Comparison: "Japanese puts objects before the verb (私を見て). PT-EU has complex rules: 'Vê-me' (see me, after) vs 'Não me vê' (doesn't see me, before). Position depends on sentence context.",
      },
      {
        concept: "Reflexive verbs",
        explanation: "Many common verbs need a reflexive pronoun (se)",
        l1Comparison: "Japanese has no reflexive system. PT-EU uses reflexives constantly: 'Chamo-me Ana' (My name is Ana, lit. I call myself Ana), 'Levanto-me' (I get up). The pronoun changes with person.",
      },
      {
        concept: "Preposition contractions",
        explanation: "Mandatory: em+o=no, de+a=da, a+o=ao, por+o=pelo",
        l1Comparison: "Japanese particles never merge. PT-EU contractions are mandatory and frequent: 'no' (em + o), 'da' (de + a). You cannot separate them.",
      },
      {
        concept: "Continuous with 'estar a + infinitive'",
        explanation: "'Estou a trabalhar' = I am working (PT-EU form)",
        l1Comparison: "Japanese uses -ている (-te iru) for ongoing actions, which is conceptually similar. PT-EU uses 'estar a + infinitive': 'Estou a ler' (I am reading). The Brazilian gerund form ('estou lendo') is not PT-EU.",
      },
    ],
    skipBasics: false,
    startingCEFR: "A1",
  },
};
