import type { CulturalRef } from "../types.js";

export const koCulturalRefs: readonly CulturalRef[] = [
  {
    id: "ko_saudade",
    type: "expression",
    contentPt: "Saudade",
    contentL1: "그리움 / 한 (han)",
    explanation: "Korean '한' (han) — a deep, collective sorrow — and '그리움' (longing) together approximate saudade. Both cultures value melancholy as an emotion worth expressing through art: fado in Portugal, 판소리 (pansori) in Korea.",
    cefrMin: "B1",
    tags: ["culture", "emotion"],
  },
  {
    id: "ko_fixe",
    type: "expression",
    contentPt: "Fixe!",
    contentL1: "대박! / 멋져!",
    explanation: "'Fixe' means 'cool'. Use it like 대박 or 멋져. 'Que fixe!' = 완전 대박!",
    cefrMin: "A1",
    tags: ["slang", "daily-life"],
  },
  {
    id: "ko_pois",
    type: "expression",
    contentPt: "Pois...",
    contentL1: "음... / 그러니까...",
    explanation: "'Pois' is the most versatile Portuguese filler, like Korean 음 or 그러니까. It fills pauses and expresses agreement or hesitation.",
    cefrMin: "A1",
    tags: ["conversation", "daily-life"],
  },
  {
    id: "ko_pasteis",
    type: "reference",
    contentPt: "Pastéis de nata",
    contentL1: "에그타르트 (포르투갈 오리지널)",
    explanation: "Korea's egg tart trend comes from the Portuguese original. What Korean bakeries sell as 에그타르트 is a pastél de nata — the original from Belém is richer and more caramelized. About one euro each in Portugal.",
    cefrMin: "A1",
    tags: ["food", "culture"],
  },
  {
    id: "ko_fado",
    type: "reference",
    contentPt: "Fado",
    contentL1: "판소리처럼 감정적인 음악",
    explanation: "Fado's emotional depth parallels Korean pansori — both are vocal traditions where a singer channels deep emotion. Both value 한 (han) and saudade: the beauty in sorrow.",
    cefrMin: "B1",
    tags: ["music", "culture"],
  },
  {
    id: "ko_coffee",
    type: "reference",
    contentPt: "Uma bica / um galão",
    contentL1: "에스프레소 / 라떼",
    explanation: "Portugal and Korea both have intense coffee cultures. In Lisbon, espresso is called 'bica'. Portuguese drink it standing at the counter in two sips. Different ritual from Korean 카페 culture, but equally obsessive.",
    cefrMin: "A1",
    tags: ["food", "daily-life"],
  },
  {
    id: "ko_25_abril",
    type: "reference",
    contentPt: "25 de Abril — Revolução dos Cravos",
    contentL1: "카네이션 혁명 (1974)",
    explanation: "Portugal's 1974 peaceful revolution ended decades of dictatorship. Soldiers put carnations in their rifles. Koreans, familiar with their own democratic struggle (민주화 운동), can appreciate this watershed moment.",
    cefrMin: "B1",
    tags: ["history", "identity"],
  },
  {
    id: "ko_pronto",
    type: "expression",
    contentPt: "Pronto!",
    contentL1: "됐! / 준비 됐!",
    explanation: "'Pronto' = done/ready/OK then. Like 됐 or 준비 됐. 'Pronto, vamos!' = 됐, 가자!",
    cefrMin: "A1",
    tags: ["daily-life", "conversation"],
  },
  {
    id: "ko_skincare",
    type: "reference",
    contentPt: "Cuidados com a pele",
    contentL1: "피부 관리 (한국 vs 포르투갈)",
    explanation: "Korean and Portuguese cultures both value skincare. Portuguese women have traditionally used olive oil, rosehip oil, and thermal waters. Different approach from K-beauty's multi-step routine, but the cultural value placed on skin health is shared.",
    cefrMin: "A2",
    tags: ["culture", "daily-life"],
  },
  {
    id: "ko_family",
    type: "reference",
    contentPt: "Família é tudo",
    contentL1: "가족이 제일 중요해",
    explanation: "Like Korean culture, Portuguese culture is deeply family-oriented. Respect for elders, Sunday family lunches, and strong family bonds are central. Korean speakers will recognize this family-first attitude.",
    cefrMin: "A2",
    tags: ["culture", "family"],
  },
  {
    id: "ko_azulejo",
    type: "reference",
    contentPt: "Azulejos",
    contentL1: "타일 예술 (청화백자 같은)",
    explanation: "Portugal's blue and white ceramic tiles echo Korean 청화백자 (blue and white porcelain). Both traditions value blue decorative art. The Portuguese style was influenced by Islamic and Chinese ceramics via trade.",
    cefrMin: "A2",
    tags: ["art", "culture"],
  },
  {
    id: "ko_santos",
    type: "reference",
    contentPt: "Festas dos Santos Populares",
    contentL1: "축제 (사람들이 거리에서 노는 축제)",
    explanation: "Every June, streets fill with grilled sardines, music, and dancing. The communal street food atmosphere is like Korean 야시장 culture — eating together outdoors is the whole point.",
    cefrMin: "A2",
    tags: ["culture", "festivals"],
  },
  {
    id: "ko_desenrascar",
    type: "expression",
    contentPt: "Desenrascar-se",
    contentL1: "대충 해결하다 / 어떻게든 하다",
    explanation: "The art of improvising solutions. Like Korean 대충 or 어떻게든. Both cultures celebrate resourcefulness and getting things done creatively.",
    cefrMin: "B1",
    tags: ["culture", "daily-life"],
  },
  {
    id: "ko_hierarchy",
    type: "reference",
    contentPt: "Tu vs O Senhor",
    contentL1: "반말 vs 존댓말",
    explanation: "Like Korean 반말/존댓말, Portuguese has informal 'tu' and formal 'o senhor/a senhora'. Korean speakers will naturally understand the social hierarchy in language. Avoid 'você' in Portugal — it sounds cold.",
    cefrMin: "A1",
    tags: ["social", "etiquette"],
  },
  {
    id: "ko_nas_tintas",
    type: "expression",
    contentPt: "Estar-se nas tintas",
    contentL1: "상관없어 / 알 바 아니야",
    explanation: "Literally 'to be in the paints' — couldn't care less. Like 상관없어. Very common, mildly rude.",
    cefrMin: "B1",
    tags: ["slang", "emotion"],
  },
];
