import type { CulturalRef } from "../types.js";

export const koCulturalRefs: readonly CulturalRef[] = [
  {
    id: "ko_saudade",
    type: "expression",
    contentPt: "Saudade",
    contentL1: "그리움 / 한 (han)",
    explanation: "Korean '한' (han) — a deep, collective sorrow — and '그리움' (longing) together approximate saudade. Both cultures value melancholy as an emotion worth expressing through art: fado in Portugal, 판소리 (pansori) in Korea.",
    cefrMin: "B1",
    tags: ["culture", "emotion"],
  },
  {
    id: "ko_fixe",
    type: "expression",
    contentPt: "Fixe!",
    contentL1: "대박! / 멋져!",
    explanation: "'Fixe' means 'cool'. Use it like 대박 or 멋져. 'Que fixe!' = 완전 대박!",
    cefrMin: "A1",
    tags: ["slang", "daily-life"],
  },
  {
    id: "ko_pois",
    type: "expression",
    contentPt: "Pois...",
    contentL1: "음... / 그러니까...",
    explanation: "'Pois' is the most versatile Portuguese filler, like Korean 음 or 그러니까. It fills pauses and expresses agreement or hesitation.",
    cefrMin: "A1",
    tags: ["conversation", "daily-life"],
  },
  {
    id: "ko_pasteis",
    type: "reference",
    contentPt: "Pastéis de nata",
    contentL1: "에그타르트 (포르투갈 오리지널)",
    explanation: "Korea's egg tart trend comes from the Portuguese original. What Korean bakeries sell as 에그타르트 is a pastél de nata — the original from Belém is richer and more caramelized. About one euro each in Portugal.",
    cefrMin: "A1",
    tags: ["food", "culture"],
  },
  {
    id: "ko_fado",
    type: "reference",
    contentPt: "Fado",
    contentL1: "판소리처럼 감정적인 음악",
    explanation: "Fado's emotional depth parallels Korean pansori — both are vocal traditions where a singer channels deep emotion. Both value 한 (han) and saudade: the beauty in sorrow.",
    cefrMin: "B1",
    tags: ["music", "culture"],
  },
  {
    id: "ko_coffee",
    type: "reference",
    contentPt: "Uma bica / um galão",
    contentL1: "에스프레소 / 라떼",
    explanation: "Portugal and Korea both have intense coffee cultures. In Lisbon, espresso is called 'bica'. Portuguese drink it standing at the counter in two sips. Different ritual from Korean 카페 culture, but equally obsessive.",
    cefrMin: "A1",
    tags: ["food", "daily-life"],
  },
  {
    id: "ko_25_abril",
    type: "reference",
    contentPt: "25 de Abril — Revolução dos Cravos",
    contentL1: "카네이션 혁명 (1974)",
    explanation: "Portugal's 1974 peaceful revolution ended decades of dictatorship. Soldiers put carnations in their rifles. Koreans, familiar with their own democratic struggle (민주화 운동), can appreciate this watershed moment.",
    cefrMin: "B1",
    tags: ["history", "identity"],
  },
  {
    id: "ko_pronto",
    type: "expression",
    contentPt: "Pronto!",
    contentL1: "됐! / 준비 됐!",
    explanation: "'Pronto' = done/ready/OK then. Like 됐 or 준비 됐. 'Pronto, vamos!' = 됐, 가자!",
    cefrMin: "A1",
    tags: ["daily-life", "conversation"],
  },
  {
    id: "ko_skincare",
    type: "reference",
    contentPt: "Cuidados com a pele",
    contentL1: "피부 관리 (한국 vs 포르투갈)",
    explanation: "Korean and Portuguese cultures both value skincare. Portuguese women have traditionally used olive oil, rosehip oil, and thermal waters. Different approach from K-beauty's multi-step routine, but the cultural value placed on skin health is shared.",
    cefrMin: "A2",
    tags: ["culture", "daily-life"],
  },
  {
    id: "ko_family",
    type: "reference",
    contentPt: "Família é tudo",
    contentL1: "가족이 제일 중요해",
    explanation: "Like Korean culture, Portuguese culture is deeply family-oriented. Respect for elders, Sunday family lunches, and strong family bonds are central. Korean speakers will recognize this family-first attitude.",
    cefrMin: "A2",
    tags: ["culture", "family"],
  },
  {
    id: "ko_azulejo",
    type: "reference",
    contentPt: "Azulejos",
    contentL1: "타일 예술 (청화백자 같은)",
    explanation: "Portugal's blue and white ceramic tiles echo Korean 청화백자 (blue and white porcelain). Both traditions value blue decorative art. The Portuguese style was influenced by Islamic and Chinese ceramics via trade.",
    cefrMin: "A2",
    tags: ["art", "culture"],
  },
  {
    id: "ko_santos",
    type: "reference",
    contentPt: "Festas dos Santos Populares",
    contentL1: "축제 (사람들이 거리에서 노는 축제)",
    explanation: "Every June, streets fill with grilled sardines, music, and dancing. The communal street food atmosphere is like Korean 야시장 culture — eating together outdoors is the whole point.",
    cefrMin: "A2",
    tags: ["culture", "festivals"],
  },
  {
    id: "ko_desenrascar",
    type: "expression",
    contentPt: "Desenrascar-se",
    contentL1: "대충 해결하다 / 어떻게든 하다",
    explanation: "The art of improvising solutions. Like Korean 대충 or 어떻게든. Both cultures celebrate resourcefulness and getting things done creatively.",
    cefrMin: "B1",
    tags: ["culture", "daily-life"],
  },
  {
    id: "ko_hierarchy",
    type: "reference",
    contentPt: "Tu vs O Senhor",
    contentL1: "반말 vs 존댓말",
    explanation: "Like Korean 반말/존댓말, Portuguese has informal 'tu' and formal 'o senhor/a senhora'. Korean speakers will naturally understand the social hierarchy in language. Avoid 'você' in Portugal — it sounds cold.",
    cefrMin: "A1",
    tags: ["social", "etiquette"],
  },
  {
    id: "ko_nas_tintas",
    type: "expression",
    contentPt: "Estar-se nas tintas",
    contentL1: "상관없어 / 알 바 아니야",
    explanation: "Literally 'to be in the paints' — couldn't care less. Like 상관없어. Very common, mildly rude.",
    cefrMin: "B1",
    tags: ["slang", "emotion"],
  },
  {
    id: "ko_futebol",
    type: "reference",
    contentPt: "Futebol — religião nacional",
    contentL1: "축구 — 포르투갈의 국민 종교",
    explanation: "Football in Portugal has the same intensity as Korean football culture during the 2002 World Cup — except it never fades. Benfica, Sporting, and Porto divide the country like 전북 현대 vs 울산. Cristiano Ronaldo is a national hero on the level of 손흥민. Learning football vocabulary (golo, falta, penálti) is essential for conversation with any Portuguese person.",
    cefrMin: "A2",
    tags: ["sport", "culture", "conversation"],
  },
  {
    id: "ko_street_food",
    type: "reference",
    contentPt: "Bifanas e sardinhas — comida de rua",
    contentL1: "비파나와 정어리 — 포장마차 같은 길거리 음식",
    explanation: "Portugal's street food culture parallels Korean 포장마차. A 'bifana' (thin pork steak in bread) is Portugal's most popular street sandwich — quick, cheap, eaten standing at the counter. During the Santos Populares festivals in June, entire streets become open-air grills of sardines (sardinhas assadas). The communal, casual eating style will feel familiar.",
    cefrMin: "A2",
    tags: ["food", "culture", "daily-life"],
  },
  {
    id: "ko_drinking_culture",
    type: "reference",
    contentPt: "Vinho e cerveja — cultura de beber",
    contentL1: "음주 문화 — 소주 대신 비뉴 베르드",
    explanation: "Like Korean drinking culture with 소주 and 맥주, Portugal has a strong social drinking culture. 'Vinho verde' (young, slightly sparkling wine) is light and casual like 소주, while 'imperial' (draught beer) or 'fino' in Lisbon is the after-work standard. Drinking with colleagues and friends is normal and common, but Portuguese drinking is slower and always accompanies food — never on an empty stomach.",
    cefrMin: "A2",
    tags: ["food", "culture", "daily-life"],
  },
  // --- MODERN SLANG ---
  {
    id: "ko_bue",
    type: "expression",
    contentPt: "Bué",
    contentL1: "완전 / 엄청 / 개-",
    explanation: "'Bué' means 'a lot' or 'very' — from Kimbundu (Angolan language). 'Bué fixe' (완전 대박), 'bué caro' (엄청 비싸), 'bué gente' (사람 완전 많아). Used constantly by young Portuguese. Functions like 완전 or the slang prefix 개- as a universal intensifier.",
    cefrMin: "A2",
    tags: ["slang", "daily-life"],
  },
  {
    id: "ko_cena",
    type: "expression",
    contentPt: "Cena",
    contentL1: "거 / 그거 / 그런 거",
    explanation: "Originally means 'scene' but in PT-EU slang it means 'thing/stuff/situation'. 'Que cena!' (헐, 대박!), 'é uma cena estranha' (이상한 거야). Like Korean 그거 or 그런 거 when you can't name the thing. 'Dá-me aquela cena' (그거 줘).",
    cefrMin: "A2",
    tags: ["slang", "daily-life"],
  },
  {
    id: "ko_tipo",
    type: "expression",
    contentPt: "Tipo...",
    contentL1: "약간... / 뭐랄까...",
    explanation: "The Portuguese filler word, used exactly like Korean 약간 or 뭐랄까. 'Ele é tipo alto' (걔는 약간 키가 커). Young Portuguese pepper every sentence with 'tipo'. Not appropriate in formal speech, like using 약간 in a 면접.",
    cefrMin: "A2",
    tags: ["slang", "conversation"],
  },
  {
    id: "ko_ganda",
    type: "expression",
    contentPt: "Ganda / Granda",
    contentL1: "대박! / 쩔어!",
    explanation: "Contraction of 'grande' — used as an intensifier. 'Ganda filme!' (대박 영화!), 'Granda maluco!' (쩌는 놈!). Like 대박 or 쩔어 in casual Korean. Colloquial Lisbon slang, slightly vulgar — don't use with 선배 or 상사.",
    cefrMin: "B1",
    tags: ["slang"],
  },
  {
    id: "ko_bazar",
    type: "expression",
    contentPt: "Bazar",
    contentL1: "가다 / 튀다 (slang: 빠지다)",
    explanation: "'Bazar' means 'to leave/bounce'. 'Vou bazar' (나 간다 / 나 튄다). Informal, like Korean 빠지다 or 튀다 in casual speech. The more formal version is 'ir-se embora': 'Vou-me embora' (가겠습니다).",
    cefrMin: "B1",
    tags: ["slang", "daily-life"],
  },
  {
    id: "ko_curtir",
    type: "expression",
    contentPt: "Curtir",
    contentL1: "즐기다 / 좋아하다 / 빠지다",
    explanation: "'Curtir' means to enjoy or to be into something. 'Curto bué música portuguesa' (포르투갈 음악 완전 좋아해). 'Vamos curtir a noite' (밤을 즐기자). Also used for liking someone romantically: 'Ela curte-o' (걔가 걔를 좋아해).",
    cefrMin: "A2",
    tags: ["slang", "daily-life"],
  },
  {
    id: "ko_na_boa",
    type: "expression",
    contentPt: "Na boa",
    contentL1: "괜찮아 / 문제 없어",
    explanation: "'Na boa' means 'no worries / it's all good'. 'Podes usar o meu carro, na boa' (내 차 써도 돼, 괜찮아). Also used as a question: 'Tás na boa?' (괜찮아?). Like 괜찮아 — one of the most useful casual phrases.",
    cefrMin: "A1",
    tags: ["slang", "daily-life"],
  },
  {
    id: "ko_o_pa",
    type: "expression",
    contentPt: "Ó pá!",
    contentL1: "야! / 이봐!",
    explanation: "The quintessential Portuguese interjection. 'Ó pá, não acredito!' (야, 진짜?!). Used between friends, like 야 or 이봐. Short for 'rapaz' (boy). Can express surprise, frustration, or just be a casual address. Heard constantly in any conversation between Portuguese friends.",
    cefrMin: "A1",
    tags: ["slang", "daily-life"],
  },
  {
    id: "ko_mano",
    type: "expression",
    contentPt: "Mano / Mana",
    contentL1: "형 / 언니 / 오빠 / 누나 (친구 사이)",
    explanation: "Short for 'irmão/irmã' (brother/sister). Used as 'bro/sis' between close friends. 'Olha, mano, ouve lá...' (야 형, 좀 들어봐...). Korean speakers will find this familiar — Korean also uses family terms (형, 언니, 오빠, 누나) among friends. Very common in Lisbon's multicultural neighbourhoods.",
    cefrMin: "A2",
    tags: ["slang", "daily-life"],
  },
  {
    id: "ko_mandar_vir",
    type: "expression",
    contentPt: "Mandar vir",
    contentL1: "불평하다 / 시키다 (두 가지 뜻!)",
    explanation: "Has two completely different meanings depending on context. 1) 'To complain/rant': 'Ele está sempre a mandar vir com tudo' (걔는 맨날 불평이야). 2) 'To order': 'Manda vir mais uma cerveja' (맥주 하나 더 시켜). Context always makes it clear which meaning.",
    cefrMin: "B1",
    tags: ["slang", "daily-life"],
  },
  {
    id: "ko_ta_se_bem",
    type: "expression",
    contentPt: "Tá-se bem",
    contentL1: "좋아! / 오케이!",
    explanation: "Contraction of 'está-se bem' — 'it's all good'. Used to accept a proposal or confirm you're fine. 'Vamos ao cinema?' — 'Tá-se bem!' (영화 보러 갈까? — 좋아!). Very casual, very common.",
    cefrMin: "A1",
    tags: ["slang", "daily-life"],
  },
  // --- ANCIENT PROVERBS / PROVÉRBIOS ---
  {
    id: "ko_agua_pedra",
    type: "expression",
    contentPt: "Água mole em pedra dura, tanto bate até que fura",
    contentL1: "낙수물이 바위를 뚫는다",
    explanation: "Literally: 'Soft water on hard stone, hits until it pierces.' Persistence wins. Korean has the nearly identical 낙수물이 바위를 뚫는다 (dripping water pierces rock). Both proverbs celebrate 끈기 (tenacity) — a value central to both cultures.",
    cefrMin: "B1",
    tags: ["proverb", "wisdom"],
  },
  {
    id: "ko_cao_gato",
    type: "expression",
    contentPt: "Quem não tem cão, caça com gato",
    contentL1: "없으면 있는 것으로 해라",
    explanation: "Literally: 'Who doesn't have a dog, hunts with a cat.' Make do with what you have. The proverb form of 'desenrascar-se'. Korean values resourcefulness and making do — 있는 대로 해결하다 captures the same spirit of creative improvisation.",
    cefrMin: "B1",
    tags: ["proverb", "culture"],
  },
  {
    id: "ko_grao_galinha",
    type: "expression",
    contentPt: "Grão a grão, enche a galinha o papo",
    contentL1: "티끌 모아 태산",
    explanation: "Literally: 'Grain by grain, the hen fills her crop.' Small things add up. Korean has the famous 티끌 모아 태산 (gather dust, make a mountain). Both proverbs celebrate small, consistent effort — every Korean student knows this saying.",
    cefrMin: "B1",
    tags: ["proverb", "wisdom"],
  },
  {
    id: "ko_pepino",
    type: "expression",
    contentPt: "De pequenino se torce o pepino",
    contentL1: "세 살 버릇 여든까지 간다",
    explanation: "Literally: 'You bend the cucumber when it's small.' Habits are formed young. Korean has 세 살 버릇 여든까지 간다 (habits from age three last until eighty). Both cultures believe early education shapes the adult.",
    cefrMin: "B1",
    tags: ["proverb", "education"],
  },
  {
    id: "ko_tripas_coracao",
    type: "expression",
    contentPt: "Fazer das tripas coração",
    contentL1: "이를 악물다 / 용기를 내다",
    explanation: "Literally: 'To make heart out of guts.' To summon courage when you have none. Like Korean 이를 악물다 (to grit your teeth) or 용기를 내다 (to muster courage). Origin may be linked to Porto, whose residents ate only tripe after sending good meat to the fleets.",
    cefrMin: "B1",
    tags: ["proverb", "history", "porto"],
  },
  {
    id: "ko_ver_navios",
    type: "expression",
    contentPt: "Ficar a ver navios",
    contentL1: "헛수고하다 / 바람맞다",
    explanation: "Literally: 'To be left watching ships.' To be left empty-handed or stood up. Origin: during the Age of Discoveries, women waited for ships that never returned. Like Korean 바람맞다 (to be stood up) or 헛수고하다 (to have done useless work).",
    cefrMin: "B1",
    tags: ["proverb", "history", "discoveries"],
  },
  {
    id: "ko_engolir_sapos",
    type: "expression",
    contentPt: "Engolir sapos",
    contentL1: "참다 / 삼키다",
    explanation: "Literally: 'To swallow frogs.' To endure insults or unfair situations without reacting. Like Korean 참다 (to endure/bear it). 'No trabalho, tenho de engolir muitos sapos' (직장에서 많이 참아야 해). Ancient proverb, still used daily.",
    cefrMin: "B1",
    tags: ["proverb", "daily-life"],
  },
  {
    id: "ko_burros_agua",
    type: "expression",
    contentPt: "Dar com os burros na água",
    contentL1: "실패하다 / 물거품이 되다",
    explanation: "Literally: 'To end up with the donkeys in the water.' To fail completely. Like Korean 물거품이 되다 (to become water foam = to come to nothing). Origin: donkeys falling into rivers while crossing, losing all the cargo.",
    cefrMin: "B1",
    tags: ["proverb", "daily-life"],
  },
  {
    id: "ko_rossio_betesga",
    type: "expression",
    contentPt: "Meter o Rossio na Betesga",
    contentL1: "불가능한 것을 시도하다",
    explanation: "Literally: 'To fit the Rossio (Lisbon's grand square) into the Betesga (a tiny alley nearby).' Attempting the impossible. A purely Lisbon-born proverb from the Middle Ages. Like trying to fit 광화문 광장 into a 골목.",
    cefrMin: "B2",
    tags: ["proverb", "lisbon", "history"],
  },
  {
    id: "ko_mar_lugar",
    type: "expression",
    contentPt: "Quem vai ao mar, perde o lugar",
    contentL1: "자리를 비우면 자리를 잃는다",
    explanation: "Literally: 'Who goes to sea, loses their place.' If you leave, someone else takes your spot. Maritime origin. Used today for parking spots, restaurant seats, any contested position. The Portuguese version of 빈자리는 다른 사람이 채운다.",
    cefrMin: "A2",
    tags: ["proverb", "maritime", "daily-life"],
  },
  // --- DAILY IDIOMS ---
  {
    id: "ko_ora_essa",
    type: "expression",
    contentPt: "Ora essa!",
    contentL1: "아이고, 아닙니다! / 별말씀을!",
    explanation: "An exclamation of modest denial when thanked. 'Obrigado pela ajuda!' — 'Ora essa!' (도와줘서 고마워! — 별말씀을!). Like Korean 별말씀을 — both cultures value modesty when receiving thanks.",
    cefrMin: "A2",
    tags: ["daily-life", "etiquette"],
  },
  {
    id: "ko_descansado",
    type: "expression",
    contentPt: "Está descansado / Fica descansado",
    contentL1: "걱정 마 / 안심해",
    explanation: "Literally: 'Be rested/at ease.' Means 'don't worry, I've got it covered.' 'Fica descansado, eu trato disso' (걱정 마, 내가 할게). Like 걱정 마. Feminine form: 'Fica descansada'.",
    cefrMin: "A2",
    tags: ["daily-life", "conversation"],
  },
  {
    id: "ko_nao_faz_mal",
    type: "expression",
    contentPt: "Não faz mal",
    contentL1: "괜찮아요 / 아무것도 아니에요",
    explanation: "Literally: 'It doesn't do harm.' The standard response when someone apologizes. 'Desculpa o atraso!' — 'Não faz mal!' (늦어서 미안! — 괜찮아!). Like Korean 괜찮아요. One of the first phrases you will hear and need.",
    cefrMin: "A1",
    tags: ["daily-life", "etiquette"],
  },
  {
    id: "ko_deixa_la",
    type: "expression",
    contentPt: "Deixa lá",
    contentL1: "됐어 / 신경 쓰지 마",
    explanation: "'Deixa lá' means 'let it go / forget about it.' 'Queres que te pague?' — 'Deixa lá!' (돈 줄까? — 됐어!). Can also be consoling: 'Deixa lá, amanhã corre melhor' (됐어, 내일은 나을 거야). Like 됐어 or 신경 쓰지 마.",
    cefrMin: "A1",
    tags: ["daily-life", "conversation"],
  },
  {
    id: "ko_e_o_que_e",
    type: "expression",
    contentPt: "É o que é",
    contentL1: "어쩔 수 없지 / 그런 거지 뭐",
    explanation: "The Portuguese 'it is what it is.' 'O preço subiu? É o que é.' (가격 올랐어? 어쩔 수 없지). Like Korean 어쩔 수 없지 — a philosophical acceptance of things you can't change.",
    cefrMin: "A2",
    tags: ["daily-life", "culture"],
  },
  {
    id: "ko_olha_la",
    type: "expression",
    contentPt: "Olha lá / Ouve lá",
    contentL1: "저기요 / 있잖아",
    explanation: "'Olha lá' (look here) and 'ouve lá' (listen here) get attention or start a question. 'Olha lá, sabes onde fica o correio?' (저기요, 우체국 어디 있어요?). Like 저기요 or 있잖아. Not rude — it's how you approach someone.",
    cefrMin: "A1",
    tags: ["daily-life", "conversation"],
  },
  {
    id: "ko_entao",
    type: "expression",
    contentPt: "Então?",
    contentL1: "그래서? / 뭐해?",
    explanation: "'Então?' is the universal Portuguese greeting-question. 'Então, tudo bem?' (그래서, 잘 지내?). Also used to prompt: 'Então, o que queres fazer?' (그래서, 뭐 할 거야?). Like 그래서 — short, warm, multipurpose.",
    cefrMin: "A1",
    tags: ["daily-life", "conversation"],
  },
  {
    id: "ko_se_calhar",
    type: "expression",
    contentPt: "Se calhar",
    contentL1: "아마 / 혹시",
    explanation: "Literally: 'if it falls (that way).' Means 'maybe / perhaps.' 'Se calhar vou ao cinema amanhã' (아마 내일 영화 볼 거야). More common than 'talvez' in everyday speech. Note: in PT-EU this does NOT trigger the subjunctive, unlike 'talvez'.",
    cefrMin: "A2",
    tags: ["daily-life", "grammar"],
  },
  {
    id: "ko_com_certeza",
    type: "expression",
    contentPt: "Com certeza",
    contentL1: "물론이죠 (주의: 진심이 아닐 수도!)",
    explanation: "'Com certeza' means 'certainly.' BUT in PT-EU it is often used as a polite but non-committal agreement — like 물론이죠 but without really meaning it. A Portuguese 'com certeza' can mean 'I'll think about it' (and forget). Korean speakers familiar with 눈치 will pick up on this nuance faster than most.",
    cefrMin: "A2",
    tags: ["daily-life", "etiquette", "culture"],
  },
];
