import type { L1Profile } from "../types.js";

export const koProfile: L1Profile = {
  code: "ko",
  name: "Korean",
  nativeName: "한국어",
  writingDirection: "ltr",
  hasLatinScript: false,
  transfer: {
    cognates: [
      "카페 kapé (café — coffee/café)",
      "레스토랑 resutorang (restaurante — restaurant)",
      "텔레비전 tellebijeon (televisão — television)",
      "라디오 radio (rádio — radio)",
      "그룹 geurup (grupo — group)",
      "시스템 siseutem (sistema — system)",
      "호텔 hotel (hotel — hotel)",
      "택시 taeksi (táxi — taxi)",
      "버스 beoseu (autocarro — bus, shared concept)",
      "컴퓨터 keompyuteo (computador — computer)",
      "인터넷 inteonet (internet — internet)",
      "초콜릿 chokollit (chocolate — chocolate)",
      "카메라 kamera (câmara — camera)",
      "비타민 bitamin (vitamina — vitamin)",
      "파스타 paseuta (massa — pasta, same food)",
      "바나나 banana (banana — banana)",
      "토마토 tomato (tomate — tomato)",
      "기타 gita (guitarra — guitar)",
      "피아노 piano (piano — piano)",
      "뮤지컬 myujikeol (musical — musical)",
      "발코니 balkoni (varanda — balcony)",
      "슈퍼마켓 syupeomakes (supermercado — supermarket)",
      "마사지 masaji (massagem — massage)",
      "비자 bija (visto — visa, shared concept)",
      "알레르기 allereуgi (alergia — allergy)",
      "에너지 eneoji (energia — energy)",
      "비디오 bidio (vídeo — video)",
      "모터 moteo (motor — motor)",
      "알코올 alkool (álcool — alcohol)",
      "카페 kape (café — coffee/cafe)",
    ],
    falseFriends: [
      { word: "não", l1Meaning: "나오 (nao) sounds like 나와 (nawa) — 'come out'", ptMeaning: "não means 'no' — the most basic PT word" },
      { word: "dia", l1Meaning: "디아 sounds like no Korean word specifically", ptMeaning: "dia means 'day' — 'bom dia' = good morning" },
      { word: "pai", l1Meaning: "파이 (pai) — pie (English loanword)", ptMeaning: "pai means 'father'" },
      { word: "mal", l1Meaning: "말 (mal) means 'horse' or 'speech/word'", ptMeaning: "mal means 'badly/evil'" },
      { word: "golo", l1Meaning: "골 (gol) — goal (in sports)", ptMeaning: "golo means 'goal' in PT-PT — same sports meaning, slightly different form" },
      { word: "bar", l1Meaning: "바 (ba) means 'bar' — same!", ptMeaning: "bar — true cognate" },
      { word: "sala", l1Meaning: "살아 (sara) means 'alive / live!' (imperative)", ptMeaning: "sala means 'room/living room'" },
      { word: "cara", l1Meaning: "카라 — no standard Korean meaning", ptMeaning: "cara means 'face' or 'guy' (informal)" },
      { word: "bola", l1Meaning: "볼라 — no direct meaning", ptMeaning: "bola means 'ball'" },
      { word: "sol", l1Meaning: "솔 (sol) — pine tree or musical note", ptMeaning: "sol means 'sun'" },
      { word: "comer", l1Meaning: "커머 — no Korean meaning", ptMeaning: "comer means 'to eat'" },
      { word: "largo", l1Meaning: "라르고 — no Korean meaning", ptMeaning: "largo means 'wide' or 'public square'" },
      { word: "mar", l1Meaning: "말 (mal) already listed — 마르 sounds like 마르다 (to dry up)", ptMeaning: "mar means 'sea/ocean'" },
      { word: "ser", l1Meaning: "서 (seo) — sounds like standing", ptMeaning: "ser means 'to be' (identity/permanent)" },
      { word: "ter", l1Meaning: "터 (teo) — sounds like 'site/ground'", ptMeaning: "ter means 'to have'" },
      { word: "porta", l1Meaning: "포르타 — no Korean meaning (문 = door)", ptMeaning: "porta means 'door'" },
      { word: "banco", l1Meaning: "방코 — sounds like 방 (room) + 코 (nose)", ptMeaning: "banco means 'bank' or 'bench'" },
      { word: "gato", l1Meaning: "가토 — no Korean meaning (고양이 = cat)", ptMeaning: "gato means 'cat'" },
      { word: "cola", l1Meaning: "콜라 (kolla) — cola drink", ptMeaning: "cola means 'glue' — cola drink = Coca-Cola" },
      { word: "caro", l1Meaning: "카로 — no Korean meaning (비싼 = expensive)", ptMeaning: "caro means 'expensive' or 'dear'" },
      { word: "dar", l1Meaning: "다르 — sounds like 다르다 (to be different)", ptMeaning: "dar means 'to give' — different = diferente" },
      { word: "conta", l1Meaning: "콘타 — no Korean meaning", ptMeaning: "conta means 'bill/account/story'" },
      { word: "pena", l1Meaning: "페나 — no Korean meaning", ptMeaning: "pena means 'feather' or 'pity' or 'penalty'" },
      { word: "rua", l1Meaning: "루아 — no Korean meaning (거리 = street)", ptMeaning: "rua means 'street'" },
      { word: "massa", l1Meaning: "마사 — sounds like 마사지 (masaji, massage)", ptMeaning: "massa means 'dough/pasta' — massage = massagem" },
      { word: "lista", l1Meaning: "리스타 — sounds like 리스트 (riseuteu, list)", ptMeaning: "lista means 'list' AND 'menu' — broader meaning than English 'list'" },
      { word: "forma", l1Meaning: "포르마 — no Korean meaning", ptMeaning: "forma means 'form/shape/mould' — shape = 형태 in Korean" },
      { word: "data", l1Meaning: "다타 — sounds like 데이터 (deiteo, data)", ptMeaning: "data means 'date' (calendar), not digital data — date = data, digital data = dados" },
      { word: "nota", l1Meaning: "노타 — sounds like 노트 (noteu, notebook)", ptMeaning: "nota means 'grade/mark' AND 'banknote' — notebook = caderno" },
      { word: "mala", l1Meaning: "말라 — sounds like 말라 (malla, dry up/wither)", ptMeaning: "mala means 'suitcase/bag' — to dry up = secar" },
      { word: "fala", l1Meaning: "팔아 (para) — sounds like 'sell!' (imperative)", ptMeaning: "fala means 'speaks' or 'speech' — to sell = vender" },
      { word: "cama", l1Meaning: "카마 — sounds like 가마 (gama, kiln/palanquin)", ptMeaning: "cama means 'bed' — kiln = forno" },
      { word: "prato", l1Meaning: "프라토 — no Korean meaning", ptMeaning: "prato means 'plate/dish' AND 'course of a meal'" },
      { word: "pasta", l1Meaning: "파스타 (paseuta) — pasta (Italian food)", ptMeaning: "pasta means 'folder/briefcase' — pasta food = massa" },
      { word: "casa", l1Meaning: "카사 — no Korean meaning (집 = house)", ptMeaning: "casa means 'house/home' — also used in 'em casa' (at home)" },
      { word: "manga", l1Meaning: "만화 (manhwa) — Korean comics (similar to Japanese manga)", ptMeaning: "manga primarily means 'sleeve' — also means mango fruit" },
      { word: "nome", l1Meaning: "노메 — sounds like 놈에 (nome, 'that guy' + particle)", ptMeaning: "nome means 'name' — 놈 is informal/rude for 'fellow'" },
      { word: "prima", l1Meaning: "프리마 — prima donna (from Italian)", ptMeaning: "prima means 'female cousin' — primo = male cousin" },
      { word: "dom", l1Meaning: "돔 (dom) — dome (English loanword)", ptMeaning: "dom means 'Mr/Sir' (title) or 'gift/talent' — dome = cúpula" },
      { word: "taça", l1Meaning: "타사 — sounds like 타자 (taja, typing/batter)", ptMeaning: "taça means 'trophy/wine glass/goblet' — typing = digitação" },
    ],
    phoneticDifficulties: [
      {
        sound: "ão",
        ipa: "/ɐ̃w̃/",
        description: "Nasal diphthong -ão",
        tip: "Korean has no nasal vowels or diphthongs like this. Open your mouth for 'a', nasalize by lowering the soft palate, then glide to a rounded nasal 'u'. Entirely new articulation. Practice: pão, mão, não.",
        mouthPosition: "nasal_ao",
      },
      {
        sound: "ã/õ/ẽ",
        ipa: "/ɐ̃/ /õ/ /ẽ/",
        description: "Nasal vowels",
        tip: "Korean doesn't nasalize vowels — the ㅇ (ng) final is a consonant, not vowel nasalization. PT-EU nasalizes the entire vowel: air flows through the nose throughout. 'Maçã' (apple), 'limão' (lemon).",
        mouthPosition: "nasal_vowel",
      },
      {
        sound: "r/l distinction",
        ipa: "/ɾ/ vs /l/ vs /ʁ/",
        description: "Three distinct liquids",
        tip: "Korean ㄹ (rieul) alternates between r and l. PT-EU has three separate sounds: tap /ɾ/ (caro), dark L /ɫ/ (sol), and uvular R /ʁ/ (rato, carro). Each is a different phoneme — confusing them changes meaning.",
        mouthPosition: "uvular_r",
      },
      {
        sound: "lh",
        ipa: "/ʎ/",
        description: "Palatal lateral lh",
        tip: "No Korean equivalent. Press the middle of your tongue flat against the hard palate while making an L sound. 'Trabalho' (work), 'filho' (son), 'olho' (eye).",
        mouthPosition: "palatal_lateral",
      },
      {
        sound: "nh",
        ipa: "/ɲ/",
        description: "Palatal nasal nh",
        tip: "Similar to Korean ㄴ before ㅣ (니) but more fully palatal. Tongue on the palate, air through the nose. 'Vinho' (wine), 'amanhã' (tomorrow), 'minha' (my).",
        mouthPosition: "palatal_nasal",
      },
      {
        sound: "f/v",
        ipa: "/f/ /v/",
        description: "Labiodental fricatives",
        tip: "Korean has neither /f/ nor /v/ (using ㅍ p' and ㅂ b instead). Both need upper teeth touching lower lip. /f/ is voiceless, /v/ adds vocal cord vibration. 'Falar' (speak) vs 'valer' (be worth).",
        mouthPosition: "labiodental_v",
      },
      {
        sound: "b/d/g",
        ipa: "/b/ /d/ /g/",
        description: "Voiced stops",
        tip: "Korean ㅂ/ㄷ/ㄱ between vowels are voiced but initially are voiceless. PT-EU b/d/g are ALWAYS voiced — vocal cords vibrate from the start. 'Bom' (good), 'dar' (give), 'gato' (cat).",
      },
      {
        sound: "consonant clusters",
        ipa: "/pr/ /tr/ /pl/ /str/",
        description: "Initial consonant clusters",
        tip: "Korean syllables follow strict C-V-C patterns with no clusters. PT-EU stacks consonants: 'prato' (plate), 'três' (three). Do not insert 으 (eu) between consonants — say them together.",
      },
      {
        sound: "reduced vowels",
        ipa: "/ɨ/ /ə/",
        description: "Unstressed vowels nearly vanish",
        tip: "Korean pronounces every syllable evenly. PT-EU swallows unstressed vowels — 'telefonema' sounds like 'tlfnema'. This timing shift is the biggest rhythm challenge.",
      },
      {
        sound: "s/z/ʃ/ʒ",
        ipa: "/s/ /z/ /ʃ/ /ʒ/",
        description: "Four sibilants",
        tip: "Korean has ㅅ (s) and ㅈ (j/ch). PT-EU has four: /s/ (sal), /z/ (casa), /ʃ/ (final s, like sh), /ʒ/ (j, like French je). /z/ and /ʒ/ are new and require voicing.",
        mouthPosition: "sibilant_sh",
      },
      {
        sound: "open/closed vowels",
        ipa: "/ɛ/ vs /e/, /ɔ/ vs /o/",
        description: "Vowel height contrasts",
        tip: "Korean ㅔ and ㅐ used to contrast but merged in modern Seoul Korean. PT-EU keeps them distinct: 'é' (open, café) vs 'ê' (closed, você). The accent mark guides you.",
        mouthPosition: "open_e",
      },
      {
        sound: "word stress",
        ipa: "variable",
        description: "Unpredictable stress",
        tip: "Korean has relatively even syllable timing. PT-EU is stress-timed — stressed syllables are louder and longer, others shrink. Stress can change meaning: 'sábia' (wise) vs 'sabiá' (bird).",
      },
      {
        sound: "dark L",
        ipa: "/ɫ/",
        description: "Velarized L at end of syllables",
        tip: "Korean ㄹ at the end of a syllable is a lateral, but light. PT-EU final L is dark and heavy — the back of the tongue raises toward the velum, almost like a 'w'. 'Portugal', 'sol' (sun), 'mal' (badly).",
      },
      {
        sound: "diphthongs (ei, ou, ai)",
        ipa: "/ɐj/ /ow/ /aj/",
        description: "Oral diphthongs — two vowels gliding together",
        tip: "Korean has diphthongs (ㅐ, ㅔ, ㅘ) but they work differently. PT-EU diphthongs glide smoothly: 'pai' (father, /aj/), 'coisa' (thing, /oj/), 'eu' (I, /ew/). Do not break them into two syllables.",
      },
      {
        sound: "word-final -e",
        ipa: "/ɨ/ or silent",
        description: "Final -e nearly disappears",
        tip: "Korean always gives final syllables full weight. PT-EU final -e is barely a whisper or silent entirely. 'Cidade' sounds like 'cidadɨ' or 'cidad'. Do not pronounce it as a full 에 (e).",
      },
    ],
    grammarGaps: [
      {
        concept: "Articles (o/a, um/uma)",
        explanation: "Every noun requires a definite or indefinite article",
        l1Comparison: "Korean has no articles. You must say 'o livro' (the book), not just 'livro'. The article signals gender (masculine/feminine) and definiteness (the/a).",
      },
      {
        concept: "Grammatical gender",
        explanation: "Every noun is masculine or feminine, affecting articles and adjectives",
        l1Comparison: "Korean has no grammatical gender. PT-EU assigns gender to all nouns: 'o sol' (sun, m), 'a lua' (moon, f). Adjectives change form too: 'bonito' (m) vs 'bonita' (f).",
      },
      {
        concept: "SVO word order",
        explanation: "Subject-Verb-Object is the default",
        l1Comparison: "Korean is SOV with particles (나는 책을 읽었다). PT-EU is SVO: 'Eu li o livro' (I read the book). The verb moves to the middle. No particles — word position shows function.",
      },
      {
        concept: "Verb conjugation",
        explanation: "6 person forms × 12+ tenses across 3 moods",
        l1Comparison: "Korean conjugates for politeness and tense with suffixes. PT-EU conjugates for PERSON: eu falo, tu falas, ele fala... Each person gets a unique ending. The concept of person-based endings is new.",
      },
      {
        concept: "Ser vs Estar",
        explanation: "Two verbs for 'to be'",
        l1Comparison: "Korean 이다 (ida) for identity and 있다 (itda) for existence actually mirror ser/estar somewhat! 'Sou coreano' (I am Korean — ser/이다) vs 'Estou em Lisboa' (I am in Lisbon — estar/있다).",
      },
      {
        concept: "Prepositions (not particles)",
        explanation: "de, em, a, para, com, por — come BEFORE the noun",
        l1Comparison: "Korean uses particles AFTER nouns (에/에서/의/를/을). PT-EU prepositions precede: 'em Lisboa' (in Lisbon), 'de Portugal' (from Portugal). They also contract with articles: em+o=no.",
      },
      {
        concept: "Subjunctive mood",
        explanation: "Required for doubt, desire, emotion",
        l1Comparison: "Korean has no subjunctive. It uses different sentence endings for politeness/mood. PT-EU requires specific verb forms: 'Espero que venhas' (I hope you come) — 'venhas' is subjunctive.",
      },
      {
        concept: "Personal infinitive",
        explanation: "Infinitive conjugated for person — unique to Portuguese",
        l1Comparison: "No Korean equivalent. 'Para nós fazermos' (for us to do) — the infinitive gets a personal ending. This replaces an entire subordinate clause.",
      },
      {
        concept: "Adjective agreement and position",
        explanation: "Adjectives agree in gender/number and usually follow the noun",
        l1Comparison: "Korean adjectives precede the noun and never change form. PT-EU adjectives follow the noun AND change: 'casa bonita' (f), 'livro bonito' (m), 'casas bonitas' (f.pl).",
      },
      {
        concept: "Plural formation",
        explanation: "Add -s or -es, articles change too",
        l1Comparison: "Korean rarely marks plurals (들 is optional). PT-EU always marks them: 'livro' → 'livros', 'o' → 'os'. Every countable noun shows its number.",
      },
      {
        concept: "Tu vs Você vs O Senhor",
        explanation: "Three formality levels for 'you'",
        l1Comparison: "Korean has elaborate honorifics (존댓말/반말). PT-EU is simpler: 'tu' (intimate), 'você' (neutral but can be awkward), 'o senhor/a senhora' (formal). In Portugal, default to 'tu' among peers.",
      },
      {
        concept: "Object pronoun placement",
        explanation: "Before or after the verb depending on triggers",
        l1Comparison: "Korean puts objects before the verb (나를 봐). PT-EU has complex pronoun rules: 'Vê-me' (see me, after verb) vs 'Não me vê' (doesn't see me, before verb).",
      },
      {
        concept: "Reflexive verbs",
        explanation: "Many common verbs need a reflexive pronoun (se)",
        l1Comparison: "Korean has no reflexive verbs. PT-EU uses them constantly: 'Chamo-me Ana' (I call myself Ana = My name is Ana), 'Levanto-me' (I get up). The pronoun changes with the person.",
      },
      {
        concept: "Continuous with 'estar a + infinitive'",
        explanation: "'Estou a trabalhar' = I am working (PT-EU form)",
        l1Comparison: "Korean uses -고 있다 (-go itda) for ongoing actions, which is similar in concept. PT-EU uses 'estar a + infinitive': 'Estou a ler' (I am reading). The Brazilian gerund form ('estou lendo') is not PT-EU.",
      },
      {
        concept: "Definite article with names",
        explanation: "'A Maria', 'o João' — articles before proper names",
        l1Comparison: "Korean never uses articles with names (or at all). PT-EU requires them: 'A Maria vem amanhã' (Maria is coming tomorrow). This is standard spoken Portuguese, not optional.",
      },
    ],
    skipBasics: false,
    startingCEFR: "A1",
  },
};
