import type { L1Profile } from "../types.js";

export const koProfile: L1Profile = {
  code: "ko",
  name: "Korean",
  nativeName: "한국어",
  writingDirection: "ltr",
  hasLatinScript: false,
  transfer: {
    cognates: [
      "카페 kapé (café — coffee/café)",
      "레스토랑 resutorang (restaurante — restaurant)",
      "텔레비전 tellebijeon (televisão — television)",
      "라디오 radio (rádio — radio)",
      "그룹 geurup (grupo — group)",
      "시스템 siseutem (sistema — system)",
    ],
    falseFriends: [
      { word: "não", l1Meaning: "나오 (nao) sounds like 나와 (nawa) — 'come out'", ptMeaning: "não means 'no' — the most basic PT word" },
      { word: "dia", l1Meaning: "디아 sounds like no Korean word specifically", ptMeaning: "dia means 'day' — 'bom dia' = good morning" },
      { word: "pai", l1Meaning: "파이 (pai) — pie (English loanword)", ptMeaning: "pai means 'father'" },
      { word: "mal", l1Meaning: "말 (mal) means 'horse' or 'speech/word'", ptMeaning: "mal means 'badly/evil'" },
      { word: "golo", l1Meaning: "골 (gol) — goal (in sports)", ptMeaning: "golo means 'goal' in PT-PT — same sports meaning, slightly different form" },
      { word: "bar", l1Meaning: "바 (ba) means 'bar' — same!", ptMeaning: "bar — true cognate" },
      { word: "sala", l1Meaning: "살아 (sara) means 'alive / live!' (imperative)", ptMeaning: "sala means 'room/living room'" },
      { word: "cara", l1Meaning: "카라 — no standard Korean meaning", ptMeaning: "cara means 'face' or 'guy' (informal)" },
      { word: "bola", l1Meaning: "볼라 — no direct meaning", ptMeaning: "bola means 'ball'" },
      { word: "sol", l1Meaning: "솔 (sol) — pine tree or musical note", ptMeaning: "sol means 'sun'" },
    ],
    phoneticDifficulties: [
      {
        sound: "ão",
        ipa: "/ɐ̃w̃/",
        description: "Nasal diphthong -ão",
        tip: "Korean has no nasal vowels or diphthongs like this. Open your mouth for 'a', nasalize by lowering the soft palate, then glide to a rounded nasal 'u'. Entirely new articulation. Practice: pão, mão, não.",
        mouthPosition: "nasal_ao",
      },
      {
        sound: "ã/õ/ẽ",
        ipa: "/ɐ̃/ /õ/ /ẽ/",
        description: "Nasal vowels",
        tip: "Korean doesn't nasalize vowels — the ㅇ (ng) final is a consonant, not vowel nasalization. PT-EU nasalizes the entire vowel: air flows through the nose throughout. 'Maçã' (apple), 'limão' (lemon).",
        mouthPosition: "nasal_vowel",
      },
      {
        sound: "r/l distinction",
        ipa: "/ɾ/ vs /l/ vs /ʁ/",
        description: "Three distinct liquids",
        tip: "Korean ㄹ (rieul) alternates between r and l. PT-EU has three separate sounds: tap /ɾ/ (caro), dark L /ɫ/ (sol), and uvular R /ʁ/ (rato, carro). Each is a different phoneme — confusing them changes meaning.",
        mouthPosition: "uvular_r",
      },
      {
        sound: "lh",
        ipa: "/ʎ/",
        description: "Palatal lateral lh",
        tip: "No Korean equivalent. Press the middle of your tongue flat against the hard palate while making an L sound. 'Trabalho' (work), 'filho' (son), 'olho' (eye).",
        mouthPosition: "palatal_lateral",
      },
      {
        sound: "nh",
        ipa: "/ɲ/",
        description: "Palatal nasal nh",
        tip: "Similar to Korean ㄴ before ㅣ (니) but more fully palatal. Tongue on the palate, air through the nose. 'Vinho' (wine), 'amanhã' (tomorrow), 'minha' (my).",
        mouthPosition: "palatal_nasal",
      },
      {
        sound: "f/v",
        ipa: "/f/ /v/",
        description: "Labiodental fricatives",
        tip: "Korean has neither /f/ nor /v/ (using ㅍ p' and ㅂ b instead). Both need upper teeth touching lower lip. /f/ is voiceless, /v/ adds vocal cord vibration. 'Falar' (speak) vs 'valer' (be worth).",
        mouthPosition: "labiodental_v",
      },
      {
        sound: "b/d/g",
        ipa: "/b/ /d/ /g/",
        description: "Voiced stops",
        tip: "Korean ㅂ/ㄷ/ㄱ between vowels are voiced but initially are voiceless. PT-EU b/d/g are ALWAYS voiced — vocal cords vibrate from the start. 'Bom' (good), 'dar' (give), 'gato' (cat).",
      },
      {
        sound: "consonant clusters",
        ipa: "/pr/ /tr/ /pl/ /str/",
        description: "Initial consonant clusters",
        tip: "Korean syllables follow strict C-V-C patterns with no clusters. PT-EU stacks consonants: 'prato' (plate), 'três' (three). Do not insert 으 (eu) between consonants — say them together.",
      },
      {
        sound: "reduced vowels",
        ipa: "/ɨ/ /ə/",
        description: "Unstressed vowels nearly vanish",
        tip: "Korean pronounces every syllable evenly. PT-EU swallows unstressed vowels — 'telefonema' sounds like 'tlfnema'. This timing shift is the biggest rhythm challenge.",
      },
      {
        sound: "s/z/ʃ/ʒ",
        ipa: "/s/ /z/ /ʃ/ /ʒ/",
        description: "Four sibilants",
        tip: "Korean has ㅅ (s) and ㅈ (j/ch). PT-EU has four: /s/ (sal), /z/ (casa), /ʃ/ (final s, like sh), /ʒ/ (j, like French je). /z/ and /ʒ/ are new and require voicing.",
        mouthPosition: "sibilant_sh",
      },
      {
        sound: "open/closed vowels",
        ipa: "/ɛ/ vs /e/, /ɔ/ vs /o/",
        description: "Vowel height contrasts",
        tip: "Korean ㅔ and ㅐ used to contrast but merged in modern Seoul Korean. PT-EU keeps them distinct: 'é' (open, café) vs 'ê' (closed, você). The accent mark guides you.",
        mouthPosition: "open_e",
      },
      {
        sound: "word stress",
        ipa: "variable",
        description: "Unpredictable stress",
        tip: "Korean has relatively even syllable timing. PT-EU is stress-timed — stressed syllables are louder and longer, others shrink. Stress can change meaning: 'sábia' (wise) vs 'sabiá' (bird).",
      },
    ],
    grammarGaps: [
      {
        concept: "Articles (o/a, um/uma)",
        explanation: "Every noun requires a definite or indefinite article",
        l1Comparison: "Korean has no articles. You must say 'o livro' (the book), not just 'livro'. The article signals gender (masculine/feminine) and definiteness (the/a).",
      },
      {
        concept: "Grammatical gender",
        explanation: "Every noun is masculine or feminine, affecting articles and adjectives",
        l1Comparison: "Korean has no grammatical gender. PT-EU assigns gender to all nouns: 'o sol' (sun, m), 'a lua' (moon, f). Adjectives change form too: 'bonito' (m) vs 'bonita' (f).",
      },
      {
        concept: "SVO word order",
        explanation: "Subject-Verb-Object is the default",
        l1Comparison: "Korean is SOV with particles (나는 책을 읽었다). PT-EU is SVO: 'Eu li o livro' (I read the book). The verb moves to the middle. No particles — word position shows function.",
      },
      {
        concept: "Verb conjugation",
        explanation: "6 person forms × 12+ tenses across 3 moods",
        l1Comparison: "Korean conjugates for politeness and tense with suffixes. PT-EU conjugates for PERSON: eu falo, tu falas, ele fala... Each person gets a unique ending. The concept of person-based endings is new.",
      },
      {
        concept: "Ser vs Estar",
        explanation: "Two verbs for 'to be'",
        l1Comparison: "Korean 이다 (ida) for identity and 있다 (itda) for existence actually mirror ser/estar somewhat! 'Sou coreano' (I am Korean — ser/이다) vs 'Estou em Lisboa' (I am in Lisbon — estar/있다).",
      },
      {
        concept: "Prepositions (not particles)",
        explanation: "de, em, a, para, com, por — come BEFORE the noun",
        l1Comparison: "Korean uses particles AFTER nouns (에/에서/의/를/을). PT-EU prepositions precede: 'em Lisboa' (in Lisbon), 'de Portugal' (from Portugal). They also contract with articles: em+o=no.",
      },
      {
        concept: "Subjunctive mood",
        explanation: "Required for doubt, desire, emotion",
        l1Comparison: "Korean has no subjunctive. It uses different sentence endings for politeness/mood. PT-EU requires specific verb forms: 'Espero que venhas' (I hope you come) — 'venhas' is subjunctive.",
      },
      {
        concept: "Personal infinitive",
        explanation: "Infinitive conjugated for person — unique to Portuguese",
        l1Comparison: "No Korean equivalent. 'Para nós fazermos' (for us to do) — the infinitive gets a personal ending. This replaces an entire subordinate clause.",
      },
      {
        concept: "Adjective agreement and position",
        explanation: "Adjectives agree in gender/number and usually follow the noun",
        l1Comparison: "Korean adjectives precede the noun and never change form. PT-EU adjectives follow the noun AND change: 'casa bonita' (f), 'livro bonito' (m), 'casas bonitas' (f.pl).",
      },
      {
        concept: "Plural formation",
        explanation: "Add -s or -es, articles change too",
        l1Comparison: "Korean rarely marks plurals (들 is optional). PT-EU always marks them: 'livro' → 'livros', 'o' → 'os'. Every countable noun shows its number.",
      },
      {
        concept: "Tu vs Você vs O Senhor",
        explanation: "Three formality levels for 'you'",
        l1Comparison: "Korean has elaborate honorifics (존댓말/반말). PT-EU is simpler: 'tu' (intimate), 'você' (neutral but can be awkward), 'o senhor/a senhora' (formal). In Portugal, default to 'tu' among peers.",
      },
      {
        concept: "Object pronoun placement",
        explanation: "Before or after the verb depending on triggers",
        l1Comparison: "Korean puts objects before the verb (나를 봐). PT-EU has complex pronoun rules: 'Vê-me' (see me, after verb) vs 'Não me vê' (doesn't see me, before verb).",
      },
      {
        concept: "Reflexive verbs",
        explanation: "Many common verbs need a reflexive pronoun (se)",
        l1Comparison: "Korean has no reflexive verbs. PT-EU uses them constantly: 'Chamo-me Ana' (I call myself Ana = My name is Ana), 'Levanto-me' (I get up). The pronoun changes with the person.",
      },
    ],
    skipBasics: false,
    startingCEFR: "A1",
  },
};
