import type { CulturalRef } from "../types.js";

export const zhCulturalRefs: readonly CulturalRef[] = [
  {
    id: "zh_cha_tea",
    type: "reference",
    contentPt: "Chá",
    contentL1: "茶 (chá)",
    explanation: "The Portuguese word 'chá' comes directly from Cantonese. Portugal was the first European nation to trade tea from China via Macau. The pronunciation is nearly identical. Most European languages got 'tea' from Hokkien; Portuguese kept the Cantonese form because of their Macau connection.",
    cefrMin: "A1",
    tags: ["vocabulary", "history"],
  },
  {
    id: "zh_macau",
    type: "reference",
    contentPt: "Macau — 450 anos portugueses",
    contentL1: "澳门 — 450年葡萄牙管治",
    explanation: "Macau was Portuguese from 1557 to 1999. Portuguese is still an official language there. Macanese cuisine fuses Portuguese and Cantonese cooking. This shared history means Chinese speakers have a unique cultural bridge to Portugal.",
    cefrMin: "A2",
    tags: ["history", "culture", "macau"],
  },
  {
    id: "zh_pasteis_egg_tart",
    type: "reference",
    contentPt: "Pastéis de nata",
    contentL1: "葡式蛋挞",
    explanation: "Macau's famous egg tarts are adapted from Portuguese pastéis de nata. Andrew Stow brought the recipe to Macau in 1989. The Macanese version uses a slightly different crust, but the origin is the same Belém recipe. When you eat a pastél de nata in Lisbon, you are tasting the original.",
    cefrMin: "A1",
    tags: ["food", "macau", "culture"],
  },
  {
    id: "zh_saudade",
    type: "expression",
    contentPt: "Saudade",
    contentL1: "思乡 / 怀念",
    explanation: "The famous untranslatable Portuguese word. Chinese 思乡 (homesickness) and 怀念 (nostalgia) are close but miss the bittersweet pleasure of the longing itself. Saudade connects to the melancholy of classical Chinese poetry about separation.",
    cefrMin: "B1",
    tags: ["culture", "emotion"],
  },
  {
    id: "zh_fixe",
    type: "expression",
    contentPt: "Fixe!",
    contentL1: "太棒了!",
    explanation: "'Fixe' means 'cool' or 'awesome'. Use it like 太棒了. When something impresses you: 'Que fixe!' The most common positive reaction word in everyday Portuguese.",
    cefrMin: "A1",
    tags: ["slang", "daily-life"],
  },
  {
    id: "zh_pois",
    type: "expression",
    contentPt: "Pois...",
    contentL1: "喔... / 是啊...",
    explanation: "'Pois' is the most versatile Portuguese filler. Like Chinese 喔 or 是啊, it expresses agreement, resignation, or fills a pause. 'Pois pois' (doubled) is politely disinterested.",
    cefrMin: "A1",
    tags: ["conversation", "daily-life"],
  },
  {
    id: "zh_fado",
    type: "reference",
    contentPt: "Fado",
    contentL1: "如二胡曲的情感深度",
    explanation: "Fado is Portugal's soul music — mournful, about fate and longing. Chinese speakers can connect it to the emotional depth of erhu music or Tang dynasty poetry. Amália Rodrigues is fado's greatest voice.",
    cefrMin: "B1",
    tags: ["music", "culture"],
  },
  {
    id: "zh_family",
    type: "reference",
    contentPt: "Família é tudo",
    contentL1: "家庭为重",
    explanation: "Like Chinese culture, Portuguese culture is deeply family-oriented. Sunday family lunches are sacred. Elders are respected. Children often live with parents until marriage. The concept of filial respect will feel familiar.",
    cefrMin: "A2",
    tags: ["culture", "family"],
  },
  {
    id: "zh_navigation",
    type: "reference",
    contentPt: "Os Descobrimentos",
    contentL1: "大航海时代 (如郑和下西洋)",
    explanation: "Portugal's Age of Discoveries parallels Zheng He's voyages. Both were maritime powers. Vasco da Gama reached India in 1498; Portuguese reached China by 1513 and established Macau. This shared seafaring history connects the two cultures.",
    cefrMin: "B1",
    tags: ["history", "culture"],
  },
  {
    id: "zh_25_abril",
    type: "reference",
    contentPt: "25 de Abril — Revolução dos Cravos",
    contentL1: "康乃馨革命 (1974)",
    explanation: "On April 25, 1974, Portugal peacefully overthrew its dictatorship. Soldiers put carnations in their rifles. This revolution directly led to the return of Macau to China in 1999.",
    cefrMin: "B1",
    tags: ["history", "identity"],
  },
  {
    id: "zh_bacalhau",
    type: "reference",
    contentPt: "Bacalhau",
    contentL1: "咸鱼干 (365种做法)",
    explanation: "Salted cod is Portugal's national ingredient. Chinese cuisine also values preserved fish. 'Bacalhau à Brás' (shredded cod with eggs and potatoes) is the most popular preparation.",
    cefrMin: "A2",
    tags: ["food", "culture"],
  },
  {
    id: "zh_pronto",
    type: "expression",
    contentPt: "Pronto!",
    contentL1: "好了! / 行了!",
    explanation: "'Pronto' means 'done!', 'ready!', or 'OK then!'. Used like 好了. 'Pronto, vamos!' = OK, let's go. One of the most common words in everyday Portuguese.",
    cefrMin: "A1",
    tags: ["daily-life", "conversation"],
  },
  {
    id: "zh_azulejo",
    type: "reference",
    contentPt: "Azulejos",
    contentL1: "青花瓷砖 (如中国青花瓷)",
    explanation: "Portugal's blue and white ceramic tiles have a visual connection to Chinese blue and white porcelain. The Portuguese were major importers of Chinese porcelain, and azulejo artists were inspired by Chinese motifs. Both traditions share Islamic artistic roots.",
    cefrMin: "A2",
    tags: ["art", "culture", "history"],
  },
  {
    id: "zh_santos_populares",
    type: "reference",
    contentPt: "Festas dos Santos Populares",
    contentL1: "六月街头节日 (如庙会)",
    explanation: "Every June, Portugal celebrates street festivals with grilled sardines, music, and dancing. The atmosphere is like a Chinese temple fair — food stalls, crowds, and community joy. Santo António in Lisbon (June 13) is the biggest.",
    cefrMin: "A2",
    tags: ["culture", "festivals"],
  },
  {
    id: "zh_bica_coffee",
    type: "reference",
    contentPt: "Uma bica / um galão",
    contentL1: "浓缩咖啡 / 奶咖啡",
    explanation: "In Lisbon, espresso is called 'bica'. Coffee culture is fast — stand at the counter, drink in two sips. Very different from Chinese tea culture's contemplative pace, but equally embedded in daily life.",
    cefrMin: "A1",
    tags: ["food", "daily-life"],
  },
  {
    id: "zh_macanese_cuisine",
    type: "reference",
    contentPt: "Cozinha macaense",
    contentL1: "澳门土生菜 — 中葡融合料理",
    explanation: "Macanese cuisine is the world's oldest fusion food — 450 years of Portuguese and Cantonese ingredients blending together. 'Minchi' (ground meat with fried potatoes and egg), 'galinha à africana' (African chicken), and 'arroz gordo' (rich rice) exist nowhere else. In Portugal, 'restaurante macaense' is a niche delicacy. Learning food vocabulary through this shared culinary heritage makes Portuguese feel less foreign.",
    cefrMin: "A2",
    tags: ["food", "macau", "culture"],
  },
  {
    id: "zh_filial_piety",
    type: "reference",
    contentPt: "Respeito pelos mais velhos",
    contentL1: "敬老 — 和中国孝道相似",
    explanation: "Portuguese culture shares a deep respect for elders that Chinese speakers will recognize as similar to 孝 (filial piety). Grandparents are central to family life. Children often live at home until marriage. 'O senhor' and 'a senhora' (formal 'you') are used with elders, parallel to Chinese honorific speech. Sunday lunch at the grandparents' house is sacred and non-negotiable.",
    cefrMin: "A2",
    tags: ["culture", "family", "etiquette"],
  },
  {
    id: "zh_porcelain_trade",
    type: "reference",
    contentPt: "Porcelana e azulejos — ligação artística",
    contentL1: "瓷器贸易 — 从青花瓷到青花瓷砖",
    explanation: "Portuguese azulejo tiles were directly inspired by Chinese 青花瓷 (blue and white porcelain) imported via Macau in the 16th century. The word 'porcelana' in Portuguese comes from the same trade. Portuguese artists adapted Chinese motifs into their own tile tradition. Visiting an azulejo museum in Portugal, a Chinese speaker will spot familiar patterns — dragons, flowers, geometric borders — that crossed the ocean five centuries ago.",
    cefrMin: "B1",
    tags: ["art", "history", "macau", "culture"],
  },
  // --- MODERN SLANG ---
  {
    id: "zh_bue",
    type: "expression",
    contentPt: "Bué",
    contentL1: "超 / 特别 / 巨",
    explanation: "'Bué' means 'a lot' or 'very' — from Kimbundu (Angolan language). 'Bué fixe' (超棒), 'bué caro' (特别贵), 'bué gente' (巨多人). Used constantly by young Portuguese. Functions like 超 or 特别 as an informal intensifier.",
    cefrMin: "A2",
    tags: ["slang", "daily-life"],
  },
  {
    id: "zh_cena",
    type: "expression",
    contentPt: "Cena",
    contentL1: "那个东西 / 那个事儿",
    explanation: "Originally means 'scene' but in PT-EU slang it means 'thing/stuff/situation'. 'Que cena!' (什么情况!), 'é uma cena estranha' (一件奇怪的事儿). Like Chinese 那个 when you can't name the thing. 'Dá-me aquela cena' (把那个给我).",
    cefrMin: "A2",
    tags: ["slang", "daily-life"],
  },
  {
    id: "zh_tipo",
    type: "expression",
    contentPt: "Tipo...",
    contentL1: "就是... / 那个... / 怎么说呢...",
    explanation: "The Portuguese filler word, used exactly like Chinese 那个 or 就是. 'Ele é tipo alto' (他就是...很高). Young Portuguese pepper every sentence with 'tipo'. Not appropriate in formal speech.",
    cefrMin: "A2",
    tags: ["slang", "conversation"],
  },
  {
    id: "zh_ganda",
    type: "expression",
    contentPt: "Ganda / Granda",
    contentL1: "牛! / 太厉害了!",
    explanation: "Contraction of 'grande' — used as an intensifier. 'Ganda filme!' (牛逼的电影!), 'Granda maluco!' (太厉害了这人!). Like 牛 or 厉害 in Chinese internet slang. Colloquial Lisbon slang, slightly vulgar — don't use in formal settings.",
    cefrMin: "B1",
    tags: ["slang"],
  },
  {
    id: "zh_bazar",
    type: "expression",
    contentPt: "Bazar",
    contentL1: "走了 / 撤了 / 闪人",
    explanation: "'Bazar' means 'to leave/bounce'. 'Vou bazar' (我走了 / 我撤了). Informal, like Chinese 闪人 or 撤了 in casual speech. The more formal version is 'ir-se embora': 'Vou-me embora' (我走了/我要离开了).",
    cefrMin: "B1",
    tags: ["slang", "daily-life"],
  },
  {
    id: "zh_curtir",
    type: "expression",
    contentPt: "Curtir",
    contentL1: "享受 / 喜欢 / 玩得开心",
    explanation: "'Curtir' means to enjoy or to be into something. 'Curto bué música portuguesa' (我超喜欢葡萄牙音乐). 'Vamos curtir a noite' (我们今晚去玩吧). Also used for liking someone: 'Ela curte-o' (她喜欢他).",
    cefrMin: "A2",
    tags: ["slang", "daily-life"],
  },
  {
    id: "zh_na_boa",
    type: "expression",
    contentPt: "Na boa",
    contentL1: "没问题 / 没事儿",
    explanation: "'Na boa' means 'no worries / it's all good'. 'Podes usar o meu carro, na boa' (你用我的车吧，没问题). Also used as a question: 'Tás na boa?' (你没事吧?). Like 没问题 or 没事儿 — one of the most useful casual phrases.",
    cefrMin: "A1",
    tags: ["slang", "daily-life"],
  },
  {
    id: "zh_o_pa",
    type: "expression",
    contentPt: "Ó pá!",
    contentL1: "哎! / 喂! / 老兄!",
    explanation: "The quintessential Portuguese interjection. 'Ó pá, não acredito!' (哎，不会吧!). Used between friends, like 哎 or 喂. Short for 'rapaz' (boy). Can express surprise, frustration, or just be a casual address.",
    cefrMin: "A1",
    tags: ["slang", "daily-life"],
  },
  {
    id: "zh_mano",
    type: "expression",
    contentPt: "Mano / Mana",
    contentL1: "兄弟 / 姐妹 (朋友之间的称呼)",
    explanation: "Short for 'irmão/irmã' (brother/sister). Used as 'bro/sis' between close friends. 'Olha, mano, ouve lá...' (兄弟，你听我说...). Like Chinese 兄弟 or 哥们儿 between friends. Very common in Lisbon's multicultural neighbourhoods.",
    cefrMin: "A2",
    tags: ["slang", "daily-life"],
  },
  {
    id: "zh_mandar_vir",
    type: "expression",
    contentPt: "Mandar vir",
    contentL1: "抱怨 / 点菜 (两个意思!)",
    explanation: "Has two completely different meanings depending on context. 1) 'To complain': 'Ele está sempre a mandar vir com tudo' (他总是在抱怨). 2) 'To order': 'Manda vir mais uma cerveja' (再点一杯啤酒). Context always makes it clear.",
    cefrMin: "B1",
    tags: ["slang", "daily-life"],
  },
  {
    id: "zh_ta_se_bem",
    type: "expression",
    contentPt: "Tá-se bem",
    contentL1: "行! / 好的!",
    explanation: "Contraction of 'está-se bem' — 'it's all good'. Used to accept a proposal. 'Vamos ao cinema?' — 'Tá-se bem!' (去看电影吗? — 行!). Very casual, very common.",
    cefrMin: "A1",
    tags: ["slang", "daily-life"],
  },
  // --- ANCIENT PROVERBS / PROVÉRBIOS ---
  {
    id: "zh_agua_pedra",
    type: "expression",
    contentPt: "Água mole em pedra dura, tanto bate até que fura",
    contentL1: "滴水穿石",
    explanation: "Literally: 'Soft water on hard stone, hits until it pierces.' Chinese has the identical 滴水穿石 (dripping water pierces stone). Both come from ancient wisdom traditions. This is one of the clearest cultural parallels between Portuguese and Chinese proverbs.",
    cefrMin: "B1",
    tags: ["proverb", "wisdom"],
  },
  {
    id: "zh_cao_gato",
    type: "expression",
    contentPt: "Quem não tem cão, caça com gato",
    contentL1: "没有条件创造条件也要上",
    explanation: "Literally: 'Who doesn't have a dog, hunts with a cat.' Make do with what you have. Similar to Chinese 没有条件创造条件也要上 (if there are no conditions, create them and push forward). The Portuguese philosophy of 'desenrascar-se' in proverb form.",
    cefrMin: "B1",
    tags: ["proverb", "culture"],
  },
  {
    id: "zh_grao_galinha",
    type: "expression",
    contentPt: "Grão a grão, enche a galinha o papo",
    contentL1: "积少成多 / 聚沙成塔",
    explanation: "Literally: 'Grain by grain, the hen fills her crop.' Small things add up. Chinese has 积少成多 (accumulate little to make much) and 聚沙成塔 (gather sand to build a pagoda). All celebrate patient, consistent effort.",
    cefrMin: "B1",
    tags: ["proverb", "wisdom"],
  },
  {
    id: "zh_pepino",
    type: "expression",
    contentPt: "De pequenino se torce o pepino",
    contentL1: "三岁看大，七岁看老",
    explanation: "Literally: 'You bend the cucumber when it's small.' Habits are formed young. Chinese has 三岁看大，七岁看老 (at three you see the adult, at seven you see the elder). Both cultures believe early education shapes character permanently.",
    cefrMin: "B1",
    tags: ["proverb", "education"],
  },
  {
    id: "zh_tripas_coracao",
    type: "expression",
    contentPt: "Fazer das tripas coração",
    contentL1: "硬着头皮上 / 鼓起勇气",
    explanation: "Literally: 'To make heart out of guts.' To summon courage when you have none. Like Chinese 硬着头皮上 (to push forward with a stiff scalp) or 鼓起勇气 (to drum up courage). Origin may be linked to Porto, whose residents ate only tripe after sending good meat to the discovery fleets.",
    cefrMin: "B1",
    tags: ["proverb", "history", "porto"],
  },
  {
    id: "zh_ver_navios",
    type: "expression",
    contentPt: "Ficar a ver navios",
    contentL1: "竹篮打水一场空 / 白等",
    explanation: "Literally: 'To be left watching ships.' To be left empty-handed. Origin: during the Age of Discoveries, women waited for ships that never returned. Like Chinese 竹篮打水一场空 (drawing water with a bamboo basket — ending with nothing). 'Fiquei a ver navios' = 白等了.",
    cefrMin: "B1",
    tags: ["proverb", "history", "discoveries"],
  },
  {
    id: "zh_engolir_sapos",
    type: "expression",
    contentPt: "Engolir sapos",
    contentL1: "忍气吞声",
    explanation: "Literally: 'To swallow frogs.' To endure insults without reacting. Chinese has the nearly identical 忍气吞声 (swallow anger and voice). 'No trabalho, tenho de engolir muitos sapos' (工作中不得不忍气吞声). Ancient proverb, still used daily.",
    cefrMin: "B1",
    tags: ["proverb", "daily-life"],
  },
  {
    id: "zh_burros_agua",
    type: "expression",
    contentPt: "Dar com os burros na água",
    contentL1: "功亏一篑 / 搞砸了",
    explanation: "Literally: 'To end up with the donkeys in the water.' To fail completely. Like Chinese 功亏一篑 (to fail at the last basket of earth — almost finished but ruined). Origin: donkeys falling into rivers while crossing, losing all the cargo.",
    cefrMin: "B1",
    tags: ["proverb", "daily-life"],
  },
  {
    id: "zh_rossio_betesga",
    type: "expression",
    contentPt: "Meter o Rossio na Betesga",
    contentL1: "把天安门塞进胡同 — 不可能的事",
    explanation: "Literally: 'To fit the Rossio (Lisbon's grand square) into the Betesga (a tiny alley nearby).' Attempting the impossible. A purely Lisbon-born proverb from the Middle Ages. Like trying to fit 天安门广场 into a 胡同.",
    cefrMin: "B2",
    tags: ["proverb", "lisbon", "history"],
  },
  {
    id: "zh_mar_lugar",
    type: "expression",
    contentPt: "Quem vai ao mar, perde o lugar",
    contentL1: "离开了位子就别想回来",
    explanation: "Literally: 'Who goes to sea, loses their place.' If you leave, someone else takes your spot. Maritime origin — fishermen who went to sea lost their seat at the tavern. Used today for parking spots, seats, any contested position.",
    cefrMin: "A2",
    tags: ["proverb", "maritime", "daily-life"],
  },
  // --- DAILY IDIOMS ---
  {
    id: "zh_ora_essa",
    type: "expression",
    contentPt: "Ora essa!",
    contentL1: "哪里哪里! / 不客气!",
    explanation: "An exclamation of modest denial when thanked. 'Obrigado pela ajuda!' — 'Ora essa!' (谢谢帮忙! — 哪里哪里!). Like Chinese 哪里哪里 — both cultures value modesty when receiving compliments or thanks.",
    cefrMin: "A2",
    tags: ["daily-life", "etiquette"],
  },
  {
    id: "zh_descansado",
    type: "expression",
    contentPt: "Está descansado / Fica descansado",
    contentL1: "放心吧 / 别担心",
    explanation: "Literally: 'Be rested/at ease.' Means 'don't worry, I've got it covered.' 'Fica descansado, eu trato disso' (放心吧，我来处理). Like 放心吧. Feminine form: 'Fica descansada'.",
    cefrMin: "A2",
    tags: ["daily-life", "conversation"],
  },
  {
    id: "zh_nao_faz_mal",
    type: "expression",
    contentPt: "Não faz mal",
    contentL1: "没关系 / 没事儿",
    explanation: "Literally: 'It doesn't do harm.' The standard response when someone apologizes. 'Desculpa o atraso!' — 'Não faz mal!' (对不起迟到了! — 没关系!). Like 没关系 or 没事儿. One of the first phrases you will hear and need.",
    cefrMin: "A1",
    tags: ["daily-life", "etiquette"],
  },
  {
    id: "zh_deixa_la",
    type: "expression",
    contentPt: "Deixa lá",
    contentL1: "算了 / 别管了",
    explanation: "'Deixa lá' means 'let it go / forget about it.' 'Queres que te pague?' — 'Deixa lá!' (要不要我付钱? — 算了!). Can also be consoling: 'Deixa lá, amanhã corre melhor' (算了，明天会更好). Like 算了.",
    cefrMin: "A1",
    tags: ["daily-life", "conversation"],
  },
  {
    id: "zh_e_o_que_e",
    type: "expression",
    contentPt: "É o que é",
    contentL1: "就这样吧 / 没办法",
    explanation: "The Portuguese 'it is what it is.' 'O preço subiu? É o que é.' (涨价了? 没办法). Like 没办法 or 就这样吧 — a philosophical acceptance of things you can't change.",
    cefrMin: "A2",
    tags: ["daily-life", "culture"],
  },
  {
    id: "zh_olha_la",
    type: "expression",
    contentPt: "Olha lá / Ouve lá",
    contentL1: "喂 / 你看 / 我问一下",
    explanation: "'Olha lá' (look here) and 'ouve lá' (listen here) get attention or start a question. 'Olha lá, sabes onde fica o correio?' (喂，你知道邮局在哪吗?). Like 喂 or 你看 — the standard way to approach someone. Not rude.",
    cefrMin: "A1",
    tags: ["daily-life", "conversation"],
  },
  {
    id: "zh_entao",
    type: "expression",
    contentPt: "Então?",
    contentL1: "那? / 怎样?",
    explanation: "'Então?' is the universal Portuguese greeting-question. 'Então, tudo bem?' (怎样，一切好吗?). Also used to prompt: 'Então, o que queres fazer?' (那，你想干什么?). Short, warm, multipurpose.",
    cefrMin: "A1",
    tags: ["daily-life", "conversation"],
  },
  {
    id: "zh_se_calhar",
    type: "expression",
    contentPt: "Se calhar",
    contentL1: "也许 / 说不定",
    explanation: "Literally: 'if it falls (that way).' Means 'maybe / perhaps.' 'Se calhar vou ao cinema amanhã' (说不定明天去看电影). More common than 'talvez' in everyday speech. Note: in PT-EU this does NOT trigger the subjunctive, unlike 'talvez'.",
    cefrMin: "A2",
    tags: ["daily-life", "grammar"],
  },
  {
    id: "zh_com_certeza",
    type: "expression",
    contentPt: "Com certeza",
    contentL1: "当然 (注意: 可能不是真心的!)",
    explanation: "'Com certeza' means 'certainly.' BUT in PT-EU it is often a polite but non-committal agreement — like saying 当然 but not really meaning it. A Portuguese 'com certeza' can mean 'I'll think about it' (and forget). Similar to how 好好好 in Chinese doesn't always mean genuine agreement.",
    cefrMin: "A2",
    tags: ["daily-life", "etiquette", "culture"],
  },
];
