import type { CulturalRef } from "../types.js";

export const zhCulturalRefs: readonly CulturalRef[] = [
  {
    id: "zh_cha_tea",
    type: "reference",
    contentPt: "Chá",
    contentL1: "茶 (chá)",
    explanation: "The Portuguese word 'chá' comes directly from Cantonese. Portugal was the first European nation to trade tea from China via Macau. The pronunciation is nearly identical. Most European languages got 'tea' from Hokkien; Portuguese kept the Cantonese form because of their Macau connection.",
    cefrMin: "A1",
    tags: ["vocabulary", "history"],
  },
  {
    id: "zh_macau",
    type: "reference",
    contentPt: "Macau — 450 anos portugueses",
    contentL1: "澳门 — 450年葡萄牙管治",
    explanation: "Macau was Portuguese from 1557 to 1999. Portuguese is still an official language there. Macanese cuisine fuses Portuguese and Cantonese cooking. This shared history means Chinese speakers have a unique cultural bridge to Portugal.",
    cefrMin: "A2",
    tags: ["history", "culture", "macau"],
  },
  {
    id: "zh_pasteis_egg_tart",
    type: "reference",
    contentPt: "Pastéis de nata",
    contentL1: "葡式蛋挞",
    explanation: "Macau's famous egg tarts are adapted from Portuguese pastéis de nata. Andrew Stow brought the recipe to Macau in 1989. The Macanese version uses a slightly different crust, but the origin is the same Belém recipe. When you eat a pastél de nata in Lisbon, you are tasting the original.",
    cefrMin: "A1",
    tags: ["food", "macau", "culture"],
  },
  {
    id: "zh_saudade",
    type: "expression",
    contentPt: "Saudade",
    contentL1: "思乡 / 怀念",
    explanation: "The famous untranslatable Portuguese word. Chinese 思乡 (homesickness) and 怀念 (nostalgia) are close but miss the bittersweet pleasure of the longing itself. Saudade connects to the melancholy of classical Chinese poetry about separation.",
    cefrMin: "B1",
    tags: ["culture", "emotion"],
  },
  {
    id: "zh_fixe",
    type: "expression",
    contentPt: "Fixe!",
    contentL1: "太棒了!",
    explanation: "'Fixe' means 'cool' or 'awesome'. Use it like 太棒了. When something impresses you: 'Que fixe!' The most common positive reaction word in everyday Portuguese.",
    cefrMin: "A1",
    tags: ["slang", "daily-life"],
  },
  {
    id: "zh_pois",
    type: "expression",
    contentPt: "Pois...",
    contentL1: "喔... / 是啊...",
    explanation: "'Pois' is the most versatile Portuguese filler. Like Chinese 喔 or 是啊, it expresses agreement, resignation, or fills a pause. 'Pois pois' (doubled) is politely disinterested.",
    cefrMin: "A1",
    tags: ["conversation", "daily-life"],
  },
  {
    id: "zh_fado",
    type: "reference",
    contentPt: "Fado",
    contentL1: "如二胡曲的情感深度",
    explanation: "Fado is Portugal's soul music — mournful, about fate and longing. Chinese speakers can connect it to the emotional depth of erhu music or Tang dynasty poetry. Amália Rodrigues is fado's greatest voice.",
    cefrMin: "B1",
    tags: ["music", "culture"],
  },
  {
    id: "zh_family",
    type: "reference",
    contentPt: "Família é tudo",
    contentL1: "家庭为重",
    explanation: "Like Chinese culture, Portuguese culture is deeply family-oriented. Sunday family lunches are sacred. Elders are respected. Children often live with parents until marriage. The concept of filial respect will feel familiar.",
    cefrMin: "A2",
    tags: ["culture", "family"],
  },
  {
    id: "zh_navigation",
    type: "reference",
    contentPt: "Os Descobrimentos",
    contentL1: "大航海时代 (如郑和下西洋)",
    explanation: "Portugal's Age of Discoveries parallels Zheng He's voyages. Both were maritime powers. Vasco da Gama reached India in 1498; Portuguese reached China by 1513 and established Macau. This shared seafaring history connects the two cultures.",
    cefrMin: "B1",
    tags: ["history", "culture"],
  },
  {
    id: "zh_25_abril",
    type: "reference",
    contentPt: "25 de Abril — Revolução dos Cravos",
    contentL1: "康乃馨革命 (1974)",
    explanation: "On April 25, 1974, Portugal peacefully overthrew its dictatorship. Soldiers put carnations in their rifles. This revolution directly led to the return of Macau to China in 1999.",
    cefrMin: "B1",
    tags: ["history", "identity"],
  },
  {
    id: "zh_bacalhau",
    type: "reference",
    contentPt: "Bacalhau",
    contentL1: "咸鱼干 (365种做法)",
    explanation: "Salted cod is Portugal's national ingredient. Chinese cuisine also values preserved fish. 'Bacalhau à Brás' (shredded cod with eggs and potatoes) is the most popular preparation.",
    cefrMin: "A2",
    tags: ["food", "culture"],
  },
  {
    id: "zh_pronto",
    type: "expression",
    contentPt: "Pronto!",
    contentL1: "好了! / 行了!",
    explanation: "'Pronto' means 'done!', 'ready!', or 'OK then!'. Used like 好了. 'Pronto, vamos!' = OK, let's go. One of the most common words in everyday Portuguese.",
    cefrMin: "A1",
    tags: ["daily-life", "conversation"],
  },
  {
    id: "zh_azulejo",
    type: "reference",
    contentPt: "Azulejos",
    contentL1: "青花瓷砖 (如中国青花瓷)",
    explanation: "Portugal's blue and white ceramic tiles have a visual connection to Chinese blue and white porcelain. The Portuguese were major importers of Chinese porcelain, and azulejo artists were inspired by Chinese motifs. Both traditions share Islamic artistic roots.",
    cefrMin: "A2",
    tags: ["art", "culture", "history"],
  },
  {
    id: "zh_santos_populares",
    type: "reference",
    contentPt: "Festas dos Santos Populares",
    contentL1: "六月街头节日 (如庙会)",
    explanation: "Every June, Portugal celebrates street festivals with grilled sardines, music, and dancing. The atmosphere is like a Chinese temple fair — food stalls, crowds, and community joy. Santo António in Lisbon (June 13) is the biggest.",
    cefrMin: "A2",
    tags: ["culture", "festivals"],
  },
  {
    id: "zh_bica_coffee",
    type: "reference",
    contentPt: "Uma bica / um galão",
    contentL1: "浓缩咖啡 / 奶咖啡",
    explanation: "In Lisbon, espresso is called 'bica'. Coffee culture is fast — stand at the counter, drink in two sips. Very different from Chinese tea culture's contemplative pace, but equally embedded in daily life.",
    cefrMin: "A1",
    tags: ["food", "daily-life"],
  },
];
