import type { L1Profile } from "../types.js";

export const zhProfile: L1Profile = {
  code: "zh",
  name: "Chinese",
  nativeName: "中文",
  writingDirection: "ltr",
  hasLatinScript: false,
  transfer: {
    cognates: [
      "咖啡 kāfēi (café — coffee, via Portuguese trade routes)",
      "面包 miànbāo (pão — bread, Portuguese missionaries introduced the concept)",
      "肥皂 féizào (sabão — soap, via Portuguese contact in Macau)",
      "地图 dìtú (from Portuguese/Spanish mappa mundi influence)",
    ],
    falseFriends: [
      { word: "não", l1Meaning: "闹 (nào) sounds like 'make noise/fuss' in Mandarin", ptMeaning: "não means 'no' — the most common word in PT-EU" },
      { word: "dia", l1Meaning: "弟啊 (dì a) sounds like 'younger brother' vocative", ptMeaning: "dia means 'day' — 'bom dia' = good morning" },
      { word: "mal", l1Meaning: "卖 (mài) sounds similar — means 'to sell'", ptMeaning: "mal means 'badly/evil'" },
      { word: "pai", l1Meaning: "拍 (pāi) means 'to clap/hit/take a photo'", ptMeaning: "pai means 'father'" },
      { word: "mãe", l1Meaning: "sounds somewhat like 妹 (mèi) — younger sister", ptMeaning: "mãe means 'mother'" },
      { word: "dar", l1Meaning: "打 (dǎ) sounds similar — means 'to hit/strike'", ptMeaning: "dar means 'to give'" },
      { word: "fala", l1Meaning: "发啦 (fā la) sounds like 'got rich!' (informal)", ptMeaning: "fala means 'speaks' or 'speech'" },
      { word: "sala", l1Meaning: "撒拉 (sā la) — no clear meaning, but sounds like a Salar ethnic group name", ptMeaning: "sala means 'room/living room'" },
      { word: "bom", l1Meaning: "笨 (bèn) sounds somewhat similar — means 'stupid'", ptMeaning: "bom means 'good' — as in 'bom dia'" },
      { word: "mala", l1Meaning: "麻辣 (málà) sounds similar — means 'numbing spicy'", ptMeaning: "mala means 'suitcase/bag'" },
      { word: "chá", l1Meaning: "茶 (chá) — same word! Tea came to Europe via Portuguese trade with China", ptMeaning: "chá means 'tea' — one of the few true Chinese-Portuguese cognates" },
      { word: "sopa", l1Meaning: "sounds like 缩 (suō) + 怕 (pà) — no meaning", ptMeaning: "sopa means 'soup'" },
      { word: "largo", l1Meaning: "拉过 (lā guò) — 'pulled past'", ptMeaning: "largo means 'wide' or 'public square'" },
      { word: "comer", l1Meaning: "可么 — no standard meaning", ptMeaning: "comer means 'to eat'" },
      { word: "mar", l1Meaning: "马 (mǎ) sounds similar — 'horse'", ptMeaning: "mar means 'sea/ocean'" },
      { word: "ser", l1Meaning: "色 (sè) sounds similar — 'colour'", ptMeaning: "ser means 'to be' (identity/permanent)" },
      { word: "ter", l1Meaning: "特 (tè) sounds similar — 'special'", ptMeaning: "ter means 'to have'" },
      { word: "nome", l1Meaning: "no direct Mandarin cognate", ptMeaning: "nome means 'name'" },
      { word: "porta", l1Meaning: "泼他 (pō tā) — 'splash him'", ptMeaning: "porta means 'door'" },
      { word: "conta", l1Meaning: "sounds like 看他 (kàn tā) — 'look at him'", ptMeaning: "conta means 'bill/account/story'" },
      { word: "caro", l1Meaning: "卡肉 — no meaning", ptMeaning: "caro means 'expensive' or 'dear'" },
      { word: "gato", l1Meaning: "嘎头 — no standard meaning", ptMeaning: "gato means 'cat'" },
      { word: "banco", l1Meaning: "搬口 — no meaning", ptMeaning: "banco means 'bank' or 'bench'" },
      { word: "rua", l1Meaning: "如啊 — no meaning", ptMeaning: "rua means 'street'" },
      { word: "mesa", l1Meaning: "没撒 (méi sā) — sounds like 'didn't scatter'", ptMeaning: "mesa means 'table' — a key word in restaurants and offices" },
      { word: "casa", l1Meaning: "卡撒 — sounds like 刷卡 (shuā kǎ, swipe card) reversed", ptMeaning: "casa means 'house/home' — 'em casa' = at home" },
      { word: "água", l1Meaning: "阿瓜 — sounds like a nickname for 瓜 (guā, melon)", ptMeaning: "água means 'water' — the most essential word for daily life" },
      { word: "falar", l1Meaning: "发啦 (fā la) — 'got rich/sent it'", ptMeaning: "falar means 'to speak/talk' — the most common verb in conversation" },
      { word: "pagar", l1Meaning: "怕嘎 — no standard meaning", ptMeaning: "pagar means 'to pay' — essential for shops, restaurants, bills" },
      { word: "morada", l1Meaning: "莫拉达 — no meaning", ptMeaning: "morada means 'address' — needed for official documents in Portugal" },
      { word: "trabalho", l1Meaning: "sounds vaguely like 他把了后 — no meaning", ptMeaning: "trabalho means 'work/job' — essential vocabulary for immigrants" },
      { word: "dinheiro", l1Meaning: "no Mandarin similarity", ptMeaning: "dinheiro means 'money' — 'Quanto dinheiro?' = How much money?" },
      { word: "prato", l1Meaning: "sounds like 怕他 (pà tā) — 'afraid of him/her'", ptMeaning: "prato means 'plate' or 'dish/course' — 'prato do dia' = dish of the day" },
      { word: "cama", l1Meaning: "卡麻 — sounds like 'stuck numb'", ptMeaning: "cama means 'bed'" },
      { word: "vida", l1Meaning: "维达 — sounds like a brand name", ptMeaning: "vida means 'life' — 'boa vida' = good life" },
      { word: "loja", l1Meaning: "螺蛳 (luósī) — vaguely similar, means 'river snail'", ptMeaning: "loja means 'shop/store'" },
      { word: "hora", l1Meaning: "活啦 (huó la) — sounds like 'alive!'", ptMeaning: "hora means 'hour/time' — 'Que horas são?' = What time is it?" },
      { word: "filho", l1Meaning: "no Mandarin similarity (儿子 = son)", ptMeaning: "filho means 'son' — filha means 'daughter'" },
      { word: "muito", l1Meaning: "sounds like 没偷 (méi tōu) — 'didn't steal'", ptMeaning: "muito means 'very/much/a lot' — one of the most frequent PT-EU words" },
      { word: "boa", l1Meaning: "sounds like 波啊 (bō a) — 'wave!' ", ptMeaning: "boa means 'good' (feminine) — 'boa noite' = good evening/night" },
    ],
    phoneticDifficulties: [
      {
        sound: "ão",
        ipa: "/ɐ̃w̃/",
        description: "Nasal diphthong -ão",
        tip: "Mandarin has no nasal diphthongs. Start with mouth open for 'a', nasalize by lowering the soft palate, then glide lips into a round 'u' shape — all while keeping air flowing through the nose. Practice: pão, não, mão.",
        mouthPosition: "nasal_ao",
      },
      {
        sound: "ã/õ/ẽ",
        ipa: "/ɐ̃/ /õ/ /ẽ/",
        description: "Nasal vowels",
        tip: "Mandarin -n and -ng finals are not the same as nasal vowels. PT-EU nasalizes the entire vowel, not just the ending. Keep air flowing through the nose throughout the vowel, not just at the end.",
        mouthPosition: "nasal_vowel",
      },
      {
        sound: "r/rr",
        ipa: "/ʁ/",
        description: "Uvular R (initial and double)",
        tip: "Not like Mandarin 日 (rì). PT-EU initial R and double RR are produced at the back of the throat — a uvular fricative, like gargling gently. 'Rato' (mouse), 'carro' (car).",
        mouthPosition: "uvular_r",
      },
      {
        sound: "r (tap)",
        ipa: "/ɾ/",
        description: "Alveolar tap between vowels",
        tip: "A quick flap of the tongue tip against the alveolar ridge. Mandarin has nothing like it. 'Caro' (expensive) vs 'carro' (car) — the single r is a light, fast touch.",
        mouthPosition: "alveolar_tap",
      },
      {
        sound: "lh",
        ipa: "/ʎ/",
        description: "Palatal lateral lh",
        tip: "No Mandarin equivalent. Press the middle of your tongue against the hard palate while air flows around the sides. 'Trabalho' (work), 'filho' (son). Like Italian 'gli'.",
        mouthPosition: "palatal_lateral",
      },
      {
        sound: "nh",
        ipa: "/ɲ/",
        description: "Palatal nasal nh",
        tip: "Similar to Mandarin 'ni' in some ways, but the tongue is further back against the palate. 'Vinho' (wine), 'amanhã' (tomorrow), 'Espanha' (Spain).",
        mouthPosition: "palatal_nasal",
      },
      {
        sound: "b/d/g",
        ipa: "/b/ /d/ /g/",
        description: "Voiced stops",
        tip: "Mandarin b/d/g are actually voiceless unaspirated. PT-EU b/d/g are truly voiced — your vocal cords vibrate from the start. Feel the buzz in your throat for 'bola', 'dar', 'gato'.",
      },
      {
        sound: "v vs f",
        ipa: "/v/ vs /f/",
        description: "Voiced vs voiceless labiodental",
        tip: "Mandarin has no /v/. Both /v/ and /f/ need upper teeth on lower lip, but /v/ adds vocal cord vibration. 'Vaca' (cow) vs 'faca' (knife).",
        mouthPosition: "labiodental_v",
      },
      {
        sound: "consonant clusters",
        ipa: "/pr/ /tr/ /pl/ /bl/ /str/",
        description: "Initial consonant clusters",
        tip: "Mandarin syllables follow a strict C-V pattern — no clusters. PT-EU stacks consonants: 'prato' (plate), 'três' (three), 'construção' (construction). Do not insert vowels between consonants.",
      },
      {
        sound: "reduced vowels",
        ipa: "/ɨ/ /ə/",
        description: "Unstressed vowels vanish",
        tip: "Mandarin pronounces every syllable with a tone. PT-EU swallows unstressed syllables — 'telefonema' sounds like 'tlfnema'. This is the biggest rhythm shock for Mandarin speakers.",
      },
      {
        sound: "s/z/ʃ/ʒ",
        ipa: "/s/ /z/ /ʃ/ /ʒ/",
        description: "Four sibilants",
        tip: "Mandarin has s, sh, but no z or zh (as fricatives). PT-EU 's' between vowels = /z/ ('casa' = 'kaza'). Final 's' = /ʃ/. 'J' = /ʒ/ (buzzing 'sh'). Each one is a different letter pattern.",
        mouthPosition: "sibilant_sh",
      },
      {
        sound: "word stress",
        ipa: "variable",
        description: "Stress-timed rhythm",
        tip: "Mandarin is syllable-timed with tones. PT-EU is stress-timed — stressed syllables are louder and longer, unstressed ones shrink. This gives PT-EU its 'rushing' rhythm that differs from Mandarin's even beat.",
      },
      {
        sound: "dark L",
        ipa: "/ɫ/",
        description: "Velarized L at end of syllables",
        tip: "Mandarin 'l' is always light (as in 拉 lā). PT-EU final L is dark and heavy — the back of the tongue raises toward the velum, making it sound almost like a 'w'. 'Portugal', 'sol' (sun), 'mal' (badly). This dark L does not exist in Mandarin.",
      },
      {
        sound: "diphthongs (ei, ou, ai)",
        ipa: "/ɐj/ /ow/ /aj/",
        description: "Oral diphthongs",
        tip: "Mandarin has diphthongs (ai, ei, ao, ou) so the concept is familiar. PT-EU diphthongs are similar but with European vowel qualities: 'pai' (/paj/), 'sei' (/sɐj/), 'vou' (/vow/). The glide is faster and less emphasised than in Mandarin.",
      },
      {
        sound: "word-final -e",
        ipa: "/ɨ/ or silent",
        description: "Final -e nearly disappears",
        tip: "Mandarin always pronounces final vowels clearly. PT-EU final -e is barely a whisper or drops entirely — 'cidade' sounds like 'cidadɨ' or 'cidad'. Never add a full Mandarin-style vowel at the end.",
      },
    ],
    grammarGaps: [
      {
        concept: "Articles (o/a, um/uma)",
        explanation: "Every noun needs a definite or indefinite article that matches gender",
        l1Comparison: "Chinese has no articles. You must say 'o livro' (the book) not just 'livro'. Articles also signal gender: 'o' (masculine), 'a' (feminine). This has no Chinese parallel.",
      },
      {
        concept: "Grammatical gender",
        explanation: "Every noun is masculine or feminine, affecting articles, adjectives, pronouns",
        l1Comparison: "Chinese has no grammatical gender. PT-EU assigns gender to all nouns, even objects: 'o sol' (the sun, m), 'a lua' (the moon, f). Adjectives change too: 'bonito' (m) vs 'bonita' (f).",
      },
      {
        concept: "Verb conjugation",
        explanation: "Verbs change form for person (6), tense (12+), and mood (3)",
        l1Comparison: "Chinese verbs never change form (吃 is always 吃). PT-EU verbs have dozens of forms: eu falo, tu falas, ele fala, nós falamos... across present, past, future, subjunctive. This is the single biggest learning challenge.",
      },
      {
        concept: "Tense system",
        explanation: "Past, present, future with multiple sub-tenses each",
        l1Comparison: "Chinese uses particles (了/过/着) and context for time. PT-EU encodes time in verb endings: 'falei' (I spoke), 'falo' (I speak), 'falarei' (I will speak). Each tense has a specific form.",
      },
      {
        concept: "Ser vs Estar",
        explanation: "Two verbs for 'to be' — ser for identity, estar for states",
        l1Comparison: "Chinese 是 (shì) covers all 'to be'. PT-EU splits: 'Sou chinês' (I am Chinese — ser) vs 'Estou cansado' (I am tired — estar). Getting this wrong changes meaning.",
      },
      {
        concept: "Subjunctive mood",
        explanation: "Special verb forms for doubt, desire, emotion, uncertainty",
        l1Comparison: "Chinese expresses doubt/desire with particles and context. PT-EU requires a completely different verb form: 'Espero que venhas' (I hope you come) — 'venhas' is subjunctive, not indicative 'vens'.",
      },
      {
        concept: "Prepositions",
        explanation: "de, em, a, para, com, por — come BEFORE the noun",
        l1Comparison: "Chinese uses prepositions (在/从/到) and postpositions. PT-EU prepositions contract with articles: em + o = no, de + a = da. These contractions are mandatory.",
      },
      {
        concept: "Plural formation",
        explanation: "Add -s or -es, articles change too (o→os, a→as)",
        l1Comparison: "Chinese rarely marks plurals (们 only for people). PT-EU marks every countable noun: 'livro' → 'livros', 'animal' → 'animais'. The article changes too: 'o livro' → 'os livros'.",
      },
      {
        concept: "Adjective agreement",
        explanation: "Adjectives match noun in gender and number, usually come after",
        l1Comparison: "Chinese adjectives are invariable and come before the noun. PT-EU adjectives change: 'livro bonito' (pretty book, m), 'casa bonita' (pretty house, f), 'livros bonitos' (m.pl). They also usually follow the noun.",
      },
      {
        concept: "Object pronouns",
        explanation: "Me/te/o/a/nos/vos/os/as with placement rules",
        l1Comparison: "Chinese uses the same pronoun form regardless of function (我 is 'I' and 'me'). PT-EU has separate object forms and complex placement: 'Vejo-te' (I see you) vs 'Não te vejo' (I don't see you).",
      },
      {
        concept: "Personal infinitive",
        explanation: "Infinitive conjugated for person — unique to Portuguese",
        l1Comparison: "No Chinese equivalent. 'Para nós entendermos' (for us to understand) — the infinitive 'entender' gets a personal ending '-mos'. This simplifies subordinate clauses.",
      },
      {
        concept: "Word order (SVO with flexibility)",
        explanation: "Default SVO, but pronouns, emphasis, and questions change order",
        l1Comparison: "Chinese is also SVO, which helps. But PT-EU inverts for questions ('Onde estás?' — Where are you?), moves pronouns ('Não o vi' — I didn't see him), and uses emphasis fronting.",
      },
      {
        concept: "Reflexive verbs",
        explanation: "Many common verbs require 'se': levantar-se, sentar-se, chamar-se",
        l1Comparison: "Chinese has no reflexive pronouns. PT-EU marks many actions as self-directed: 'Chamo-me Ana' (I call myself Ana = My name is Ana). The pronoun changes with person.",
      },
      {
        concept: "Tu vs Você vs O Senhor",
        explanation: "Three formality levels for 'you'",
        l1Comparison: "Chinese 你 (nǐ) vs 您 (nín) gives two levels. PT-EU has three: 'tu' (intimate, like 你), 'você' (neutral but can be awkward), 'o senhor/a senhora' (formal, like 您). In Portugal, default to 'tu' with peers.",
      },
      {
        concept: "Definite article with names",
        explanation: "'A Maria', 'o João' — articles before proper names in speech",
        l1Comparison: "Chinese never uses articles with names (just 小王, 张先生). PT-EU requires them in speech: 'A Maria vem amanhã' (Maria is coming tomorrow). Omitting the article sounds foreign or overly formal.",
      },
    ],
    skipBasics: false,
    startingCEFR: "A1",
  },
};
