import type { CulturalRef } from "../types.js";

export const hiCulturalRefs: readonly CulturalRef[] = [
  {
    id: "hi_goa_connection",
    type: "reference",
    contentPt: "Goa foi portuguesa durante 450 anos",
    contentL1: "Goa was Portuguese for 450 years (1510-1961)",
    explanation: "Goa was a Portuguese colony longer than most of Portuguese history itself. Konkani absorbed hundreds of Portuguese words, and Goan cuisine (vindaloo, bebinca) is Portuguese-Indian fusion. This connection is why Hindi has so many Portuguese loanwords.",
    cefrMin: "A2",
    tags: ["history", "culture", "goa"],
  },
  {
    id: "hi_chai_cha",
    type: "reference",
    contentPt: "Chá",
    contentL1: "Chai / Chaa",
    explanation: "The Portuguese word 'chá' and Hindi 'chai' share the same Chinese root. Portugal was the first European nation to trade tea from China. In Portugal, 'chá' is tea, just like 'chai' — the similarity is not a coincidence but a shared trade history.",
    cefrMin: "A1",
    tags: ["food", "daily-life", "history"],
  },
  {
    id: "hi_almari_armario",
    type: "reference",
    contentPt: "Armário",
    contentL1: "Almari",
    explanation: "Hindi 'almari' comes directly from Portuguese 'armário'. When Portuguese traders arrived in India, they brought furniture and the words for it. This is one of dozens of Portuguese words absorbed into Hindi through centuries of contact.",
    cefrMin: "A1",
    tags: ["vocabulary", "history", "daily-life"],
  },
  {
    id: "hi_pav_pao",
    type: "reference",
    contentPt: "Pão",
    contentL1: "Pav / Pao",
    explanation: "Mumbai's beloved 'pav' in pav bhaji and vada pav comes from Portuguese 'pão' (bread). Portuguese bakers in colonial India introduced wheat bread, transforming Indian street food forever. When you learn 'pão' in Portuguese, you already know its Indian descendant.",
    cefrMin: "A1",
    tags: ["food", "history", "vocabulary"],
  },
  {
    id: "hi_saudade",
    type: "expression",
    contentPt: "Saudade",
    contentL1: "A deep, bittersweet longing (no Hindi equivalent)",
    explanation: "The famous untranslatable Portuguese word. Hindi 'yaad' (memory/missing) is close but lacks the bittersweet pleasure of saudade. It is missing someone while finding comfort in the missing itself. Central to Portuguese fado music, which Hindi speakers can connect to the melancholy of ghazals.",
    cefrMin: "B1",
    tags: ["culture", "emotion", "music"],
  },
  {
    id: "hi_desenrascar",
    type: "expression",
    contentPt: "Desenrascar-se",
    contentL1: "Jugaad",
    explanation: "Portuguese 'desenrascar-se' is the perfect match for Hindi 'jugaad' — the art of improvising creative solutions with limited resources. Both cultures celebrate this resourcefulness. When a Portuguese person says 'vou-me desenrascar', think 'jugaad kar lunga'.",
    cefrMin: "B1",
    tags: ["culture", "daily-life"],
  },
  {
    id: "hi_spice_trade",
    type: "reference",
    contentPt: "Especiarias: pimenta, canela, cravo, cardamomo",
    contentL1: "Masale: mirch, dalchini, laung, elaichi",
    explanation: "Vasco da Gama sailed to India in 1498 seeking spices. Portugal controlled the Indian spice trade for over a century. Both cuisines love bold spices — Portuguese 'piri-piri' (chilli) parallels India's love of mirch. When learning spice vocabulary, the cultural connection makes it memorable.",
    cefrMin: "A2",
    tags: ["food", "history", "vocabulary"],
  },
  {
    id: "hi_football_cricket",
    type: "reference",
    contentPt: "Futebol vs Críquete",
    contentL1: "Football vs Cricket",
    explanation: "Portugal is football-mad (Cristiano Ronaldo is the national hero). India is cricket-mad. But Goa is the one place in India where football rivals cricket — another Portuguese legacy. Learning to talk about futebol is essential for conversation with Portuguese people.",
    cefrMin: "A2",
    tags: ["sport", "culture", "conversation"],
  },
  {
    id: "hi_fixe",
    type: "expression",
    contentPt: "Fixe!",
    contentL1: "Mast! / Badhiya!",
    explanation: "'Fixe' means 'cool' or 'awesome' in Portuguese slang. Use it like you would 'mast' or 'badhiya'. When something impresses you: 'Que fixe!' (How cool!). The most common positive reaction word in everyday Portuguese.",
    cefrMin: "A1",
    tags: ["slang", "daily-life"],
  },
  {
    id: "hi_bica_coffee",
    type: "reference",
    contentPt: "Uma bica / um galão",
    contentL1: "Espresso / milky coffee (like cutting chai vs regular chai)",
    explanation: "In Lisbon, espresso is called 'bica', not 'café'. A 'galão' is a large milky coffee served in a glass — think of the difference like cutting chai vs regular chai. Coffee culture in Portugal is as serious as chai culture in India.",
    cefrMin: "A1",
    tags: ["food", "daily-life", "lisbon"],
  },
  {
    id: "hi_fado_ghazal",
    type: "reference",
    contentPt: "Fado",
    contentL1: "Fado (similar emotional depth to ghazal)",
    explanation: "Fado is Portugal's soul music — mournful, beautiful, about saudade and fate. Hindi speakers can connect it to the emotional depth of ghazals. Both traditions value melancholy as an art form. Amália Rodrigues is to fado what Jagjit Singh is to ghazals.",
    cefrMin: "B1",
    tags: ["music", "culture", "emotion"],
  },
  {
    id: "hi_family_values",
    type: "reference",
    contentPt: "Família é tudo",
    contentL1: "Family is everything",
    explanation: "Like Indian culture, Portuguese culture is deeply family-oriented. Sunday family lunches are sacred. Elders are respected. Children often live with parents until marriage (or beyond). The concept of a joint/extended family will feel familiar.",
    cefrMin: "A2",
    tags: ["culture", "family", "daily-life"],
  },
  {
    id: "hi_sabao_soap",
    type: "reference",
    contentPt: "Sabão / sabonete",
    contentL1: "Sabun",
    explanation: "Hindi 'sabun' comes directly from Portuguese 'sabão'. The Portuguese introduced bar soap to India. 'Sabão' is laundry soap, 'sabonete' is toilet soap. Another everyday word connecting the two languages across 500 years.",
    cefrMin: "A1",
    tags: ["vocabulary", "history", "daily-life"],
  },
  {
    id: "hi_janela_window",
    type: "reference",
    contentPt: "Janela",
    contentL1: "Janela / Jharokha-style window",
    explanation: "Hindi borrowed 'janela' directly from Portuguese for the European-style window with glass panes, as opposed to the traditional jharokha. In Goa and Mumbai, the Portuguese word persists in local languages. When you learn 'janela' in PT-EU, you are relearning a word India already knows.",
    cefrMin: "A1",
    tags: ["vocabulary", "history", "architecture"],
  },
  {
    id: "hi_nas_tintas",
    type: "expression",
    contentPt: "Estar-se nas tintas",
    contentL1: "To not care at all",
    explanation: "Literally 'to be in the paints' — means you couldn't care less. Similar energy to 'mujhe fark nahi padta'. Very common, mildly rude. Used when someone genuinely doesn't care about the outcome.",
    cefrMin: "B1",
    tags: ["slang", "emotion"],
  },
  {
    id: "hi_bacalhau_fish",
    type: "reference",
    contentPt: "Bacalhau (salted cod)",
    contentL1: "Salted dried fish (sookhi machhi/bombil)",
    explanation: "Bacalhau (salt cod) is Portugal's national dish — they have 365 recipes, one for each day. India has its own dried fish traditions (Bombay duck/bombil, dried shrimp in Goa). The concept of preserving fish with salt is shared, though the fish is different.",
    cefrMin: "A2",
    tags: ["food", "culture"],
  },
  {
    id: "hi_vindaloo_origin",
    type: "reference",
    contentPt: "Vinha d'alhos",
    contentL1: "Vindaloo",
    explanation: "The famous Indian vindaloo comes from Portuguese 'vinha d'alhos' (wine and garlic marinade). Portuguese sailors marinated pork in wine and garlic; Goans added chillies and spices. The word transformed: vinha d'alhos became vindaloo. A delicious piece of shared culinary history.",
    cefrMin: "B1",
    tags: ["food", "history", "goa"],
  },
  {
    id: "hi_mesa_mez",
    type: "reference",
    contentPt: "Mesa",
    contentL1: "Mez",
    explanation: "Hindi 'mez' comes from Portuguese 'mesa' (table). Before Portuguese contact, the Indian dining tradition was floor-based. The Portuguese introduced raised tables to Indian households, along with the word for them.",
    cefrMin: "A1",
    tags: ["vocabulary", "history", "daily-life"],
  },
  {
    id: "hi_hospitality",
    type: "expression",
    contentPt: "Fique à vontade",
    contentL1: "Make yourself at home (apna ghar samjhiye)",
    explanation: "'Fique à vontade' literally means 'stay at will' — it is the Portuguese equivalent of 'apna ghar samjhiye'. Both cultures have deep hospitality traditions. When visiting a Portuguese home, you will hear this immediately. The warmth will feel familiar.",
    cefrMin: "A2",
    tags: ["culture", "daily-life", "hospitality"],
  },
  {
    id: "hi_tu_voce",
    type: "reference",
    contentPt: "Tu vs Você vs O Senhor",
    contentL1: "तू/तुम/आप — respect levels, just like Hindi",
    explanation: "Portuguese has three formality levels for 'you', just like Hindi's tu/tum/aap. 'Tu' is intimate (like Hindi तू), 'você' is neutral but can feel rude in some regions, 'o senhor/a senhora' is formal (like Hindi आप). Hindi speakers have a natural advantage understanding this social hierarchy. Start formal with elders, let them invite you to use 'tu'.",
    cefrMin: "A1",
    tags: ["social", "grammar", "etiquette"],
  },
  {
    id: "hi_pasteis_nata",
    type: "reference",
    contentPt: "Pastéis de nata",
    contentL1: "Portugal's most famous sweet (mithai jaisi cheez)",
    explanation: "Flaky pastry filled with egg custard, baked until caramelized. Found in every pastelaria for about one euro. The original secret recipe comes from the Jerónimos monastery in Belém, Lisbon. If you love the richness of Indian mithai, pastéis de nata will win your heart. Eat them warm, sprinkled with cinnamon.",
    cefrMin: "A1",
    tags: ["food", "culture", "lisbon"],
  },
  {
    id: "hi_pois",
    type: "expression",
    contentPt: "Pois...",
    contentL1: "Achhaa... / Haan... (versatile filler)",
    explanation: "The most versatile Portuguese word. Like Hindi 'achha' which can mean 'OK', 'really?', 'I see', or just fill a pause, Portuguese 'pois' does it all. It can express agreement, hesitation, or resignation, depending entirely on intonation. 'Pois pois' (doubled) is polite but slightly disinterested.",
    cefrMin: "A1",
    tags: ["conversation", "daily-life"],
  },
  {
    id: "hi_santos_populares",
    type: "reference",
    contentPt: "Festas dos Santos Populares",
    contentL1: "Street festivals — like Indian melas but in June",
    explanation: "Every June, Portugal explodes with street festivals for Santo António (Lisbon, June 13), São João (Porto, June 24), and São Pedro (June 29). Streets fill with music, grilled sardines, and dancing. São João in Porto involves hitting people on the head with plastic hammers. The energy of community celebration will remind Hindi speakers of Holi or Diwali street festivities.",
    cefrMin: "A2",
    tags: ["culture", "festivals", "daily-life"],
  },
  {
    id: "hi_lisbon_porto",
    type: "reference",
    contentPt: "Lisboa vs Porto",
    contentL1: "The Lisbon-Porto rivalry (like Mumbai vs Delhi)",
    explanation: "Lisbon and Porto have a friendly rivalry like Mumbai and Delhi. Lisbon (lisboetas) is the cosmopolitan capital; Porto (tripeiros, 'tripe-eaters') is proudly working-class and independent. Food, accent, football clubs, and attitudes differ. Never tell someone from Porto that Lisbon is better. Each city has its own word for espresso: bica (Lisbon), cimbalino (Porto).",
    cefrMin: "B1",
    tags: ["culture", "cities", "identity"],
  },
  {
    id: "hi_25_abril",
    type: "reference",
    contentPt: "25 de Abril — Revolução dos Cravos",
    contentL1: "The Carnation Revolution (1974) — Portugal's independence moment",
    explanation: "On April 25, 1974, Portugal peacefully overthrew its dictatorship. Soldiers put red carnations in their rifle barrels. Like India's independence in 1947, this date defines modern Portugal. The main bridge in Lisbon is named Ponte 25 de Abril, and the revolution's song 'Grândola, Vila Morena' is deeply symbolic. Understanding this history is essential to understanding Portuguese people.",
    cefrMin: "B1",
    tags: ["history", "culture", "identity"],
  },
  {
    id: "hi_pronto",
    type: "expression",
    contentPt: "Pronto!",
    contentL1: "Ho gaya! / Bas! / Chalo!",
    explanation: "'Pronto' is one of the most common Portuguese words. It means 'done!', 'ready!', or 'OK then!'. Used to signal completion ('Pronto, acabei!' — Done, finished!), to move things along ('Pronto, vamos!' — OK, let's go), or as a filler. Like Hindi 'chalo' or 'bas', it wraps up a thought or changes topic.",
    cefrMin: "A1",
    tags: ["daily-life", "conversation"],
  },
];
