import type { CulturalRef } from "../types.js";

export const hiCulturalRefs: readonly CulturalRef[] = [
  {
    id: "hi_goa_connection",
    type: "reference",
    contentPt: "Goa foi portuguesa durante 450 anos",
    contentL1: "Goa was Portuguese for 450 years (1510-1961)",
    explanation: "Goa was a Portuguese colony longer than most of Portuguese history itself. Konkani absorbed hundreds of Portuguese words, and Goan cuisine (vindaloo, bebinca) is Portuguese-Indian fusion. This connection is why Hindi has so many Portuguese loanwords.",
    cefrMin: "A2",
    tags: ["history", "culture", "goa"],
  },
  {
    id: "hi_chai_cha",
    type: "reference",
    contentPt: "Cha",
    contentL1: "Chai / Chaa",
    explanation: "The Portuguese word 'cha' and Hindi 'chai' share the same Chinese root. Portugal was the first European nation to trade tea from China. In Portugal, 'cha' is tea, just like 'chai' — the similarity is not a coincidence but a shared trade history.",
    cefrMin: "A1",
    tags: ["food", "daily-life", "history"],
  },
  {
    id: "hi_almari_armario",
    type: "reference",
    contentPt: "Armario",
    contentL1: "Almari",
    explanation: "Hindi 'almari' comes directly from Portuguese 'armario'. When Portuguese traders arrived in India, they brought furniture and the words for it. This is one of dozens of Portuguese words absorbed into Hindi through centuries of contact.",
    cefrMin: "A1",
    tags: ["vocabulary", "history", "daily-life"],
  },
  {
    id: "hi_pav_pao",
    type: "reference",
    contentPt: "Pao",
    contentL1: "Pav / Pao",
    explanation: "Mumbai's beloved 'pav' in pav bhaji and vada pav comes from Portuguese 'pao' (bread). Portuguese bakers in colonial India introduced wheat bread, transforming Indian street food forever. When you learn 'pao' in Portuguese, you already know its Indian descendant.",
    cefrMin: "A1",
    tags: ["food", "history", "vocabulary"],
  },
  {
    id: "hi_saudade",
    type: "expression",
    contentPt: "Saudade",
    contentL1: "A deep, bittersweet longing (no Hindi equivalent)",
    explanation: "The famous untranslatable Portuguese word. Hindi 'yaad' (memory/missing) is close but lacks the bittersweet pleasure of saudade. It is missing someone while finding comfort in the missing itself. Central to Portuguese fado music, which Hindi speakers can connect to the melancholy of ghazals.",
    cefrMin: "B1",
    tags: ["culture", "emotion", "music"],
  },
  {
    id: "hi_desenrascar",
    type: "expression",
    contentPt: "Desenrascar-se",
    contentL1: "Jugaad",
    explanation: "Portuguese 'desenrascar-se' is the perfect match for Hindi 'jugaad' — the art of improvising creative solutions with limited resources. Both cultures celebrate this resourcefulness. When a Portuguese person says 'vou-me desenrascar', think 'jugaad kar lunga'.",
    cefrMin: "B1",
    tags: ["culture", "daily-life"],
  },
  {
    id: "hi_spice_trade",
    type: "reference",
    contentPt: "Especiarias: pimenta, canela, cravo, cardamomo",
    contentL1: "Masale: mirch, dalchini, laung, elaichi",
    explanation: "Vasco da Gama sailed to India in 1498 seeking spices. Portugal controlled the Indian spice trade for over a century. Both cuisines love bold spices — Portuguese 'piri-piri' (chilli) parallels India's love of mirch. When learning spice vocabulary, the cultural connection makes it memorable.",
    cefrMin: "A2",
    tags: ["food", "history", "vocabulary"],
  },
  {
    id: "hi_football_cricket",
    type: "reference",
    contentPt: "Futebol vs Criquete",
    contentL1: "Football vs Cricket",
    explanation: "Portugal is football-mad (Cristiano Ronaldo is the national hero). India is cricket-mad. But Goa is the one place in India where football rivals cricket — another Portuguese legacy. Learning to talk about futebol is essential for conversation with Portuguese people.",
    cefrMin: "A2",
    tags: ["sport", "culture", "conversation"],
  },
  {
    id: "hi_fixe",
    type: "expression",
    contentPt: "Fixe!",
    contentL1: "Mast! / Badhiya!",
    explanation: "'Fixe' means 'cool' or 'awesome' in Portuguese slang. Use it like you would 'mast' or 'badhiya'. When something impresses you: 'Que fixe!' (How cool!). The most common positive reaction word in everyday Portuguese.",
    cefrMin: "A1",
    tags: ["slang", "daily-life"],
  },
  {
    id: "hi_bica_coffee",
    type: "reference",
    contentPt: "Uma bica / um galao",
    contentL1: "Espresso / milky coffee (like cutting chai vs regular chai)",
    explanation: "In Lisbon, espresso is called 'bica', not 'cafe'. A 'galao' is a large milky coffee served in a glass — think of the difference like cutting chai vs regular chai. Coffee culture in Portugal is as serious as chai culture in India.",
    cefrMin: "A1",
    tags: ["food", "daily-life", "lisbon"],
  },
  {
    id: "hi_fado_ghazal",
    type: "reference",
    contentPt: "Fado",
    contentL1: "Fado (similar emotional depth to ghazal)",
    explanation: "Fado is Portugal's soul music — mournful, beautiful, about saudade and fate. Hindi speakers can connect it to the emotional depth of ghazals. Both traditions value melancholy as an art form. Amalia Rodrigues is to fado what Jagjit Singh is to ghazals.",
    cefrMin: "B1",
    tags: ["music", "culture", "emotion"],
  },
  {
    id: "hi_family_values",
    type: "reference",
    contentPt: "Familia e tudo",
    contentL1: "Family is everything",
    explanation: "Like Indian culture, Portuguese culture is deeply family-oriented. Sunday family lunches are sacred. Elders are respected. Children often live with parents until marriage (or beyond). The concept of a joint/extended family will feel familiar.",
    cefrMin: "A2",
    tags: ["culture", "family", "daily-life"],
  },
  {
    id: "hi_sabao_soap",
    type: "reference",
    contentPt: "Sabao / sabonete",
    contentL1: "Sabun",
    explanation: "Hindi 'sabun' comes directly from Portuguese 'sabao'. The Portuguese introduced bar soap to India. 'Sabao' is laundry soap, 'sabonete' is toilet soap. Another everyday word connecting the two languages across 500 years.",
    cefrMin: "A1",
    tags: ["vocabulary", "history", "daily-life"],
  },
  {
    id: "hi_janela_window",
    type: "reference",
    contentPt: "Janela",
    contentL1: "Janela / Jharokha-style window",
    explanation: "Hindi borrowed 'janela' directly from Portuguese for the European-style window with glass panes, as opposed to the traditional jharokha. In Goa and Mumbai, the Portuguese word persists in local languages. When you learn 'janela' in PT-EU, you are relearning a word India already knows.",
    cefrMin: "A1",
    tags: ["vocabulary", "history", "architecture"],
  },
  {
    id: "hi_nas_tintas",
    type: "expression",
    contentPt: "Estar-se nas tintas",
    contentL1: "To not care at all",
    explanation: "Literally 'to be in the paints' — means you couldn't care less. Similar energy to 'mujhe fark nahi padta'. Very common, mildly rude. Used when someone genuinely doesn't care about the outcome.",
    cefrMin: "B1",
    tags: ["slang", "emotion"],
  },
  {
    id: "hi_bacalhau_fish",
    type: "reference",
    contentPt: "Bacalhau (salted cod)",
    contentL1: "Salted dried fish (sookhi machhi/bombil)",
    explanation: "Bacalhau (salt cod) is Portugal's national dish — they have 365 recipes, one for each day. India has its own dried fish traditions (Bombay duck/bombil, dried shrimp in Goa). The concept of preserving fish with salt is shared, though the fish is different.",
    cefrMin: "A2",
    tags: ["food", "culture"],
  },
  {
    id: "hi_vindaloo_origin",
    type: "reference",
    contentPt: "Vinha d'alhos",
    contentL1: "Vindaloo",
    explanation: "The famous Indian vindaloo comes from Portuguese 'vinha d'alhos' (wine and garlic marinade). Portuguese sailors marinated pork in wine and garlic; Goans added chillies and spices. The word transformed: vinha d'alhos became vindaloo. A delicious piece of shared culinary history.",
    cefrMin: "B1",
    tags: ["food", "history", "goa"],
  },
  {
    id: "hi_mesa_mez",
    type: "reference",
    contentPt: "Mesa",
    contentL1: "Mez",
    explanation: "Hindi 'mez' comes from Portuguese 'mesa' (table). Before Portuguese contact, the Indian dining tradition was floor-based. The Portuguese introduced raised tables to Indian households, along with the word for them.",
    cefrMin: "A1",
    tags: ["vocabulary", "history", "daily-life"],
  },
  {
    id: "hi_hospitality",
    type: "expression",
    contentPt: "Fique a vontade",
    contentL1: "Make yourself at home (apna ghar samjhiye)",
    explanation: "'Fique a vontade' literally means 'stay at will' — it is the Portuguese equivalent of 'apna ghar samjhiye'. Both cultures have deep hospitality traditions. When visiting a Portuguese home, you will hear this immediately. The warmth will feel familiar.",
    cefrMin: "A2",
    tags: ["culture", "daily-life", "hospitality"],
  },
];
