import type { L1Profile } from "../types.js";

export const hiProfile: L1Profile = {
  code: "hi",
  name: "Hindi",
  nativeName: "हिन्दी",
  writingDirection: "ltr",
  hasLatinScript: false,
  transfer: {
    cognates: [
      "almari (armário — wardrobe)",
      "kamra (câmara — room)",
      "mez (mesa — table)",
      "sabun (sabão — soap)",
      "janela (janela — window)",
      "balti (balde — bucket)",
      "chabi (chave — key)",
      "tauliya (toalha — towel)",
      "padre (padre — priest)",
      "girja (igreja — church)",
      "pippa (pipa — barrel/cask)",
      "ananás (ananás — pineapple)",
      "cobra (cobra — snake)",
      "caju (caju — cashew)",
      "verandah (varanda — balcony/veranda)",
      "kamiz (camisa — shirt)",
      "leilão (leilão — auction)",
      "pagoda (pagode — pagoda/temple)",
      "pav (pão — bread, as in pav bhaji and vada pav)",
      "fita (fita — ribbon/tape)",
      "istri (engomar — ironing/pressing clothes)",
      "copa (copo — cup/glass, from Portuguese trade)",
      "martelo (martelo — hammer, via Goan contact)",
      "tanque (tanque — water tank/reservoir)",
      "pistola (pistola — pistol/handgun)",
      "kadira (cadeira — chair, in Konkani-influenced dialects)",
      "sapaat (sapato — shoe, via Konkani-Marathi contact)",
      "biscoito (biscoito — biscuit/cookie, via trade routes)",
      "bandeira (bandeira — flag, via Goan-Portuguese contact)",
      "vindaloo (vinha d'alhos — wine and garlic marinade, transformed in Goa)",
    ],
    falseFriends: [
      { word: "pão", l1Meaning: "पाओ (pav) — a bread roll, from Portuguese", ptMeaning: "pão means 'bread' in general, not just the roll — papo-seco is the roll" },
      { word: "mal", l1Meaning: "माल (maal) — goods, property, wealth", ptMeaning: "mal means 'badly/evil' — completely different" },
      { word: "sala", l1Meaning: "साला (saala) — brother-in-law / insult", ptMeaning: "sala means 'room/living room' — no rude connotation" },
      { word: "cara", l1Meaning: "कारा (kaaraa) — prison/confinement", ptMeaning: "cara means 'face' or 'guy' (informal)" },
      { word: "bar", l1Meaning: "बार (baar) — time/turn (as in 'ek baar')", ptMeaning: "bar means a drinking establishment" },
      { word: "gato", l1Meaning: "sounds like Hindi 'gaata' (body)", ptMeaning: "gato means 'cat'" },
      { word: "pai", l1Meaning: "पाई (pai) — a small coin / pie fraction", ptMeaning: "pai means 'father'" },
      { word: "pal", l1Meaning: "पल (pal) — moment/instant", ptMeaning: "no direct Portuguese word, but 'pau' (stick) sounds similar and can be vulgar" },
      { word: "campo", l1Meaning: "कैम्प (camp) — English loanword for camping", ptMeaning: "campo means 'field/countryside'" },
      { word: "nota", l1Meaning: "नोट (note) — banknote (English loan)", ptMeaning: "nota means 'grade/mark' as well as 'banknote'" },
      { word: "dar", l1Meaning: "डर (dar) — fear", ptMeaning: "dar means 'to give' — completely opposite emotional association" },
      { word: "mala", l1Meaning: "माला (mala) — garland/necklace", ptMeaning: "mala means 'suitcase/bag'" },
      { word: "cama", l1Meaning: "काम (kaam) — work/task/desire", ptMeaning: "cama means 'bed' — 'ir para a cama' means to go to bed, not to go to work" },
      { word: "dia", l1Meaning: "दिया (diya) — an oil lamp / past tense of 'to give'", ptMeaning: "dia means 'day' — 'bom dia' (good day/morning)" },
      { word: "dor", l1Meaning: "डोर (dor) — string/thread", ptMeaning: "dor means 'pain/ache'" },
      { word: "bola", l1Meaning: "बोला (bola) — said/spoke (past tense)", ptMeaning: "bola means 'ball'" },
      { word: "logo", l1Meaning: "लोग (log) — people", ptMeaning: "logo means 'soon/immediately' or 'therefore'" },
      { word: "todo", l1Meaning: "थोड़ा (thoda) — a little/some", ptMeaning: "todo means 'all/everything' — essentially the opposite meaning" },
      { word: "rato", l1Meaning: "रात (raat) — night", ptMeaning: "rato means 'mouse'" },
      { word: "pato", l1Meaning: "पत्ता (patta) — leaf/playing card/address", ptMeaning: "pato means 'duck'" },
      { word: "gola", l1Meaning: "गोला (gola) — round ball/round sweet/throat", ptMeaning: "gola means 'collar' (of a shirt)" },
      { word: "lata", l1Meaning: "लता (lata) — vine/creeper (also a female name)", ptMeaning: "lata means 'tin can'" },
      { word: "terra", l1Meaning: "तेरा (tera) — your (informal)", ptMeaning: "terra means 'earth/land/homeland'" },
      { word: "manga", l1Meaning: "आम (aam), but 'manga' sounds like mango", ptMeaning: "manga primarily means 'sleeve' — also means mango in Portuguese, but sleeve is the first association" },
      { word: "carro", l1Meaning: "करो (karo) — do! (imperative of 'karna')", ptMeaning: "carro means 'car'" },
      { word: "massa", l1Meaning: "मसाला (masala) — spice blend", ptMeaning: "massa means 'dough/pasta/mass' — nothing to do with spices" },
      { word: "fora", l1Meaning: "फ़ौरन (fauran) — immediately", ptMeaning: "fora means 'outside/out' — 'vai fora' means 'go outside'" },
      { word: "saco", l1Meaning: "sounds like सको (sako, 'could' from sakna)", ptMeaning: "saco means 'bag/sack'" },
      { word: "meta", l1Meaning: "मेथी (methi) — fenugreek", ptMeaning: "meta means 'goal/target'" },
      { word: "lado", l1Meaning: "लाड (laad) — affection/pampering", ptMeaning: "lado means 'side' — 'do outro lado' means 'on the other side'" },
      { word: "faca", l1Meaning: "फ़ाका (faaka) — starvation/going hungry", ptMeaning: "faca means 'knife'" },
      { word: "sumo", l1Meaning: "सूमो (sumo) — wrestler/SUV (Japanese loan)", ptMeaning: "sumo means 'juice' — 'sumo de laranja' is orange juice" },
      { word: "mola", l1Meaning: "मोल (mol) — price/value/worth", ptMeaning: "mola means 'spring (coil)' or 'clothespin'" },
      { word: "vida", l1Meaning: "विदा (vidaa) — farewell/departure", ptMeaning: "vida means 'life' — opposite association: farewell vs life" },
      { word: "ganga", l1Meaning: "गंगा (Ganga) — the sacred river", ptMeaning: "ganga means 'denim/jeans' or 'bargain'" },
      { word: "mata", l1Meaning: "माता (mata) — mother", ptMeaning: "mata means 'forest' or 'kills' (3rd person of matar)" },
      { word: "seda", l1Meaning: "सीधा (seedha) — straight/simple/direct", ptMeaning: "seda means 'silk'" },
      { word: "roda", l1Meaning: "रोड़ा (roda) — obstacle/pebble", ptMeaning: "roda means 'wheel' or 'circle'" },
      { word: "fino", l1Meaning: "sounds like 'fine' (English loan used in Hindi)", ptMeaning: "fino means 'thin/refined' — also a small draught beer in Lisbon" },
      { word: "pata", l1Meaning: "पता (pata) — address/knowledge", ptMeaning: "pata means 'paw' or 'animal leg'" },
    ],
    phoneticDifficulties: [
      { sound: "ão", ipa: "/ɐ̃w̃/", description: "Nasal diphthong", tip: "Hindi has nasal vowels via chandrabindu (अँ) — use that instinct but add a strong glide at the end. Not just nasalization, it is a moving vowel." },
      { sound: "ã/õ/ẽ", ipa: "/ɐ̃/ /õ/ /ẽ/", description: "Nasal vowels throughout", tip: "Hindi nasalizes vowels freely — good foundation. But PT-EU nasal vowels are phonemic: 'avô' (grandfather) vs 'avó' (grandmother) depends on nasality + openness." },
      { sound: "r/rr", ipa: "/ʁ/", description: "Uvular R (initial and double)", tip: "Nothing like Hindi र (alveolar tap). This is a back-of-throat sound, almost like gargling. Think of it as a voiced version of the Arabic خ." },
      { sound: "r (between vowels)", ipa: "/ɾ/", description: "Alveolar tap (intervocalic)", tip: "This one IS like Hindi र — 'caro' (expensive) uses the same tap as Hindi 'para'." },
      { sound: "v vs b", ipa: "/v/ vs /b/", description: "Labiodental v vs bilabial b", tip: "Hindi व is often pronounced between v and w. PT-EU v is always labiodental (teeth on lip). 'Vaca' (cow) must have a sharp V, never W." },
      { sound: "lh", ipa: "/ʎ/", description: "Palatal lateral", tip: "No Hindi equivalent. Place your tongue flat against the hard palate and let air flow around the sides. 'Filho' (son), 'trabalho' (work)." },
      { sound: "nh", ipa: "/ɲ/", description: "Palatal nasal", tip: "Similar to Hindi ञ (nya) but more common. Used in 'minha' (my), 'vinho' (wine), 'amanhã' (tomorrow)." },
      { sound: "open vs closed vowels", ipa: "/ɛ/ vs /e/, /ɔ/ vs /o/", description: "Vowel height contrast", tip: "Hindi doesn't distinguish open and closed e/o. In PT-EU, 'avó' (grandmother, open ó) and 'avô' (grandfather, closed ô) are different words." },
      { sound: "reduced vowels", ipa: "/ɨ/ /ɐ/", description: "Unstressed vowel reduction", tip: "Hindi pronounces every vowel fully. PT-EU swallows unstressed vowels — 'Portugal' sounds like 'Purtugal' with a barely-there first vowel." },
      { sound: "s/z/ʃ/ʒ", ipa: "/s/ /z/ /ʃ/ /ʒ/", description: "Four sibilants", tip: "Hindi has s and sh but not z or zh. PT-EU 's' becomes /ʃ/ before consonants: 'estar' sounds like 'eshtar'. 'J' is always /ʒ/ as in French 'je'." },
      { sound: "word stress", ipa: "varies", description: "Unpredictable stress patterns", tip: "Hindi stress is relatively even. PT-EU stress falls on different syllables and changes meaning: 'sábia' (wise woman) vs 'sabiá' (a bird) vs 'sabia' (she knew)." },
      { sound: "consonant clusters", ipa: "/pr/ /tr/ /pl/ /bl/", description: "Initial consonant clusters", tip: "Hindi avoids initial clusters (adds a vowel: 'school' → 'iskool'). PT-EU has many: 'prato' (plate), 'três' (three). Resist adding a vowel before them." },
      { sound: "f", ipa: "/f/", description: "Labiodental fricative", tip: "Hindi फ (pha) is aspirated, not fricative. PT-EU /f/ needs your upper teeth on your lower lip with continuous airflow, not a puff of air. 'Falar' (to speak), 'fazer' (to do)." },
      { sound: "dark L", ipa: "/ɫ/", description: "Velarized L at end of syllables", tip: "Hindi ल is always light/clear. PT-EU 'l' at end of a syllable becomes dark and thick, almost like a 'w'. 'Portugal' has a very heavy final L. 'Sol' (sun), 'mal' (badly)." },
      { sound: "diphthongs ei/ou/ai", ipa: "/ej/ /ow/ /aj/", description: "Oral diphthongs", tip: "Hindi has diphthongs too (ai, au) but PT-EU has more variety. 'Primeiro' (first) has /ej/, 'pouco' (little) has /ow/. The glide must stay within one syllable." },
    ],
    grammarGaps: [
      { concept: "Definite articles", explanation: "o (m), a (f), os (m.pl), as (f.pl)", l1Comparison: "Hindi has no articles at all — you must learn to say 'o livro' (the book), not just 'livro'. Every noun needs its article." },
      { concept: "Indefinite articles", explanation: "um (m), uma (f)", l1Comparison: "Hindi uses 'ek' for 'one' but not as an article. PT-EU uses 'um/uma' before nouns the listener doesn't know about." },
      { concept: "Grammatical gender (different assignments)", explanation: "Every noun is masculine or feminine", l1Comparison: "Hindi has gender too, but assigns it differently — 'mesa' (table) is feminine in PT, while Hindi mez is masculine. Learn each noun with its article." },
      { concept: "SVO word order", explanation: "Subject-Verb-Object is the default", l1Comparison: "Hindi is SOV (Ram ne kitaab padhii). PT-EU puts the verb before the object: 'O Ram leu o livro'. The verb moves to the middle." },
      { concept: "Verb conjugation (6 persons)", explanation: "Each person has a unique verb form", l1Comparison: "Hindi conjugates for gender and formality but not for each person separately. PT-EU has 6 distinct forms: eu falo, tu falas, ele fala, nós falamos, vós falais, eles falam." },
      { concept: "Subjunctive mood", explanation: "Used for doubt, desire, emotion, uncertainty", l1Comparison: "Hindi has no subjunctive — it uses different verb forms or particles. PT-EU requires subjunctive after 'talvez' (maybe), 'quero que' (I want that), 'espero que' (I hope that)." },
      { concept: "Ser vs Estar", explanation: "Two verbs for 'to be'", l1Comparison: "Hindi होना (hona) covers both. PT-EU uses 'ser' for permanent qualities (sou português) and 'estar' for states (estou cansado — I'm tired)." },
      { concept: "Prepositions", explanation: "de, em, a, para, com, por, etc.", l1Comparison: "Hindi uses postpositions (ke baad, mein, par). PT-EU prepositions come BEFORE the noun and contract with articles: em + o = no, de + a = da." },
      { concept: "Plural formation", explanation: "Add -s, -es, or change -ão to -ões", l1Comparison: "Hindi plural is simpler. PT-EU plurals follow rules: livro→livros, animal→animais, coração→corações. The article changes too: o→os, a→as." },
      { concept: "Relative clauses with 'que'", explanation: "'que' introduces relative clauses", l1Comparison: "Hindi uses 'jo...vo' (the one who...that one). PT-EU uses a single 'que': 'o homem que fala' (the man who speaks) — much simpler structure." },
      { concept: "Personal infinitive", explanation: "Infinitive conjugated for person", l1Comparison: "Unique to Portuguese — doesn't exist in Hindi or most other languages. 'Para nós fazermos' (for us to do) — the infinitive 'fazer' gets a personal ending." },
      { concept: "Object pronoun placement", explanation: "Before or after the verb depending on context", l1Comparison: "Hindi puts objects before the verb (mujhe do — me give). PT-EU has complex rules: 'Dá-me' (give me) vs 'Não me dás' (you don't give me) — the 'me' moves based on what comes before." },
      { concept: "Tu vs Você vs O Senhor", explanation: "Three formality levels for 'you'", l1Comparison: "Hindi has तू/तुम/आप (tu/tum/aap) — three levels just like PT-EU. 'Tu' is intimate (like Hindi तू), 'você' is neutral but awkward in some regions, 'o senhor/a senhora' is formal (like Hindi आप). Start with the formal and let the Portuguese person invite you to use 'tu'." },
      { concept: "Reflexive verbs", explanation: "Many common verbs require a reflexive pronoun (se)", l1Comparison: "Hindi has some reflexive constructions ('apne aap') but PT-EU uses them constantly: levantar-se (get up), sentar-se (sit down), chamar-se (be called), lembrar-se (remember). The pronoun must match the subject." },
      { concept: "Compound tenses with ter", explanation: "ter + past participle: 'tenho feito' (I have done)", l1Comparison: "Hindi uses 'chuka hai' or compound verbs for completed actions. PT-EU builds compound tenses with 'ter': tenho falado, tinha comido, terei feito. The past participle doesn't change for gender/number." },
    ],
    skipBasics: false,
    startingCEFR: "A1",
  },
};
