import type { L1Profile } from "../types.js";

export const hiProfile: L1Profile = {
  code: "hi",
  name: "Hindi",
  nativeName: "हिन्दी",
  writingDirection: "ltr",
  hasLatinScript: false,
  transfer: {
    cognates: [
      "almari (armário — wardrobe)",
      "kamra (câmara — room)",
      "mez (mesa — table)",
      "sabão (sabão — soap)",
      "janela (janela — window)",
      "balti (balde — bucket)",
      "chabi (chave — key)",
      "tauliya (toalha — towel)",
      "padre (padre — priest)",
      "girja (igreja — church)",
      "pippa (pipa — barrel/cask)",
      "ananás (ananás — pineapple)",
      "cobra (cobra — snake)",
      "caju (caju — cashew)",
      "verandah (varanda — balcony/veranda)",
      "kamiz (camisa — shirt)",
      "leilão (leilão — auction)",
      "pagoda (pagode — pagoda/temple)",
    ],
    falseFriends: [
      { word: "pão", l1Meaning: "पाओ (pav) — a bread roll, from Portuguese", ptMeaning: "pão means 'bread' in general, not just the roll — papo-seco is the roll" },
      { word: "mal", l1Meaning: "माल (maal) — goods, property, wealth", ptMeaning: "mal means 'badly/evil' — completely different" },
      { word: "sala", l1Meaning: "साला (saala) — brother-in-law / insult", ptMeaning: "sala means 'room/living room' — no rude connotation" },
      { word: "cara", l1Meaning: "कारा (kaaraa) — prison/confinement", ptMeaning: "cara means 'face' or 'guy' (informal)" },
      { word: "bar", l1Meaning: "बार (baar) — time/turn (as in 'ek baar')", ptMeaning: "bar means a drinking establishment" },
      { word: "gato", l1Meaning: "गाटो — no direct Hindi cognate", ptMeaning: "gato means 'cat' — often confused with Hindi 'gaata' (body)" },
      { word: "pai", l1Meaning: "पाई (pai) — a small coin / pie fraction", ptMeaning: "pai means 'father'" },
      { word: "pal", l1Meaning: "पल (pal) — moment/instant", ptMeaning: "no direct Portuguese word, but 'pau' (stick) sounds similar" },
      { word: "campo", l1Meaning: "कैम्प (camp) — English loanword", ptMeaning: "campo means 'field/countryside'" },
      { word: "nota", l1Meaning: "नोट (note) — banknote (English loan)", ptMeaning: "nota means 'grade/mark' as well as 'banknote'" },
    ],
    phoneticDifficulties: [
      { sound: "ão", ipa: "/ɐ̃w̃/", description: "Nasal diphthong", tip: "Hindi has nasal vowels via chandrabindu (अँ) — use that instinct but add a strong glide at the end. Not just nasalization, it is a moving vowel." },
      { sound: "ã/õ/ẽ", ipa: "/ɐ̃/ /õ/ /ẽ/", description: "Nasal vowels throughout", tip: "Hindi nasalizes vowels freely — good foundation. But PT-EU nasal vowels are phonemic: 'avô' (grandfather) vs 'avó' (grandmother) depends on nasality + openness." },
      { sound: "r/rr", ipa: "/ʁ/", description: "Uvular R (initial and double)", tip: "Nothing like Hindi र (alveolar tap). This is a back-of-throat sound, almost like gargling. Think of it as a voiced version of the Arabic خ." },
      { sound: "r (between vowels)", ipa: "/ɾ/", description: "Alveolar tap (intervocalic)", tip: "This one IS like Hindi र — 'caro' (expensive) uses the same tap as Hindi 'para'." },
      { sound: "v vs b", ipa: "/v/ vs /b/", description: "Labiodental v vs bilabial b", tip: "Hindi व is often pronounced between v and w. PT-EU v is always labiodental (teeth on lip). 'Vaca' (cow) must have a sharp V, never W." },
      { sound: "lh", ipa: "/ʎ/", description: "Palatal lateral", tip: "No Hindi equivalent. Place your tongue flat against the hard palate and let air flow around the sides. 'Filho' (son), 'trabalho' (work)." },
      { sound: "nh", ipa: "/ɲ/", description: "Palatal nasal", tip: "Similar to Hindi ञ (nya) but more common. Used in 'minha' (my), 'vinho' (wine), 'amanhã' (tomorrow)." },
      { sound: "open vs closed vowels", ipa: "/ɛ/ vs /e/, /ɔ/ vs /o/", description: "Vowel height contrast", tip: "Hindi doesn't distinguish open and closed e/o. In PT-EU, 'avó' (grandmother, open ó) and 'avô' (grandfather, closed ô) are different words." },
      { sound: "reduced vowels", ipa: "/ɨ/ /ɐ/", description: "Unstressed vowel reduction", tip: "Hindi pronounces every vowel fully. PT-EU swallows unstressed vowels — 'Portugal' sounds like 'Purtugal' with a barely-there first vowel." },
      { sound: "s/z/ʃ/ʒ", ipa: "/s/ /z/ /ʃ/ /ʒ/", description: "Four sibilants", tip: "Hindi has s and sh but not z or zh. PT-EU 's' becomes /ʃ/ before consonants: 'estar' sounds like 'eshtar'. 'J' is always /ʒ/ as in French 'je'." },
      { sound: "word stress", ipa: "varies", description: "Unpredictable stress patterns", tip: "Hindi stress is relatively even. PT-EU stress falls on different syllables and changes meaning: 'sábia' (wise woman) vs 'sabiá' (a bird) vs 'sabia' (she knew)." },
      { sound: "consonant clusters", ipa: "/pr/ /tr/ /pl/ /bl/", description: "Initial consonant clusters", tip: "Hindi avoids initial clusters (adds a vowel: 'school' → 'iskool'). PT-EU has many: 'prato' (plate), 'três' (three). Resist adding a vowel before them." },
    ],
    grammarGaps: [
      { concept: "Definite articles", explanation: "o (m), a (f), os (m.pl), as (f.pl)", l1Comparison: "Hindi has no articles at all — you must learn to say 'o livro' (the book), not just 'livro'. Every noun needs its article." },
      { concept: "Indefinite articles", explanation: "um (m), uma (f)", l1Comparison: "Hindi uses 'ek' for 'one' but not as an article. PT-EU uses 'um/uma' before nouns the listener doesn't know about." },
      { concept: "Grammatical gender (different assignments)", explanation: "Every noun is masculine or feminine", l1Comparison: "Hindi has gender too, but assigns it differently — 'mesa' (table) is feminine in PT, while Hindi mez is masculine. Learn each noun with its article." },
      { concept: "SVO word order", explanation: "Subject-Verb-Object is the default", l1Comparison: "Hindi is SOV (Ram ne kitaab padhii). PT-EU puts the verb before the object: 'O Ram leu o livro'. The verb moves to the middle." },
      { concept: "Verb conjugation (6 persons)", explanation: "Each person has a unique verb form", l1Comparison: "Hindi conjugates for gender and formality but not for each person separately. PT-EU has 6 distinct forms: eu falo, tu falas, ele fala, nós falamos, vós falais, eles falam." },
      { concept: "Subjunctive mood", explanation: "Used for doubt, desire, emotion, uncertainty", l1Comparison: "Hindi has no subjunctive — it uses different verb forms or particles. PT-EU requires subjunctive after 'talvez' (maybe), 'quero que' (I want that), 'espero que' (I hope that)." },
      { concept: "Ser vs Estar", explanation: "Two verbs for 'to be'", l1Comparison: "Hindi होना (hona) covers both. PT-EU uses 'ser' for permanent qualities (sou português) and 'estar' for states (estou cansado — I'm tired)." },
      { concept: "Prepositions", explanation: "de, em, a, para, com, por, etc.", l1Comparison: "Hindi uses postpositions (ke baad, mein, par). PT-EU prepositions come BEFORE the noun and contract with articles: em + o = no, de + a = da." },
      { concept: "Plural formation", explanation: "Add -s, -es, or change -ão to -ões", l1Comparison: "Hindi plural is simpler. PT-EU plurals follow rules: livro→livros, animal→animais, coração→corações. The article changes too: o→os, a→as." },
      { concept: "Relative clauses with 'que'", explanation: "'que' introduces relative clauses", l1Comparison: "Hindi uses 'jo...vo' (the one who...that one). PT-EU uses a single 'que': 'o homem que fala' (the man who speaks) — much simpler structure." },
      { concept: "Personal infinitive", explanation: "Infinitive conjugated for person", l1Comparison: "Unique to Portuguese — doesn't exist in Hindi or most other languages. 'Para nós fazermos' (for us to do) — the infinitive 'fazer' gets a personal ending." },
      { concept: "Object pronoun placement", explanation: "Before or after the verb depending on context", l1Comparison: "Hindi puts objects before the verb (mujhe do — me give). PT-EU has complex rules: 'Dá-me' (give me) vs 'Não me dás' (you don't give me) — the 'me' moves based on what comes before." },
    ],
    skipBasics: false,
    startingCEFR: "A1",
  },
};
