import type { CulturalRef } from "../types.js";

export const arCulturalRefs: readonly CulturalRef[] = [
  {
    id: "ar_moorish_heritage",
    type: "reference",
    contentPt: "O legado mouro em Portugal",
    contentL1: "التراث المغربي في البرتغال",
    explanation: "Portugal was under Moorish rule for over 500 years (711-1249). This left a massive mark on the language, architecture, food, and culture. Over 1,000 Portuguese words come from Arabic. As an Arabic speaker, you have a unique cultural bridge to Portugal that no other L1 group shares.",
    cefrMin: "A2",
    tags: ["history", "culture"],
  },
  {
    id: "ar_oxala",
    type: "expression",
    contentPt: "Oxalá!",
    contentL1: "إن شاء الله (inshallah)",
    explanation: "One of the most direct Arabic survivals in Portuguese. 'Oxalá que chova' (God willing it rains). Used the same way as inshallah — to express hope. You already know this concept perfectly.",
    cefrMin: "A1",
    tags: ["language", "culture", "daily-life"],
  },
  {
    id: "ar_azulejo",
    type: "reference",
    contentPt: "Azulejos",
    contentL1: "الزليج (az-zulayj) — البلاط المزخرف",
    explanation: "Portugal's iconic painted tiles come directly from the Arabic tradition of zellige. The word 'azulejo' comes from Arabic 'az-zulayj' (polished stone). You'll see them everywhere in Lisbon and Porto — a living connection to Arabic art.",
    cefrMin: "A1",
    tags: ["art", "architecture", "culture"],
  },
  {
    id: "ar_arabic_words_food",
    type: "reference",
    contentPt: "Azeite, azeitona, laranja, limão, alface",
    contentL1: "زيت، زيتونة، نارنج، ليمون، خس",
    explanation: "Many Portuguese food words are Arabic: azeite (olive oil, from az-zayt), azeitona (olive, from az-zaytuna), laranja (orange, from naranj), limão (lemon, from laymun), alface (lettuce, from al-khass). Your vocabulary already has a head start.",
    cefrMin: "A1",
    tags: ["food", "language", "vocabulary"],
  },
  {
    id: "ar_saudade",
    type: "expression",
    contentPt: "Saudade",
    contentL1: "شعور عميق بالشوق والحنين (لا ترجمة مباشرة)",
    explanation: "The famous untranslatable Portuguese word — a deep, bittersweet longing for something absent. Arabic has 'hanin' (حنين) and 'shawq' (شوق), but saudade combines both with a melancholic acceptance. Central to Portuguese identity and fado music.",
    cefrMin: "B1",
    tags: ["culture", "emotion"],
  },
  {
    id: "ar_bica_cafe",
    type: "reference",
    contentPt: "Uma bica / um galão",
    contentL1: "قهوة إسبريسو / قهوة بالحليب",
    explanation: "Coffee (from Arabic qahwa) is central to Portuguese life. In Lisbon, espresso is 'uma bica'. A 'galão' is a large milky coffee in a glass. Portuguese coffee culture is intense but different from Arabic coffee — it's always espresso-based, never cardamom-spiced.",
    cefrMin: "A1",
    tags: ["food", "daily-life"],
  },
  {
    id: "ar_fado_arabic_music",
    type: "reference",
    contentPt: "O fado e as raízes musicais árabes",
    contentL1: "الفادو والجذور الموسيقية العربية",
    explanation: "Fado, Portugal's soulful music genre, has debated Arabic origins. The melancholic scales, ornamental singing, and guitarra portuguesa may trace back to Moorish musical traditions. If you love Arabic music, fado's emotional depth will resonate with you.",
    cefrMin: "B1",
    tags: ["music", "culture", "history"],
  },
  {
    id: "ar_algarve",
    type: "reference",
    contentPt: "O Algarve (al-Gharb)",
    contentL1: "الغرب — الجنوب البرتغالي",
    explanation: "Portugal's southern region is called 'Algarve' — directly from Arabic 'al-Gharb' (the west). It was the last region reconquered from the Moors in 1249. The architecture, food, and even the fig and almond trees reflect its Moorish past.",
    cefrMin: "A2",
    tags: ["geography", "history", "culture"],
  },
  {
    id: "ar_desenrascar",
    type: "expression",
    contentPt: "Desenrascar-se",
    contentL1: "التدبير / الاحتيال لحل مشكلة",
    explanation: "The quintessential Portuguese concept — improvising a solution when everything seems impossible. Similar to the Arabic concept of 'tadbir' — resourceful problem-solving. Portuguese people are proud of this national trait.",
    cefrMin: "A2",
    tags: ["culture", "daily-life"],
  },
  {
    id: "ar_fixe",
    type: "expression",
    contentPt: "Fixe!",
    contentL1: "!رائع / حلو",
    explanation: "The Portuguese word for 'cool/awesome'. Young people say it constantly. 'A festa foi fixe!' (The party was cool!). Not to be confused with 'fixo' (fixed/permanent).",
    cefrMin: "A1",
    tags: ["slang", "daily-life"],
  },
  {
    id: "ar_hospitality",
    type: "reference",
    contentPt: "A hospitalidade portuguesa",
    contentL1: "كرم الضيافة البرتغالي",
    explanation: "Like Arabic culture, Portuguese culture values hospitality deeply. Offering food and drink to guests is non-negotiable. If a Portuguese person invites you for 'um cafezinho' (a small coffee), refusing is almost rude — just like refusing Arabic coffee.",
    cefrMin: "A2",
    tags: ["culture", "social", "daily-life"],
  },
  {
    id: "ar_numbers",
    type: "reference",
    contentPt: "Algarismos (do nome al-Khwarizmi)",
    contentL1: "أرقام — من اسم الخوارزمي",
    explanation: "The Portuguese word for digits/numerals — 'algarismos' — comes from the name of the Arabic mathematician al-Khwarizmi. 'Zero' also came to European languages through Portuguese, from Arabic 'sifr'. Portugal was the gateway for Arabic mathematics to Europe.",
    cefrMin: "B1",
    tags: ["history", "language", "science"],
  },
  {
    id: "ar_alfama",
    type: "reference",
    contentPt: "Alfama — o bairro mais antigo de Lisboa",
    contentL1: "الحمّة — أقدم حي في لشبونة",
    explanation: "Lisbon's oldest neighbourhood is named 'Alfama', from Arabic 'al-hamma' (hot springs/baths). Walking through its narrow winding streets feels like a medina. The Moorish urban layout survives to this day.",
    cefrMin: "A2",
    tags: ["geography", "history", "lisbon"],
  },
  {
    id: "ar_estar_nas_tintas",
    type: "expression",
    contentPt: "Estar-se nas tintas",
    contentL1: "ما يهمني / لا أكترث",
    explanation: "Literally 'to be in the paints'. Means you couldn't care less. 'Estou-me nas tintas para isso' (I don't give a damn about that). Very common, mildly rude. Similar in spirit to the colloquial Arabic expression 'ma bihamni'.",
    cefrMin: "B1",
    tags: ["slang", "emotion"],
  },
  {
    id: "ar_family_values",
    type: "reference",
    contentPt: "A família portuguesa",
    contentL1: "العائلة البرتغالية",
    explanation: "Like Arabic culture, Portuguese culture is deeply family-oriented. Sunday lunch with the extended family is sacred. Grandparents often live nearby or in the same house. Children frequently live at home until marriage. This is a strong cultural bridge for Arabic speakers.",
    cefrMin: "A2",
    tags: ["culture", "social", "family"],
  },
  {
    id: "ar_pasteis_nata",
    type: "reference",
    contentPt: "Pastéis de nata",
    contentL1: "حلوى الكاسترد البرتغالية",
    explanation: "Portugal's iconic custard tart. The original recipe comes from the Jerónimos monastery. Like Arabic sweets, they combine eggs, sugar, and pastry in a rich way. Every pastelaria (pastry shop/cafe) sells them — eat them warm with cinnamon.",
    cefrMin: "A1",
    tags: ["food", "culture"],
  },
  {
    id: "ar_mesoclisis",
    type: "expression",
    contentPt: "Dir-lhe-ia (mesóclise)",
    contentL1: "إدراج الضمير في وسط الفعل",
    explanation: "A uniquely Portuguese phenomenon: inserting a pronoun inside the verb. 'Dizer + lhe + ia' becomes 'dir-lhe-ia' (I would tell him/her). Only happens with future and conditional tenses. Formal and written — you rarely hear it in speech, but you'll see it in text.",
    cefrMin: "C1",
    tags: ["grammar", "formal"],
  },
  {
    id: "ar_arabic_place_names",
    type: "reference",
    contentPt: "Nomes árabes de cidades portuguesas",
    contentL1: "أسماء عربية لمدن برتغالية",
    explanation: "Many Portuguese cities have Arabic names: Lisboa (al-Ushbuna), Algarve (al-Gharb), Alfama (al-Hamma), Alcácer do Sal (al-Qasr), Almada (al-Ma'din), Fátima (a Moorish princess's name). The map of Portugal is a map of Arabic heritage.",
    cefrMin: "B1",
    tags: ["geography", "history", "language"],
  },
  {
    id: "ar_bacalhau",
    type: "reference",
    contentPt: "Bacalhau",
    contentL1: "سمك القد المملح والمجفف",
    explanation: "The Portuguese say they have 365 recipes for salt cod — one for every day of the year. Bacalhau is dried, salted cod that must be soaked before cooking. It is the unofficial national dish. Like Arabic preserved foods, it was born from the need to preserve fish for long voyages.",
    cefrMin: "A2",
    tags: ["food", "culture"],
  },
  {
    id: "ar_25_abril",
    type: "reference",
    contentPt: "25 de Abril — Revolução dos Cravos",
    contentL1: "25 أبريل — ثورة القرنفل (1974)",
    explanation: "Portugal's defining modern moment. On April 25, 1974, a peaceful military coup overthrew Europe's longest dictatorship. Soldiers put red carnations in their rifle barrels. The main bridge in Lisbon is named after this date. Understanding this history is essential to understanding modern Portugal's democracy and values.",
    cefrMin: "B1",
    tags: ["history", "culture", "identity"],
  },
  {
    id: "ar_santos_populares",
    type: "reference",
    contentPt: "Santos Populares — Festas de Junho",
    contentL1: "أعياد القديسين الشعبية — احتفالات يونيو",
    explanation: "All of June, Portugal celebrates popular saints: Santo António (Lisbon, June 13), São João (Porto, June 24), São Pedro (June 29). Grilled sardines, caldo verde soup, wine, and street dancing. São João in Porto features plastic hammers to tap people's heads. It is the biggest celebration of the year.",
    cefrMin: "A2",
    tags: ["culture", "traditions"],
  },
  {
    id: "ar_pronto",
    type: "expression",
    contentPt: "Pronto!",
    contentL1: "!خلاص / تمام / جاهز",
    explanation: "One of the most frequently heard words. Used to signal completion ('Pronto, acabei!' = Done!), to move conversation along ('Pronto, vamos lá' = OK let's go), or as a filler. Similar to how Arabic speakers use 'khalas' — the Portuguese equivalent, used dozens of times daily.",
    cefrMin: "A1",
    tags: ["daily-life", "conversation"],
  },
  {
    id: "ar_pois",
    type: "expression",
    contentPt: "Pois... / Pois, pois...",
    contentL1: "أيوه... / يعني... / طيب...",
    explanation: "The most versatile Portuguese filler word. Can mean agreement, hesitation, resignation, or just fill silence — depending on intonation. 'Pois pois' (double) often means polite but disinterested agreement. Like Arabic 'yaʿnī' in its flexibility. Mastering 'pois' is a fluency milestone.",
    cefrMin: "A1",
    tags: ["daily-life", "conversation"],
  },
  {
    id: "ar_tu_voce",
    type: "reference",
    contentPt: "Tu vs Você vs O Senhor/A Senhora",
    contentL1: "أنتَ/أنتِ مقابل حضرتك مقابل سيادتك",
    explanation: "Portuguese has three levels of 'you': tu (informal, like Arabic anta/anti with friends), você (semi-formal, uses 3rd person verb), o senhor/a senhora (formal, like Arabic hadretак). Using the wrong level is a social mistake — like using anta with an elder in Arabic. Start formal, let them switch you to tu.",
    cefrMin: "A1",
    tags: ["social", "grammar", "etiquette"],
  },
  {
    id: "ar_meal_structure",
    type: "reference",
    contentPt: "Pequeno-almoço, almoço, lanche, jantar",
    contentL1: "فطور، غداء، وجبة خفيفة، عشاء",
    explanation: "Portuguese meal times: pequeno-almoço (breakfast, light — coffee and pastry), almoço (lunch, 12:30-14:00, the main meal), lanche (afternoon snack, ~16:00), jantar (dinner, 20:00-21:00). Like Arabic culture, lunch is the biggest meal. Eating dinner before 19:30 is considered very early.",
    cefrMin: "A1",
    tags: ["food", "daily-life", "culture"],
  },
  // --- MODERN SLANG ---
  {
    id: "ar_bue",
    type: "expression",
    contentPt: "Bué",
    contentL1: "كتير / مرة (عامية شبابية)",
    explanation: "'Bué' means 'a lot' or 'very' — from Kimbundu (Angolan). 'Tenho bué fome' (I'm really hungry), 'Havia bué gente' (There were loads of people). Used like Arabic 'ktīr' in Levantine or 'barsha' in Tunisian. Ubiquitous among anyone under 40 in Portugal. Also used as an adjective: 'É bué fixe' (It's really cool).",
    cefrMin: "A2",
    tags: ["slang", "daily-life"],
  },
  {
    id: "ar_cena",
    type: "expression",
    contentPt: "Cena",
    contentL1: "شي / حاجة / قصة",
    explanation: "The ultimate placeholder word. Literally means 'scene' but in slang means 'thing/stuff/situation'. 'Que cena!' (What a thing!), 'É uma cena estranha' (It's a weird situation). Like Arabic 'shī' or Egyptian 'ḥāga'. Can replace any noun you can't remember: 'Dá-me aquela cena' (Give me that thing).",
    cefrMin: "A2",
    tags: ["slang", "daily-life"],
  },
  {
    id: "ar_tipo",
    type: "expression",
    contentPt: "Tipo...",
    contentL1: "يعني... / مثل... (كلمة حشو)",
    explanation: "The Portuguese filler word 'like'. 'Ele disse, tipo, que não podia vir' (He said, like, he couldn't come). Used exactly like Arabic 'yaʿnī' in casual speech. Every young Portuguese person uses it constantly. Not appropriate in formal settings.",
    cefrMin: "A2",
    tags: ["slang", "conversation"],
  },
  {
    id: "ar_ganda",
    type: "expression",
    contentPt: "Ganda / Granda",
    contentL1: "عظيم / رهيب / ضخم (مبالغة)",
    explanation: "Contraction of 'grande' — used as an intensifier. 'Ganda filme!' (What a great film!), 'Granda maluco!' (What a legend!). Like Arabic 'ʿaẓīm' or 'rahīb'. Colloquial Lisbon slang, slightly vulgar — don't use with your boss.",
    cefrMin: "B1",
    tags: ["slang"],
  },
  {
    id: "ar_bazar",
    type: "expression",
    contentPt: "Bazar",
    contentL1: "يمشي / يروح (عامية)",
    explanation: "'Bazar' means 'to leave/bounce'. From Arabic 'bazara'. 'Vou bazar' (I'm leaving). Informal, like Arabic 'rāyeḥ' or 'māshī'. Interesting that this word traveled from Arabic → Portuguese slang. The more formal version is 'ir-se embora': 'Vou-me embora'.",
    cefrMin: "B1",
    tags: ["slang", "daily-life"],
  },
  {
    id: "ar_curtir",
    type: "expression",
    contentPt: "Curtir",
    contentL1: "يستمتع / يحب (عامية)",
    explanation: "'Curtir' means to enjoy or be into something. 'Curto bué música portuguesa' (I really enjoy Portuguese music). Also used for liking someone: 'Ela curte-o' (She's into him). Like Arabic 'yistamtiʿ' or Egyptian 'baḥibb'. Very common in casual speech.",
    cefrMin: "A2",
    tags: ["slang", "daily-life"],
  },
  {
    id: "ar_na_boa",
    type: "expression",
    contentPt: "Na boa",
    contentL1: "ما في مشكلة / عادي / تمام",
    explanation: "'Na boa' means 'no worries / it's all good / no problem'. 'Podes usar o meu carro, na boa' (You can use my car, no problem). Also used as a question: 'Tás na boa?' (You OK?). Like Arabic 'māfī mushkila' or Egyptian 'ʿādi'. One of the most useful casual phrases in Portuguese.",
    cefrMin: "A1",
    tags: ["slang", "daily-life"],
  },
  {
    id: "ar_o_pa",
    type: "expression",
    contentPt: "Ó pá!",
    contentL1: "!يا زلمة / يا راجل",
    explanation: "The quintessential Portuguese interjection. 'Ó pá, não acredito!' (Man, I can't believe it!). Used between friends, like Arabic 'yā zalame' (Levantine) or 'yā rājel' (Egyptian). Short for 'rapaz'. Heard dozens of times daily in Portuguese conversations between friends.",
    cefrMin: "A1",
    tags: ["slang", "daily-life"],
  },
  {
    id: "ar_mano",
    type: "expression",
    contentPt: "Mano / Mana",
    contentL1: "أخي / أختي (بين الأصدقاء)",
    explanation: "Short for 'irmão/irmã' (brother/sister). Used as 'bro/sis' between close friends. 'Olha, mano, ouve lá...' (Look, bro, listen...). Like Arabic 'akhī/ukhtī' used between friends. Very common in Lisbon, especially in multicultural neighbourhoods.",
    cefrMin: "A2",
    tags: ["slang", "daily-life"],
  },
  {
    id: "ar_mandar_vir",
    type: "expression",
    contentPt: "Mandar vir",
    contentL1: "يتذمر / يطلب (معنيين مختلفين)",
    explanation: "Two completely different meanings. 1) 'To complain/rant': 'Ele está sempre a mandar vir com tudo' (He's always complaining) — like Arabic 'yitdhammar'. 2) 'To order': 'Manda vir mais uma cerveja' (Order another beer). Context always tells you which meaning applies.",
    cefrMin: "B1",
    tags: ["slang", "daily-life"],
  },
  {
    id: "ar_ta_se_bem",
    type: "expression",
    contentPt: "Tá-se bem",
    contentL1: "!تمام / ماشي الحال",
    explanation: "Contraction of 'está-se bem' — 'it's all good'. Used to accept proposals or confirm you're fine. 'Vamos ao cinema?' — 'Tá-se bem!' (Let's go to the cinema? — Sure!). Like Arabic 'tamām' or 'māshī el-ḥāl'. Very casual, very common.",
    cefrMin: "A1",
    tags: ["slang", "daily-life"],
  },
  // --- ANCIENT PROVERBS / PROVÉRBIOS ---
  {
    id: "ar_cao_gato",
    type: "expression",
    contentPt: "Quem não tem cão, caça com gato",
    contentL1: "اللي ما عنده كلب يصيد بالقط — الحاجة أم الاختراع",
    explanation: "Literally: 'Who doesn't have a dog, hunts with a cat.' Make do with what you have. Arabic has 'al-ḥāja umm al-ikhtirāʿ' (Necessity is the mother of invention). This Portuguese proverb captures 'desenrascar-se' — the philosophy of creative survival with limited resources. Centuries old, still used daily.",
    cefrMin: "B1",
    tags: ["proverb", "culture"],
  },
  {
    id: "ar_agua_pedra",
    type: "expression",
    contentPt: "Água mole em pedra dura, tanto bate até que fura",
    contentL1: "الماء الناعم يثقب الصخرة — النقطة تثقب الحجر",
    explanation: "Literally: 'Soft water on hard stone, hits until it pierces.' Persistence wins. Arabic has 'an-nuqṭa tuthqub al-ḥajar' (The drop pierces the stone). Both cultures share this ancient wisdom about patient persistence — likely from the same Mediterranean origin. Still used when encouraging perseverance.",
    cefrMin: "B1",
    tags: ["proverb", "wisdom"],
  },
  {
    id: "ar_grao_galinha",
    type: "expression",
    contentPt: "Grão a grão, enche a galinha o papo",
    contentL1: "حبة حبة، تملأ الدجاجة حوصلتها — القرش الأبيض ينفع في اليوم الأسود",
    explanation: "Literally: 'Grain by grain, the hen fills her crop.' Small things add up. Arabic has 'el-ʾirsh el-abyaḍ yinfaʿ fi el-yōm el-iswid' (The white penny helps on the black day). Both celebrate small, consistent effort. Used when someone dismisses a small gain.",
    cefrMin: "B1",
    tags: ["proverb", "wisdom"],
  },
  {
    id: "ar_pepino",
    type: "expression",
    contentPt: "De pequenino se torce o pepino",
    contentL1: "لوِّ الخيارة وهي صغيرة — التعليم في الصغر كالنقش على الحجر",
    explanation: "Literally: 'You bend the cucumber when it's small.' Habits are formed young. Arabic has 'at-taʿlīm fī aṣ-ṣighar kal-naqsh ʿalā al-ḥajar' (Learning in youth is like engraving on stone). Used by Portuguese parents and grandparents forever.",
    cefrMin: "B1",
    tags: ["proverb", "education"],
  },
  {
    id: "ar_tripas_coracao",
    type: "expression",
    contentPt: "Fazer das tripas coração",
    contentL1: "يجعل الأمعاء قلباً — يتشجع رغم الصعوبات",
    explanation: "Literally: 'To make heart out of guts.' To summon courage when you have none. Origin: Porto residents sent all good meat to the Discovery fleets and ate only tripe ('tripas') — hence Porto's nickname 'cidade dos tripeiros'. Like Arabic 'yitjassar' (to summon bravery). Still used daily when facing difficulties.",
    cefrMin: "B1",
    tags: ["proverb", "history", "porto"],
  },
  {
    id: "ar_ver_navios",
    type: "expression",
    contentPt: "Ficar a ver navios",
    contentL1: "يبقى يتفرج على السفن — يضيع عليه الأمر",
    explanation: "Literally: 'To be left watching ships.' To be left empty-handed, stood up. Origin: during the Age of Discoveries, women waited on the docks for ships that never returned. Like Arabic 'ḍāʿ ʿalayh el-amr' (the matter was lost on him). 'Fiquei a ver navios' = 'I was left hanging'.",
    cefrMin: "B1",
    tags: ["proverb", "history", "discoveries"],
  },
  {
    id: "ar_engolir_sapos",
    type: "expression",
    contentPt: "Engolir sapos",
    contentL1: "يبلع ضفادع — يصبر على الإهانة",
    explanation: "Literally: 'To swallow frogs.' To endure insults or unfair situations silently. Like Arabic 'yiṣbur ʿalā al-ihāna' (to endure humiliation patiently). 'No trabalho, tenho de engolir muitos sapos' (At work, I have to swallow many frogs). Ancient proverb, still used daily in Portugal.",
    cefrMin: "B1",
    tags: ["proverb", "daily-life"],
  },
  {
    id: "ar_burros_agua",
    type: "expression",
    contentPt: "Dar com os burros na água",
    contentL1: "يطيح الحمير في الماء — يفشل",
    explanation: "Literally: 'To end up with the donkeys in the water.' To fail. Origin: donkey drivers crossing rivers — sometimes the donkeys and cargo fell in. Like Arabic 'fāshal' or Levantine 'wiʾiʿ' (fell down). 'Tentei negociar mas dei com os burros na água' (I tried to negotiate but it all went wrong).",
    cefrMin: "B1",
    tags: ["proverb", "daily-life"],
  },
  {
    id: "ar_rossio_betesga",
    type: "expression",
    contentPt: "Meter o Rossio na Betesga",
    contentL1: "يحط الساحة الكبيرة في الزقاق — يحاول المستحيل",
    explanation: "Literally: 'To fit the Rossio (Lisbon's grand square) into the Betesga (a tiny alley nearby).' Attempting the impossible. Like Arabic 'yuḥāwil al-mustaḥīl'. A purely Lisbon-born proverb from the Middle Ages that survives today. The Rossio is still one of Lisbon's main squares.",
    cefrMin: "B2",
    tags: ["proverb", "lisbon", "history"],
  },
  {
    id: "ar_mar_lugar",
    type: "expression",
    contentPt: "Quem vai ao mar, perde o lugar",
    contentL1: "اللي يروح للبحر يخسر مكانه — مكان الغائب لا يُحفظ",
    explanation: "Literally: 'Who goes to sea, loses their place.' If you leave, someone else takes your spot. Maritime origin — fishermen who went to sea lost their seat at the tavern. Like Arabic 'makān al-ghāʾib lā yuḥfaẓ' (The absent's place is not kept). Used for parking spots, restaurant seats, any contested position.",
    cefrMin: "A2",
    tags: ["proverb", "maritime", "daily-life"],
  },
  // --- DAILY IDIOMS ---
  {
    id: "ar_ora_essa",
    type: "expression",
    contentPt: "Ora essa!",
    contentL1: "!لا شكر على واجب / يا سلام",
    explanation: "An exclamation of modest denial when thanked. 'Obrigado pela ajuda!' — 'Ora essa!' (Thank you! — Don't mention it!). Like Arabic 'lā shukr ʿalā wājib' (No thanks for a duty). Can also express surprise: 'Ora essa, quem diria!' (Well I never!).",
    cefrMin: "A2",
    tags: ["daily-life", "etiquette"],
  },
  {
    id: "ar_descansado",
    type: "expression",
    contentPt: "Está descansado / Fica descansado",
    contentL1: "لا تقلق / اطمئن / على راسي",
    explanation: "Literally: 'Be rested/at ease.' Means 'don't worry, I've got it.' 'Fica descansado, eu trato disso' (Don't worry, I'll handle it). Like Arabic 'lā tiqlaʾ' or 'ʿalā rāsī' (on my head = I've got it). Feminine form: 'Fica descansada'. Used constantly to reassure.",
    cefrMin: "A2",
    tags: ["daily-life", "conversation"],
  },
  {
    id: "ar_nao_faz_mal",
    type: "expression",
    contentPt: "Não faz mal",
    contentL1: "ما في مشكلة / مش مهم / عادي",
    explanation: "Literally: 'It doesn't do harm.' Standard response to minor apologies. 'Desculpa o atraso!' — 'Não faz mal!' (Sorry for being late! — No problem!). Like Arabic 'māfī mushkila' or 'mish muhimm'. One of the first phrases you'll hear and need in Portugal.",
    cefrMin: "A1",
    tags: ["daily-life", "etiquette"],
  },
  {
    id: "ar_deixa_la",
    type: "expression",
    contentPt: "Deixa lá",
    contentL1: "خلّيها / سيبها / ما تهتم",
    explanation: "'Deixa lá' means 'let it go / forget about it / never mind.' 'Queres que te pague?' — 'Deixa lá!' (Want me to pay you back? — Forget it!). Also consoling: 'Deixa lá, amanhã corre melhor' (Never mind, tomorrow will be better). Like Arabic 'khallīhā' or Egyptian 'sībhā'.",
    cefrMin: "A1",
    tags: ["daily-life", "conversation"],
  },
  {
    id: "ar_e_o_que_e",
    type: "expression",
    contentPt: "É o que é",
    contentL1: "هو ما هو / هيك الحياة",
    explanation: "The Portuguese 'it is what it is' — philosophical acceptance of things you can't change. 'O preço subiu? É o que é.' (The price went up? It is what it is.) Spoken with a shrug. Like Arabic 'hēk el-ḥayāt' (That's life). Captures the Portuguese fatalism that coexists with 'desenrascar-se'.",
    cefrMin: "A2",
    tags: ["daily-life", "culture"],
  },
  {
    id: "ar_olha_la",
    type: "expression",
    contentPt: "Olha lá / Ouve lá",
    contentL1: "اسمع / شوف / يا هو",
    explanation: "'Olha lá' (look here) and 'ouve lá' (listen here) — used to get attention or start a question. 'Olha lá, sabes onde fica o correio?' (Hey, do you know where the post office is?). Like Arabic 'ismaʿ' (listen). Not rude — it's the standard way to approach someone in Portugal.",
    cefrMin: "A1",
    tags: ["daily-life", "conversation"],
  },
  {
    id: "ar_entao",
    type: "expression",
    contentPt: "Então?",
    contentL1: "شو الأخبار؟ / إيه الأحوال؟",
    explanation: "'Então?' is the universal Portuguese greeting-question. 'Então, tudo bem?' (So, all good?). Also prompts: 'Então, o que é que queres fazer?' (So, what do you want to do?). Like Arabic 'shū el-akhbār?' or Egyptian 'ēh el-aḥwāl?'. Short, warm, multipurpose.",
    cefrMin: "A1",
    tags: ["daily-life", "conversation"],
  },
  {
    id: "ar_se_calhar",
    type: "expression",
    contentPt: "Se calhar",
    contentL1: "يمكن / ممكن / بلكي",
    explanation: "Literally: 'if it falls (that way).' Means 'maybe / perhaps.' 'Se calhar vou ao cinema amanhã' (Maybe I'll go to the cinema tomorrow). More common than 'talvez' in everyday speech. Like Arabic 'yimkin' or Levantine 'balkī'. Note: in PT-EU this does NOT trigger the subjunctive — unlike 'talvez'.",
    cefrMin: "A2",
    tags: ["daily-life", "grammar"],
  },
  {
    id: "ar_com_certeza",
    type: "expression",
    contentPt: "Com certeza",
    contentL1: "طبعاً / أكيد (لكن ليس دائماً صادق!)",
    explanation: "'Com certeza' means 'certainly / of course.' BUT beware: in PT-EU it is often used as polite but non-committal agreement — like saying 'sure' without meaning it. A Portuguese 'com certeza' can mean 'I'll think about it' (and forget). Arabic 'ṭabʿan' is usually more sincere. This cultural nuance catches many immigrants off guard.",
    cefrMin: "A2",
    tags: ["daily-life", "etiquette", "culture"],
  },
];
