import type { CulturalRef } from "../types.js";

export const arCulturalRefs: readonly CulturalRef[] = [
  {
    id: "ar_moorish_heritage",
    type: "reference",
    contentPt: "O legado mouro em Portugal",
    contentL1: "التراث المغربي في البرتغال",
    explanation: "Portugal was under Moorish rule for over 500 years (711-1249). This left a massive mark on the language, architecture, food, and culture. Over 1,000 Portuguese words come from Arabic. As an Arabic speaker, you have a unique cultural bridge to Portugal that no other L1 group shares.",
    cefrMin: "A2",
    tags: ["history", "culture"],
  },
  {
    id: "ar_oxala",
    type: "expression",
    contentPt: "Oxalá!",
    contentL1: "إن شاء الله (inshallah)",
    explanation: "One of the most direct Arabic survivals in Portuguese. 'Oxalá que chova' (God willing it rains). Used the same way as inshallah — to express hope. You already know this concept perfectly.",
    cefrMin: "A1",
    tags: ["language", "culture", "daily-life"],
  },
  {
    id: "ar_azulejo",
    type: "reference",
    contentPt: "Azulejos",
    contentL1: "الزليج (az-zulayj) — البلاط المزخرف",
    explanation: "Portugal's iconic painted tiles come directly from the Arabic tradition of zellige. The word 'azulejo' comes from Arabic 'az-zulayj' (polished stone). You'll see them everywhere in Lisbon and Porto — a living connection to Arabic art.",
    cefrMin: "A1",
    tags: ["art", "architecture", "culture"],
  },
  {
    id: "ar_arabic_words_food",
    type: "reference",
    contentPt: "Azeite, azeitona, laranja, limão, alface",
    contentL1: "زيت، زيتونة، نارنج، ليمون، خس",
    explanation: "Many Portuguese food words are Arabic: azeite (olive oil, from az-zayt), azeitona (olive, from az-zaytuna), laranja (orange, from naranj), limão (lemon, from laymun), alface (lettuce, from al-khass). Your vocabulary already has a head start.",
    cefrMin: "A1",
    tags: ["food", "language", "vocabulary"],
  },
  {
    id: "ar_saudade",
    type: "expression",
    contentPt: "Saudade",
    contentL1: "شعور عميق بالشوق والحنين (لا ترجمة مباشرة)",
    explanation: "The famous untranslatable Portuguese word — a deep, bittersweet longing for something absent. Arabic has 'hanin' (حنين) and 'shawq' (شوق), but saudade combines both with a melancholic acceptance. Central to Portuguese identity and fado music.",
    cefrMin: "B1",
    tags: ["culture", "emotion"],
  },
  {
    id: "ar_bica_cafe",
    type: "reference",
    contentPt: "Uma bica / um galão",
    contentL1: "قهوة إسبريسو / قهوة بالحليب",
    explanation: "Coffee (from Arabic qahwa) is central to Portuguese life. In Lisbon, espresso is 'uma bica'. A 'galão' is a large milky coffee in a glass. Portuguese coffee culture is intense but different from Arabic coffee — it's always espresso-based, never cardamom-spiced.",
    cefrMin: "A1",
    tags: ["food", "daily-life"],
  },
  {
    id: "ar_fado_arabic_music",
    type: "reference",
    contentPt: "O fado e as raízes musicais árabes",
    contentL1: "الفادو والجذور الموسيقية العربية",
    explanation: "Fado, Portugal's soulful music genre, has debated Arabic origins. The melancholic scales, ornamental singing, and guitarra portuguesa may trace back to Moorish musical traditions. If you love Arabic music, fado's emotional depth will resonate with you.",
    cefrMin: "B1",
    tags: ["music", "culture", "history"],
  },
  {
    id: "ar_algarve",
    type: "reference",
    contentPt: "O Algarve (al-Gharb)",
    contentL1: "الغرب — الجنوب البرتغالي",
    explanation: "Portugal's southern region is called 'Algarve' — directly from Arabic 'al-Gharb' (the west). It was the last region reconquered from the Moors in 1249. The architecture, food, and even the fig and almond trees reflect its Moorish past.",
    cefrMin: "A2",
    tags: ["geography", "history", "culture"],
  },
  {
    id: "ar_desenrascar",
    type: "expression",
    contentPt: "Desenrascar-se",
    contentL1: "التدبير / الاحتيال لحل مشكلة",
    explanation: "The quintessential Portuguese concept — improvising a solution when everything seems impossible. Similar to the Arabic concept of 'tadbir' — resourceful problem-solving. Portuguese people are proud of this national trait.",
    cefrMin: "A2",
    tags: ["culture", "daily-life"],
  },
  {
    id: "ar_fixe",
    type: "expression",
    contentPt: "Fixe!",
    contentL1: "!رائع / حلو",
    explanation: "The Portuguese word for 'cool/awesome'. Young people say it constantly. 'A festa foi fixe!' (The party was cool!). Not to be confused with 'fixo' (fixed/permanent).",
    cefrMin: "A1",
    tags: ["slang", "daily-life"],
  },
  {
    id: "ar_hospitality",
    type: "reference",
    contentPt: "A hospitalidade portuguesa",
    contentL1: "كرم الضيافة البرتغالي",
    explanation: "Like Arabic culture, Portuguese culture values hospitality deeply. Offering food and drink to guests is non-negotiable. If a Portuguese person invites you for 'um cafezinho' (a small coffee), refusing is almost rude — just like refusing Arabic coffee.",
    cefrMin: "A2",
    tags: ["culture", "social", "daily-life"],
  },
  {
    id: "ar_numbers",
    type: "reference",
    contentPt: "Algarismos (do nome al-Khwarizmi)",
    contentL1: "أرقام — من اسم الخوارزمي",
    explanation: "The Portuguese word for digits/numerals — 'algarismos' — comes from the name of the Arabic mathematician al-Khwarizmi. 'Zero' also came to European languages through Portuguese, from Arabic 'sifr'. Portugal was the gateway for Arabic mathematics to Europe.",
    cefrMin: "B1",
    tags: ["history", "language", "science"],
  },
  {
    id: "ar_alfama",
    type: "reference",
    contentPt: "Alfama — o bairro mais antigo de Lisboa",
    contentL1: "الحمّة — أقدم حي في لشبونة",
    explanation: "Lisbon's oldest neighbourhood is named 'Alfama', from Arabic 'al-hamma' (hot springs/baths). Walking through its narrow winding streets feels like a medina. The Moorish urban layout survives to this day.",
    cefrMin: "A2",
    tags: ["geography", "history", "lisbon"],
  },
  {
    id: "ar_estar_nas_tintas",
    type: "expression",
    contentPt: "Estar-se nas tintas",
    contentL1: "ما يهمني / لا أكترث",
    explanation: "Literally 'to be in the paints'. Means you couldn't care less. 'Estou-me nas tintas para isso' (I don't give a damn about that). Very common, mildly rude. Similar in spirit to the colloquial Arabic expression 'ma bihamni'.",
    cefrMin: "B1",
    tags: ["slang", "emotion"],
  },
  {
    id: "ar_family_values",
    type: "reference",
    contentPt: "A família portuguesa",
    contentL1: "العائلة البرتغالية",
    explanation: "Like Arabic culture, Portuguese culture is deeply family-oriented. Sunday lunch with the extended family is sacred. Grandparents often live nearby or in the same house. Children frequently live at home until marriage. This is a strong cultural bridge for Arabic speakers.",
    cefrMin: "A2",
    tags: ["culture", "social", "family"],
  },
  {
    id: "ar_pasteis_nata",
    type: "reference",
    contentPt: "Pastéis de nata",
    contentL1: "حلوى الكاسترد البرتغالية",
    explanation: "Portugal's iconic custard tart. The original recipe comes from the Jerónimos monastery. Like Arabic sweets, they combine eggs, sugar, and pastry in a rich way. Every pastelaria (pastry shop/cafe) sells them — eat them warm with cinnamon.",
    cefrMin: "A1",
    tags: ["food", "culture"],
  },
  {
    id: "ar_mesoclisis",
    type: "expression",
    contentPt: "Dir-lhe-ia (mesóclise)",
    contentL1: "إدراج الضمير في وسط الفعل",
    explanation: "A uniquely Portuguese phenomenon: inserting a pronoun inside the verb. 'Dizer + lhe + ia' becomes 'dir-lhe-ia' (I would tell him/her). Only happens with future and conditional tenses. Formal and written — you rarely hear it in speech, but you'll see it in text.",
    cefrMin: "C1",
    tags: ["grammar", "formal"],
  },
  {
    id: "ar_arabic_place_names",
    type: "reference",
    contentPt: "Nomes árabes de cidades portuguesas",
    contentL1: "أسماء عربية لمدن برتغالية",
    explanation: "Many Portuguese cities have Arabic names: Lisboa (al-Ushbuna), Algarve (al-Gharb), Alfama (al-Hamma), Alcácer do Sal (al-Qasr), Almada (al-Ma'din), Fátima (a Moorish princess's name). The map of Portugal is a map of Arabic heritage.",
    cefrMin: "B1",
    tags: ["geography", "history", "language"],
  },
  {
    id: "ar_bacalhau",
    type: "reference",
    contentPt: "Bacalhau",
    contentL1: "سمك القد المملح والمجفف",
    explanation: "The Portuguese say they have 365 recipes for salt cod — one for every day of the year. Bacalhau is dried, salted cod that must be soaked before cooking. It is the unofficial national dish. Like Arabic preserved foods, it was born from the need to preserve fish for long voyages.",
    cefrMin: "A2",
    tags: ["food", "culture"],
  },
  {
    id: "ar_25_abril",
    type: "reference",
    contentPt: "25 de Abril — Revolução dos Cravos",
    contentL1: "25 أبريل — ثورة القرنفل (1974)",
    explanation: "Portugal's defining modern moment. On April 25, 1974, a peaceful military coup overthrew Europe's longest dictatorship. Soldiers put red carnations in their rifle barrels. The main bridge in Lisbon is named after this date. Understanding this history is essential to understanding modern Portugal's democracy and values.",
    cefrMin: "B1",
    tags: ["history", "culture", "identity"],
  },
  {
    id: "ar_santos_populares",
    type: "reference",
    contentPt: "Santos Populares — Festas de Junho",
    contentL1: "أعياد القديسين الشعبية — احتفالات يونيو",
    explanation: "All of June, Portugal celebrates popular saints: Santo António (Lisbon, June 13), São João (Porto, June 24), São Pedro (June 29). Grilled sardines, caldo verde soup, wine, and street dancing. São João in Porto features plastic hammers to tap people's heads. It is the biggest celebration of the year.",
    cefrMin: "A2",
    tags: ["culture", "traditions"],
  },
  {
    id: "ar_pronto",
    type: "expression",
    contentPt: "Pronto!",
    contentL1: "!خلاص / تمام / جاهز",
    explanation: "One of the most frequently heard words. Used to signal completion ('Pronto, acabei!' = Done!), to move conversation along ('Pronto, vamos lá' = OK let's go), or as a filler. Similar to how Arabic speakers use 'khalas' — the Portuguese equivalent, used dozens of times daily.",
    cefrMin: "A1",
    tags: ["daily-life", "conversation"],
  },
  {
    id: "ar_pois",
    type: "expression",
    contentPt: "Pois... / Pois, pois...",
    contentL1: "أيوه... / يعني... / طيب...",
    explanation: "The most versatile Portuguese filler word. Can mean agreement, hesitation, resignation, or just fill silence — depending on intonation. 'Pois pois' (double) often means polite but disinterested agreement. Like Arabic 'yaʿnī' in its flexibility. Mastering 'pois' is a fluency milestone.",
    cefrMin: "A1",
    tags: ["daily-life", "conversation"],
  },
  {
    id: "ar_tu_voce",
    type: "reference",
    contentPt: "Tu vs Você vs O Senhor/A Senhora",
    contentL1: "أنتَ/أنتِ مقابل حضرتك مقابل سيادتك",
    explanation: "Portuguese has three levels of 'you': tu (informal, like Arabic anta/anti with friends), você (semi-formal, uses 3rd person verb), o senhor/a senhora (formal, like Arabic hadretак). Using the wrong level is a social mistake — like using anta with an elder in Arabic. Start formal, let them switch you to tu.",
    cefrMin: "A1",
    tags: ["social", "grammar", "etiquette"],
  },
  {
    id: "ar_meal_structure",
    type: "reference",
    contentPt: "Pequeno-almoço, almoço, lanche, jantar",
    contentL1: "فطور، غداء، وجبة خفيفة، عشاء",
    explanation: "Portuguese meal times: pequeno-almoço (breakfast, light — coffee and pastry), almoço (lunch, 12:30-14:00, the main meal), lanche (afternoon snack, ~16:00), jantar (dinner, 20:00-21:00). Like Arabic culture, lunch is the biggest meal. Eating dinner before 19:30 is considered very early.",
    cefrMin: "A1",
    tags: ["food", "daily-life", "culture"],
  },
];
