import type { L1Profile } from "../types.js";

export const arProfile: L1Profile = {
  code: "ar",
  name: "Arabic",
  nativeName: "العربية",
  writingDirection: "rtl",
  hasLatinScript: false,
  transfer: {
    cognates: [
      "aldeia (from الضيعة ad-day'a)",
      "alfândega (from الفندق al-funduq)",
      "almofada (from المخدة al-mukhadda)",
      "alface (from الخس al-khass)",
      "azulejo (from الزليج az-zulayj)",
      "azeitona (from الزيتونة az-zaytuna)",
      "garrafa (from غرافة gharrafa)",
      "laranja (from نارنج naranj)",
      "xarope (from شراب sharab)",
      "oxalá (from إن شاء الله inshallah)",
      "alfaiate (from الخياط al-khayyat)",
      "algodão (from القطن al-qutn)",
      "armazém (from المخزن al-makhzan)",
      "enxaqueca (from الشقيقة ash-shaqiqa)",
      "javali (from جبلي jabali)",
      "azeite (from الزيت az-zayt)",
      "refém (from رهينة rahina)",
      "algarismo (from الخوارزمي al-Khwarizmi)",
      "alcatifa (from القطيفة al-qatifa)",
      "açúcar (from سكر sukkar)",
      "álcool (from الكحول al-kuḥūl)",
      "alfazema (from الخزامى al-khuzāmā)",
      "almanaque (from المناخ al-manākh)",
      "assassino (from الحشاشين al-ḥashshāshīn)",
      "calibre (from قالب qālib)",
      "cifra (from صفر ṣifr)",
      "mesquita (from المسجد al-masjid)",
      "tarifa (from تعريفة taʿrīfa)",
      "xadrez (from الشطرنج ash-shaṭranj)",
      "alcachofra (from الخرشوف al-kharshūf)",
    ],
    falseFriends: [
      { word: "café", l1Meaning: "قهوة (qahwa) — from the same root", ptMeaning: "In PT-EU, 'café' means both coffee and a cafe/bar. The drink is usually 'uma bica' in Lisbon." },
      { word: "almofada", l1Meaning: "المخدة (pillow in Arabic origin)", ptMeaning: "almofada means 'cushion/pillow' — same root but the Arabic word shifted meaning regionally." },
      { word: "garrafa", l1Meaning: "غرافة (a ladle/scoop)", ptMeaning: "garrafa means 'bottle' in PT-EU, not a ladle." },
      { word: "até", l1Meaning: "Sounds like حتى (hatta, 'until')", ptMeaning: "até also means 'until/even' — genuine cognate through Moorish influence, same usage." },
      { word: "armazém", l1Meaning: "المخزن (storehouse)", ptMeaning: "armazém means 'warehouse/shop' — close to the original but broader in modern PT-EU." },
      { word: "aldeia", l1Meaning: "الضيعة (estate/farm)", ptMeaning: "aldeia means 'village' in PT-EU — shifted from 'estate' to 'small settlement'." },
      { word: "alfândega", l1Meaning: "الفندق (hotel/inn)", ptMeaning: "alfândega means 'customs (border)' — the original Arabic meant 'inn for merchants'." },
      { word: "limão", l1Meaning: "ليمون (lemon)", ptMeaning: "limão means 'lemon' — direct cognate, but in PT-EU 'lima' is the lime." },
      { word: "algarismo", l1Meaning: "الخوارزمي (al-Khwarizmi, the mathematician)", ptMeaning: "algarismo means 'digit/numeral' — named after the Arabic mathematician." },
      { word: "zero", l1Meaning: "صفر (sifr)", ptMeaning: "zero comes from Arabic sifr via PT-EU — Portuguese merchants spread the word to Europe." },
      { word: "álcool", l1Meaning: "الكحول (al-kuḥūl, originally kohl/antimony powder)", ptMeaning: "álcool means 'alcohol' — the meaning shifted entirely from eye cosmetic to the chemical substance via alchemy." },
      { word: "alcova", l1Meaning: "القبة (al-qubba, dome/vault)", ptMeaning: "alcova means 'bedroom alcove / inner room' — shifted from dome to the private space beneath it." },
      { word: "azar", l1Meaning: "الزهر (az-zahr, dice/flowers)", ptMeaning: "azar means 'bad luck / misfortune' — from dice (gambling) to the misfortune of losing." },
      { word: "cifra", l1Meaning: "صفر (ṣifr, zero/empty)", ptMeaning: "cifra means 'figure / digit / cipher' — from 'zero' to any numeral, then to encoded text." },
      { word: "quintal", l1Meaning: "قنطار (qinṭār, unit of weight)", ptMeaning: "quintal means 'backyard / yard' — completely unrelated to the Arabic weight unit." },
      { word: "xadrez", l1Meaning: "الشطرنج (ash-shaṭranj, chess)", ptMeaning: "xadrez means 'chess' AND 'prison' (slang) AND 'checkered pattern' — multiple meanings from one root." },
      { word: "assassino", l1Meaning: "الحشاشين (al-ḥashshāshīn, the hashish sect)", ptMeaning: "assassino means 'murderer / killer' — from the sect's name to the act of killing." },
      { word: "máscara", l1Meaning: "مسخرة (maskhara, buffoon / mockery)", ptMeaning: "máscara means 'mask' — from the jester's comic face to any face covering." },
      { word: "tarifa", l1Meaning: "تعريفة (taʿrīfa, notification / price list)", ptMeaning: "tarifa means 'rate / fare / tariff' — now means the price itself, not the notification of it." },
      { word: "alecrim", l1Meaning: "الإكليل (al-iklīl, wreath / crown)", ptMeaning: "alecrim means 'rosemary' — from the crown-shaped flowers to the herb itself." },
      { word: "alforreca", l1Meaning: "الحريقة (al-ḥarīqa, burning thing)", ptMeaning: "alforreca means 'jellyfish' — named for its burning sting, preserving the Arabic metaphor." },
      { word: "alvará", l1Meaning: "البراءة (al-barāʾa, patent / certificate)", ptMeaning: "alvará means 'permit / official license' — narrowed from general certificate to government permit." },
      { word: "almirante", l1Meaning: "أمير البحر (amīr al-baḥr, commander of the sea)", ptMeaning: "almirante means 'admiral' — the Arabic compound became one word. Not related to 'emir' in PT." },
      { word: "algemas", l1Meaning: "الجامعة (al-jāmiʿa, gathering/collecting)", ptMeaning: "algemas means 'handcuffs' — from the Arabic root for 'gathering' to restraints that bind wrists." },
      { word: "alforreca", l1Meaning: "الحريقة (al-ḥarīqa, burning thing)", ptMeaning: "alforreca means 'jellyfish' — named for its sting, not for fire." },
      { word: "alvará", l1Meaning: "البراءة (al-barāʾa, innocence / patent)", ptMeaning: "alvará means 'official license / permit' — narrowed from 'certificate of innocence' to government permit." },
      { word: "azenha", l1Meaning: "السانية (as-sāniya, water wheel)", ptMeaning: "azenha means 'watermill' — from the irrigation wheel to the whole mill structure." },
      { word: "javali", l1Meaning: "جبلي (jabalī, of the mountain)", ptMeaning: "javali means 'wild boar' — from 'mountain creature' to the specific animal." },
      { word: "azulejo", l1Meaning: "الزليج (az-zulayj, smooth stone)", ptMeaning: "azulejo means 'decorative tile' — same root, but azulejo in PT became an art form with blue/white painted designs." },
      { word: "alfazema", l1Meaning: "الخزامى (al-khuzāmā, lavender)", ptMeaning: "alfazema means 'lavender' — direct match, but in PT it also refers to lavender-scented cleaning products." },
      { word: "acepipe", l1Meaning: "الزبيب (az-zabīb, raisins)", ptMeaning: "acepipe means 'appetizer / snack' — from dried raisins served before meals to any appetizer." },
      { word: "alambique", l1Meaning: "الأنبيق (al-anbīq, distillation vessel)", ptMeaning: "alambique means 'still / distillery' — same instrument, but in PT also means 'in a confused state' (colloquial)." },
      { word: "azagaia", l1Meaning: "الزغاية (az-zaghāya, light spear)", ptMeaning: "azagaia means 'javelin / assegai' — preserved the weapon meaning but now mostly historical/literary." },
      { word: "alfaiate", l1Meaning: "الخياط (al-khayyāṭ, tailor)", ptMeaning: "alfaiate means 'tailor' — direct match in meaning, one of the clearest Arabic survivals in daily PT." },
      { word: "atalaia", l1Meaning: "الطليعة (aṭ-ṭalīʿa, vanguard / lookout)", ptMeaning: "atalaia means 'watchtower / lookout' — from military scout to the tower itself." },
      { word: "enxaqueca", l1Meaning: "الشقيقة (ash-shaqīqa, migraine / half-head pain)", ptMeaning: "enxaqueca means 'migraine' — same meaning, direct loanword. The 'enx-' prefix is from the Arabic shin." },
      { word: "alcatifa", l1Meaning: "القطيفة (al-qaṭīfa, velvet / plush)", ptMeaning: "alcatifa means 'carpet / rug' — from 'soft fabric' to floor covering. In modern PT-EU, mostly replaced by 'tapete'." },
      { word: "alqueire", l1Meaning: "الكيل (al-kayl, measure)", ptMeaning: "alqueire means 'bushel / land measure' — from dry goods measure to a unit of area in rural PT." },
      { word: "taberna", l1Meaning: "Not Arabic — but sounds like طبرنة", ptMeaning: "taberna means 'tavern / traditional bar' — actually Latin, not Arabic, despite sounding similar. A common false assumption." },
      { word: "recheio", l1Meaning: "Unrelated to Arabic رشا (rashā, bribe)", ptMeaning: "recheio means 'filling / stuffing' (food) — from Latin, not Arabic. The similar sound to 'rashā' is coincidental." },
    ],
    phoneticDifficulties: [
      { sound: "e / i distinction", ipa: "/e/ /ɛ/ /i/", description: "Multiple front vowels", tip: "Arabic has only /i/ and /a/. PT-EU distinguishes open e /ɛ/ (as in 'pé'), closed e /e/ (as in 'medo'), and i /i/. Listen carefully to the difference." },
      { sound: "o / u distinction", ipa: "/o/ /ɔ/ /u/", description: "Multiple back vowels", tip: "Arabic has only /u/ and /a/. PT-EU distinguishes open o /ɔ/ (as in 'pó'), closed o /o/ (as in 'avô'), and u /u/. The open/closed difference changes word meaning." },
      { sound: "p", ipa: "/p/", description: "The voiceless bilabial stop", tip: "Arabic has no /p/ — don't substitute /b/. 'Pão' (bread) is NOT 'bão'. Press both lips together without vibrating your throat." },
      { sound: "ão", ipa: "/ɐ̃w̃/", description: "Nasal diphthong", tip: "No Arabic equivalent. Start with a nasal /a/, then glide to a nasal /w/. Let air through your nose throughout. Practice with 'pão', 'não', 'mão'." },
      { sound: "ã / õ / ẽ", ipa: "/ɐ̃/ /õ/ /ẽ/", description: "Nasal vowels", tip: "Arabic has no nasal vowels at all. Let air flow through your nose while saying the vowel. Start by humming, then open your mouth while keeping the nasal flow." },
      { sound: "lh", ipa: "/ʎ/", description: "Palatal lateral", tip: "No Arabic equivalent. Press the middle of your tongue against the hard palate while making an L sound. Like Italian 'gli' in 'famiglia'." },
      { sound: "nh", ipa: "/ɲ/", description: "Palatal nasal", tip: "No Arabic equivalent. Like the 'ny' in English 'canyon'. The middle of the tongue touches the palate while nasalizing." },
      { sound: "v", ipa: "/v/", description: "Labiodental fricative", tip: "Arabic has /f/ but most dialects lack /v/. Bite your lower lip gently and vibrate — 'vaca' (cow) must have a buzzing V, not an F." },
      { sound: "reduced vowels", ipa: "/ɨ/ or silent", description: "Unstressed vowels nearly disappear", tip: "Like how Arabic short vowels are often unwritten and unpronounced in rapid speech. Unstressed 'e' in PT-EU often becomes /ɨ/ or disappears entirely." },
      { sound: "diphthongs ei / ou / ai", ipa: "/ej/ /ow/ /aj/", description: "Vowel glides", tip: "Arabic has diphthongs too (like في /fay/). PT-EU diphthongs are similar in concept — two vowels gliding together in one syllable." },
      { sound: "word stress", ipa: "variable", description: "Unpredictable stress patterns", tip: "Arabic stress follows regular rules. PT-EU stress can fall on any of the last three syllables and changes meaning: 'sabia' (knew) vs 'sabiá' (thrush bird)." },
      { sound: "consonant clusters", ipa: "various", description: "Initial and final clusters", tip: "Arabic avoids complex clusters. PT-EU allows clusters like 'pr-', 'tr-', 'str-', '-lps'. Practice splitting them slowly: 'trans-por-te'." },
      { sound: "x (multiple values)", ipa: "/ʃ/ /z/ /ks/ /s/", description: "The letter X has four pronunciations", tip: "The letter 'x' changes sound by word: xarope = /ʃ/ (like Arabic shin), exame = /z/, fixo = /ks/, próximo = /s/. No rule — must memorize per word." },
      { sound: "final -l", ipa: "/ɫ/", description: "Dark L at end of syllables", tip: "Arabic has clear L (lam) and emphatic L. PT-EU final 'l' is velarized (dark), almost like /w/. 'Portugal' has a very thick final L unlike any Arabic L." },
      { sound: "nasal diphthongs -ões, -ães", ipa: "/õj̃/ /ɐ̃j̃/", description: "Additional nasal diphthongs beyond -ão", tip: "Beyond -ão, Portuguese has -ões (corações, limões) and -ães (cães, pães). Each combines nasalization with a vowel glide — two challenges at once for Arabic speakers." },
    ],
    grammarGaps: [
      { concept: "Word order (SVO)", explanation: "Subject-Verb-Object is the default order", l1Comparison: "Arabic is typically VSO (verb first). In PT-EU, 'O João come o pão' (The João eats the bread) — subject comes first." },
      { concept: "Gendered articles (o/a)", explanation: "Definite articles change by gender: o (m), a (f)", l1Comparison: "Arabic has 'ال' (al-) for all genders. PT-EU splits into 'o livro' (the book, m) and 'a mesa' (the table, f). Gender assignments differ from Arabic." },
      { concept: "Indefinite articles (um/uma)", explanation: "PT-EU has gendered indefinite articles", l1Comparison: "Arabic doesn't mark indefiniteness with an article (uses tanwin). PT-EU requires 'um' (m) or 'uma' (f) before indefinite nouns." },
      { concept: "No dual number", explanation: "PT-EU has only singular and plural", l1Comparison: "Arabic has singular, dual (-ayn/-ayn), and plural. PT-EU uses 'dois/duas' + plural noun instead of a dual form." },
      { concept: "Verb conjugation system", explanation: "6 persons, many tenses, 3 conjugation classes (-ar, -er, -ir)", l1Comparison: "Arabic conjugates for person/gender too, but PT-EU has 3 verb classes and many more tense/mood combinations. The concept is familiar; the forms are entirely different." },
      { concept: "Subjunctive mood", explanation: "Used for doubt, desire, emotion, hypothetical", l1Comparison: "Arabic has mansoub (subjunctive-like) mood triggered by 'an/lan/kay'. PT-EU subjunctive is triggered differently — after 'talvez', 'espero que', 'embora', etc." },
      { concept: "Ser vs Estar", explanation: "Two verbs for 'to be': ser (permanent) and estar (temporary/state)", l1Comparison: "Arabic also distinguishes — sentences without a copula (permanent) vs using كان (was/temporary). But PT-EU always requires a verb." },
      { concept: "Prepositions", explanation: "Complex preposition system: em, de, a, para, com, por", l1Comparison: "Arabic prepositions (في, من, إلى, على) don't map 1:1. 'Em' covers في and على, 'de' covers من and عن. Preposition + article contracts: em + o = no, de + a = da." },
      { concept: "Personal infinitive", explanation: "Infinitive conjugated for person: fazermos (for us to do)", l1Comparison: "Unique to Portuguese — doesn't exist in Arabic or most languages. It replaces a que-clause: 'para nós fazermos' instead of 'para que nós façamos'." },
      { concept: "Relative clauses", explanation: "Uses 'que' for all relative clauses", l1Comparison: "Arabic uses الذي/التي/الذين (gender/number-specific). PT-EU uses just 'que' for everything: 'o homem que vi', 'a mulher que falou'." },
      { concept: "Object pronoun placement", explanation: "Pronouns go before or after the verb depending on context", l1Comparison: "Arabic attaches pronoun suffixes to the verb. PT-EU uses separate words: 'dou-te' (I give you) vs 'não te dou' (I don't give you). Placement rules are complex." },
      { concept: "Compound tenses", explanation: "ter + past participle: 'tenho feito' (I have done)", l1Comparison: "Arabic uses قد + past for perfective aspect. PT-EU builds compound tenses with 'ter': tenho falado, tinha comido, terei feito." },
      { concept: "Reflexive verbs", explanation: "Many common verbs require a reflexive pronoun (se)", l1Comparison: "Arabic has reflexive verb forms (Form V, VII, VIII) built into the root pattern. PT-EU uses a separate pronoun: levantar-se (get up), chamar-se (be called), lembrar-se (remember). The pronoun must match the subject and follows placement rules." },
      { concept: "Continuous with 'estar a + infinitive'", explanation: "Ongoing actions use 'estar a + infinitive'", l1Comparison: "Arabic uses the imperfective aspect for ongoing actions. PT-EU uses a separate construction: 'Estou a comer' (I am eating). This is different from the simple present 'como' (I eat)." },
      { concept: "Diminutives -inho/-inha", explanation: "Extremely productive diminutive suffix used in daily speech", l1Comparison: "Arabic uses the diminutive pattern (fuʿayl) but rarely in modern speech. PT-EU diminutives are everywhere: cafezinho (small coffee), pouquinho (a little bit), obrigadinho (thanks!). They express affection, politeness, or smallness." },
    ],
    skipBasics: false,
    startingCEFR: "A1",
  },
};
