import type { L1Profile } from "../types.js";

export const arProfile: L1Profile = {
  code: "ar",
  name: "Arabic",
  nativeName: "العربية",
  writingDirection: "rtl",
  hasLatinScript: false,
  transfer: {
    cognates: [
      "aldeia (from الضيعة ad-day'a)",
      "alfândega (from الفندق al-funduq)",
      "almofada (from المخدة al-mukhadda)",
      "alface (from الخس al-khass)",
      "azulejo (from الزليج az-zulayj)",
      "azeitona (from الزيتونة az-zaytuna)",
      "garrafa (from غرافة gharrafa)",
      "laranja (from نارنج naranj)",
      "xarope (from شراب sharab)",
      "oxalá (from إن شاء الله inshallah)",
      "alfaiate (from الخياط al-khayyat)",
      "algodão (from القطن al-qutn)",
      "armazém (from المخزن al-makhzan)",
      "enxaqueca (from الشقيقة ash-shaqiqa)",
      "javali (from جبلي jabali)",
      "azeite (from الزيت az-zayt)",
      "refém (from رهينة rahina)",
      "algarismo (from الخوارزمي al-Khwarizmi)",
      "alcatifa (from القطيفة al-qatifa)",
    ],
    falseFriends: [
      { word: "café", l1Meaning: "قهوة (qahwa) — from the same root", ptMeaning: "In PT-EU, 'café' means both coffee and a cafe/bar. The drink is usually 'uma bica' in Lisbon." },
      { word: "almofada", l1Meaning: "المخدة (pillow in Arabic origin)", ptMeaning: "almofada means 'cushion/pillow' — same root but the Arabic word shifted meaning regionally." },
      { word: "garrafa", l1Meaning: "غرافة (a ladle/scoop)", ptMeaning: "garrafa means 'bottle' in PT-EU, not a ladle." },
      { word: "até", l1Meaning: "Sounds like حتى (hatta, 'until')", ptMeaning: "até also means 'until/even' — genuine cognate through Moorish influence, same usage." },
      { word: "armazém", l1Meaning: "المخزن (storehouse)", ptMeaning: "armazém means 'warehouse/shop' — close to the original but broader in modern PT-EU." },
      { word: "aldeia", l1Meaning: "الضيعة (estate/farm)", ptMeaning: "aldeia means 'village' in PT-EU — shifted from 'estate' to 'small settlement'." },
      { word: "alfândega", l1Meaning: "الفندق (hotel/inn)", ptMeaning: "alfândega means 'customs (border)' — the original Arabic meant 'inn for merchants'." },
      { word: "limão", l1Meaning: "ليمون (lemon)", ptMeaning: "limão means 'lemon' — direct cognate, but in PT-EU 'lima' is the lime." },
      { word: "algarismo", l1Meaning: "الخوارزمي (al-Khwarizmi, the mathematician)", ptMeaning: "algarismo means 'digit/numeral' — named after the Arabic mathematician." },
      { word: "zero", l1Meaning: "صفر (sifr)", ptMeaning: "zero comes from Arabic sifr via PT-EU — Portuguese merchants spread the word to Europe." },
    ],
    phoneticDifficulties: [
      { sound: "e / i distinction", ipa: "/e/ /ɛ/ /i/", description: "Multiple front vowels", tip: "Arabic has only /i/ and /a/. PT-EU distinguishes open e /ɛ/ (as in 'pé'), closed e /e/ (as in 'medo'), and i /i/. Listen carefully to the difference." },
      { sound: "o / u distinction", ipa: "/o/ /ɔ/ /u/", description: "Multiple back vowels", tip: "Arabic has only /u/ and /a/. PT-EU distinguishes open o /ɔ/ (as in 'pó'), closed o /o/ (as in 'avô'), and u /u/. The open/closed difference changes word meaning." },
      { sound: "p", ipa: "/p/", description: "The voiceless bilabial stop", tip: "Arabic has no /p/ — don't substitute /b/. 'Pão' (bread) is NOT 'bão'. Press both lips together without vibrating your throat." },
      { sound: "ão", ipa: "/ɐ̃w̃/", description: "Nasal diphthong", tip: "No Arabic equivalent. Start with a nasal /a/, then glide to a nasal /w/. Let air through your nose throughout. Practice with 'pão', 'não', 'mão'." },
      { sound: "ã / õ / ẽ", ipa: "/ɐ̃/ /õ/ /ẽ/", description: "Nasal vowels", tip: "Arabic has no nasal vowels at all. Let air flow through your nose while saying the vowel. Start by humming, then open your mouth while keeping the nasal flow." },
      { sound: "lh", ipa: "/ʎ/", description: "Palatal lateral", tip: "No Arabic equivalent. Press the middle of your tongue against the hard palate while making an L sound. Like Italian 'gli' in 'famiglia'." },
      { sound: "nh", ipa: "/ɲ/", description: "Palatal nasal", tip: "No Arabic equivalent. Like the 'ny' in English 'canyon'. The middle of the tongue touches the palate while nasalizing." },
      { sound: "v", ipa: "/v/", description: "Labiodental fricative", tip: "Arabic has /f/ but most dialects lack /v/. Bite your lower lip gently and vibrate — 'vaca' (cow) must have a buzzing V, not an F." },
      { sound: "reduced vowels", ipa: "/ɨ/ or silent", description: "Unstressed vowels nearly disappear", tip: "Like how Arabic short vowels are often unwritten and unpronounced in rapid speech. Unstressed 'e' in PT-EU often becomes /ɨ/ or disappears entirely." },
      { sound: "diphthongs ei / ou / ai", ipa: "/ej/ /ow/ /aj/", description: "Vowel glides", tip: "Arabic has diphthongs too (like في /fay/). PT-EU diphthongs are similar in concept — two vowels gliding together in one syllable." },
      { sound: "word stress", ipa: "variable", description: "Unpredictable stress patterns", tip: "Arabic stress follows regular rules. PT-EU stress can fall on any of the last three syllables and changes meaning: 'sabia' (knew) vs 'sabiá' (thrush bird)." },
      { sound: "consonant clusters", ipa: "various", description: "Initial and final clusters", tip: "Arabic avoids complex clusters. PT-EU allows clusters like 'pr-', 'tr-', 'str-', '-lps'. Practice splitting them slowly: 'trans-por-te'." },
    ],
    grammarGaps: [
      { concept: "Word order (SVO)", explanation: "Subject-Verb-Object is the default order", l1Comparison: "Arabic is typically VSO (verb first). In PT-EU, 'O João come o pão' (The João eats the bread) — subject comes first." },
      { concept: "Gendered articles (o/a)", explanation: "Definite articles change by gender: o (m), a (f)", l1Comparison: "Arabic has 'ال' (al-) for all genders. PT-EU splits into 'o livro' (the book, m) and 'a mesa' (the table, f). Gender assignments differ from Arabic." },
      { concept: "Indefinite articles (um/uma)", explanation: "PT-EU has gendered indefinite articles", l1Comparison: "Arabic doesn't mark indefiniteness with an article (uses tanwin). PT-EU requires 'um' (m) or 'uma' (f) before indefinite nouns." },
      { concept: "No dual number", explanation: "PT-EU has only singular and plural", l1Comparison: "Arabic has singular, dual (-ayn/-ayn), and plural. PT-EU uses 'dois/duas' + plural noun instead of a dual form." },
      { concept: "Verb conjugation system", explanation: "6 persons, many tenses, 3 conjugation classes (-ar, -er, -ir)", l1Comparison: "Arabic conjugates for person/gender too, but PT-EU has 3 verb classes and many more tense/mood combinations. The concept is familiar; the forms are entirely different." },
      { concept: "Subjunctive mood", explanation: "Used for doubt, desire, emotion, hypothetical", l1Comparison: "Arabic has mansoub (subjunctive-like) mood triggered by 'an/lan/kay'. PT-EU subjunctive is triggered differently — after 'talvez', 'espero que', 'embora', etc." },
      { concept: "Ser vs Estar", explanation: "Two verbs for 'to be': ser (permanent) and estar (temporary/state)", l1Comparison: "Arabic also distinguishes — sentences without a copula (permanent) vs using كان (was/temporary). But PT-EU always requires a verb." },
      { concept: "Prepositions", explanation: "Complex preposition system: em, de, a, para, com, por", l1Comparison: "Arabic prepositions (في, من, إلى, على) don't map 1:1. 'Em' covers في and على, 'de' covers من and عن. Preposition + article contracts: em + o = no, de + a = da." },
      { concept: "Personal infinitive", explanation: "Infinitive conjugated for person: fazermos (for us to do)", l1Comparison: "Unique to Portuguese — doesn't exist in Arabic or most languages. It replaces a que-clause: 'para nós fazermos' instead of 'para que nós façamos'." },
      { concept: "Relative clauses", explanation: "Uses 'que' for all relative clauses", l1Comparison: "Arabic uses الذي/التي/الذين (gender/number-specific). PT-EU uses just 'que' for everything: 'o homem que vi', 'a mulher que falou'." },
      { concept: "Object pronoun placement", explanation: "Pronouns go before or after the verb depending on context", l1Comparison: "Arabic attaches pronoun suffixes to the verb. PT-EU uses separate words: 'dou-te' (I give you) vs 'não te dou' (I don't give you). Placement rules are complex." },
      { concept: "Compound tenses", explanation: "ter + past participle: 'tenho feito' (I have done)", l1Comparison: "Arabic uses قد + past for perfective aspect. PT-EU builds compound tenses with 'ter': tenho falado, tinha comido, terei feito." },
    ],
    skipBasics: false,
    startingCEFR: "A1",
  },
};
