import type { CulturalRef } from "../types.js";

export const urCulturalRefs: readonly CulturalRef[] = [
  {
    id: "ur_arabic_shared_words",
    type: "reference",
    contentPt: "Palavras portuguesas de origem árabe",
    contentL1: "Portuguese words from Arabic — familiar to Urdu speakers",
    explanation: "Portugal was under Moorish rule for 500 years (711-1249). Portuguese absorbed hundreds of Arabic words — and Urdu did too via Persian. Many Portuguese words will sound familiar: 'aldeia' (village, from ad-day'a), 'alfândega' (customs, from al-funduq), 'azulejo' (tile, from az-zulayj), 'alface' (lettuce, from al-khas), 'almofada' (pillow, from al-mukhadda). This shared Arabic layer is a unique bridge between Urdu and Portuguese.",
    cefrMin: "A2",
    tags: ["vocabulary", "history", "arabic"],
  },
  {
    id: "ur_moorish_portugal",
    type: "reference",
    contentPt: "Portugal mouro: 500 anos de história islâmica",
    contentL1: "Moorish Portugal: 500 years of Islamic history",
    explanation: "Southern Portugal (Algarve, from al-Gharb 'the west') was Muslim for over 500 years. The architecture in Sintra, Silves, and Mertola shows Islamic influence. Fado music may have Arabic melodic roots. Urdu speakers will recognize geometric patterns in azulejos (tiles) that mirror Islamic art traditions. This shared heritage creates an unexpected cultural bridge.",
    cefrMin: "B1",
    tags: ["history", "culture", "architecture"],
  },
  {
    id: "ur_chai_cha",
    type: "reference",
    contentPt: "Chá",
    contentL1: "Chai — same origin, different drink culture",
    explanation: "Urdu 'chai' and Portuguese 'cha' share the same Chinese root. Both nations are serious about their hot drinks. But in Portugal, coffee dominates daily life while 'cha' is for afternoons and evenings. A 'galão' (milky coffee in a glass) is the morning ritual — like chai but with coffee.",
    cefrMin: "A1",
    tags: ["food", "daily-life", "history"],
  },
  {
    id: "ur_loanwords_colonial",
    type: "reference",
    contentPt: "Palavras portuguesas no urdu",
    contentL1: "Portuguese words in everyday Urdu",
    explanation: "Through the Goan and Indian Ocean trade, Portuguese words entered Urdu: 'almari' (armário — wardrobe), 'kamra' (câmara — room), 'mez' (mesa — table), 'sabun' (sabão — soap), 'tauliya' (toalha — towel), 'kamiz' (camisa — shirt), 'balti' (balde — bucket). When you learn these Portuguese words, you are reconnecting with words your language already borrowed centuries ago.",
    cefrMin: "A1",
    tags: ["vocabulary", "history"],
  },
  {
    id: "ur_saudade_ghazal",
    type: "expression",
    contentPt: "Saudade",
    contentL1: "A bittersweet longing — like the dard of ghazals",
    explanation: "Portuguese 'saudade' — the untranslatable longing — maps closely to the Urdu ghazal tradition's concept of 'dard' and 'hasrat'. Both cultures have elevated melancholic longing to an art form. Fado music (Portugal's mournful genre) and ghazals share the same emotional DNA: pain made beautiful through art.",
    cefrMin: "B1",
    tags: ["culture", "emotion", "music"],
  },
  {
    id: "ur_desenrascar",
    type: "expression",
    contentPt: "Desenrascar-se",
    contentL1: "Jugaad — creative problem-solving",
    explanation: "The Portuguese concept of 'desenrascar-se' — improvising a solution when everything seems impossible — is a perfect cultural match for 'jugaad'. Both Portuguese and Pakistani cultures take pride in this resourcefulness. 'Vou-me desenrascar' = 'jugaad kar lunga'.",
    cefrMin: "B1",
    tags: ["culture", "daily-life"],
  },
  {
    id: "ur_football_cricket",
    type: "reference",
    contentPt: "Futebol e religião em Portugal",
    contentL1: "Football is religion — like cricket in Pakistan",
    explanation: "What cricket is to Pakistan, football is to Portugal. The passion for Benfica, Sporting, and Porto mirrors the intensity of Pakistan Super League rivalries. Cristiano Ronaldo is a national hero on the level of cricket legends. Learning football vocabulary is essential for Portuguese conversation.",
    cefrMin: "A2",
    tags: ["sport", "culture", "conversation"],
  },
  {
    id: "ur_family_sunday",
    type: "reference",
    contentPt: "Almoço de domingo com a família",
    contentL1: "Sunday family lunch — sacred tradition",
    explanation: "Like Pakistani family gatherings, Portuguese Sunday lunch is sacred and non-negotiable. Extended family gathers, grandparents are central, children play while adults talk for hours. The meal is elaborate, always at someone's home. Portuguese family values will feel familiar to Pakistani culture.",
    cefrMin: "A2",
    tags: ["culture", "family", "daily-life"],
  },
  {
    id: "ur_hospitality",
    type: "expression",
    contentPt: "Fique a vontade",
    contentL1: "Make yourself at home — Pakistani-level hospitality",
    explanation: "'Fique a vontade' means 'make yourself comfortable'. Portuguese hospitality, while not quite at Pakistani mehmaan-nawazi levels, is warm and genuine. Guests are always offered food and drink. Refusing food is considered rude — similar to Pakistani customs.",
    cefrMin: "A2",
    tags: ["culture", "hospitality", "daily-life"],
  },
  {
    id: "ur_halal_food",
    type: "reference",
    contentPt: "Comida halal em Portugal",
    contentL1: "Finding halal food in Portugal",
    explanation: "Portugal has a growing halal food scene, especially in Lisbon and Porto where Muslim communities are established. However, pork (porco) is central to Portuguese cuisine — 'presunto' (cured ham), 'chouriço' (sausage), 'leitão' (suckling pig). Learning food vocabulary helps navigate menus: 'frango' (chicken), 'peixe' (fish), 'bacalhau' (cod) are safe choices. 'Sem porco, por favor' (without pork, please) is essential.",
    cefrMin: "A1",
    tags: ["food", "daily-life", "practical"],
  },
  {
    id: "ur_azulejo_art",
    type: "reference",
    contentPt: "Azulejos portugueses",
    contentL1: "Azulejos — tiles with Islamic geometric roots",
    explanation: "Portuguese 'azulejo' comes from Arabic 'az-zulayj' (polished stone). These decorative tiles cover buildings across Portugal. Early designs were geometric, directly from Moorish tradition — Urdu speakers will recognize patterns similar to Islamic art in mosques and Mughal architecture. Later Portuguese azulejos evolved into figurative scenes, but the geometric tradition persists.",
    cefrMin: "A2",
    tags: ["art", "architecture", "history", "arabic"],
  },
  {
    id: "ur_fado_music",
    type: "reference",
    contentPt: "Fado",
    contentL1: "Fado — Portugal's soul music (ghazal ki tarah)",
    explanation: "Fado is mournful, melodic, and deeply emotional — the Portuguese ghazal. Some scholars believe fado's melodic patterns have Arabic/Moorish roots, which would make the connection to Urdu musical traditions even deeper. Like qawwali, fado is best experienced live, in intimate venues. Amalia Rodrigues is the undisputed queen of fado.",
    cefrMin: "B1",
    tags: ["music", "culture", "emotion"],
  },
  {
    id: "ur_fixe",
    type: "expression",
    contentPt: "Fixe!",
    contentL1: "Cool! / Zabardast!",
    explanation: "'Fixe' is the Portuguese 'zabardast' or 'mast'. When something is cool or awesome: 'Que fixe!' (How cool!). The most common positive reaction in everyday Portuguese conversation.",
    cefrMin: "A1",
    tags: ["slang", "daily-life"],
  },
  {
    id: "ur_pois",
    type: "expression",
    contentPt: "Pois...",
    contentL1: "Achha... / Haan... (versatile filler/agreement)",
    explanation: "Like Urdu 'achha' which can mean 'okay', 'really?', 'I see', or be a pure filler, Portuguese 'pois' is infinitely versatile. It can express agreement, hesitation, resignation, or acknowledgement — all depending on intonation. 'Pois pois' (doubled) is polite but slightly disinterested agreement.",
    cefrMin: "A1",
    tags: ["daily-life", "conversation"],
  },
  {
    id: "ur_algarve_algharb",
    type: "reference",
    contentPt: "Algarve — do árabe 'al-Gharb'",
    contentL1: "Algarve — from Arabic 'al-Gharb' (the West)",
    explanation: "Portugal's southernmost region 'Algarve' is literally Arabic for 'the West' (al-Gharb). The Moors named it because it was the western frontier of their territory. Many Portuguese place names have Arabic origins: Alfama (al-hamma, hot springs), Almada (al-ma'dan, the mine), Fatima (yes, the famous Portuguese town is named after a Moorish princess).",
    cefrMin: "B1",
    tags: ["history", "geography", "arabic"],
  },
  {
    id: "ur_spice_trade",
    type: "reference",
    contentPt: "Rota das especiarias",
    contentL1: "The spice route — Portugal's connection to the subcontinent",
    explanation: "Vasco da Gama reached India in 1498. The Portuguese controlled the Indian Ocean spice trade for over a century, establishing forts in Goa, Daman, Diu, and along the East African coast. This trade brought Portuguese words into Urdu/Hindi and Indian spices into Portuguese cooking. 'Piri-piri' (chilli) in Portuguese cuisine is a direct legacy.",
    cefrMin: "A2",
    tags: ["history", "food", "vocabulary"],
  },
  {
    id: "ur_nas_tintas",
    type: "expression",
    contentPt: "Estar-se nas tintas",
    contentL1: "To not care at all — mujhe koi fark nahi padta",
    explanation: "Literally 'to be in the paints' — means you couldn't care less. Common, mildly rude but acceptable in casual speech. 'Estou-me nas tintas para isso' = 'mujhe is se koi matlab nahi'.",
    cefrMin: "B1",
    tags: ["slang", "emotion"],
  },
  {
    id: "ur_pastel_nata",
    type: "reference",
    contentPt: "Pastel de nata",
    contentL1: "Custard tart — Portugal's iconic pastry",
    explanation: "Flaky pastry shell filled with egg custard, baked until caramelized on top. The recipe originated in a monastery in Belém, Lisbon. Sprinkled with cinnamon and powdered sugar. The closest Pakistani parallel might be the egg-based sweets (like falooda or cream rolls), but pastéis de nata are in a class of their own. Available everywhere in Portugal for about one euro.",
    cefrMin: "A1",
    tags: ["food", "culture", "lisbon"],
  },
  {
    id: "ur_nif_bureaucracy",
    type: "reference",
    contentPt: "NIF — Número de Identificação Fiscal",
    contentL1: "Tax number — your first bureaucratic step in Portugal",
    explanation: "The NIF is Portugal's tax identification number, essential for everything: opening a bank account, renting a flat, signing a phone contract, even buying furniture on credit. You get it at 'as Finanças' (tax office). Like Pakistan's CNIC, but Portugal won't let you do anything without it. Your first Portuguese word after 'olá' should be 'NIF'. 'Preciso de um NIF' (I need a NIF) is the most important sentence for any newcomer.",
    cefrMin: "A1",
    tags: ["practical", "bureaucracy", "immigration"],
  },
  {
    id: "ur_sef_residencia",
    type: "reference",
    contentPt: "AIMA (antigo SEF) — autorização de residência",
    contentL1: "Residence permits — the immigration process",
    explanation: "AIMA (formerly SEF) handles immigration in Portugal. The process involves 'agendamento' (appointment booking), 'autorização de residência' (residence permit), and 'reagrupamento familiar' (family reunification). Key vocabulary: 'visto' (visa), 'título de residência' (residence card), 'renovação' (renewal), 'comprovativo de morada' (proof of address). The Portuguese bureaucracy is slow but generally respectful — 'paciência' (patience) is the key word.",
    cefrMin: "A2",
    tags: ["practical", "bureaucracy", "immigration"],
  },
  {
    id: "ur_santos_populares",
    type: "reference",
    contentPt: "Festas dos Santos Populares",
    contentL1: "June street festivals — like melas but with sardines",
    explanation: "Every June, Portugal explodes into street festivals for Santo António (Lisbon, June 13), São João (Porto, June 24), and São Pedro (June 29). Grilled sardines fill the streets, there is music, dancing, and in Porto people hit strangers on the head with plastic hammers. The energy and street food culture is comparable to Pakistani melas and Basant. Entire neighbourhoods set up outdoor tables. Learning to eat sardines on bread with your hands is a Portuguese rite of passage.",
    cefrMin: "A2",
    tags: ["culture", "festivals", "food"],
  },
  {
    id: "ur_lisbon_porto",
    type: "reference",
    contentPt: "Lisboa vs Porto",
    contentL1: "The rivalry — like Lahore vs Karachi",
    explanation: "Lisbon and Porto have a friendly but intense rivalry, much like Lahore and Karachi. Lisbon is the cosmopolitan capital; Porto (whose residents are called 'tripeiros', tripe-eaters) is proudly independent and working-class. Each city has its own word for espresso: 'bica' (Lisbon) vs 'cimbalino' (Porto). Never tell someone from Porto that Lisbon is better.",
    cefrMin: "B1",
    tags: ["culture", "cities"],
  },
  {
    id: "ur_pronto",
    type: "expression",
    contentPt: "Pronto!",
    contentL1: "Bus! / Chal theek hai!",
    explanation: "'Pronto' is one of the most useful Portuguese words. It means 'done!', 'ready!', 'OK then!', or 'that's it!'. It works like 'bus' or 'chal theek hai' in Urdu — wrapping up a conversation, signalling completion, or expressing resigned acceptance. 'Pronto, vamos!' (Right then, let's go!).",
    cefrMin: "A1",
    tags: ["daily-life", "conversation"],
  },
  {
    id: "ur_25_abril",
    type: "reference",
    contentPt: "25 de Abril — Revolução dos Cravos",
    contentL1: "The Carnation Revolution (1974)",
    explanation: "On April 25, 1974, Portugal peacefully overthrew its 48-year dictatorship. Soldiers put red carnations in their rifle barrels instead of firing them. The bridge in Lisbon is named Ponte 25 de Abril. This date defines modern Portugal — democracy, freedom of speech, and the end of colonial wars. Understanding it is essential for understanding Portuguese identity.",
    cefrMin: "B1",
    tags: ["history", "identity"],
  },
  {
    id: "ur_bacalhau",
    type: "reference",
    contentPt: "Bacalhau — 365 receitas",
    contentL1: "Salt cod — Portugal's national ingredient",
    explanation: "Dried salt cod is to Portugal what biryani is to Pakistan — the defining national dish, prepared in 365 ways (one for each day). 'Bacalhau à Brás' (shredded cod with eggs and potatoes), 'bacalhau com natas' (cod with cream), 'pastéis de bacalhau' (cod fritters). Portuguese imported cod from Norway and Iceland for centuries. The fish is always salted and must be soaked in water for 24-48 hours before cooking. Every Portuguese family has their own bacalhau recipe.",
    cefrMin: "A2",
    tags: ["food", "culture"],
  },
  {
    id: "ur_bue",
    type: "expression",
    contentPt: "Bué",
    contentL1: "Bohat / Bahut — bué = a LOT",
    explanation: "'Bué' means 'a lot' or 'very' in PT-EU slang. 'Bué fixe' (really cool), 'bué caro' (really expensive), 'há bué gente' (loads of people). From Kimbundu (Angolan language). Used constantly by young Portuguese. Like Urdu 'bohat' — a universal intensifier for everything.",
    cefrMin: "A2",
    tags: ["slang", "daily-life"],
  },
  {
    id: "ur_cena",
    type: "expression",
    contentPt: "Cena",
    contentL1: "Cheez / Mamla — that thing, that situation",
    explanation: "Originally means 'scene' but in slang it means 'thing', 'stuff', 'situation'. 'Que cena!' (What a scene!), 'é uma cena' (it's a thing). Like Urdu 'cheez' or 'mamla' used vaguely. 'Tenho uma cena para te contar' could mean gossip, news, a secret — literally anything.",
    cefrMin: "A2",
    tags: ["slang", "daily-life"],
  },
  {
    id: "ur_tipo",
    type: "expression",
    contentPt: "Tipo...",
    contentL1: "Jaise... / Matlab... — like..., you know...",
    explanation: "'Tipo' is the PT-EU filler word, exactly like English 'like' or Urdu 'jaise' / 'matlab'. 'Ele é tipo estranho' (He's like weird). Young Portuguese pepper every sentence with 'tipo'. Overuse it and you will sound authentically Portuguese.",
    cefrMin: "A2",
    tags: ["slang", "conversation"],
  },
  {
    id: "ur_ganda",
    type: "expression",
    contentPt: "Ganda!",
    contentL1: "Zabardast! / Kamaal!",
    explanation: "'Ganda' (or 'granda') means 'great', 'massive', 'amazing' in Lisbon slang. 'Ganda filme!' (Great movie!), 'ganda maluco!' (you absolute legend!). Raw, emphatic, street-level praise. Like Urdu 'zabardast' or 'kamaal' — not polite but deeply enthusiastic.",
    cefrMin: "B1",
    tags: ["slang", "emotion"],
  },
  {
    id: "ur_bazar",
    type: "expression",
    contentPt: "Bazar!",
    contentL1: "Nikal jana / Bhaagna — to leave fast",
    explanation: "'Bazar' in PT-EU slang means 'to leave', 'to get out'. 'Vou bazar' (I'm out), 'ele bazou' (he bolted). From Romani, nothing to do with a marketplace (bazaar). Like Urdu 'nikal jaana'. Informal, used among friends.",
    cefrMin: "B1",
    tags: ["slang", "daily-life"],
  },
  {
    id: "ur_curtir",
    type: "expression",
    contentPt: "Curtir",
    contentL1: "Mazay karna / Enjoy karna",
    explanation: "'Curtir' means 'to enjoy', 'to have fun', 'to like'. 'Vamos curtir!' (Let's enjoy!), 'curto bué isso' (I really like that). Also slang for 'making out'. Like Urdu 'mazay karna'. One of the most common slang verbs in young Portuguese speech.",
    cefrMin: "A2",
    tags: ["slang", "daily-life"],
  },
  {
    id: "ur_na_boa",
    type: "expression",
    contentPt: "Na boa",
    contentL1: "Sab theek / Koi masla nahi",
    explanation: "'Na boa' means 'all good', 'no worries'. 'Estás bem?' — 'Na boa!' (You OK? — All good!). Like Urdu 'sab theek' or 'koi masla nahi'. One of the most used casual expressions in Portugal — effortlessly positive.",
    cefrMin: "A1",
    tags: ["slang", "daily-life", "conversation"],
  },
  {
    id: "ur_o_pa",
    type: "expression",
    contentPt: "Ó pá!",
    contentL1: "Oye! / Yaar!",
    explanation: "'Ó pá' (from 'rapaz', boy) is how Portuguese address friends or express surprise. 'Ó pá, que se passa?' (Hey, what's up?). Like Urdu 'oye' or 'yaar' — casual, friendly, only between peers. Never use with strangers or elders.",
    cefrMin: "A2",
    tags: ["slang", "conversation"],
  },
  {
    id: "ur_ta_se_bem",
    type: "expression",
    contentPt: "Tá-se bem!",
    contentL1: "Sab acha! / Theek hai!",
    explanation: "Contraction of 'está-se bem'. Means 'it's all good', 'we're fine'. Often as a greeting response: 'Como estás?' — 'Tá-se bem!' Like Urdu 'sab acha' — easy, optimistic, avoids details.",
    cefrMin: "A1",
    tags: ["slang", "conversation", "daily-life"],
  },
  {
    id: "ur_agua_mole",
    type: "expression",
    contentPt: "Água mole em pedra dura, tanto bate até que fura",
    contentL1: "Qatra qatra darya banta hai — patience wins",
    explanation: "'Soft water on hard stone, keeps hitting until it pierces.' Persistence wins. Like Urdu 'qatra qatra darya banta hai' (drop by drop the river forms). One of the oldest Portuguese proverbs, used daily to encourage patience — in learning, work, or navigating Portuguese bureaucracy.",
    cefrMin: "B1",
    tags: ["proverb", "wisdom", "ancient"],
  },
  {
    id: "ur_quem_nao_tem_cao",
    type: "expression",
    contentPt: "Quem não tem cão, caça com gato",
    contentL1: "Jo hai usse kaam chalao — jugaad ka proverb",
    explanation: "'If you don't have a dog, hunt with a cat.' Make do with what you have. This ancient Portuguese proverb is jugaad in proverbial form — use whatever resources are available. It proves that 'desenrascar-se' is centuries-old philosophy, baked into Portuguese DNA just like jugaad is in Pakistani DNA.",
    cefrMin: "B1",
    tags: ["proverb", "wisdom", "ancient"],
  },
  {
    id: "ur_grao_a_grao",
    type: "expression",
    contentPt: "Grão a grão, enche a galinha o papo",
    contentL1: "Dana dana dheere dheere — sabr ka phal meetha",
    explanation: "'Grain by grain, the hen fills her crop.' Small efforts accumulate to big results. Used when advising patience. Like Urdu 'sabr ka phal meetha hota hai' (the fruit of patience is sweet). This proverb dates to at least the 15th century and remains in everyday use.",
    cefrMin: "B1",
    tags: ["proverb", "wisdom", "ancient"],
  },
  {
    id: "ur_fazer_tripas_coracao",
    type: "expression",
    contentPt: "Fazer das tripas coração",
    contentL1: "Himmat karna / Dil mazboot karna",
    explanation: "'Make a heart out of tripe' — to summon courage and push through something difficult. When facing a long AIMA queue or a hard exam: 'vou fazer das tripas coração'. Like Urdu 'himmat karna'. Ancient, visceral, still alive in daily speech.",
    cefrMin: "B1",
    tags: ["proverb", "emotion", "ancient"],
  },
  {
    id: "ur_ficar_ver_navios",
    type: "expression",
    contentPt: "Ficar a ver navios",
    contentL1: "Haath khaali reh gaye — left waiting, empty-handed",
    explanation: "'To stay watching ships' — to be left with nothing. From the Age of Discoveries when families watched ships leave, many never returning. 'Fiquei a ver navios' (I was left empty-handed). Like Urdu 'haath khaali reh gaye'. A poetic expression with 500 years of maritime history.",
    cefrMin: "B2",
    tags: ["proverb", "history", "ancient"],
  },
  {
    id: "ur_deixa_la",
    type: "expression",
    contentPt: "Deixa lá",
    contentL1: "Chhoro / Rehne do — never mind",
    explanation: "'Let it go' or 'never mind'. Used constantly: when something minor goes wrong ('Deixa lá, não faz mal' — Never mind, it's OK), to comfort someone, or to drop a subject. Like Urdu 'chhoro' or 'rehne do'. One of the most comforting phrases in Portuguese.",
    cefrMin: "A1",
    tags: ["daily-life", "conversation"],
  },
  {
    id: "ur_se_calhar",
    type: "expression",
    contentPt: "Se calhar",
    contentL1: "Shayad / Ho sakta hai",
    explanation: "'Perhaps', 'maybe'. PT-EU uses 'se calhar' where PT-BR uses 'talvez'. 'Se calhar amanhã chove' (Maybe it'll rain tomorrow). Like Urdu 'shayad'. Using 'se calhar' instead of 'talvez' marks you as a European Portuguese speaker.",
    cefrMin: "A2",
    tags: ["daily-life", "conversation", "pt-eu-vs-br"],
  },
  {
    id: "ur_e_o_que_e",
    type: "expression",
    contentPt: "É o que é",
    contentL1: "Jo hai so hai / Yehi haal hai",
    explanation: "'It is what it is.' The ultimate Portuguese resigned acceptance. When rent goes up, bureaucracy is slow, the train is late: 'é o que é'. Like Urdu 'jo hai so hai'. Philosophical acceptance without drama — captures the Portuguese temperament perfectly.",
    cefrMin: "A1",
    tags: ["daily-life", "conversation", "philosophy"],
  },
  {
    id: "ur_engolir_sapos",
    type: "expression",
    contentPt: "Engolir sapos",
    contentL1: "Kadvaahat peena / Zulm sehna — swallow bitterness",
    explanation: "'To swallow frogs' — to endure something unpleasant without complaining. When your boss is unfair, when bureaucracy grinds you: 'tenho de engolir sapos'. Like Urdu 'kadvaahat peena'. Ancient expression, still used daily.",
    cefrMin: "B1",
    tags: ["proverb", "emotion", "ancient"],
  },
  {
    id: "ur_nao_faz_mal",
    type: "expression",
    contentPt: "Não faz mal",
    contentL1: "Koi baat nahi",
    explanation: "'It doesn't matter' / 'No worries'. The most common response to an apology. Someone bumps you: 'Desculpe!' — 'Não faz mal!' Exactly Urdu 'koi baat nahi'. You will hear and use this multiple times every day in Portugal.",
    cefrMin: "A1",
    tags: ["daily-life", "conversation"],
  },
  {
    id: "ur_mandar_vir",
    type: "expression",
    contentPt: "Mandar vir",
    contentL1: "Daantna / Sunana — to tell someone off",
    explanation: "'To send someone coming' — to scold or complain aggressively. 'A minha mãe mandou-me vir' (My mum told me off). Like Urdu 'daantna' or 'sunana'. Very common in everyday Portuguese, from family arguments to workplace frustrations.",
    cefrMin: "B1",
    tags: ["slang", "emotion", "daily-life"],
  },
  {
    id: "ur_mais_vale_passaro",
    type: "expression",
    contentPt: "Mais vale um pássaro na mão do que dois a voar",
    contentL1: "Haath ki chiriya achi, do urte hue se",
    explanation: "'A bird in the hand is worth two flying.' Don't risk what you have for uncertain gains. Like Urdu 'haath ki chiriya achi do urte hue se'. The Portuguese version uses 'a voar' (flying) giving it a poetic, maritime feel. Used daily about jobs, money, and relationships.",
    cefrMin: "B1",
    tags: ["proverb", "wisdom", "ancient"],
  },
];
