import type { CulturalRef } from "../types.js";

export const urCulturalRefs: readonly CulturalRef[] = [
  {
    id: "ur_arabic_shared_words",
    type: "reference",
    contentPt: "Palavras portuguesas de origem arabe",
    contentL1: "Portuguese words from Arabic — familiar to Urdu speakers",
    explanation: "Portugal was under Moorish rule for 500 years (711-1249). Portuguese absorbed hundreds of Arabic words — and Urdu did too via Persian. Many Portuguese words will sound familiar: 'aldeia' (village, from ad-day'a), 'alfandega' (customs, from al-funduq), 'azulejo' (tile, from az-zulayj), 'alface' (lettuce, from al-khas), 'almofada' (pillow, from al-mukhadda). This shared Arabic layer is a unique bridge between Urdu and Portuguese.",
    cefrMin: "A2",
    tags: ["vocabulary", "history", "arabic"],
  },
  {
    id: "ur_moorish_portugal",
    type: "reference",
    contentPt: "Portugal mouro: 500 anos de historia islamica",
    contentL1: "Moorish Portugal: 500 years of Islamic history",
    explanation: "Southern Portugal (Algarve, from al-Gharb 'the west') was Muslim for over 500 years. The architecture in Sintra, Silves, and Mertola shows Islamic influence. Fado music may have Arabic melodic roots. Urdu speakers will recognize geometric patterns in azulejos (tiles) that mirror Islamic art traditions. This shared heritage creates an unexpected cultural bridge.",
    cefrMin: "B1",
    tags: ["history", "culture", "architecture"],
  },
  {
    id: "ur_chai_cha",
    type: "reference",
    contentPt: "Cha",
    contentL1: "Chai — same origin, different drink culture",
    explanation: "Urdu 'chai' and Portuguese 'cha' share the same Chinese root. Both nations are serious about their hot drinks. But in Portugal, coffee dominates daily life while 'cha' is for afternoons and evenings. A 'galao' (milky coffee in a glass) is the morning ritual — like chai but with coffee.",
    cefrMin: "A1",
    tags: ["food", "daily-life", "history"],
  },
  {
    id: "ur_loanwords_colonial",
    type: "reference",
    contentPt: "Palavras portuguesas no urdu",
    contentL1: "Portuguese words in everyday Urdu",
    explanation: "Through the Goan and Indian Ocean trade, Portuguese words entered Urdu: 'almari' (armario — wardrobe), 'kamra' (camara — room), 'mez' (mesa — table), 'sabun' (sabao — soap), 'tauliya' (toalha — towel), 'kamiz' (camisa — shirt), 'balti' (balde — bucket). When you learn these Portuguese words, you are reconnecting with words your language already borrowed centuries ago.",
    cefrMin: "A1",
    tags: ["vocabulary", "history"],
  },
  {
    id: "ur_saudade_ghazal",
    type: "expression",
    contentPt: "Saudade",
    contentL1: "A bittersweet longing — like the dard of ghazals",
    explanation: "Portuguese 'saudade' — the untranslatable longing — maps closely to the Urdu ghazal tradition's concept of 'dard' and 'hasrat'. Both cultures have elevated melancholic longing to an art form. Fado music (Portugal's mournful genre) and ghazals share the same emotional DNA: pain made beautiful through art.",
    cefrMin: "B1",
    tags: ["culture", "emotion", "music"],
  },
  {
    id: "ur_desenrascar",
    type: "expression",
    contentPt: "Desenrascar-se",
    contentL1: "Jugaad — creative problem-solving",
    explanation: "The Portuguese concept of 'desenrascar-se' — improvising a solution when everything seems impossible — is a perfect cultural match for 'jugaad'. Both Portuguese and Pakistani cultures take pride in this resourcefulness. 'Vou-me desenrascar' = 'jugaad kar lunga'.",
    cefrMin: "B1",
    tags: ["culture", "daily-life"],
  },
  {
    id: "ur_football_cricket",
    type: "reference",
    contentPt: "Futebol e religiao em Portugal",
    contentL1: "Football is religion — like cricket in Pakistan",
    explanation: "What cricket is to Pakistan, football is to Portugal. The passion for Benfica, Sporting, and Porto mirrors the intensity of Pakistan Super League rivalries. Cristiano Ronaldo is a national hero on the level of cricket legends. Learning football vocabulary is essential for Portuguese conversation.",
    cefrMin: "A2",
    tags: ["sport", "culture", "conversation"],
  },
  {
    id: "ur_family_sunday",
    type: "reference",
    contentPt: "Almoco de domingo com a familia",
    contentL1: "Sunday family lunch — sacred tradition",
    explanation: "Like Pakistani family gatherings, Portuguese Sunday lunch is sacred and non-negotiable. Extended family gathers, grandparents are central, children play while adults talk for hours. The meal is elaborate, always at someone's home. Portuguese family values will feel familiar to Pakistani culture.",
    cefrMin: "A2",
    tags: ["culture", "family", "daily-life"],
  },
  {
    id: "ur_hospitality",
    type: "expression",
    contentPt: "Fique a vontade",
    contentL1: "Make yourself at home — Pakistani-level hospitality",
    explanation: "'Fique a vontade' means 'make yourself comfortable'. Portuguese hospitality, while not quite at Pakistani mehmaan-nawazi levels, is warm and genuine. Guests are always offered food and drink. Refusing food is considered rude — similar to Pakistani customs.",
    cefrMin: "A2",
    tags: ["culture", "hospitality", "daily-life"],
  },
  {
    id: "ur_halal_food",
    type: "reference",
    contentPt: "Comida halal em Portugal",
    contentL1: "Finding halal food in Portugal",
    explanation: "Portugal has a growing halal food scene, especially in Lisbon and Porto where Muslim communities are established. However, pork (porco) is central to Portuguese cuisine — 'presunto' (cured ham), 'chourico' (sausage), 'leitao' (suckling pig). Learning food vocabulary helps navigate menus: 'frango' (chicken), 'peixe' (fish), 'bacalhau' (cod) are safe choices. 'Sem porco, por favor' (without pork, please) is essential.",
    cefrMin: "A1",
    tags: ["food", "daily-life", "practical"],
  },
  {
    id: "ur_azulejo_art",
    type: "reference",
    contentPt: "Azulejos — azuleijos portugueses",
    contentL1: "Azulejos — tiles with Islamic geometric roots",
    explanation: "Portuguese 'azulejo' comes from Arabic 'az-zulayj' (polished stone). These decorative tiles cover buildings across Portugal. Early designs were geometric, directly from Moorish tradition — Urdu speakers will recognize patterns similar to Islamic art in mosques and Mughal architecture. Later Portuguese azulejos evolved into figurative scenes, but the geometric tradition persists.",
    cefrMin: "A2",
    tags: ["art", "architecture", "history", "arabic"],
  },
  {
    id: "ur_fado_music",
    type: "reference",
    contentPt: "Fado",
    contentL1: "Fado — Portugal's soul music (ghazal ki tarah)",
    explanation: "Fado is mournful, melodic, and deeply emotional — the Portuguese ghazal. Some scholars believe fado's melodic patterns have Arabic/Moorish roots, which would make the connection to Urdu musical traditions even deeper. Like qawwali, fado is best experienced live, in intimate venues. Amalia Rodrigues is the undisputed queen of fado.",
    cefrMin: "B1",
    tags: ["music", "culture", "emotion"],
  },
  {
    id: "ur_fixe",
    type: "expression",
    contentPt: "Fixe!",
    contentL1: "Cool! / Zabardast!",
    explanation: "'Fixe' is the Portuguese 'zabardast' or 'mast'. When something is cool or awesome: 'Que fixe!' (How cool!). The most common positive reaction in everyday Portuguese conversation.",
    cefrMin: "A1",
    tags: ["slang", "daily-life"],
  },
  {
    id: "ur_pois",
    type: "expression",
    contentPt: "Pois...",
    contentL1: "Achha... / Haan... (versatile filler/agreement)",
    explanation: "Like Urdu 'achha' which can mean 'okay', 'really?', 'I see', or be a pure filler, Portuguese 'pois' is infinitely versatile. It can express agreement, hesitation, resignation, or acknowledgement — all depending on intonation. 'Pois pois' (doubled) is polite but slightly disinterested agreement.",
    cefrMin: "A1",
    tags: ["daily-life", "conversation"],
  },
  {
    id: "ur_algarve_algharb",
    type: "reference",
    contentPt: "Algarve — do arabe 'al-Gharb'",
    contentL1: "Algarve — from Arabic 'al-Gharb' (the West)",
    explanation: "Portugal's southernmost region 'Algarve' is literally Arabic for 'the West' (al-Gharb). The Moors named it because it was the western frontier of their territory. Many Portuguese place names have Arabic origins: Alfama (al-hamma, hot springs), Almada (al-ma'dan, the mine), Fatima (yes, the famous Portuguese town is named after a Moorish princess).",
    cefrMin: "B1",
    tags: ["history", "geography", "arabic"],
  },
  {
    id: "ur_spice_trade",
    type: "reference",
    contentPt: "Rota das especiarias",
    contentL1: "The spice route — Portugal's connection to the subcontinent",
    explanation: "Vasco da Gama reached India in 1498. The Portuguese controlled the Indian Ocean spice trade for over a century, establishing forts in Goa, Daman, Diu, and along the East African coast. This trade brought Portuguese words into Urdu/Hindi and Indian spices into Portuguese cooking. 'Piri-piri' (chilli) in Portuguese cuisine is a direct legacy.",
    cefrMin: "A2",
    tags: ["history", "food", "vocabulary"],
  },
  {
    id: "ur_nas_tintas",
    type: "expression",
    contentPt: "Estar-se nas tintas",
    contentL1: "To not care at all — mujhe koi fark nahi padta",
    explanation: "Literally 'to be in the paints' — means you couldn't care less. Common, mildly rude but acceptable in casual speech. 'Estou-me nas tintas para isso' = 'mujhe is se koi matlab nahi'.",
    cefrMin: "B1",
    tags: ["slang", "emotion"],
  },
  {
    id: "ur_pastel_nata",
    type: "reference",
    contentPt: "Pastel de nata",
    contentL1: "Custard tart — Portugal's iconic pastry",
    explanation: "Flaky pastry shell filled with egg custard, baked until caramelized on top. The recipe originated in a monastery in Belem, Lisbon. Sprinkled with cinnamon and powdered sugar. The closest Pakistani parallel might be the egg-based sweets (like falooda or cream rolls), but pasteis de nata are in a class of their own. Available everywhere in Portugal for about one euro.",
    cefrMin: "A1",
    tags: ["food", "culture", "lisbon"],
  },
];
