import type { L1Profile } from "../types.js";

export const urProfile: L1Profile = {
  code: "ur",
  name: "Urdu",
  nativeName: "اردو",
  writingDirection: "rtl",
  hasLatinScript: false,
  transfer: {
    cognates: [
      "almari (armario — wardrobe)",
      "kamra (camara — room)",
      "mez (mesa — table)",
      "sabun (sabao — soap)",
      "tauliya (toalha — towel)",
      "padre (padre — priest)",
      "girja (igreja — church)",
      "balti (balde — bucket)",
      "chabi (chave — key)",
      "kamiz (camisa — shirt)",
      "anannas (ananas — pineapple)",
      "cobra (cobra — snake)",
      "verandah (varanda — balcony/veranda)",
      "caju (caju — cashew)",
      "leilao (leilao — auction)",
      "piala (piala — cup, from taça via Persian)",
      "almirah (armario — via almari, same root)",
    ],
    falseFriends: [
      { word: "pao", l1Meaning: "Urdu 'pav' borrowed from Portuguese — bread roll", ptMeaning: "pao means bread in general, not just the roll — papo-seco is the specific roll" },
      { word: "mal", l1Meaning: "maal — goods, wealth, property", ptMeaning: "mal means 'badly' or 'evil' in Portuguese" },
      { word: "sala", l1Meaning: "saala — brother-in-law / mild insult", ptMeaning: "sala means 'room' or 'living room' — no negative connotation" },
      { word: "azar", l1Meaning: "Urdu 'azaar' — torment, discomfort", ptMeaning: "azar means 'bad luck' (from Arabic al-zahr, the dice)" },
      { word: "bar", l1Meaning: "baar — time/occasion (ek baar = one time)", ptMeaning: "bar means a drinking establishment" },
      { word: "cara", l1Meaning: "kaaraa — confinement, bitterness", ptMeaning: "cara means 'face' or 'guy' (informal)" },
      { word: "pai", l1Meaning: "pai — foot (as in 'pair')", ptMeaning: "pai means 'father'" },
      { word: "nota", l1Meaning: "note — banknote (English loan)", ptMeaning: "nota means grade/mark AND banknote" },
      { word: "aldeia", l1Meaning: "Urdu 'aldeia' is not used, but Arabic 'ad-day'a' means village", ptMeaning: "aldeia means 'village' — one of many Portuguese words from Arabic" },
      { word: "alfandega", l1Meaning: "Urdu/Arabic 'al-funduq' — inn/hotel", ptMeaning: "alfandega means 'customs' (the border/tax kind)" },
    ],
    phoneticDifficulties: [
      { sound: "ao", ipa: "/ɐ̃w̃/", description: "Nasal diphthong", tip: "Urdu has nasal vowels via nun ghunna — use that instinct but add a strong diphthong glide. This is a moving nasal sound, not a static one." },
      { sound: "a/o/e (nasal)", ipa: "/ɐ̃/ /õ/ /ẽ/", description: "Nasal vowels throughout", tip: "Urdu nasalizes vowels freely (nun ghunna). PT-EU nasal vowels are phonemic — they change word meaning. 'la' (there) vs 'la' (wool, nasal) are different words." },
      { sound: "r/rr", ipa: "/ʁ/", description: "Uvular R (initial and double)", tip: "Urdu has a uvular sound in some Arabic loans (ghain/غ). PT-EU initial R and double RR use a similar position — 'rato' (mouse), 'carro' (car). Think of Arabic ghain." },
      { sound: "r (between vowels)", ipa: "/ɾ/", description: "Alveolar tap (intervocalic)", tip: "Similar to Urdu 'ra' — a quick flap of the tongue. 'Caro' (expensive) vs 'carro' (car) — the single r is the light tap." },
      { sound: "v vs b", ipa: "/v/ vs /b/", description: "Labiodental v vs bilabial b", tip: "Urdu often merges v/w/b. PT-EU 'v' is always labiodental (upper teeth on lower lip). 'Vaca' (cow) must have a clear V sound, never W or B." },
      { sound: "p", ipa: "/p/", description: "The P sound (unaspirated)", tip: "Urdu has both p and ph (aspirated). PT-EU p is always unaspirated — 'pao' (bread) has a clean p without a puff of air." },
      { sound: "lh", ipa: "/ʎ/", description: "Palatal lateral", tip: "No Urdu equivalent. Place your tongue flat against the hard palate and let air flow around the sides. 'Filho' (son), 'trabalho' (work), 'olho' (eye)." },
      { sound: "nh", ipa: "/ɲ/", description: "Palatal nasal", tip: "Close to Urdu noon (ن) in certain positions but more palatal. Used in 'minha' (my), 'vinho' (wine), 'amanha' (tomorrow)." },
      { sound: "open vs closed vowels", ipa: "/ɛ/ vs /e/, /ɔ/ vs /o/", description: "Vowel height contrast", tip: "Urdu doesn't distinguish open and closed e/o. In PT-EU, 'avo' (grandmother, open o) vs 'avo' (grandfather, closed o) are different words based on vowel openness." },
      { sound: "reduced vowels", ipa: "/ɨ/ /ɐ/", description: "Unstressed vowel reduction", tip: "Urdu pronounces vowels relatively clearly. PT-EU swallows unstressed vowels — 'Portugal' sounds like 'Purtugal' with a barely audible first vowel." },
      { sound: "s/z/sh/zh", ipa: "/s/ /z/ /ʃ/ /ʒ/", description: "Four sibilants", tip: "Urdu has s, z, and sh but typically no zh. PT-EU 's' becomes /ʃ/ before consonants ('estar' = 'eshtar'). 'J' is always /ʒ/ as in French 'je'. Good news: Urdu's Arabic loans give you practice with z." },
      { sound: "LTR reading direction", ipa: "n/a", description: "Left-to-right script", tip: "The Latin script reads left to right — opposite to Nastaliq/Arabic. Reading speed will improve with practice. Focus on letter recognition before worrying about reading speed." },
    ],
    grammarGaps: [
      { concept: "Definite articles", explanation: "o (m), a (f), os (m.pl), as (f.pl)", l1Comparison: "Urdu has no articles (Arabic has 'al-' but Urdu dropped it). Every Portuguese noun needs its article: 'o livro' (the book), not just 'livro'." },
      { concept: "Indefinite articles", explanation: "um (m), uma (f)", l1Comparison: "Urdu uses 'ek' for 'one' but not as an article in the same way. PT-EU 'um/uma' must match noun gender." },
      { concept: "Grammatical gender (different assignments)", explanation: "Every noun is masculine or feminine", l1Comparison: "Urdu has gender too (from Hindi/Sanskrit), but assigns it differently. 'Mesa' (table) is feminine in PT; 'mez' is masculine in Urdu. Learn each noun with its article." },
      { concept: "SVO word order", explanation: "Subject-Verb-Object is default", l1Comparison: "Urdu is SOV. PT-EU puts the verb before the object: 'Ali ne kitab parhi' becomes 'O Ali leu o livro'. The verb moves to the middle." },
      { concept: "Verb conjugation (6 persons)", explanation: "Each person has a unique verb form", l1Comparison: "Urdu conjugates for gender and formality. PT-EU conjugates for each person: eu falo, tu falas, ele fala, nos falamos, vos falais, eles falam — 6 distinct forms per tense." },
      { concept: "Subjunctive mood", explanation: "Used for doubt, desire, emotion, uncertainty", l1Comparison: "Urdu has no subjunctive mood. PT-EU requires it after 'talvez' (maybe), 'quero que' (I want that), 'espero que' (I hope that). It is one of the hardest concepts for Urdu speakers." },
      { concept: "Ser vs Estar", explanation: "Two verbs for 'to be'", l1Comparison: "Urdu 'hona' covers both permanent and temporary states. PT-EU splits them: 'ser' for identity (sou portugues) and 'estar' for states (estou cansado — I'm tired)." },
      { concept: "Prepositions (not postpositions)", explanation: "de, em, a, para, com, por", l1Comparison: "Urdu uses postpositions (ke baad, mein, par) that come AFTER the noun. PT-EU prepositions come BEFORE: 'em Portugal' (in Portugal), 'de Lisboa' (from Lisbon). They also contract with articles: em + o = no." },
      { concept: "Plural formation", explanation: "Add -s, -es, or change -ao to -oes", l1Comparison: "Urdu plural forms vary (broken plurals from Arabic, suffix changes). PT-EU follows rules: livro to livros, animal to animais, coracao to coracoes. The article changes too." },
      { concept: "Relative clauses with 'que'", explanation: "'que' introduces relative clauses", l1Comparison: "Urdu uses 'jo...vo' structure. PT-EU uses a single 'que': 'o homem que fala' (the man who speaks). Simpler structure, no resumptive pronoun needed." },
      { concept: "Personal infinitive", explanation: "Infinitive conjugated for person", l1Comparison: "Unique to Portuguese. Doesn't exist in Urdu or most other languages. 'Para nos fazermos' (for us to do) — the infinitive 'fazer' gets a personal ending." },
      { concept: "Object pronoun placement", explanation: "Before or after the verb depending on context", l1Comparison: "Urdu puts objects before the verb. PT-EU has complex rules: 'Da-me' (give me) vs 'Nao me das' (you don't give me) — the pronoun moves based on what precedes the verb." },
    ],
    skipBasics: false,
    startingCEFR: "A1",
  },
};
